force-app/main/default/objects/Claim_Setting__c/Claim_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>All default values for Claims</description>
    <label>Claims Settings</label>
</CustomObject>

force-app/main/default/objects/Claim_Setting__c/fields/Deductible_LAE_Applied_After__c.field-meta.xml
<CustomField>
    <fullName>Deductible_LAE_Applied_After__c</fullName>
    <description>Deductible is applied: 
Yes. After first $5,000 of LAE paid. Deductible applies to first dollar on indemnity (Loss). 
This field is use for only Deductible LAE applied after given amount.</description>
    <label>Deductible LAE Applied After</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Aggregate_Limit__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Limit__c</fullName>
    <label>Aggregate Limit</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Cancel_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Date__c</fullName>
    <label>Cancel Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount__c</fullName>
    <label>Deductible Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Deductible_ID__c.field-meta.xml
<CustomField>
    <fullName>Deductible_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deductible</label>
    <referenceTo>Deductible_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/ERE_Date__c.field-meta.xml
<CustomField>
    <fullName>ERE_Date__c</fullName>
    <label>ERE Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Limits</label>
    <referenceTo>ILF_Coverage_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Mini_Tail_Override_Date__c.field-meta.xml
<CustomField>
    <fullName>Mini_Tail_Override_Date__c</fullName>
    <label>Mini Tail Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Per_Claim_Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Deductible_Amount__c</fullName>
    <formula>Deductible_ID__r.Deductible_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Per Claim Deductible Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Per_Claim_Limit__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Limit__c</fullName>
    <label>Per Claim Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is to identify the type of record, the formula get the record type name that tell the type to be &apos;Application&apos; or &apos;Policy&apos;.</description>
    <formula>RecordType.Name</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Aggregate_Limit__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Limit__c</fullName>
    <label>Aggregate Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claim</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Date__c.field-meta.xml
<CustomField>
    <fullName>Claim_Date__c</fullName>
    <label>Claim Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Firm_Name__c.field-meta.xml
<CustomField>
    <fullName>Claim_Firm_Name__c</fullName>
    <label>Claim Firm Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Invoice</fullName>
            </value>
            <value>
                <fullName>Pending Close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Deductible_LAE_Applied_Limit__c.field-meta.xml
<CustomField>
    <fullName>Deductible_LAE_Applied_Limit__c</fullName>
    <label>Deductible LAE Applied Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incident</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Suit</fullName>
            </value>
            <value>
                <fullName>ARDC Complaint</fullName>
            </value>
            <value>
                <fullName>Memo</fullName>
            </value>
            <value>
                <fullName>Supoena</fullName>
                <label>Subpoena</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5000__c.field-meta.xml
<CustomField>
    <fullName>GL_5000__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5000</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5030__c.field-meta.xml
<CustomField>
    <fullName>GL_5030__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5030</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incident__c.field-meta.xml
<CustomField>
    <fullName>Incident__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Incident</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incident_Date__c.field-meta.xml
<CustomField>
    <fullName>Incident_Date__c</fullName>
    <label>Incident Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Is_Reserve_Creation_Block__c.field-meta.xml
<CustomField>
    <fullName>Is_Reserve_Creation_Block__c</fullName>
    <formula>OR(
Not(Policy__r.Active__c)
,

   OR(ISPICKVAL(File_Type__c, &apos;ARDC Complaint&apos;) ,
      ISPICKVAL(File_Type__c, &apos;Memo&apos;)
      )

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Reserve Creation Block</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Legacy_Import__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Import__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Legacy Import</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Per_Claim_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Deductible__c</fullName>
    <label>Per Claim Deductible</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy_Cancel_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Cancel_Date__c</fullName>
    <label>Policy Cancel Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Policy_Deductible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy Deductible</label>
    <referenceTo>Deductible_Factor__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Effective_Date__c</fullName>
    <label>Policy Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy_ERE_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_ERE_Date__c</fullName>
    <label>Policy ERE Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy_Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Expire_Date__c</fullName>
    <label>Policy Expire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy_Limit_ID__c.field-meta.xml
<CustomField>
    <fullName>Policy_Limit_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy Limit ID</label>
    <referenceTo>ILF_Coverage_Factor__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy_Mini_Tail_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Mini_Tail_Date__c</fullName>
    <label>Policy_Mini_Tail_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <label>Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Reserve_LAE__c.field-meta.xml
<CustomField>
    <fullName>Reserve_LAE__c</fullName>
    <defaultValue>$Setup.Claim_Setting__c.Open_Reserve_LAE_Value__c</defaultValue>
    <label>zzzOpen Reserve LAE</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Reserve_Loss__c.field-meta.xml
<CustomField>
    <fullName>Reserve_Loss__c</fullName>
    <defaultValue>$Setup.Claim_Setting__c.Open_Reserve_Loss_Value__c</defaultValue>
    <label>zzzOpen Reserve Loss</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Suit__c.field-meta.xml
<CustomField>
    <fullName>Suit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Suit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Suit_Date__c.field-meta.xml
<CustomField>
    <fullName>Suit_Date__c</fullName>
    <label>Suit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/recordTypes/Incident.recordType-meta.xml
<RecordType>
    <fullName>Incident</fullName>
    <active>true</active>
    <label>Incident</label>
</RecordType>

force-app/main/default/objects/Policy_Claim_Detail__c/Policy_Claim_Detail__c.object-meta.xml
<CustomObject>
    <label>Policy Claim Detail</label>
    <nameField>
        <displayFormat>Claim-{0000000}</displayFormat>
        <label>Claim Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Claims Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/LAE_Amount__c.field-meta.xml
<CustomField>
    <fullName>LAE_Amount__c</fullName>
    <label>LAE Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Loss_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loss_Amount__c</fullName>
    <label>Loss Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Policy_Claim__c.field-meta.xml
<CustomField>
    <fullName>Policy_Claim__c</fullName>
    <label>Policy Claim</label>
    <referenceTo>Policy_Claim__c</referenceTo>
    <relationshipLabel>Claims Detail</relationshipLabel>
    <relationshipName>Policy_Claims_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reserve_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/recordTypes/Deductible.recordType-meta.xml
<RecordType>
    <fullName>Deductible</fullName>
    <active>true</active>
    <description>1) Allocate Deductible Loss/LAE. 2) Cash Received / Write-off against Deductible.</description>
    <label>Deductible</label>
</RecordType>

force-app/main/default/objects/Policy_Claim_Detail__c/recordTypes/Reinsurance.recordType-meta.xml
<RecordType>
    <fullName>Reinsurance</fullName>
    <active>true</active>
    <description>1) Create Due from Reinsurance Loss/LAE. 2) Change in Ceded Reserve for Loss/LAE.</description>
    <label>Reinsurance</label>
</RecordType>

force-app/main/default/objects/Policy_Claim_Detail__c/recordTypes/Reserve.recordType-meta.xml
<RecordType>
    <fullName>Reserve</fullName>
    <active>true</active>
    <description>1) Increase Reserve(User Reserve)  2) Close/Re-Open Reserve</description>
    <label>Reserve</label>
</RecordType>

force-app/main/default/globalValueSets/Reserve_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>User Reserve</fullName>
        <label>Change Reserve</label>
    </customValue>
    <customValue>
        <fullName>Close Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Reopen Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Loss Payment</fullName>
    </customValue>
    <customValue>
        <fullName>LAE Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Deductible Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Deductible Expense</fullName>
    </customValue>
    <customValue>
        <fullName>Change in Ceded Loss Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Change in Ceded LAE Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Due from Reins. - Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Due from Reins. - LAE</fullName>
    </customValue>
    <customValue>
        <fullName>Open Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Claim Coverage - ARDC</fullName>
        <label>ARDC Payment</label>
    </customValue>
    <customValue>
        <fullName>Unallocated LAE Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Deductible Expense New</fullName>
    </customValue>
    <customValue>
        <fullName>SBL</fullName>
    </customValue>
    <customValue>
        <fullName>CPSBL</fullName>
    </customValue>
    <customValue>
        <fullName>CPSBE</fullName>
    </customValue>
    <masterLabel>Reserve Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Policy_Claim_Gateway.cls
public class Policy_Claim_Gateway {
/*
//Created By    :   Shoukat Hussain
//Created Date  :   11/27/2016
//Purpose       :   Different function for  Policy Claim
//              :   Public Valirables  Record Type for Claim
*/

    
    // Public static record type
    public static ID ReserveRTID = Schema.SObjectType.Policy_Claim_Detail__C.getRecordTypeInfosByName().get('Reserve').getRecordTypeId();
    public static ID ReinsuranceRTID = Schema.SObjectType.Policy_Claim_Detail__C.getRecordTypeInfosByName().get('Reinsurance').getRecordTypeId();

    public static void InsertReserveOpenRecord(list<Policy_Claim__c> PClaimData){
        // Iterate Trigger.
        system.debug('InsertReserveOpenRecord' +PClaimData);
        List<Policy_Claim_Detail__c> PCDLst = new List<Policy_Claim_Detail__c>();
        system.debug('PClaimData '+PClaimData);
        If(PClaimData.size()>0){
            For(Policy_Claim__c PCLoop : PClaimData){
                system.debug('PCLoop.Is_Reserve_Creation_Block__c : ' + PCLoop.Is_Reserve_Creation_Block__c);
                system.debug('PCLoop.Legacy_Import__c :: ' + PCLoop.Legacy_Import__c);
                 If(!PCLoop.Is_Reserve_Creation_Block__c && !PCLoop.Legacy_Import__c){
                       
                PCDLst.add(new Policy_Claim_Detail__c(
                    Policy_Claim__c = PCLoop.ID,
                    Loss_Amount__c  = PCLoop.Reserve_Loss__c,
                    LAE_Amount__c   =  PCLoop.Reserve_LAE__c,
                    Date__c         =  PCLoop.Report_Date__c,
                    Type__c         =  'Open Reserve',
                    RecordTypeId    =  ReserveRTID) );
                   }
                
            }
            Try{
                If(PCDLst.size()>0){
                    Database.insert(PCDLst);    
                }
               
            }
            catch(DmlException e) {
                System.debug('Error: ' + e.getMessage());  
            }            
        }
    }
    
    // Update Checks box for Incedent , Claim and Suit     
    Public static void UpdateClaimCheck(List<Policy_Claim__c> PClaimData){
        For(Policy_Claim__c PolicyClaimData : PClaimData ){
            If(PolicyClaimData.File_Type__c=='Incident' && !PolicyClaimData.Incident__c){
                PolicyClaimData.Incident__c = true;
                PolicyClaimData.Incident_Date__c = system.Date.today();
            }
            If(PolicyClaimData.File_Type__c=='Claim' && !PolicyClaimData.Claim__c){
                PolicyClaimData.Claim__c = true;
                PolicyClaimData.Claim_Date__c = system.Date.today();                
            }
            If(PolicyClaimData.File_Type__c=='Suit' && !PolicyClaimData.Suit__c){
                PolicyClaimData.Suit__c = true;
                PolicyClaimData.Suit_Date__c = system.Date.today();                
            }

        }
    }
    
    // Update Policy information on Claim
    Public static void UpdatePolicyInfoOnClaim(List<Policy_Claim__c> PClaimData){
        Set<ID> PolicyDataSet = new Set<ID>();
        For(Policy_Claim__c PolicyClaimData : PClaimData ){
            PolicyDataSet.add(PolicyClaimData.Policy__c);
        }
        Map<ID,Policy__c> PolicyDataMap = new Map<ID,Policy__c>([select 
                                                                 Limit__c, Deductible_ID__c, Deductible_Amount__c, Per_Claim_Limit__c,
                                                                 Aggregate_Limit__c,Effective_Date__c,Expiration_Date__c,ERE_Date__c,
                                                                 Mini_Tail_Override_Date__c,Cancel_Date__c,Per_Claim_Deductible_Amount__c,Account__r.Name
                                                                 from Policy__c 
                                                                 where id in :PolicyDataSet ]);
        
        
        For(Policy_Claim__c PolicyClaimData : PClaimData ){
            
            PolicyClaimData.Policy_Limit_ID__c      = PolicyDataMap.get(PolicyClaimData.Policy__c).Limit__c;
            PolicyClaimData.Policy_Deductible__c    = PolicyDataMap.get(PolicyClaimData.Policy__c).Deductible_ID__c;
            PolicyClaimData.Per_Claim_Deductible__c = PolicyDataMap.get(PolicyClaimData.Policy__c).Per_Claim_Deductible_Amount__c;
            PolicyClaimData.Per_Claim_Limit__c      = PolicyDataMap.get(PolicyClaimData.Policy__c).Per_Claim_Limit__c;
            PolicyClaimData.Aggregate_Limit__c      = PolicyDataMap.get(PolicyClaimData.Policy__c).Aggregate_Limit__c;
            PolicyClaimData.Policy_Effective_Date__c= PolicyDataMap.get(PolicyClaimData.Policy__c).Effective_Date__c;
            PolicyClaimData.Policy_Expire_Date__c   = PolicyDataMap.get(PolicyClaimData.Policy__c).Expiration_Date__c;
            PolicyClaimData.Policy_ERE_Date__c      = PolicyDataMap.get(PolicyClaimData.Policy__c).ERE_Date__c;
            PolicyClaimData.Policy_Mini_Tail_Date__c= PolicyDataMap.get(PolicyClaimData.Policy__c).Mini_Tail_Override_Date__c;
            PolicyClaimData.Policy_Cancel_Date__c   = PolicyDataMap.get(PolicyClaimData.Policy__c).Cancel_Date__c;       
            
            PolicyClaimData.Claim_Firm_Name__c = PolicyDataMap.get(PolicyClaimData.Policy__c).Account__r.Name;  
            system.debug('effective'+PolicyClaimData.Policy__r.Effective_Date__c);
            system.debug('pcdata:'+PolicyClaimData.Policy_Effective_Date__c);
            
        }
    }
    
    // Update Deductible LAE limit on Claim    
    Public static void UpdateCustomSettingInfoOnClaim(List<Policy_Claim__c> PClaimData){
        Claim_Setting__c ObjClaimSetting = [select Deductible_LAE_Applied_After__c from Claim_Setting__c limit 1];        
        For(Policy_Claim__c PolicyClaimData : PClaimData ){            
            PolicyClaimData.Deductible_LAE_Applied_Limit__c      = ObjClaimSetting.Deductible_LAE_Applied_After__c;       
          //  system.debug('Newcheck '+PolicyClaimData.Deductible_LAE_Applied_Limit__c);            
        }
    }
    
    public static void InsertReserveRecord(Map<Id,Policy_Claim__c> oldItems, Map<Id,Policy_Claim__c> newItems) {
        List<Policy_Claim_Detail__c> PCDLst = new List<Policy_Claim_Detail__c>();
        for(Policy_Claim__c claim : newItems.values()){
            if(claim.Claim_Status__c !='Closed'){
                /*if(claim.Claim_Status__c!=oldItems.get(claim.id).Claim_Status__c){
                    PCDLst.add(new Policy_Claim_Detail__c(
                        Policy_Claim__c = claim.ID,
                        Loss_Amount__c  = claim.Reserve_Loss__c - Math.abs(claim.GL_5000__c),
                        LAE_Amount__c   =  claim.Reserve_LAE__c - Math.abs(claim.GL_5030__c),
                        Date__c         =  System.today(),
                        Type__c         =  'Reopen Reserve',
                        RecordTypeId    =  ReserveRTID) );
                }else */ //if((claim.Reserve_Loss__c!=oldItems.get(claim.id).Reserve_Loss__c && claim.Reserve_Loss__c!= claim.Unpaid_Reserves_Direct_Loss__c) || (claim.Reserve_LAE__c!=oldItems.get(claim.id).Reserve_LAE__c && claim.Reserve_LAE__c!=claim.Unpaid_Reserves_Direct_LAE__c)){
                if((claim.Reserve_Loss__c!=oldItems.get(claim.id).Reserve_Loss__c) || (claim.Reserve_LAE__c!=oldItems.get(claim.id).Reserve_LAE__c)){
                    Decimal reserveLoss = claim.GL_5010__c;
                    Decimal reserveLae = claim.GL_5035__c;
                    if(claim.Reserve_Loss__c!=oldItems.get(claim.id).Reserve_Loss__c){
                        PCDLst.add(new Policy_Claim_Detail__c(
                        Policy_Claim__c = claim.ID,
                        Loss_Amount__c  = claim.Reserve_Loss__c,
                        Date__c         =  (QuickClaimController.transDate == null ? System.today() : QuickClaimController.transDate),
                        Type__c         =  'User Reserve',
                        RecordTypeId    =  ReserveRTID) );
                        reserveLoss += claim.Reserve_Loss__c;
                    }
                    if(claim.Reserve_LAE__c!=oldItems.get(claim.id).Reserve_LAE__c){
                        PCDLst.add(new Policy_Claim_Detail__c(
                        Policy_Claim__c = claim.ID,
                        LAE_Amount__c   =  claim.Reserve_LAE__c,
                        Date__c         =  (QuickClaimController.transDate == null ? System.today() : QuickClaimController.transDate),
                        Type__c         =  'User Reserve',
                        RecordTypeId    =  ReserveRTID) );
                        reserveLae += claim.Reserve_LAE__c;
                    }
                    
                    
                    Decimal cededLoss = 0 ;
                    Decimal cededLAE = 0 ;
                    
                    if(( reserveLoss + reserveLae) >= (claim.Ceded_Cutoff_Amount__c + claim.Per_Claim_Deductible__c)){
                        Decimal lossProRata = (claim.GL_5000__c + reserveLoss) / ( reserveLoss + reserveLae);
                        Decimal laeProRata = 1 - lossProRata;
                        Decimal totalCeded = (claim.Ceded_Cutoff_Amount__c + claim.Per_Claim_Deductible__c) - ( reserveLoss + reserveLae);
                        cededLoss = totalCeded * lossProRata;
                        cededLAE = totalCeded * laeProRata;
                        
                        cededLoss = cededLoss - claim.GL_2120__c;
                        cededLAE = cededLAE - claim.GL_2160__c;
                        
                    }else if(( oldItems.get(claim.id).Reserve_Loss__c + oldItems.get(claim.id).Reserve_LAE__c) >= (claim.Ceded_Cutoff_Amount__c + claim.Per_Claim_Deductible__c)){
                        cededLoss = - claim.GL_2120__c;
                        cededLAE = - claim.GL_2160__c;
                    }
                    
                    /*if(cededLoss != 0){
                        PCDLst.add(new Policy_Claim_Detail__c(
                            Policy_Claim__c = claim.ID,
                            //Reinsurance_Amount__c  = (claim.Reserve_Loss__c - oldItems.get(claim.id).Reserve_Loss__c)==0?null:(claim.Reserve_Loss__c - oldItems.get(claim.id).Reserve_Loss__c),
                            Reinsurance_Amount__c  = cededLoss,
                            Date__c         =  (QuickClaimController.transDate == null ? System.today() : QuickClaimController.transDate),
                            Type__c         =  'Change in Ceded Loss Reserve',
                            RecordTypeId    =  ReinsuranceRTID) );
                    }
                    if(cededLAE != 0){
                        PCDLst.add(new Policy_Claim_Detail__c(
                            Policy_Claim__c = claim.ID,
                            //Reinsurance_Amount__c   =  (claim.Reserve_LAE__c - oldItems.get(claim.id).Reserve_LAE__c)==0?null:(claim.Reserve_LAE__c - oldItems.get(claim.id).Reserve_LAE__c),
                            Reinsurance_Amount__c   =  cededLAE,
                            Date__c         =  (QuickClaimController.transDate == null ? System.today() : QuickClaimController.transDate),
                            Type__c         =  'Change in Ceded LAE Reserve',
                            RecordTypeId    =  ReinsuranceRTID) );
                    }*/
                }
            }/*else if(claim.Claim_Status__c=='Closed'){
                if(claim.Claim_Status__c!=oldItems.get(claim.id).Claim_Status__c){
                    PCDLst.add(new Policy_Claim_Detail__c(
                        Policy_Claim__c = claim.ID,
                        Loss_Amount__c  = - claim.Unpaid_Reserves_Direct_Loss__c,
                        LAE_Amount__c   =  - claim.Unpaid_Reserves_Direct_LAE__c,
                        Date__c         =  System.today(),
                        Type__c         =  'Close Reserve',
                        RecordTypeId    =  ReserveRTID) );
                }
            }*/
        }
        Try{
            If(PCDLst.size()>0){
                Database.insert(PCDLst);    
            }
            
        }
        catch(DmlException e) {
            System.debug('Error: ' + e.getMessage());  
        }   
    }
    
    public static void UpdateScheduleDate(List<Policy_Claim__c> PClaimData){
        Set<Id> policyIds = new Set<Id>();
        for(Policy_Claim__c claim : PClaimData){
            if(claim.Schedule_Date__c == null){
                policyIds.add(claim.Policy__c);
            }
        }
        Map<Id,Policy__c> policyMap = new Map<Id,Policy__c>([select id,ERE_Date__c,Expiration_Date__c,Effective_Date__c,RecordType.Name from Policy__c where id in:policyIds ]);
        for(Policy_Claim__c claim : PClaimData){
            if(claim.Schedule_Date__c == null && policyMap.containsKey(claim.Policy__c)){
                if(policyMap.get(claim.Policy__c).RecordType.Name == 'ERP Policy'){
                    claim.Schedule_Date__c = policyMap.get(claim.Policy__c).Effective_Date__c;
                    claim.Schedule_ERE__c = true;
                }else if(claim.Report_Date__c > policyMap.get(claim.Policy__c).Expiration_Date__c.addDays(60) && policyMap.get(claim.Policy__c).ERE_Date__c!=null && claim.Report_Date__c < policyMap.get(claim.Policy__c).ERE_Date__c){
                    claim.Schedule_Date__c = policyMap.get(claim.Policy__c).Effective_Date__c;
                    claim.Schedule_ERE__c = true;
                }else{
                    claim.Schedule_Date__c = claim.Report_Date__c;
                    claim.Schedule_ERE__c = false;
                }
            }
        }
    }
    
    public static void createFollowUpTasks(list<Policy_Claim__c> PClaimData){
        List<Task> tasksList = new List<Task>();
        for(Policy_Claim__c claim : PClaimData){
            if(claim.Follow_up_Date__c!=null){
                tasksList.add(new Task(OwnerId=(claim.Claim_Handler_Lookup__c==null?claim.CreatedById:claim.Claim_Handler_Lookup__c),Subject='Follow Up Task',ActivityDate=claim.Follow_up_Date__c,Description='Follow Up',WhatId=claim.Id,Status='In Progress'));
            }
        }
        if(tasksList.size()>0){
            insert tasksList;
        }
    }
    
    public static void validateClaimPolicy(List<Policy_Claim__c> PClaimData){
        Set<Id> policyIds = new Set<Id>();
        for(Policy_Claim__c claim : PClaimData){
            if(claim.Policy__c!=null){
                policyIds.add(claim.Policy__c);
            }
        }
        Map<Id,Profile> profilesMap = new Map<Id,Profile>([select id from Profile where Id =: UserInfo.getProfileId() and Name = 'System Administrator']);
        if(profilesMap.isEmpty()){
            Map<Id,Policy__c> policyMap = new Map<Id,Policy__c>([select id,Effective_Date__c,Expiration_Date__c,RecordType.Name,ERE_Date__c,Cancel_Date__c from Policy__c where id in: policyIds]);
            for(Policy_Claim__c claim : PClaimData){
                if(claim.Policy__c!=null && policyMap.containsKey(claim.Policy__c)){
                    Policy__c policy = policyMap.get(claim.Policy__c);
                    if(policy.RecordType.Name == 'Application' || (policy.ERE_Date__c==null && policy.Cancel_Date__c!=null && policy.Cancel_Date__c.addDays(90) < System.today()) || (policy.ERE_Date__c!=null && policy.ERE_Date__c.addDays(90) < System.today()) || (policy.ERE_Date__c==null && policy.Expiration_Date__c!=null && policy.Expiration_Date__c.addDays(90) < System.today())){
                        claim.addError('Claim must be filed against an active policy or must be within 90 days of cancel/expiration date of the policy');
                    }
                }
            }
        }
    }
    
    
}