force-app/main/default/objects/User_Tracking__c/User_Tracking__c.object-meta.xml
<CustomObject>
    <label>User Tracking</label>
    <nameField>
        <displayFormat>UT - {0000}</displayFormat>
        <label>User Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Tracking__c/fields/Activity_Time__c.field-meta.xml
<CustomField>
    <fullName>Activity_Time__c</fullName>
    <label>Activity Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>View</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Tracking__c/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <label>Object Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Policy__c</fullName>
            </value>
            <value>
                <fullName>Policy_Claim__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Policy_Endorsement__c</fullName>
            </value>
            <value>
                <fullName>AcctSeed__Billing__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Tracking__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserTrackingHandler.cls
public class UserTrackingHandler {
    public static User_Tracking__c createUserTrackingObject(String eventType,Id recordId,String recordName){
        User_Tracking__c userTrack = new User_Tracking__c();
        userTrack.Activity_Time__c = System.now();
        userTrack.Event_Type__c = eventType;
        userTrack.Object_Type__c = recordId.getSObjectType().getDescribe().getName();
        userTrack.Record_Id__c = recordId;
        userTrack.Record_Name__c = recordName;
        userTrack.User__c = UserInfo.getUserId();
        return userTrack;
    }
}