force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Cancel_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Date__c</fullName>
    <label>Cancel Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Dividend_Expiration_Year_Earned__c.field-meta.xml
<CustomField>
    <fullName>Dividend_Expiration_Year_Earned__c</fullName>
    <description>Dividend_Net_Written__c *  Expiration_Year_Percentage__c * 0.1</description>
    <formula>if (Expiration_Year_Percentage__c &gt; 1,
  1,
  Dividend_Net_Written__c *  Expiration_Year_Percentage__c * 0.1
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiration Year Dividend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Effective_Year_Dividend__c.field-meta.xml
<CustomField>
    <fullName>Effective_Year_Dividend__c</fullName>
    <description>Dividend_Net_Written__c *  Effective_Year_Percentage__c * .1</description>
    <formula>Dividend_Net_Written__c *  Effective_Year_Percentage__c * 0.1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Effective Year Dividend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/ISBAM_policy_dividend__c.field-meta.xml
<CustomField>
    <fullName>ISBAM_policy_dividend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Dividend value calculated when application was created</description>
    <label>ISBAM Policy Dividend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Next_Policy__c.field-meta.xml
<CustomField>
    <fullName>Next_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Next Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Application/Policy (Next Policy)</relationshipLabel>
    <relationshipName>Application_Policy1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Old_Policy__c.field-meta.xml
<CustomField>
    <fullName>Old_Policy__c</fullName>
    <externalId>true</externalId>
    <label>Old Policy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Effective_Year__c.field-meta.xml
<CustomField>
    <fullName>Policy_Effective_Year__c</fullName>
    <description>Policy Effective Year (YYYY)</description>
    <formula>TEXT(YEAR ( Effective_Date__c ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Effective Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Expiration_Year__c.field-meta.xml
<CustomField>
    <fullName>Policy_Expiration_Year__c</fullName>
    <description>Policy Expiration Year (YYYY)</description>
    <formula>TEXT ( YEAR ( Expiration_Date__c ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Expiration Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Series_Count__c.field-meta.xml
<CustomField>
    <fullName>Policy_Series_Count__c</fullName>
    <label>Policy Series Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Series_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Series_Effective_Date__c</fullName>
    <label>Policy Series Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Treaty_Version__c.field-meta.xml
<CustomField>
    <fullName>Treaty_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treaty Version</label>
    <referenceTo>Treaty_Versions__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Treaty_Versions__c/Treaty_Versions__c.object-meta.xml
<CustomObject>
    <label>Treaty Version</label>
    <nameField>
        <displayFormat>Treaty-{00}</displayFormat>
        <label>Master Treaty Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treaty Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch_MassUpdatePolicies.cls
public class Batch_MassUpdatePolicies implements Database.Batchable<Sobject>, Database.Stateful{
    public String soql;
    public String operation;
    Map<String,Decimal> effectiveYearDividendPolicies;
    Map<String,Decimal> expirationYearDividendPolicies;
    public Batch_MassUpdatePolicies(){
    }
    public Batch_MassUpdatePolicies(String soql,String operation){
        this.soql = soql;
        this.operation = operation;
        effectiveYearDividendPolicies = new Map<String,Decimal>();
        expirationYearDividendPolicies = new Map<String,Decimal>();
    }
	public Database.QueryLocator start(Database.BatchableContext BC) {
        if(String.isNotBlank(soql)){
            return Database.getQueryLocator(soql);
        }else if(operation == 'Dividend Update'){
            for(Policy__c pol : [select id,Account__c,Policy_Effective_Year__c,Policy_Expiration_Year__c,Effective_Year_Dividend__c,Dividend_Expiration_Year_Earned__c, Effective_Date__c,Policy_Series_Effective_Date__c  from Policy__c where Effective_Date__c >= 2017-01-01]){
                if(!effectiveYearDividendPolicies.containsKey(pol.Policy_Effective_Year__c + '-' + pol.Account__c)){
                    effectiveYearDividendPolicies.put(pol.Policy_Effective_Year__c + '-' + pol.Account__c,0);
                }
                if(pol.Effective_Year_Dividend__c != null){
                    effectiveYearDividendPolicies.put(pol.Policy_Effective_Year__c + '-' + pol.Account__c,effectiveYearDividendPolicies.get(pol.Policy_Effective_Year__c + '-' + pol.Account__c) + pol.Effective_Year_Dividend__c);
                }
                
                if(!expirationYearDividendPolicies.containsKey(pol.Policy_Expiration_Year__c + '-' + pol.Account__c)){
                    expirationYearDividendPolicies.put(pol.Policy_Expiration_Year__c + '-' + pol.Account__c,0);
                }
                if(pol.Dividend_Expiration_Year_Earned__c  != null){
                    expirationYearDividendPolicies.put(pol.Policy_Expiration_Year__c + '-' + pol.Account__c,expirationYearDividendPolicies.get(pol.Policy_Expiration_Year__c + '-' + pol.Account__c) + pol.Dividend_Expiration_Year_Earned__c );
                }
            }
            return Database.getQueryLocator([select id,Account__c,Policy_Effective_Year__c,Policy_Expiration_Year__c,Effective_Year_Dividend__c,Dividend_Expiration_Year_Earned__c,Effective_Date__c,Policy_Series_Effective_Date__c from Policy__c where Effective_Date__c >= 2017-01-01]);
        }else{
            operation = 'Update Treaty';
            return Database.getQueryLocator([select id,Treaty_Version__c,Effective_Date__c from Policy__c where Treaty_Version__c = null and Effective_Date__c > 2000-01-01 order by Effective_Date__c DESC]);
        }
    }
    public void execute(Database.BatchableContext BC, List<sObject> batch) {
        if(operation == 'Update Treaty'){
            List<Treaty_Versions__c> treatyVersions = new List<Treaty_Versions__c>([select id,Start_Date__c,End_Date__c from Treaty_Versions__c]);
            for(Policy__c pol : (List<Policy__c>)batch){
                for(Treaty_Versions__c version : treatyVersions){
                    if(pol.Effective_Date__c >= version.Start_Date__c && pol.Effective_Date__c <= version.End_Date__c){
                        pol.Treaty_Version__c = version.Id;
                    }
                }
            }
            update batch;
        }else if(operation == 'Update Policy Series'){
            // soql = select id,(select id,Effective_Date__c,Expiration_Date__c,Cancel_Date__c from Policies__r where RecordType.Name = \'Policy\' order by Effective_Date__c) from Account where id=\'0014A00002jNWcLQAW\'
            List<Policy__c> policies = new List<Policy__c>();
            for(Account acc : (List<Account>)batch){
                Integer policySeriesCount;
                Date policySeriesEffectiveDate;
                Date oldPolicyExpirationDate;
                for(Policy__c pol : acc.Policies__r){
                    if(pol.Effective_Date__c != oldPolicyExpirationDate){
                        policySeriesCount = 1;
                        policySeriesEffectiveDate = pol.Effective_Date__c;
                    }else{
                        policySeriesCount += 1;
                    }
                    if(pol.Cancel_Date__c != null){
                        oldPolicyExpirationDate = pol.Cancel_Date__c;
                    }else{
                        oldPolicyExpirationDate = pol.Expiration_Date__c;
                    }
                    policies.add(new Policy__c(Id = pol.Id,Policy_Series_Count__c = policySeriesCount,Policy_Series_Effective_Date__c = policySeriesEffectiveDate));
                }
            }
            update policies;
        }else if(operation == 'Dividend Update'){
            System.debug(effectiveYearDividendPolicies);
            System.debug(expirationYearDividendPolicies);
            for(Policy__C pol : (List<Policy__c>)batch){
                if(pol.Policy_Series_Effective_Date__c.year() <= (pol.Effective_Date__c.year()-2)){
                    pol.ISBAM_policy_dividend__c = ((effectiveYearDividendPolicies.containsKey((pol.Effective_Date__c.year() - 1) + '-' + pol.Account__c) ? (effectiveYearDividendPolicies.get((pol.Effective_Date__c.year() - 1) + '-' + pol.Account__c)) : 0) + 
                        + (expirationYearDividendPolicies.containsKey((pol.Effective_Date__c.year() - 1) + '-' + pol.Account__c) ? (expirationYearDividendPolicies.get((pol.Effective_Date__c.year() - 1) + '-' + pol.Account__c)) : 0)).round(System.RoundingMode.HALF_UP);
                    System.debug(pol.ISBAM_policy_dividend__c);
                }
            }
            update batch;
        }else if(operation == 'Update Next Policy'){
            // soql = select id,Old_Policy__c from Policy__c where RecordType.Name = '\Policy\' and Old_Policy__c != null
            List<Policy__c> policies = new List<Policy__c>();
            for(Policy__c pol : (List<Policy__c>)batch){
                policies.add(new Policy__c(Id = pol.Old_Policy__c,Next_Policy__c = pol.Id));
            }
            update policies;
        }
    }
    public void finish(Database.BatchableContext BC) { 
    }
}