force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/NAS_EOC_Version_Formula__c.field-meta.xml
<CustomField>
    <fullName>NAS_EOC_Version_Formula__c</fullName>
    <formula>IF( 
	Effective_Date__c &lt; DATE(2022,04,01) , &apos;&apos;,
	IF( Effective_Date__c &lt; DATE(2023,04,01) , &apos;4/22&apos;,
	IF( Effective_Date__c &lt; DATE(2024,04,01) , &apos;4/23&apos;,
	IF( Effective_Date__c &lt; DATE(2025,04,01) , &apos;4/24&apos;,
	IF( Effective_Date__c &lt; DATE(2026,04,01) , &apos;4/25&apos;,
	IF( Effective_Date__c &lt; DATE(2027,04,01) , &apos;4/26&apos;,
	IF( Effective_Date__c &lt; DATE(2028,04,01) , &apos;4/27&apos;,
	IF( Effective_Date__c &lt; DATE(2029,04,01) , &apos;4/28&apos;,
	IF( Effective_Date__c &lt; DATE(2030,04,01) , &apos;4/29&apos;,
	&apos;4/30&apos;
)))))))))</formula>
    <label>NAS EOC Version</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/classes/Batch_MassRegeneratePolicyDocuments.cls
public class Batch_MassRegeneratePolicyDocuments implements Database.Batchable<Sobject>{
	public String soql;
    public String documentType;
    public Batch_MassRegeneratePolicyDocuments(String soql){
        this.documentType = 'All';
    }
    public Batch_MassRegeneratePolicyDocuments(String soql,String documentType){
        this.soql = soql;
        this.documentType = documentType;
    }
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(soql);
    }
    public void execute(Database.BatchableContext BC, List<sObject> batch) {
        Map<Id,Id> contentDocumentIds = new Map<Id,Id>();
        Map<String,Id> documentContentIds = new Map<String,Id>();
        Set<Id> policyIds = new Set<Id>();
        for(Policy__c pol : (List<Policy__c>)batch){
            policyIds.add(pol.Id);
        }
        for(ContentDocumentLink cdl : [select id,ContentDocumentId,LinkedEntityId from ContentDocumentLink where LinkedEntityId in: policyIds]){
            contentDocumentIds.put(cdl.ContentDocumentId,cdl.LinkedEntityId);
        }
        for(ContentVersion cv : [select id,ContentDocumentId,Document_Type__c from ContentVersion where ContentDocumentId in: contentDocumentIds.keySet() and IsLatest = true and (Document_Type__c = 'Policy Letter' OR Document_Type__c = 'NAS EOC' OR Document_Type__c = 'Certificate Of Insurance' OR Document_Type__c = 'Declaration Page')]){
            documentContentIds.put(contentDocumentIds.get(cv.ContentDocumentId) + '-' + cv.Document_Type__c,cv.ContentDocumentId);
        }
        for(Policy__c pol : (List<Policy__c>)batch){
            if(documentType == 'NAS EOC'){
                Id documentId; 
                if(documentContentIds.containsKey('NAS EOC')){
                    documentId = documentContentIds.get('NAS EOC');
                }
                PolicyDocumentsUtility.createNASEOC(pol.Id, pol.NAS_EOC_Version_Formula__c  ,pol.Account__c,documentId);
            }
        }
    }
    public void finish(Database.BatchableContext BC) { 
    }
}