force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Cancel_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Date__c</fullName>
    <label>Cancel Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Renew_Application__c.field-meta.xml
<CustomField>
    <fullName>Renew_Application__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is for the ability to add “Block” to Application Renewal. If the field is unchecked then the renewal processes with not fire, both manual and automated.</description>
    <label>Block Renewal of Policy With Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/classes/AddRenewalAppLtng.cls
public class AddRenewalAppLtng {
    @AuraEnabled
    public static String getPolicy(String policyId){
        String message = '';
        Map<Id,Profile> profilesMap = new Map<Id,Profile>([select id from Profile where Name = 'System Administrator']);
        Policy__c objPolicy = [select Id,Account__c,Renew_Application__c,Expiration_Date__c,Cancel_Date__c from Policy__c where Id =: policyId];
        Account acc = [SELECT Id,(SELECT Id FROM Policies__r WHERE RecordType.Name ='Application') FROM Account Where Id=:objPolicy.Account__c];
        if(!acc.Policies__r.isEmpty()){
             message = 'There is already an open application with this customer. Please review it before creating a new application.';
        }
        else if(objPolicy.Renew_Application__c != false){
            message = 'Application Renewal Blocked!';
        }else if((System.today() > objPolicy.Expiration_Date__c.addDays(90) || (objPolicy.Cancel_Date__c!=null && System.today() > objPolicy.Cancel_Date__c.addDays(90))) && !profilesMap.containsKey(UserInfo.getProfileId())){
            message = 'Cannot renew policy due to expiration or cancel date greater than 90 days.';
        }else{
            List<String> lstResult = CloneAndRenewalUtilities.renewPolicyManually(policyId);
            if(!lstResult.isEmpty()){
                message += lstResult[1];
            }      
        }
        return message;
    }
}