force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/AOP_Percentage__c.field-meta.xml
<CustomField>
    <fullName>AOP_Percentage__c</fullName>
    <description>Sum percentage of Policy AOP</description>
    <label>AOP Percentage</label>
    <summarizedField>Policy_AOP__c.Percentage__c</summarizedField>
    <summaryForeignKey>Policy_AOP__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Is_Allow_Calculate_Premium__c.field-meta.xml
<CustomField>
    <fullName>Is_Allow_Calculate_Premium__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is control field- when &quot;Calculate Premium&quot; button pressed then &quot;Is Allow Calculate Premium&quot; will be checked and calculate premium with apex, at last &quot;Is Allow Calculate Premium&quot; will be unchecked.</description>
    <label>Is Allow Calculate Premium</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EZ Renewal</fullName>
            </value>
            <value>
                <fullName>Regular Renewal</fullName>
            </value>
            <value>
                <fullName>Super EZ</fullName>
            </value>
            <value>
                <fullName>Online Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Total_Lawyers__c.field-meta.xml
<CustomField>
    <fullName>Total_Lawyers__c</fullName>
    <description>Count for total lawyers associated with Policy.</description>
    <label>Total Lawyers</label>
    <summaryForeignKey>Policy_Lawyer__c.Policy__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Total_Quotes__c.field-meta.xml
<CustomField>
    <fullName>Total_Quotes__c</fullName>
    <label>Total Quotes</label>
    <summaryForeignKey>Policy_Quote__c.Policy__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/QuickPolicyController.cls
public with sharing class QuickPolicyController {

    @AuraEnabled
    public static Policy__c getPolicy(Id policyId) {
        return [SELECT Id,Name,Renewal_Type__c,AOP_Percentage__c,Total_Lawyers__c,Total_Quotes__c,Is_Allow_Calculate_Premium__c  
                FROM Policy__c WHERE Id = :policyId];
    }
    
    @AuraEnabled
    public static List<Policy__c> getPolicies(Id policyId) {
        return [SELECT Id,Name,Renewal_Type__c,AOP_Percentage__c,Total_Lawyers__c,Total_Quotes__c,Is_Allow_Calculate_Premium__c  
                FROM Policy__c limit 500];
    }
    
    @AuraEnabled
    public static void updatePolicy(Id policyId){
        
        List<Policy__c> lstPolicy = [SELECT Id,Name,Renewal_Type__c,AOP_Percentage__c,Total_Lawyers__c,Total_Quotes__c,Is_Allow_Calculate_Premium__c  
                FROM Policy__c WHERE Id = :policyId];
                    
        lstPolicy[0].Is_Allow_Calculate_Premium__c = true;
        
        update lstPolicy;
    }
    
}