force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Billing__c.field-meta.xml
<CustomField>
    <fullName>Billing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing</label>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Bound_Date__c.field-meta.xml
<CustomField>
    <fullName>Bound_Date__c</fullName>
    <label>Bound Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Is_Canceled__c.field-meta.xml
<CustomField>
    <fullName>Is_Canceled__c</fullName>
    <formula>IF (ISNULL(Cancel_Date__c), false, true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Canceled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Email_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Email_Date__c</fullName>
    <label>Policy Email Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/classes/SendPolicyDocumentsBatch.cls
global class SendPolicyDocumentsBatch implements Database.Batchable<SObject> ,Schedulable , Database.AllowsCallouts{
    
    global String query{get;set;}
    global Set<String> recIds{get;set;}
    
    global SendPolicyDocumentsBatch(String query){
        this.query = query;
    }
    global SendPolicyDocumentsBatch(){
        this.query = null;
    }
    
    global SendPolicyDocumentsBatch(Set<String> recIds){
        this.query = null;
        this.recIds = recIds;
    }
    global Database.QueryLocator start(Database.BatchableContext bc){
        Date dt = system.today().addDays(-10);
        if(query == null){
            query = 'SELECT Id FROM Policy__c WHERE Is_Canceled__c = false And RecordType.Name = \'Policy\' AND Bound_Date__c < TODAY AND Policy_Email_Date__c = Null AND Billing__r.Computed_Payment_Frequency__c = NULL';
        }
        if(recIds != null && !recIds.isEmpty()){
            query += ' AND Id IN : recIds';             
        }
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Policy__c> objList){
        for(policy__c obj : objList){
            SendEmailExt.EmailWrapper  emWrp= SendEmailExt.getDetails(obj.Id, 'printPolicyDocs');
            SendEmailExt.SendEmail(emWrp, 'printPolicyDocs');
        }        
    }
    
    global void finish(Database.BatchableContext bc){}
    
    global void execute(SchedulableContext SC) {
        SendPolicyDocumentsBatch b = new SendPolicyDocumentsBatch(); 
        Database.executeBatch(b,Integer.valueOf(label.SendPolicyDocsLimit));
    }    
}