force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <description>Type of application that is being created.</description>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Name__c.field-meta.xml
<CustomField>
    <fullName>Firm_Name__c</fullName>
    <formula>Account__r.Name</formula>
    <label>Firm Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Sales_User__c.field-meta.xml
<CustomField>
    <fullName>Sales_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Terms_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_Conditions__c</fullName>
    <label>Terms &amp; Conditions</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter_User__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Underwriter User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/globalValueSets/Application_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Business</fullName>
        <default>true</default>
        <label>New Business</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <description>This global list will hold the values of Application type.</description>
    <masterLabel>Application Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Terms_Of_Service_Template_Ctrl.cls
public class Terms_Of_Service_Template_Ctrl {
	public String recordId;
    public Policy__c policy{get;set;}
    public void setrecordId(String recordId){
        policy = [select id, 
                  Terms_Conditions__C, 
                  FIRM_NAME__c, 
                  Underwriter_User__r.LastName, 
                  Underwriter_User__r.FirstName, 
                  Underwriter_User__r.Title, 
                  Underwriter_User__r.Phone, 
                  Underwriter_User__r.Email,
                  Application_Type__c,
                  Sales_User__r.LastName, 
                  Sales_User__r.FirstName, 
                  Sales_User__r.Title,
                  Sales_User__r.Phone, 
                  Sales_User__r.Email,
                  NAME,Sales_User__c from Policy__C 
                  where id=: recordId];
    }
    public String getrecordId(){
        return recordId;
    }
}