force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Policy_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <label>App Sent</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Requested Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Quoted</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>Lost</label>
    </customValue>
    <customValue>
        <fullName>Bound</fullName>
    </customValue>
    <customValue>
        <fullName>Printed</fullName>
    </customValue>
    <customValue>
        <fullName>Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Pending</fullName>
        <isActive>false</isActive>
        <label>Quote Pending</label>
    </customValue>
    <masterLabel>Policy Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CM_ApplicationDetailCTRL.cls
public with sharing class CM_ApplicationDetailCTRL {
    
    public list<string> statusList {get; set;}
    public string jsonString{get; set;}
    
    public CM_ApplicationDetailCTRL(Apexpages.standardController con){
    	statusList = new list<string>();
    	jsonString = '';
        SObjectType accountType = Schema.getGlobalDescribe().get('Policy__c');
        
        //-------checking recordtypes for this object
        //GetAvailableRecordTypeNamesForSObject(accountType);
        //------------ends here---------------//
        
            Schema.SObjectField mfields = accountType.getDescribe().fields.getMap().get('Status__c');
            Map<String,Schema.SObjectField> mfields2 = accountType.getDescribe().fields.getMap();
            Schema.DescribeFieldResult  describeResult = mFields.getDescribe();
            if(describeResult.getType() == Schema.DisplayType.Picklist && describeResult.isAccessible()){
                List<Schema.PicklistEntry> P = describeResult.getPicklistValues();
                for(Schema.PicklistEntry p_temp : p){
                    if(p_temp.isActive()){
                        statusList.add(p_temp.getValue());
                    }
                    
                }
               
            }
            jsonString = JSON.serialize(statusList);
       
    }
}