force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Incurred_Direct_LAE__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Direct_LAE__c</fullName>
    <label>Expense</label>
    <summarizedField>Policy_Claim__c.Incurred_Direct_LAE__c</summarizedField>
    <summaryForeignKey>Policy_Claim__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Payment_Direct_LAE__c.field-meta.xml
<CustomField>
    <fullName>Payment_Direct_LAE__c</fullName>
    <label>Payment Direct LAE</label>
    <summarizedField>Policy_Claim__c.Payment_Direct_LAE__c</summarizedField>
    <summaryForeignKey>Policy_Claim__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Payment_Direct_Loss__c.field-meta.xml
<CustomField>
    <fullName>Payment_Direct_Loss__c</fullName>
    <label>Indemnity</label>
    <summarizedField>Policy_Claim__c.Payment_Direct_Loss__c</summarizedField>
    <summaryForeignKey>Policy_Claim__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Remaining_By_All_Claims__c.field-meta.xml
<CustomField>
    <fullName>Policy_Remaining_By_All_Claims__c</fullName>
    <formula>Aggregate_Limit__c -   All_Claims_Incurred__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is to identify the type of record, the formula get the record type name that tell the type to be &apos;Application&apos; or &apos;Policy&apos;.</description>
    <formula>RecordType.Name</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Ceded_Cutoff_Amount__c.field-meta.xml
<CustomField>
    <fullName>Ceded_Cutoff_Amount__c</fullName>
    <formula>Policy__r.Treaty_Version__r.Reinsurance_Limit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ceded Cutoff Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Invoice</fullName>
            </value>
            <value>
                <fullName>Pending Close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_2100__c.field-meta.xml
<CustomField>
    <fullName>GL_2100__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 2100</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_2120__c.field-meta.xml
<CustomField>
    <fullName>GL_2120__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 2120</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_2140__c.field-meta.xml
<CustomField>
    <fullName>GL_2140__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 2140</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_2160__c.field-meta.xml
<CustomField>
    <fullName>GL_2160__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 2160</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5000__c.field-meta.xml
<CustomField>
    <fullName>GL_5000__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5000</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5010__c.field-meta.xml
<CustomField>
    <fullName>GL_5010__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5010</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5030__c.field-meta.xml
<CustomField>
    <fullName>GL_5030__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5030</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5035__c.field-meta.xml
<CustomField>
    <fullName>GL_5035__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5035</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5050__c.field-meta.xml
<CustomField>
    <fullName>GL_5050__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5050</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5060__c.field-meta.xml
<CustomField>
    <fullName>GL_5060__c</fullName>
    <label>GL 5060</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incurred_Direct_LAE__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Direct_LAE__c</fullName>
    <formula>Unpaid_Reserves_Direct_LAE__c +
Payment_Direct_LAE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incurred Direct LAE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incurred_Direct_Loss__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Direct_Loss__c</fullName>
    <formula>Unpaid_Reserves_Direct_Loss__c +
Payment_Direct_Loss__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incurred Direct Loss</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incurred_Email_Send__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Email_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Incurred Email Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incurred_Total__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Total__c</fullName>
    <formula>LAE_Incurred_Total__c +  Loss_Incurred_Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incurred Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Payment_Direct_LAE__c.field-meta.xml
<CustomField>
    <fullName>Payment_Direct_LAE__c</fullName>
    <label>Payment Direct LAE</label>
    <summarizedField>Policy_Claim_Detail__c.LAE_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Claim_Detail__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Claim Payment</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Claim_Detail__c.Policy_Claim__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Payment_Direct_Loss__c.field-meta.xml
<CustomField>
    <fullName>Payment_Direct_Loss__c</fullName>
    <label>Payment Direct Loss</label>
    <summarizedField>Policy_Claim_Detail__c.Loss_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Claim_Detail__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Claim Payment</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Claim_Detail__c.Policy_Claim__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Per_Claim_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Deductible__c</fullName>
    <label>Per Claim Deductible</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy_Remaining_By_All_Claims__c.field-meta.xml
<CustomField>
    <fullName>Policy_Remaining_By_All_Claims__c</fullName>
    <formula>Aggregate_Limit_For_All_Claims__c -
 Policy_Incurred__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Reserve_LAE__c.field-meta.xml
<CustomField>
    <fullName>Reserve_LAE__c</fullName>
    <defaultValue>$Setup.Claim_Setting__c.Open_Reserve_LAE_Value__c</defaultValue>
    <label>zzzOpen Reserve LAE</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Reserve_Loss__c.field-meta.xml
<CustomField>
    <fullName>Reserve_Loss__c</fullName>
    <defaultValue>$Setup.Claim_Setting__c.Open_Reserve_Loss_Value__c</defaultValue>
    <label>zzzOpen Reserve Loss</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Unpaid_Reserves_Direct_LAE__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Reserves_Direct_LAE__c</fullName>
    <formula>Total_Reserve_Direct_LAE__c -
  Payment_Direct_LAE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Reserves Direct LAE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Unpaid_Reserves_Direct_Loss__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Reserves_Direct_Loss__c</fullName>
    <formula>Total_Reserve_Direct_Loss__c -
  Payment_Direct_Loss__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Reserves Direct Loss</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/Policy_Claim_Detail__c.object-meta.xml
<CustomObject>
    <label>Policy Claim Detail</label>
    <nameField>
        <displayFormat>Claim-{0000000}</displayFormat>
        <label>Claim Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Claims Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/LAE_Amount__c.field-meta.xml
<CustomField>
    <fullName>LAE_Amount__c</fullName>
    <label>LAE Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Loss_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loss_Amount__c</fullName>
    <label>Loss Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Policy_Claim__c.field-meta.xml
<CustomField>
    <fullName>Policy_Claim__c</fullName>
    <label>Policy Claim</label>
    <referenceTo>Policy_Claim__c</referenceTo>
    <relationshipLabel>Claims Detail</relationshipLabel>
    <relationshipName>Policy_Claims_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Reinsurance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reinsurance_Amount__c</fullName>
    <label>Reinsurance Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reserve_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/recordTypes/Reserve.recordType-meta.xml
<RecordType>
    <fullName>Reserve</fullName>
    <active>true</active>
    <description>1) Increase Reserve(User Reserve)  2) Close/Re-Open Reserve</description>
    <label>Reserve</label>
</RecordType>

force-app/main/default/globalValueSets/Reserve_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>User Reserve</fullName>
        <label>Change Reserve</label>
    </customValue>
    <customValue>
        <fullName>Close Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Reopen Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Loss Payment</fullName>
    </customValue>
    <customValue>
        <fullName>LAE Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Deductible Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Deductible Expense</fullName>
    </customValue>
    <customValue>
        <fullName>Change in Ceded Loss Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Change in Ceded LAE Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Due from Reins. - Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Due from Reins. - LAE</fullName>
    </customValue>
    <customValue>
        <fullName>Open Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Claim Coverage - ARDC</fullName>
        <label>ARDC Payment</label>
    </customValue>
    <customValue>
        <fullName>Unallocated LAE Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Deductible Expense New</fullName>
    </customValue>
    <customValue>
        <fullName>SBL</fullName>
    </customValue>
    <customValue>
        <fullName>CPSBL</fullName>
    </customValue>
    <customValue>
        <fullName>CPSBE</fullName>
    </customValue>
    <masterLabel>Reserve Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuickClaimController.cls
public with sharing class QuickClaimController {
    public static Date transDate;
    @AuraEnabled
    public static Policy_Claim__c getClaim(Id claimId) {
        // Perform isAccessible() checks here
        return [SELECT Id,Name,Policy__c,Policy__r.Account__c,Unpaid_Reserves_Direct_Loss__c,Claim_Status__c,
                Unpaid_Reserves_Direct_LAE__c,Payment_Direct_Loss__c,Payment_Direct_LAE__c,Incurred_Direct_Loss__c,Incurred_Direct_LAE__c,
                Reserve_Loss__c,Reserve_LAE__c,GL_2100__c,GL_2140__c,GL_5000__c,GL_5030__c,GL_5050__c,GL_5060__c,Ceded_Cutoff_Amount__c,Per_Claim_Deductible__c,GL_2120__c,GL_2160__c,GL_5010__c,GL_5035__c, Policy_Remaining_By_All_Claims__c  FROM Policy_Claim__c WHERE Id = :claimId];
    }
    @AuraEnabled
    public static String updateReserve(Decimal lossReserve,Decimal laeReserve,Policy_Claim__c claim,Date transactionDate) {
        try{
            if(transactionDate == null){
                system.debug('---ex------');
                throw new AuraHandledException('Invalid Transaction Date!');
            }
            transDate = transactionDate;
            Date startDate = transactionDate.toStartOfMonth();
            Date endDate = startDate.addMonths(1).addDays(-1);
     // Validate accounting period 
            List<AcctSeed__Accounting_Period__c> periods = [Select ID from AcctSeed__Accounting_Period__c where AcctSeed__Status__c = 'Open' 
                                                            and AcctSeed__Start_Date__c = :startDate AND AcctSeed__End_Date__C = :endDate];
            
            if(periods.size() == 0) throw new AuraHandledException('Accounting period not open for transaction!');
            
            System.debug(claim.Reserve_Loss__c);
            
            //claim.Reserve_Loss__c = claim.Reserve_Loss__c + (lossReserve - Math.abs(claim.GL_2100__c));
            
            //Decimal changeLossReserve =  (lossReserve - (Math.abs(claim.GL_5010__c) + Math.abs(claim.GL_5000__c)));
            Decimal changeLossReserve =  (lossReserve - (claim.GL_5010__c + claim.GL_5000__c));
            
            if(lossReserve - claim.GL_5000__c < 0){
                String str = 'Claim Loss Reserve Can not be in negative.';
                AuraHandledException auraEx = new AuraHandledException(str);
                auraEx.setMessage(str);
                throw auraEx;
            }
            
            //claim.Reserve_LAE__c = claim.Reserve_LAE__c + (laeReserve - Math.abs(claim.GL_2140__c));
            //Decimal changeLAEReserve = (laeReserve - (Math.abs(claim.GL_5035__c) + Math.abs(claim.GL_5030__c)));
            Decimal changeLAEReserve = (laeReserve - (claim.GL_5035__c + claim.GL_5030__c));
            
            if(laeReserve - claim.GL_5030__c < 0){
                String str = 'Claim LAE Reserve Can not be in negative.';
                AuraHandledException auraEx = new AuraHandledException(str);
                auraEx.setMessage(str);
                throw auraEx;
            }
            System.debug(changeLossReserve);
            System.debug(changeLAEReserve);
            System.debug(claim.Policy_Remaining_By_All_Claims__c);
            if(changeLossReserve + changeLAEReserve > claim.Policy_Remaining_By_All_Claims__c){
                throw new AuraHandledException('Loss Incurred and LAE Incurred cannot exceed policy limit.');
            }
            
            //upsert claim;
            
            List<Policy_Claim_Detail__c> PCDLst = new List<Policy_Claim_Detail__c>();
            if(changeLossReserve != 0 || changeLAEReserve != 0){
                Decimal reserveLoss = claim.GL_5010__c;
                Decimal reserveLae = claim.GL_5035__c;
                if(changeLossReserve != 0){
                    PCDLst.add(new Policy_Claim_Detail__c(
                        Policy_Claim__c = claim.ID,
                        Loss_Amount__c  = changeLossReserve,
                        Date__c         =  transactionDate,
                        Type__c         =  'User Reserve',
                        RecordTypeId    =  Policy_Claim_Gateway.ReserveRTID) );
                    reserveLoss += changeLossReserve;
                }
                if(changeLAEReserve != 0){
                    PCDLst.add(new Policy_Claim_Detail__c(
                        Policy_Claim__c = claim.ID,
                        LAE_Amount__c   =  changeLAEReserve,
                        Date__c         =  transactionDate,
                        Type__c         =  'User Reserve',
                        RecordTypeId    =  Policy_Claim_Gateway.ReserveRTID) );
                    reserveLae += changeLAEReserve;
                }
                
                
                Decimal cededLoss = 0 ;
                Decimal cededLAE = 0 ;
                
                if(( reserveLoss + reserveLae) >= ((claim.Ceded_Cutoff_Amount__c !=null ? claim.Ceded_Cutoff_Amount__c : 0) + (claim.Per_Claim_Deductible__c !=null ? claim.Per_Claim_Deductible__c : 0))){
                    Decimal lossProRata = (claim.GL_5000__c + reserveLoss) / ( reserveLoss + reserveLae);
                    Decimal laeProRata = 1 - lossProRata;
                    Decimal totalCeded = ((claim.Ceded_Cutoff_Amount__c !=null ? claim.Ceded_Cutoff_Amount__c : 0) + (claim.Per_Claim_Deductible__c !=null ? claim.Per_Claim_Deductible__c : 0)) - ( reserveLoss + reserveLae);
                    cededLoss = totalCeded * lossProRata;
                    cededLAE = totalCeded * laeProRata;
                    
                    cededLoss = cededLoss - claim.GL_2120__c;
                    cededLAE = cededLAE - claim.GL_2160__c;
                    
                }else if(( claim.GL_5010__c + claim.GL_5035__c) >= ((claim.Ceded_Cutoff_Amount__c !=null ? claim.Ceded_Cutoff_Amount__c : 0) + (claim.Per_Claim_Deductible__c !=null ? claim.Per_Claim_Deductible__c : 0))){
                    cededLoss = - claim.GL_2120__c;
                    cededLAE = - claim.GL_2160__c;
                }
                
                if(cededLoss != 0){
                    PCDLst.add(new Policy_Claim_Detail__c(
                        Policy_Claim__c = claim.ID,
                        //Reinsurance_Amount__c  = (claim.Reserve_Loss__c - oldItems.get(claim.id).Reserve_Loss__c)==0?null:(claim.Reserve_Loss__c - oldItems.get(claim.id).Reserve_Loss__c),
                        Reinsurance_Amount__c  = cededLoss,
                        Date__c         =  transactionDate,
                        Type__c         =  'Change in Ceded Loss Reserve',
                        RecordTypeId    =  Policy_Claim_Gateway.ReinsuranceRTID) );
                }
                if(cededLAE != 0){
                    PCDLst.add(new Policy_Claim_Detail__c(
                        Policy_Claim__c = claim.ID,
                        //Reinsurance_Amount__c   =  (claim.Reserve_LAE__c - oldItems.get(claim.id).Reserve_LAE__c)==0?null:(claim.Reserve_LAE__c - oldItems.get(claim.id).Reserve_LAE__c),
                        Reinsurance_Amount__c   =  cededLAE,
                        Date__c         =  transactionDate,
                        Type__c         =  'Change in Ceded LAE Reserve',
                        RecordTypeId    =  Policy_Claim_Gateway.ReinsuranceRTID) );
                }
            }
            
            If(PCDLst.size()>0){
                Database.insert(PCDLst);    
            }
            
            Policy_Claim__c claimObj = [SELECT Id, Incurred_Total__c,Incurred_Email_Send__c FROM Policy_Claim__c WHERE Id=:claim.Id];
            if(!claimObj.Incurred_Email_Send__c && claimObj.Incurred_Total__c >= 250000){
                Boolean success = sendEmailAlert(new Set<String>{claimObj.Id}, 'Incurred_Total_alert_email');
                if(success){
                    claimObj.Incurred_Email_Send__c = true;
                    update claimObj;
                }
            }
            else if(claimObj.Incurred_Total__c < 250000 && claimObj.Incurred_Email_Send__c){
                claimObj.Incurred_Email_Send__c = false;
                update claimObj;
            }
    
            return 'Success';
        }catch(Exception e){
            system.debug('---ex1------'+e);
            system.debug('---ex2------'+e.getLineNumber());
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString()) ;
        }
    }
    
    @AuraEnabled
    public static void updateClaimSummary(Id claimId){
        try{
            Policy_Claim__c claim = new Policy_Claim__c(Id=claimId);
            Batch_MassUpdateClaimSummary claimSummary = new Batch_MassUpdateClaimSummary();
            claimSummary.updateClaimSummary(new Policy_Claim__c[]{claim});
        }catch(Exception e){
            system.debug('---ex1------'+e);
            system.debug('---ex2------'+e.getLineNumber());
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString()) ;
        }
    }
    
    public static Boolean sendEmailAlert(Set<String> recIds , String emailTemplateName){
        if(String.isNotBlank(label.Claim_Email_Alert_send_to_email)){ 
            
            List<EmailTemplate> templateList = [SELECT Id FROM EmailTemplate WHERE DeveloperName =:emailTemplateName LIMIT 1];
            if(!templateList.isEmpty()){
                List<string> toAddress = new List<string>();
                toAddress.add(label.Claim_Email_Alert_send_to_email);
                
                List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
                for(String recId : recIds){
                    Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(templateList[0].Id,userInfo.getUserId() ,recId);
                    Messaging.SingleEmailMessage mailTOSend = new Messaging.SingleEmailMessage();
                    
                    mailTOSend.setToAddresses(toAddress);
                    mailTOSend.setSubject(mail.getSubject());
                    mailTOSend.setHtmlBody(mail.getHtmlBody());
                    mailTOSend.setOrgWideEmailAddressId([select Id,Address from OrgWideEmailAddress where Address ='claims@isbamutual.com'].Id);
                    mailTOSend.setSaveAsActivity(false);
                    allmsg.add(mailTOSend);
                }
                try {
                    Messaging.SendEmailResult [] r = Messaging.sendEmail(allmsg);
                    system.debug(r[0]);
                    return r[0].isSuccess();
                } catch (Exception e) {
                    System.debug(e.getMessage());
                }
            }
        }  
        return false;
    }
}