force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Aggregate_Limit__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Limit__c</fullName>
    <label>Aggregate Limit</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Name__c.field-meta.xml
<CustomField>
    <fullName>Firm_Name__c</fullName>
    <formula>Account__r.Name</formula>
    <label>Firm Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Incurred_Direct_LAE__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Direct_LAE__c</fullName>
    <label>Expense</label>
    <summarizedField>Policy_Claim__c.Incurred_Direct_LAE__c</summarizedField>
    <summaryForeignKey>Policy_Claim__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Payment_Direct_LAE__c.field-meta.xml
<CustomField>
    <fullName>Payment_Direct_LAE__c</fullName>
    <label>Payment Direct LAE</label>
    <summarizedField>Policy_Claim__c.Payment_Direct_LAE__c</summarizedField>
    <summaryForeignKey>Policy_Claim__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Payment_Direct_Loss__c.field-meta.xml
<CustomField>
    <fullName>Payment_Direct_Loss__c</fullName>
    <label>Indemnity</label>
    <summarizedField>Policy_Claim__c.Payment_Direct_Loss__c</summarizedField>
    <summaryForeignKey>Policy_Claim__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Aggregate_Limit__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Limit__c</fullName>
    <label>Aggregate Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claim</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Closed__c.field-meta.xml
<CustomField>
    <fullName>Claim_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It close via Reserve-Close</description>
    <label>Is Claim Closed for Reserve</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Made_Date__c.field-meta.xml
<CustomField>
    <fullName>Claim_Made_Date__c</fullName>
    <label>Claim Made Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Firm_Name__c.field-meta.xml
<CustomField>
    <fullName>Firm_Name__c</fullName>
    <formula>BLANKVALUE(Claim_Firm_Name__c, Policy__r.Account__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incurred_Direct_LAE__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Direct_LAE__c</fullName>
    <formula>Unpaid_Reserves_Direct_LAE__c +
Payment_Direct_LAE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incurred Direct LAE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incurred_Direct_Loss__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Direct_Loss__c</fullName>
    <formula>Unpaid_Reserves_Direct_Loss__c +
Payment_Direct_Loss__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incurred Direct Loss</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/LAE_Pay__c.field-meta.xml
<CustomField>
    <fullName>LAE_Pay__c</fullName>
    <label>LAE Pay</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Lawyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Name__c</fullName>
    <formula>LawyerNew__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lawyer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Payment_Direct_LAE__c.field-meta.xml
<CustomField>
    <fullName>Payment_Direct_LAE__c</fullName>
    <label>Payment Direct LAE</label>
    <summarizedField>Policy_Claim_Detail__c.LAE_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Claim_Detail__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Claim Payment</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Claim_Detail__c.Policy_Claim__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Payment_Direct_Loss__c.field-meta.xml
<CustomField>
    <fullName>Payment_Direct_Loss__c</fullName>
    <label>Payment Direct Loss</label>
    <summarizedField>Policy_Claim_Detail__c.Loss_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Claim_Detail__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Claim Payment</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Claim_Detail__c.Policy_Claim__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <label>Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Unpaid_Reserves_Direct_LAE__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Reserves_Direct_LAE__c</fullName>
    <formula>Total_Reserve_Direct_LAE__c -
  Payment_Direct_LAE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Reserves Direct LAE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Unpaid_Reserves_Direct_Loss__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Reserves_Direct_Loss__c</fullName>
    <formula>Total_Reserve_Direct_Loss__c -
  Payment_Direct_Loss__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Reserves Direct Loss</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Unpaid_Reserves_Retained_LAE__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Reserves_Retained_LAE__c</fullName>
    <formula>Unpaid_Reserves_Direct_LAE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Reserves Retained LAE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CM_AccountPayable_edit_controller.cls
/*************************************************************
    @Company        : HIC Global Solutions
    @Author         : Sachin Arora(arora.s@head-in-cloud.com)
    @Created Date   : 02/22/2017
    @Desciption     :   This class acts as a controller for 
                        AccountPayable Edit Page.
    @TestClass Name : 
    Version          Developer                    Date                        Description
*-------------------------------------------------------------------------------------------
*     1.0            sachin                       21-Feb-2017                   Initial Creation 
***************************************************************************************************/

public class CM_AccountPayable_edit_controller {

    public AcctSeed__Account_Payable__c accPayableObj{get;set;}
    public Account accountObj{get;set;}
    public Policy_Claim__c claimObj{get;set;}
    public Policy__c policyObj{get;set;}
    public string indexOfLineItemToBeRemoved {get; set;}
    public String selectedAppPolicy{get;set;}
    public String selectedPolicyClaimId{get;set;}
    public String selectedVendorId{get;set;}
    public list<HIC_AccountPayableLineItemWrapper> accPayLineWrapList{get;set;}
    
    public list<SelectOption> ClaimOptions{get;set;}    
    
    
    //Standard Controller Constructor
    public CM_AccountPayable_edit_controller(ApexPages.StandardController stdController){
    
        claimObj = new Policy_Claim__c();
        policyObj = new Policy__c();
        accPayableObj = (AcctSeed__Account_Payable__c)stdController.getRecord();
        onVendorSelect();
        selectedAppPolicy = accPayableObj.Policy__c;
        onPolicyOptionChange();
        selectedPolicyClaimId = accPayableObj.Claim__c;
        onClaimOptionChange();
        system.debug('***selectedPolicyClaimId---'+selectedPolicyClaimId);
        init();
    }
    
    //initialize function
    public void init(){
        accPayLineWrapList = new list<HIC_AccountPayableLineItemWrapper>();
        showExistingAccPaayableLine();
    }
    
    public void showExistingAccPaayableLine(){
        String accPyableId = apexpages.currentpage().getparameters().get('id');
        if(accPyableId!=null && accPyableId!=''){
            for(AcctSeed__Account_Payable_Line__c accPayLineObj :[Select Id,
                                                                         AcctSeed__Expense_GL_Account__c,
                                                                         AcctSeed__Amount__c                                                                         
                                                                         FROM AcctSeed__Account_Payable_Line__c
                                                                         WHERE AcctSeed__Account_Payable__c=:accPyableId]){
                accPayLineWrapList.add(new HIC_AccountPayableLineItemWrapper(accPayLineObj));
            }
        
        }               
               
    }
    
     public List<SelectOption> getVendorAccountOptions() {
        
        List<SelectOption> options = new List<SelectOption>();
            
            for(Account obj :[Select id,Name,Vendor_Account__c
                                             FROM Account 
                                             WHERE Vendor_Account__c =True]){
                                                
                options.add(new SelectOption(obj.Id,obj.Name));
            }
            
            return options;
        
    }
    
    //method to show vendor details on vendor select
    public void onVendorSelect(){
        
        system.debug('********');
        system.debug('vendor id****'+accPayableObj.AcctSeed__Vendor__c+'**********'+accPayableObj.AcctSeed__Payee_Reference__c);
       //claimObj = new Policy_Claim__c();
       accountObj = new Account();
       //selectedPolicyClaimId ='';
       
        if(accPayableObj.AcctSeed__Vendor__c != null){
            list<Account> accList = new list<Account>([Select Id,
                                                              Name,
                                                              AccountNumber,
                                                              AcctSeed__Accounting_Type__c,
                                                              AcctSeed__X1099_Vendor__c,
                                                              BillingCountry,
                                                              BillingStreet,
                                                              BillingCity,
                                                              type,
                                                              BillingState 
                                                              FROM Account 
                                                              WHERE Id=:accPayableObj.AcctSeed__Vendor__c]);
            
            if(!accList.isEmpty()){
                accountObj = accList.get(0);
                system.debug('accountObj ****'+accountObj.BillingStreet+'***'+accountObj.BillingState+'****'+accountObj.BillingCity);
                
                 if(accPayableObj.Claim__c == null){
            
                        accPayableObj.AcctSeed__Payee_Reference__c = accountObj.Name +' - '+Date.today().format();
                
                }
            } else {
                
                if(accPayableObj.Claim__c == null){
            
                        accPayableObj.AcctSeed__Payee_Reference__c = '';
                
                }
            }
            
            //getAppPolicyOptions();
        }
        else{
                 accountObj = new Account();
                 if(accPayableObj.Claim__c == null){
            
                        accPayableObj.AcctSeed__Payee_Reference__c = '';
                
                 }
            }
    }
    
    
     public void onPolicyOptionChange(){
         
         accPayableObj.Policy__c = selectedAppPolicy;
         
         List<Policy__c> policyList = [SELECT Id,Name FROM Policy__c WHERE Id =: selectedAppPolicy LIMIT 1];
         
         if(!policyList.isEmpty()){
             policyObj = policyList.get(0);
         }
          
         
     }   
     
     //system.debug('***selectedPolicyClaimId---'+selectedPolicyClaimId);
     
    //Method on change of claim select option
    public void onClaimOptionChange(){
    system.debug('***selectedPolicyClaimId---'+selectedPolicyClaimId);
        if(selectedPolicyClaimId!=null && selectedPolicyClaimId!=''){
            list<Policy_Claim__c> policyClaimList = new list<Policy_Claim__c>([Select Id,
                                                                                      Firm_Name__c, 
                                                                                      Claim_Made_Date__c,
                                                                                      Aggregate_Limit__c,
                                                                                      Report_Date__c,
                                                                                      LAE_Pay__c,
                                                                                      Lawyer_Name__c,
                                                                                      Claim_Closed__c,
                                                                                      Unpaid_Reserves_Direct_Loss__c,
                                                                                      Unpaid_Reserves_Direct_LAE__c,
                                                                                      Payment_Direct_Loss__c,
                                                                                      Payment_Direct_LAE__c,
                                                                                      Incurred_Direct_Loss__c,
                                                                                      Incurred_Direct_LAE__c,
                                                                                      Unpaid_Reserves_Retained_LAE__c,
                                                                                      Name
                                                                                      FROM Policy_Claim__c
                                                                                      WHERE Id =: selectedPolicyClaimId]);
            if(!policyClaimList.isEmpty()){
                claimObj = policyClaimList.get(0);
            }                                                                                      
        }
        else{
             claimObj = new Policy_Claim__c();
        }
    
    }
    
    
    // For Updating account Payable
    public pagereference onUpdateClick(){
       //Savepoint sp = Database.setSavepoint();
      try{
         accPayableObj.Policy__c = selectedAppPolicy;
         accPayableObj.Claim__c = selectedPolicyClaimId;
        update accPayableObj; 
            if(!accPayLineWrapList.isEmpty()){
                list<AcctSeed__Account_Payable_Line__c> payLineListToUpsert = new list<AcctSeed__Account_Payable_Line__c>();
                for(HIC_AccountPayableLineItemWrapper wrapObj : accPayLineWrapList ){
                    AcctSeed__Account_Payable_Line__c accLineObj =  wrapObj.accPayabaleObj;
                    
                    payLineListToUpsert.add(accLineObj);
                }
                if(!payLineListToUpsert.isEmpty()){
                    upsert payLineListToUpsert;
                }
            }
        return new ApexPages.StandardController(accPayableObj).view();
      }catch(Exception e){
          system.Debug('***excep**'+e);
          //Database.rollback(sp);
          system.Debug('**accPayableObj***'+accPayableObj);
        return null;
      }
    }
    
    //Method for removing line item row
     public void removeLineItemRow(){
      system.debug('---inside new row'+indexOfLineItemToBeRemoved);
     if(indexOfLineItemToBeRemoved != null && null != accPayLineWrapList.get(integer.valueOf(indexOfLineItemToBeRemoved))){
        HIC_AccountPayableLineItemWrapper accWrapObj = accPayLineWrapList.get(integer.valueOf(indexOfLineItemToBeRemoved));
            if(accWrapObj.accPayabaleObj!=null && null != accWrapObj.accPayabaleObj.id){
                try{
                    delete accWrapObj.accPayabaleObj;
                }   
                catch(Exception exp){
                    system.debug('**error in deleting**'+exp.getMessage());
                }
            }
        accPayLineWrapList.remove(integer.valueOf(indexOfLineItemToBeRemoved));
      }
    }
    
    //Method for adding new line item row
    public void addAccPayNewLine(){
        String accPyableId = apexpages.currentpage().getparameters().get('id');
        if(accPyableId!=null && accPyableId!=''){
            AcctSeed__Account_Payable_Line__c accLineObj = new AcctSeed__Account_Payable_Line__c();
            accLineObj.AcctSeed__Quantity__c =1;
            accLineObj.AcctSeed__Amount__c =0.0;
            accLineObj.AcctSeed__Account_Payable__c = accPyableId;
            accLineObj.AcctSeed__Date__c = date.today();
            accPayLineWrapList.add(new HIC_AccountPayableLineItemWrapper(accLineObj));
        }
    }
    
    
     
    //Wrapper Class to bind line items
    public class HIC_AccountPayableLineItemWrapper{
        public AcctSeed__Account_Payable_Line__c accPayabaleObj{get;set;}
        public HIC_AccountPayableLineItemWrapper(AcctSeed__Account_Payable_Line__c accPayabaleObj){
            this.accPayabaleObj = accPayabaleObj;
        }
    }
}