force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incident</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Suit</fullName>
            </value>
            <value>
                <fullName>ARDC Complaint</fullName>
            </value>
            <value>
                <fullName>Memo</fullName>
            </value>
            <value>
                <fullName>Supoena</fullName>
                <label>Subpoena</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Occur_Date__c.field-meta.xml
<CustomField>
    <fullName>Occur_Date__c</fullName>
    <label>Occur Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <label>Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Related_Claim__c/Related_Claim__c.object-meta.xml
<CustomObject>
    <label>Related Claim</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Related Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Claim__c/fields/Claim1__c.field-meta.xml
<CustomField>
    <fullName>Claim1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Policy_Claim__c</referenceTo>
    <relationshipLabel>Related Claims</relationshipLabel>
    <relationshipName>Related_Claims</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Claim__c/fields/Claim2__c.field-meta.xml
<CustomField>
    <fullName>Claim2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Policy_Claim__c</referenceTo>
    <relationshipLabel>Related Claims (Claim)</relationshipLabel>
    <relationshipName>Related_Claims1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RelatedClaimsComponentHandler.cls
public class RelatedClaimsComponentHandler {
    @AuraEnabled
    public static List<Policy_Claim__c> getClaims(String recordId, boolean allRecords){
        String sObjName = ((Id)recordId).getSObjectType().getDescribe().getName();
        if(sObjName == 'Policy_Claim__c'){
            Set<Id> directRelatedClaimIds = new Set<Id>();
            Set<Id> allRelatedClaimIds = new Set<Id>();
            for(Related_Claim__c claim : [select Claim1__c,Claim2__c from Related_Claim__c where Claim1__c =: recordId or Claim2__c =: recordId ]){
                directRelatedClaimIds.add(claim.Claim1__c);
                directRelatedClaimIds.add(claim.Claim2__c);
            }
            for(Related_Claim__c claim : [select Claim1__c,Claim2__c from Related_Claim__c where Claim1__c in: directRelatedClaimIds or Claim2__c in: directRelatedClaimIds ]){
                if(claim.Claim1__c != recordId){
                    allRelatedClaimIds.add(claim.Claim1__c);
                }
                if(claim.Claim2__c != recordId){
                    allRelatedClaimIds.add(claim.Claim2__c);
                }
            }
            List<Policy_Claim__c> claims = new List<Policy_Claim__c>([select id,Name,File_Type__c,Policy__c,Report_Date__c,Occur_Date__c,Policy__r.Name from Policy_Claim__c where id in: allRelatedClaimIds]);
            return claims;
        }else if(sObjName == 'Policy__c'){
            Policy__c app = [select id,Account__c from Policy__c where id=:recordId ];
            List<Policy_Claim__c> claims = new List<Policy_Claim__c>([select id,Name,File_Type__c,Policy__c,Report_Date__c,Occur_Date__c,Policy__r.Name,Account__c from Policy_Claim__c where Account__c =: app.Account__c]);
            return claims;
        }else{
            List<Policy_Claim__c> claims = new List<Policy_Claim__c>();
            return claims;
        }
    }
    @AuraEnabled
    public static String typeOfRecord(String recordId){
        String sObjName = ((Id)recordId).getSObjectType().getDescribe().getName();
        return sObjName;
    }
}