force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Accounting_Processed__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accounting Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Treaty_Correction_Processed__c.field-meta.xml
<CustomField>
    <fullName>Treaty_Correction_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Treaty Correction Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Treaty_Version__c.field-meta.xml
<CustomField>
    <fullName>Treaty_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treaty Version</label>
    <referenceTo>Treaty_Versions__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Treaty_Versions__c/Treaty_Versions__c.object-meta.xml
<CustomObject>
    <label>Treaty Version</label>
    <nameField>
        <displayFormat>Treaty-{00}</displayFormat>
        <label>Master Treaty Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treaty Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treaty_Versions__c/fields/Treaty_Correction_Processed__c.field-meta.xml
<CustomField>
    <fullName>Treaty_Correction_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Treaty Correction Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProcessCededCorrectionCtrl.cls
public class ProcessCededCorrectionCtrl {
	@AuraEnabled
    public static void processCededTransactions(String recordId){
        Treaty_Versions__c treaty = [select id,Treaty_Correction_Processed__c from Treaty_Versions__c where id =: recordId];
        if(treaty.Treaty_Correction_Processed__c){
            throw new AuraHandledException('Ceded Transactions Already Created for this Treaty.') ;
        }else{
            List<Policy__c> policies = [select id from Policy__c where Treaty_Version__c =: recordId and Accounting_Processed__c = true and RecordType.Name = 'Policy'];
            Set<Id> policyIds = new Set<Id>();
            for(Policy__c pol : policies){
                policyIds.add(pol.Id);
            }
            Batch_CededTransactionCorrection batch = new Batch_CededTransactionCorrection(policyIds,'');
            Database.executeBatch(batch,10);
        }
    }
}