force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Accounting_Processed__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accounting Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Treaty_Correction_Processed__c.field-meta.xml
<CustomField>
    <fullName>Treaty_Correction_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Treaty Correction Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Treaty_Version__c.field-meta.xml
<CustomField>
    <fullName>Treaty_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treaty Version</label>
    <referenceTo>Treaty_Versions__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treaty_Versions__c/Treaty_Versions__c.object-meta.xml
<CustomObject>
    <label>Treaty Version</label>
    <nameField>
        <displayFormat>Treaty-{00}</displayFormat>
        <label>Master Treaty Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treaty Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treaty_Versions__c/fields/Treaty_Correction_Processed__c.field-meta.xml
<CustomField>
    <fullName>Treaty_Correction_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Treaty Correction Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProcessCededCorrectionCtrlTest.cls
@isTest
public class ProcessCededCorrectionCtrlTest {

   
    @isTest
    public static void testMethod1(){
        
        Treaty_Versions__c treatyObj = new Treaty_Versions__c();
        treatyObj.Treaty_Correction_Processed__c = false;
        insert treatyObj;
        
        Account accontObj = new Account();
        accontObj.Name = 'Test test';
        insert accontObj;
        
        Policy__c PolicyObj = new Policy__c();
        PolicyObj.Accounting_Processed__c = true;
        PolicyObj.Treaty_Version__c = treatyObj.id;
        PolicyObj.Account__c = accontObj.id;
        PolicyObj.Effective_Date__c = Date.newInstance(2016, 12, 9);
        insert PolicyObj;
        
        string recordId = treatyObj.id;
        
        Test.startTest(); 
        ProcessCededCorrectionCtrl.processCededTransactions(recordId) ;
        
        Test.stopTest();
        
    }
}