force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Invoice</fullName>
            </value>
            <value>
                <fullName>Pending Close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/ClaimCloseDAte__c.field-meta.xml
<CustomField>
    <fullName>ClaimCloseDAte__c</fullName>
    <label>Claim Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/ClaimType__c.field-meta.xml
<CustomField>
    <fullName>ClaimType__c</fullName>
    <label>ClaimType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incident</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Suit</fullName>
            </value>
            <value>
                <fullName>ARDC Complaint</fullName>
            </value>
            <value>
                <fullName>Memo</fullName>
            </value>
            <value>
                <fullName>Supoena</fullName>
                <label>Subpoena</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_2100__c.field-meta.xml
<CustomField>
    <fullName>GL_2100__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 2100</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_2140__c.field-meta.xml
<CustomField>
    <fullName>GL_2140__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 2140</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5000__c.field-meta.xml
<CustomField>
    <fullName>GL_5000__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5000</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5010__c.field-meta.xml
<CustomField>
    <fullName>GL_5010__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5010</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5030__c.field-meta.xml
<CustomField>
    <fullName>GL_5030__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5030</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5035__c.field-meta.xml
<CustomField>
    <fullName>GL_5035__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5035</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incurred_Total__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Total__c</fullName>
    <formula>LAE_Incurred_Total__c +  Loss_Incurred_Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incurred Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/LAE_Incurred_Total__c.field-meta.xml
<CustomField>
    <fullName>LAE_Incurred_Total__c</fullName>
    <formula>GL_5035__c +  GL_5030__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LAE Incurred Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/LAEPay__c.field-meta.xml
<CustomField>
    <fullName>LAEPay__c</fullName>
    <formula>ABS( GL_5030__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LAE Pay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Lawyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Name__c</fullName>
    <formula>LawyerNew__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lawyer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Loss_Incurred_Total__c.field-meta.xml
<CustomField>
    <fullName>Loss_Incurred_Total__c</fullName>
    <formula>GL_5010__c +  GL_5000__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loss Incurred Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Loss_Res__c.field-meta.xml
<CustomField>
    <fullName>Loss_Res__c</fullName>
    <formula>GL_5010__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loss Res</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Occur_Date__c.field-meta.xml
<CustomField>
    <fullName>Occur_Date__c</fullName>
    <label>Occur Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp;   Policy__c  , Policy__r.Policy_Number__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <label>Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ClaimHistoryComponentHandler.cls
public class ClaimHistoryComponentHandler {
	@AuraEnabled
    public static List<Policy_Claim__c> getClaims(String recordId, boolean allRecords){
        String sObjName = ((Id)recordId).getSObjectType().getDescribe().getName();
        String accId = '';
        List<Policy_Claim__c> policies = new List<Policy_Claim__c>();
        if(sObjName == 'Policy__c'){
            Policy__c policy = [select Id,Account__c from Policy__c where  id =: recordId];
            accId = policy.Account__c;
        }else if(sObjName == 'Policy_Claim__c'){
            Policy_Claim__c claim = [select Id,Policy__r.Account__c from Policy_Claim__c where id =: recordId];
            accId = claim.Policy__r.Account__c;
        }else if(sObjName == 'Account'){
            accId = recordId;
        }
        
        if(String.isNotBlank(accId)){
            policies = new List<Policy_Claim__c>([select Id,Name,Account__c,ClaimType__c,Report_Date__c,Claim_Status__c,Policy_Number__c,File_Type__c,Occur_Date__c,Policy__r.Name,Policy__c,GL_2100__c,GL_2140__c,GL_5000__c,GL_5030__c,GL_5010__c,GL_5035__c, Lawyer_Name__c,ClaimCloseDAte__c,LAE_Incurred_Total__c,Loss_Incurred_Total__c,Incurred_Total__c,LAEPay__c,Loss_Res__c   from Policy_Claim__c where Account__c =: accId order by Report_Date__c desc ]);
            return policies;
        }
        return policies;
    }
}