force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/ClonedBy__c.field-meta.xml
<CustomField>
    <fullName>ClonedBy__c</fullName>
    <label>Cloned By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal 3 Months Before Policy Expiration</fullName>
            </value>
            <value>
                <fullName>Clone Opportunity With Application</fullName>
            </value>
            <value>
                <fullName>Clone Opportunity Without Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Renew_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Renew_Status__c</fullName>
    <label>Policy Renew Status</label>
    <length>80000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Renew_Application__c.field-meta.xml
<CustomField>
    <fullName>Renew_Application__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is for the ability to add “Block” to Application Renewal. If the field is unchecked then the renewal processes with not fire, both manual and automated.</description>
    <label>Block Renewal of Policy With Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/classes/MassRenewalPolicyCtrl.cls
public class MassRenewalPolicyCtrl {
    public String error{get;set;}
    public String success{get;set;}
    List<Policy__c> selectedPolicies;
    public MassRenewalPolicyCtrl(ApexPages.StandardSetController controller){
        selectedPolicies = (List<Policy__c>)controller.getSelected();
    }
    public void massRenewPolicies(){
        if(selectedPolicies.size()>0){
            List<Policy__c> listPolicies = [SELECT id,name,ClonedBy__c,Policy_Renew_Status__c,Renew_Application__c,RecordType.Name  FROM Policy__c WHERE Id in: selectedPolicies];
            System.debug('listPolicies---'+listPolicies);
            List<Policy__c> policiesToUpdate = new List<Policy__c>();
            for(Policy__c pol:listPolicies){
                if(pol.RecordType.Name=='Policy'){
                    if(pol.Renew_Application__c){
                        pol.Policy_Renew_Status__c = 'Error : Application Renewal Blocked!';
                    }else if(pol.ClonedBy__c == 'Manual Renewal' || pol.ClonedBy__c == 'Renewal 3 Months Before Policy Expiration'){
                        pol.Policy_Renew_Status__c = 'Error : '+'Policy Already Renewed by ' + pol.ClonedBy__c;
                    }else{
                        pol.ClonedBy__c = 'Manual Renewal';
                        pol.Policy_Renew_Status__c = 'Renewal Created Successfully';
                    }
                }else{        
                    pol.Policy_Renew_Status__c = 'This is not a valid policy for renewal.';
                }
            }
            List<Database.SaveResult> resultPolicyList = Database.update(listPolicies,false);
            System.debug('====resultPolicyList==='+resultPolicyList);
            for(Integer i=0;i<resultPolicyList.size();i++){
                if(!resultPolicyList[i].isSuccess()){
                    listPolicies.get(i).ClonedBy__c='';
                    listPolicies.get(i).Policy_Renew_Status__c='Error : ';
                    for(Database.Error err : resultPolicyList[i].getErrors()) {
                        listPolicies.get(i).Policy_Renew_Status__c = listPolicies.get(i).Policy_Renew_Status__c + err.getMessage()+'-';
                    }                policiesToUpdate.add(listPolicies.get(i));
                }
            }
            success = 'Mass Operation Successful. Please see the status field for further information.';
            
        }else{
            error = 'Please select atleast one Policy.';
        }
    }
}