force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Active1__c.field-meta.xml
<CustomField>
    <fullName>Active1__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Actrive Policy flag used by internal code, updated by nightly batch process.</description>
    <label>Active1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>if(AND(RecordType.DeveloperName = &apos;Policy&apos; ,Expiration_Date__c &gt; TODAY(), Effective_Date__c &lt;= TODAY(),OR(ISNULL(Cancel_Date__c),Cancel_Date__c&gt; TODAY())),true,false )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch_UpdatePolicyIsActive.cls
global class Batch_UpdatePolicyIsActive implements Database.Batchable<sObject>,Schedulable {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id,Active1__c,Active__c FROM Policy__c WHERE (Active1__c = false and Active__c = true) OR (Active1__c = true and Active__c = false)';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Policy__c> policyList) {
        for(Policy__c pol: policyList){
            pol.Active1__c = pol.Active__c;
        }
        Update policyList;
    }
    
    global void finish(Database.BatchableContext bc) {
    }
    global void execute(SchedulableContext sc){
        Database.executeBatch(new Batch_UpdatePolicyIsActive(),20);
    }
}