force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Cancel_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Date__c</fullName>
    <label>Cancel Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to filter the related lawyers on the basis of related account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Effective_Date__c</fullName>
    <label>Endorsement Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <formula>Policy__r.Name</formula>
    <label>Policy Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/Policy_Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Quote-{000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Policy_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Policy_Firm__c.field-meta.xml
<CustomField>
    <fullName>Policy_Firm__c</fullName>
    <formula>Policy__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Firm</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <formula>If( 
Or(ISNULL(Policy__r.Policy_Number__c),ISBLANK(Policy__r.Policy_Number__c)) , 
Policy__r.Name, 
Policy__r.Policy_Number__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Policy_Header_Ctrl.cls
public class Policy_Header_Ctrl {
    public String recordId;
    public Policy__c policy{get;set;}
    public POLICY_ENDORSEMENT__c endorsement{get;set;}
	public Policy_Quote__c quote{get;set;}    
    public void setrecordId(String recordId){
        
        Schema.SObjectType token = Id.valueOf(recordId).getSObjectType();
        Schema.DescribeSObjectResult dr = token.getDescribe();
        if(dr.getName().equalsIgnoreCase('Policy__c')){
            if(policy==null){
                policy = [select id,name,EFFECTIVE_DATE__C, POLICY_NUMBER__C , Account__r.Name  from Policy__C where id=: recordId];
            }
        }else if(dr.getName().equalsIgnoreCase('Policy_Endorsement__c')){
            if(endorsement==null){
                endorsement = [select id,RecordType.Name,Policy__c,Policy__r.Cancel_Date__c,Policy__r.Expiration_Date__c,name,ENDORSEMENT_EFFECTIVE_DATE__C, POLICY_NUMBER__C , POLICY_FIRM__C from POLICY_ENDORSEMENT__c where id=: recordId];
                
            }
        }else if(dr.getName().equalsIgnoreCase('Policy_Quote__c')){
            if(quote == null){
                quote = [select id,Policy__r.EFFECTIVE_DATE__C,Policy__r.Name,Policy__r.Account__r.Name,Name from Policy_Quote__c where id=:recordId];
            }
        }
    }
    public String getrecordId(){
        return recordId;
    }
}