force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Clone_Application_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Clone_Application_Effective_Date__c</fullName>
    <label>Clone Application Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/ClonedBy__c.field-meta.xml
<CustomField>
    <fullName>ClonedBy__c</fullName>
    <label>Cloned By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal 3 Months Before Policy Expiration</fullName>
            </value>
            <value>
                <fullName>Clone Opportunity With Application</fullName>
            </value>
            <value>
                <fullName>Clone Opportunity Without Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Old_Policy__c.field-meta.xml
<CustomField>
    <fullName>Old_Policy__c</fullName>
    <externalId>true</externalId>
    <label>Old Policy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/classes/ClonePolicyRejectedCtrl.cls
public class ClonePolicyRejectedCtrl {
    public class ClonePolicyRejectedCtrlException extends Exception{}

    @AuraEnabled
    public static String clonePolicy(String policyId, Date effDate){
        try{
            Policy__c objPolicy = [SELECT Id,Account__c FROM Policy__c WHERE Id=:policyId];
            Account acc = [SELECT Id,(SELECT Id FROM Policies__r WHERE RecordType.Name ='Application') FROM Account Where Id=:objPolicy.Account__c];
            if(!acc.Policies__r.isEmpty()){
                throw new ClonePolicyRejectedCtrlException('There is already an open application with this customer. Please review it before creating a new application.');
            }
            
            objPolicy.ClonedBy__c = 'Rejected Renewal';
            objPolicy.Clone_Application_Effective_Date__c = effDate;
            update objPolicy;
            String newPolicyId = [select id from Policy__c where Old_Policy__c = : policyId limit 1].id;
            return newPolicyId;
        }
        catch(DmlException de){
            throw new ClonePolicyRejectedCtrlException(de.getDMLMessage(0));
        }
        catch(Exception e){
            throw new ClonePolicyRejectedCtrlException(e.getMessage());
        }
    }
}