force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Aggregate_Limit_History__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Limit_History__c</fullName>
    <label>Aggregate Limit History</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Effective_Date_History__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date_History__c</fullName>
    <label>Effective Date History</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Expiration_Date_History__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date_History__c</fullName>
    <label>Expiration Date History</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Billing_Address_History__c.field-meta.xml
<CustomField>
    <fullName>Firm_Billing_Address_History__c</fullName>
    <formula>SUBSTITUTE(Firm_Billing_Address_History_Intermedia__c, &apos;_BR_ENCODED_&apos;, &apos;&lt;br&gt;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm Billing Address History</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Name_History__c.field-meta.xml
<CustomField>
    <fullName>Firm_Name_History__c</fullName>
    <label>Firm Name History</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Per_Claim_Deductible_Amount_History__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Deductible_Amount_History__c</fullName>
    <label>Per Claim Deductible Amount History</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Per_Claim_Limit_History__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Limit_History__c</fullName>
    <label>Per Claim Limit History</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Number_History__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number_History__c</fullName>
    <label>Policy Number History</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/classes/CERTIFICATION_OF_INSURANCE_Template_Ctrl.cls
public class CERTIFICATION_OF_INSURANCE_Template_Ctrl {
    public String recordId;
    public Policy__c policy{get;set;}
    public void setrecordId(String recordId){
        policy = [select id,name,FIRM_NAME_History__C, FIRM_BILLING_ADDRESS_History__C , POLICY_NUMBER_History__C,EFFECTIVE_DATE_History__C,EXPIRATION_DATE_History__C, PER_CLAIM_LIMIT_History__C,
                  AGGREGATE_LIMIT_History__C ,PER_CLAIM_DEDUCTIBLE_AMOUNT_History__C from Policy__C where id=: recordId];
    }
    public String getrecordId(){
        return recordId;
    }
}