force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Application_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Received_Date__c</fullName>
    <label>Application Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Cancel_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Date__c</fullName>
    <label>Cancel Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/ClonedBy__c.field-meta.xml
<CustomField>
    <fullName>ClonedBy__c</fullName>
    <label>Cloned By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal 3 Months Before Policy Expiration</fullName>
            </value>
            <value>
                <fullName>Clone Opportunity With Application</fullName>
            </value>
            <value>
                <fullName>Clone Opportunity Without Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Limits__c.field-meta.xml
<CustomField>
    <fullName>Limits__c</fullName>
    <formula>Limit__r.Name</formula>
    <label>Limits</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Renew_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Renew_Status__c</fullName>
    <label>Policy Renew Status</label>
    <length>80000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Total Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EZ Renewal</fullName>
            </value>
            <value>
                <fullName>Regular Renewal</fullName>
            </value>
            <value>
                <fullName>Super EZ</fullName>
            </value>
            <value>
                <fullName>Online Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter_User__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Underwriter User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/globalValueSets/Policy_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <label>App Sent</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Requested Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Quoted</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>Lost</label>
    </customValue>
    <customValue>
        <fullName>Bound</fullName>
    </customValue>
    <customValue>
        <fullName>Printed</fullName>
    </customValue>
    <customValue>
        <fullName>Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Pending</fullName>
        <isActive>false</isActive>
        <label>Quote Pending</label>
    </customValue>
    <masterLabel>Policy Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PrintPoliciesController.cls
public class PrintPoliciesController {
    public String searchFirmName{get;set;}
    public Date searchEffectiveStart{get;set;}
    public Date searchEffectiveEnd{get;set;}
    public Policy__c samplePolicy{get;set;}
    public Id selectedUnderWriter{get;set;}
    public Id rowIdx{get;set;}
    public String searchPolicyStatus{get;set;}
    public List<PrintPoliciesControllerWrapper> searchedResults{get;set;}
    public PrintPoliciesController(){
        samplePolicy = new Policy__c();
        fetchPolicy();
    }
    public void fetchPolicy(){
        
        searchedResults = new List<PrintPoliciesControllerWrapper>();
        searchEffectiveStart = samplePolicy.Application_Received_Date__c;
        searchEffectiveEnd = samplePolicy.Date_Signed__c;
        String query = 'Select Id,Name,Account__r.Name,Effective_Date__c,Expiration_Date__c,Renewal_Type__c,Limits__c,Premium__c,Cancel_Date__c,ClonedBy__c,Policy_Renew_Status__c,Account__c,' + 
                        'Underwriter_User__c,Underwriter_User__r.Name,Status__c from Policy__c';
        String Filter = '';
       if(String.IsNotBlank(searchFirmName)){
            searchFirmName = '%'+searchFirmName +'%';
            Filter += ' WHERE Account__r.Name LIKE : searchFirmName ';
        }
        if(searchEffectiveStart !=null){
            if(String.IsNotBlank(Filter)){
                Filter += ' AND Effective_Date__c >= : searchEffectiveStart ';
            }else{
                Filter += ' WHERE Effective_Date__c >= :  searchEffectiveStart ';
            }
        }
        if(searchEffectiveEnd !=null){
            if(String.IsNotBlank(Filter)){
                Filter += ' AND Effective_Date__c <= :  searchEffectiveEnd ';
            }else{
                Filter += ' WHERE Effective_Date__c <= :  searchEffectiveEnd ';
            }
        }
        if(selectedUnderWriter !=null){
            if(String.IsNotBlank(Filter)){
                Filter += ' AND Underwriter_User__c = :  selectedUnderWriter ';
            }else{
                Filter += ' WHERE Underwriter_User__c =:  selectedUnderWriter ';
            }
        }
        if(String.IsNotBlank(searchPolicyStatus)){
            if(String.IsNotBlank(Filter)){
                Filter += ' AND Status__c =: searchPolicyStatus ';
            }else{
                Filter += ' WHERE Status__c =: searchPolicyStatus ';
            }
        }
        if(String.isNotBlank(Filter)){
            query = query+''+Filter+' AND RecordType.Name = \'Policy\' and Status__c != \'Policy Sent\' LIMIT 1000';
        }else{
            query = query+' WHERE RecordType.Name = \'Policy\' and Status__c != \'Policy Sent\' LIMIT 1000';
        }
        System.debug(query);
        List<Policy__c> lstOfPolicies = database.query(query);
        system.debug('lstOfPolicies-----'+lstOfPolicies);
        for(Policy__c policy : lstOfPolicies){
            PrintPoliciesControllerWrapper wrapper = new PrintPoliciesControllerWrapper();
            wrapper.policy = policy;
            searchedResults.add(wrapper);
        }
    }
    public void sendPolicyStatus(){
        if(rowIdx!=null){
            Policy__c policy = new Policy__c(Id = rowIdx,Status__c = 'Policy Sent',Send_Date__c = System.now());
            update policy;
        }
        fetchPolicy();
    }
    public List<SelectOption> getUnderwriter() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('' ,'--None--'));
        User[] threatMappings = [SELECT Id,Name FROM User where (Profile.Name = 'Sales' OR Profile.Name = 'System Administrator' OR Profile.Name = 'Underwriting') AND ISACTIVE = TRUE ORDER BY Name LIMIT 1000];
        for (User threatMapping : threatMappings) {
                options.add(new SelectOption(threatMapping.Id,threatMapping.Name));
        }
        return options;
    }
    public List<SelectOption> getPolicyStatus(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('' ,'All'));
        options.add(new SelectOption('Printed' ,'Printed'));
        options.add(new SelectOption('Bound' ,'Bound'));
        return options;
    }
    public class PrintPoliciesControllerWrapper{
        public Policy__c policy{get;set;}
        
        public PrintPoliciesControllerWrapper(){
        }
    }
}