force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Billing__c.field-meta.xml
<CustomField>
    <fullName>Billing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing</label>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Bound_Date__c.field-meta.xml
<CustomField>
    <fullName>Bound_Date__c</fullName>
    <label>Bound Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Is_Canceled__c.field-meta.xml
<CustomField>
    <fullName>Is_Canceled__c</fullName>
    <formula>IF (ISNULL(Cancel_Date__c), false, true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Canceled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Limits__c.field-meta.xml
<CustomField>
    <fullName>Limits__c</fullName>
    <formula>Limit__r.Name</formula>
    <label>Limits</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Email_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Email_Date__c</fullName>
    <label>Policy Email Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium_FinalQuote_And_Endorsements__c.field-meta.xml
<CustomField>
    <fullName>Premium_FinalQuote_And_Endorsements__c</fullName>
    <formula>Premium_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/globalValueSets/Policy_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <label>App Sent</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Requested Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Quoted</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>Lost</label>
    </customValue>
    <customValue>
        <fullName>Bound</fullName>
    </customValue>
    <customValue>
        <fullName>Printed</fullName>
    </customValue>
    <customValue>
        <fullName>Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Pending</fullName>
        <isActive>false</isActive>
        <label>Quote Pending</label>
    </customValue>
    <masterLabel>Policy Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SendPolicyDoumentsCtrl.cls
public class SendPolicyDoumentsCtrl {
    
    public class SendPolicyDoumentsCtrlException extends Exception{} 
    
    @AuraEnabled
    public static Wrapper getDetails(){
        Wrapper wrap = new Wrapper();
        try{
            List<Policy__c> policyList = [SELECT Id, Billing__r.Computed_Payment_Frequency__c, Billing__r.Latest_Cash_Receipt__c, Billing__r.Computed_Payment_Type__c, Name, Account__c, Account__r.Name, Premium_FinalQuote_And_Endorsements__c, Limits__c, Expiration_Date__c, Effective_Date__c, Status__c FROM Policy__c WHERE Is_Canceled__c = false And RecordType.Name = 'Policy' AND Bound_Date__c < TODAY AND Policy_Email_Date__c = Null AND Billing__r.Computed_Payment_Frequency__c = NULL ORDER BY CreatedDate DESC];
            wrap.policyList = policyList;
            
            return wrap;
        }
        catch(Exception e){
            throw new SendPolicyDoumentsCtrlException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static String runBatch(List<String> ids){
        try{
            if(ids != null){
                system.debug(ids);
                Set<String> recIds = new Set<String>();
                recIds.addAll(ids);
                SendPolicyDocumentsBatch b = new SendPolicyDocumentsBatch(recIds); 
                string batchId = Database.executeBatch(b,Integer.valueOf(label.SendPolicyDocsLimit));
                
                return batchId;
            }
            else{
                throw new SendPolicyDoumentsCtrlException('Please Select an Record.');
            }
        }
        catch(Exception e){
            throw new SendPolicyDoumentsCtrlException(e.getMessage());
        }
    }
    
    public class Wrapper{
        @AuraEnabled public List<Policy__c> policyList{get;Set;}
        @AuraEnabled public String userEmail{get;set;}
        @AuraEnabled public Boolean AddBcc{get;Set;}
        
        public Wrapper(){
            this.AddBcc = false;
            this.userEmail = UserInfo.getUserEmail();
        }
    }
}