force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UserTrackViewCtrl_Test.cls
@isTest
public class UserTrackViewCtrl_Test {
    
	@isTest
    private static void test0(){
        Test.startTest();
        Account acc = new Account(
        	Name = 'Test Acc'
        );
      	insert acc;
        UserTrackViewCtrl.updateUserTrack(acc.Id);
        Test.stopTest();
    }
    
    @isTest
    private static void test1(){
        Test.startTest();
        
        Account acc = new Account(
        	Name = 'Test Acc'
        );
      	insert acc;
        
        Policy__c pol = new Policy__c(
        	Name = 'Test Pol',
            Account__c = acc.Id,
            Effective_Date__c = system.today()
        );
      	insert pol;
        UserTrackViewCtrl.updateUserTrack(pol.Id);
        Test.stopTest();
    }
    
     @isTest
    private static void test2(){
        Test.startTest();
        UserTrackViewCtrl.dummyCode();
        Test.stopTest();
    }
   
}