force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Cancel_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Date__c</fullName>
    <label>Cancel Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/ClonedBy__c.field-meta.xml
<CustomField>
    <fullName>ClonedBy__c</fullName>
    <label>Cloned By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal 3 Months Before Policy Expiration</fullName>
            </value>
            <value>
                <fullName>Clone Opportunity With Application</fullName>
            </value>
            <value>
                <fullName>Clone Opportunity Without Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/NBA_App_Source__c.field-meta.xml
<CustomField>
    <fullName>NBA_App_Source__c</fullName>
    <label>NBA App Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NBA_App_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Renew_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Renew_Status__c</fullName>
    <label>Policy Renew Status</label>
    <length>80000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Renew_Application__c.field-meta.xml
<CustomField>
    <fullName>Renew_Application__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is for the ability to add “Block” to Application Renewal. If the field is unchecked then the renewal processes with not fire, both manual and automated.</description>
    <label>Block Renewal of Policy With Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/globalValueSets/NBA_App_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Search Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Journal</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram post/story</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook post/group</fullName>
    </customValue>
    <customValue>
        <fullName>Google Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter post</fullName>
    </customValue>
    <customValue>
        <fullName>Word of mouth</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>ISBA</fullName>
        <isActive>false</isActive>
        <label>ISBA</label>
    </customValue>
    <customValue>
        <fullName>Other social media</fullName>
        <isActive>false</isActive>
        <label>Other social media</label>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
        <isActive>false</isActive>
        <label>Newspaper</label>
    </customValue>
    <customValue>
        <fullName>Other Ads</fullName>
        <isActive>false</isActive>
        <label>Other Ads</label>
    </customValue>
    <customValue>
        <fullName>TV</fullName>
        <isActive>false</isActive>
        <label>TV</label>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
        <isActive>false</isActive>
        <label>Radio</label>
    </customValue>
    <masterLabel>NBA App Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CMRenewPolicy3MonthPriorBatch.cls
global class CMRenewPolicy3MonthPriorBatch implements Database.Batchable<sObject>, Database.Stateful,Schedulable {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Date startTimeFrame = system.today();
        Date timeFrame = system.today().addDays(90);
        //timeFrame = Date.newInstance(2026, 03, 31);
        Id RecordTypeId = Schema.SObjectType.Policy__c.getRecordTypeInfosByName().get('Policy').getRecordTypeId();
        String query = 'select id,ClonedBy__c from Policy__c where RecordTypeId=:RecordTypeId AND Renew_Application__c = false AND Account__r.Count_of_Application__c<1 and Expiration_Date__c <=:timeFrame and ClonedBy__c = null and Expiration_Date__c >:startTimeFrame and Cancel_Date__c = null';
        system.debug('query-->'+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Policy__c> records) {
        try{
            for(Policy__c obj : records){
                if(test.isRunningTest()){
                    obj.NBA_App_Source__c = 'test';
                }
                obj.ClonedBy__c = 'Renewal 3 Months Before Policy Expiration';
                obj.Policy_Renew_Status__c = 'Renewal Created Successfully';
            }
            List<Database.SaveResult> results = Database.Update(records,false);
            
            
            List<Policy__c> updatedPolicyRecords = new List<Policy__c>();
            for(Database.SaveResult sr: results){
                if (!sr.isSuccess()) { 
                    Policy__c pol = new Policy__c();
                    pol.Id = sr.getId();
                    pol.ClonedBy__c = '';
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        pol.Policy_Renew_Status__c = err.getMessage();
                        System.debug('Account fields that affected this error: ' + err.getFields());
                    }
                    System.debug(pol);
                    updatedPolicyRecords.add(pol);
                }
            }
            
            if(!updatedPolicyRecords.isEmpty()){
                Database.Update(updatedPolicyRecords,false);
            }
        }catch(exception ex){
			system.debug('ex-->'+ex.getMessage());
        }
    }   
    
    global void finish(Database.BatchableContext BC){           
        
    }
    
    global void execute(SchedulableContext sc){
        Database.executeBatch(new CMRenewPolicy3MonthPriorBatch(),10);
    }
}