force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Is_Rejected_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Is_Rejected_Confirm__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Application status = Rejected and Is_Rejected_Confirm=Yes then Opportunity stages would be Rejected.</description>
    <label>Is Rejected Confirm</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Number_Before_Rejection__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number_Before_Rejection__c</fullName>
    <label>Policy Number Before Rejection</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/globalValueSets/Policy_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <label>App Sent</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Requested Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Quoted</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>Lost</label>
    </customValue>
    <customValue>
        <fullName>Bound</fullName>
    </customValue>
    <customValue>
        <fullName>Printed</fullName>
    </customValue>
    <customValue>
        <fullName>Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Pending</fullName>
        <isActive>false</isActive>
        <label>Quote Pending</label>
    </customValue>
    <masterLabel>Policy Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ReverseLostStatusController.cls
public class ReverseLostStatusController {
    @AuraEnabled
    public static String convertToApplication(Id policyId){
        try{
            Policy__c objPolicy = [select id,Policy_Number_Before_Rejection__c,Name,Is_Rejected_Confirm__c,RecordTypeId,Status__c from Policy__c where id=: policyId];
            objPolicy.Is_Rejected_Confirm__c = false;
            objPolicy.RecordTypeId = ApplicationPolicyUtil.ApplicationRTID;
            objPolicy.Status__c = 'Application created';
            objPolicy.Name = objPolicy.Policy_Number_Before_Rejection__c;
            update objPolicy;
			return 'Success';            
        }catch(Exception e){
            return 'There is some error occurred : ' + e.getMessage();
        }
    }
	
}