force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount__c</fullName>
    <label>Deductible Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/Policy_Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Quote-{000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Quote__c/fields/Coverage_Max_Per_Claim__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Max_Per_Claim__c</fullName>
    <label>Per Claim Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount__c</fullName>
    <label>Deductible Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_BillingCity__c.field-meta.xml
<CustomField>
    <fullName>Firm_BillingCity__c</fullName>
    <formula>Policy__r.Account__r.BillingCity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm BillingCity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_BillingState__c.field-meta.xml
<CustomField>
    <fullName>Firm_BillingState__c</fullName>
    <formula>Policy__r.Account__r.BillingState</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm BillingState</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_BillingStreet__c.field-meta.xml
<CustomField>
    <fullName>Firm_BillingStreet__c</fullName>
    <formula>Policy__r.Account__r.BillingStreet</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm BillingStreet</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_BillingZIP__c.field-meta.xml
<CustomField>
    <fullName>Firm_BillingZIP__c</fullName>
    <formula>Policy__r.Account__r.BillingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm BillingZIP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_Prior_Acts_Date__c.field-meta.xml
<CustomField>
    <fullName>Firm_Prior_Acts_Date__c</fullName>
    <formula>Policy__r.Policy_Retroactive_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm Prior Acts Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Full_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Full_Coverage__c</fullName>
    <label>Aggregate Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Policy_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Policy_Firm__c.field-meta.xml
<CustomField>
    <fullName>Policy_Firm__c</fullName>
    <formula>Policy__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Firm</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Quote_Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_Expire_Date__c</fullName>
    <defaultValue>TODAY() + 30</defaultValue>
    <label>Quote Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Quote_Final_Premium__c.field-meta.xml
<CustomField>
    <fullName>Quote_Final_Premium__c</fullName>
    <formula>(Quote_Premium_Amount__c + Additional_Premium__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Quote_Final_Premium_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Quote_Final_Premium_Monthly__c</fullName>
    <formula>Quote_Final_Premium__c / 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Final Premium Monthly</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Quote_Final_Premium_Qrtly__c.field-meta.xml
<CustomField>
    <fullName>Quote_Final_Premium_Qrtly__c</fullName>
    <formula>Quote_Final_Premium__c * 0.25</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Final Premium Qrtly</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Quotepdf_Ctrl.cls
public class Quotepdf_Ctrl {
    public String recordId;
    public String policyId{get;set;}
    public Policy_Quote__c quote{get;set;}
    public List<Policy_Endorsement__c> endorsements{get;set;}
    public void setrecordId(String recordId){
        
        quote = new Policy_Quote__c();
        
        List<Policy_Quote__c> quoteList = [select id,name,POLICY_EFFECTIVE_DATE__C,POLICY_FIRM__C,FIRM_BILLINGSTREET__C,FIRM_BILLINGCITY__C,FIRM_BILLINGSTATE__C,FIRM_BILLINGZIP__C,CREATEDDATE,QUOTE_EXPIRE_DATE__C,Policy__C,
                 FIRM_PRIOR_ACTS_DATE__c,COVERAGE_MAX_PER_CLAIM__c,FULL_COVERAGE__C,DEDUCTIBLE_AMOUNT__C,QUOTE_FINAL_PREMIUM__c,QUOTE_FINAL_PREMIUM_QRTLY__c,QUOTE_FINAL_PREMIUM_MONTHLY__c from Policy_Quote__c where id=: recordId];
        
        if(!quoteList.isEmpty()){
            quote = quoteList[0];
            endorsements = [select id, name from Policy_Endorsement__C where Policy__C =: quote.Policy__c];
        }
    }
    public String getrecordId(){
        return recordId;
    }
    
}