force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/User_Tracking__c.object-meta.xml
<CustomObject>
    <label>User Tracking</label>
    <nameField>
        <displayFormat>UT - {0000}</displayFormat>
        <label>User Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UserTrackViewCtrl.cls
public class UserTrackViewCtrl {
    @AuraEnabled
    public static void updateUserTrack(Id recordId) {
        User_Tracking__c userTrack;
        if(recordId.getSObjectType().getDescribe().getName() == 'Account'){
            Account obj = [select id,name from Account where id=: recordId];
            userTrack = UserTrackingHandler.createUserTrackingObject('View', recordId, obj.Name);
        }else if(recordId.getSObjectType().getDescribe().getName() == 'Policy__c'){
            Policy__c obj = [select id,name from Policy__c where id=: recordId];
            userTrack = UserTrackingHandler.createUserTrackingObject('View', recordId, obj.Name);
        }else if(recordId.getSObjectType().getDescribe().getName() == 'Policy_Claim__c'){
            Policy_Claim__c obj = [select id,name from Policy_Claim__c where id=: recordId];
            userTrack = UserTrackingHandler.createUserTrackingObject('View', recordId, obj.Name);
        }else if(recordId.getSObjectType().getDescribe().getName() == 'Policy_Endorsement__c'){
            Policy_Endorsement__c obj = [select id,name from Policy_Endorsement__c where id=: recordId];
            userTrack = UserTrackingHandler.createUserTrackingObject('View', recordId, obj.Name);
        }else if(recordId.getSObjectType().getDescribe().getName() == 'AcctSeed__Billing__c'){
            AcctSeed__Billing__c  obj = [select id,name from AcctSeed__Billing__c  where id=: recordId];
            userTrack = UserTrackingHandler.createUserTrackingObject('View', recordId, obj.Name);
        }
        insert userTrack;
    }
    
    public static void dummyCode(){
         Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    

    }
}