force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/ISBAM_Automatic_Renewal_Send__c.field-meta.xml
<CustomField>
    <fullName>ISBAM_Automatic_Renewal_Send__c</fullName>
    <formula>ISPICKVAL( Status__c ,&quot;Approved&quot;)
&amp;&amp; ISPICKVAL(Renewal_Type__c,&quot;Online Invoice&quot;)
&amp;&amp; Effective_Date__c&gt;= DATE(2025,1,1) &amp;&amp; Effective_Date__c &lt;=  (TODAY() + 40) &amp;&amp;  RecordType.Name = &apos;Application&apos;</formula>
    <label>ISBAM Automatic Renewal Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EZ Renewal</fullName>
            </value>
            <value>
                <fullName>Regular Renewal</fullName>
            </value>
            <value>
                <fullName>Super EZ</fullName>
            </value>
            <value>
                <fullName>Online Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/globalValueSets/Policy_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <label>App Sent</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Requested Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Quoted</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>Lost</label>
    </customValue>
    <customValue>
        <fullName>Bound</fullName>
    </customValue>
    <customValue>
        <fullName>Printed</fullName>
    </customValue>
    <customValue>
        <fullName>Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Pending</fullName>
        <isActive>false</isActive>
        <label>Quote Pending</label>
    </customValue>
    <masterLabel>Policy Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SendRenewalApplicationBatch.cls
global class SendRenewalApplicationBatch implements Database.Batchable<SObject> ,Schedulable , Database.AllowsCallouts{
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        //date dt = system.today().addDays(40);
        String query = 'SELECT Id, Renewal_Type__c,Account__r.AcctSeed__Billing_Contact__c,Account__r.AcctSeed__Billing_Contact__r.Email FROM Policy__c WHERE ISBAM_Automatic_Renewal_Send__c = true';// AND RecordType.Name =\'Application\' AND Status__c=\'Approved\' AND Effective_Date__c<=:dt';
        //if(!Test.isRunningTest())
          //  query += ' AND Effective_Date__c >= 2025-01-01';
        
        system.debug(query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Policy__c> objList){        
        for(Policy__c obj : objList){
            SendEmailExt.EmailWrapper  emWrp= SendEmailExt.getDetails(obj.Id, 'renewalBatch');
            //emWrp.sendToContactEmailSelected = 'kyle.hoker@isbamutual.com';
            //emWrp.sendToContactSelected = null;
            if(obj.Account__r.AcctSeed__Billing_Contact__c != null){
                emWrp.CCAddress = obj.Account__r.AcctSeed__Billing_Contact__r.Email;
            }
            SendEmailExt.SendEmail(emWrp, 'renewalBatch');            
        }
    }
    
    global void finish(Database.BatchableContext bc){}
    
    global void execute(SchedulableContext SC) {
        SendRenewalApplicationBatch b = new SendRenewalApplicationBatch(); 
        Database.executeBatch(b,1);
    }    
}