force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>IF( AND(ISNULL( Primary_Contact_Id__c ), ISNULL( Primary_Contact_Name__c ) ),&apos;&apos;, HYPERLINK(&quot;/&quot;&amp;  Primary_Contact_Id__c , Primary_Contact_Name__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EZ Renewal</fullName>
            </value>
            <value>
                <fullName>Regular Renewal</fullName>
            </value>
            <value>
                <fullName>Super EZ</fullName>
            </value>
            <value>
                <fullName>Online Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/classes/RegularRenewalPDFExtn.cls
public class RegularRenewalPDFExtn
{
    public Policy__c policy {get; set;}
    public AccountContactRelation primaryConRole {get; set;}
    
    public RegularRenewalPDFExtn(ApexPages.StandardController controller) {
        
        policy = (Policy__c)controller.getRecord();
        
        Boolean isRegularRenwalPol = false;
        
        for(Policy__c pol: [SELECT Account__c, Account__r.Account_Number_External_ID__c, Renewal_Type__c FROM Policy__c WHERE Id =: policy.Id])
        {
            policy = pol;
            if(pol.Renewal_Type__c == 'Regular Renewal')
            {
            policy = pol;
            isRegularRenwalPol = true;
            }
        }
        
        if(isRegularRenwalPol)
        {          
            for(AccountContactRelation accConRole: [SELECT AccountId, Account.Name, Account.BillingCity, Account.BillingStreet, Account.BillingState,
                                                        Contact.Email, Contact.Website__c,
                                                        Account.BillingCountry, Account.BillingPostalCode, ContactId, Contact.Name  
                                                        FROM AccountContactRelation 
                                                        WHERE AccountId =: policy.Account__c AND Contact.Primary_Contact__c = true LIMIT 1])
            {
               
                primaryConRole = accConRole;
            }
        }
    }


}