force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Aggregate_Limit_For_All_Claims__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Limit_For_All_Claims__c</fullName>
    <formula>Aggregate_Limit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aggregate Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount__c</fullName>
    <label>Deductible Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Per_Claim_Limit__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Limit__c</fullName>
    <label>Per Claim Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Total Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Quote__c/Policy_Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Quote-{000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Quote__c/fields/Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount__c</fullName>
    <label>Deductible Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Final_Quote__c.field-meta.xml
<CustomField>
    <fullName>Final_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Policy_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <formula>If( 
Or(ISNULL(Policy__r.Policy_Number__c),ISBLANK(Policy__r.Policy_Number__c)) , 
Policy__r.Name, 
Policy__r.Policy_Number__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/newQuoteExtension.cls
public with sharing class newQuoteExtension{

    public Policy__c policy {get; set;}
    public Policy_Quote__c quote{get;set;}
    
    public newQuoteExtension(ApexPages.StandardController controller) {
          
          quote = new Policy_Quote__c();
          
          policy = (Policy__c)controller.getRecord();
          policy = [SELECT Name,Effective_Date__c,Policy_Number__c,Per_Claim_Limit__c,Aggregate_Limit_For_All_Claims__c,
                      Deductible_Amount__c,Premium__c,Expiration_Date__c,Account__c,Account__r.Name,Account__r.BillingStreet,Account__r.BillingCity, 
                       Account__r.BillingState,Account__r.BillingPostalCode,Account__r.Phone,
                   Account__r.Fax,Account__r.email__c FROM Policy__c WHERE Id =: policy.Id LIMIT 1];
                   
          List<Policy_Quote__c> quoteList = new List<Policy_Quote__c>();
          quoteList = [SELECT Id,Policy__c,Final_Quote__c FROM Policy_Quote__c WHERE Policy__c =: policy.Id AND Final_Quote__c = True];
       
          if(!quoteList.isEmpty()){
            quote = quoteList[0];
          }
          
    }

}