force-app/main/default/objects/Lost_Application_Config__mdt/Lost_Application_Config__mdt.object-meta.xml
<CustomObject>
    <label>Lost Application Config</label>
    <pluralLabel>Lost Applications Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Lost_Application_Config__mdt/fields/Description_Required__c.field-meta.xml
<CustomField>
    <fullName>Description_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Description Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lost_Application_Config__mdt/fields/Lost_Reason_Sub1__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason_Sub1__c</fullName>
    <label>Lost Reason Sub1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lost_Application_Config__mdt/fields/Lost_Reason_Sub2__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason_Sub2__c</fullName>
    <label>Lost Reason Sub2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <description>Type of application that is being created.</description>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Is_Rejected_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Is_Rejected_Confirm__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Application status = Rejected and Is_Rejected_Confirm=Yes then Opportunity stages would be Rejected.</description>
    <label>Is Rejected Confirm</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Lost_Description__c.field-meta.xml
<CustomField>
    <fullName>Lost_Description__c</fullName>
    <label>Lost Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason__c</fullName>
    <label>Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coverage</fullName>
            </value>
            <value>
                <fullName>Practice Closed</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Licensed Suspension</fullName>
            </value>
            <value>
                <fullName>Non-Renewal</fullName>
            </value>
            <value>
                <fullName>Employment</fullName>
            </value>
            <value>
                <fullName>ISBA Membership Cost</fullName>
            </value>
            <value>
                <fullName>Cancelation</fullName>
            </value>
            <value>
                <fullName>Propestive Practice</fullName>
            </value>
            <value>
                <fullName>Online Inquiry Only</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>--------------------------------------------</label>
            </value>
            <value>
                <fullName>Bar Membership</fullName>
                <isActive>false</isActive>
                <label>Bar Membership</label>
            </value>
            <value>
                <fullName>CUSTOMER - Bar Membership</fullName>
                <isActive>false</isActive>
                <label>CUSTOMER - Bar Membership</label>
            </value>
            <value>
                <fullName>CUSTOMER - Complaint</fullName>
                <isActive>false</isActive>
                <label>CUSTOMER - Complaint</label>
            </value>
            <value>
                <fullName>CUSTOMER - Coverage</fullName>
                <isActive>false</isActive>
                <label>CUSTOMER - Coverage</label>
            </value>
            <value>
                <fullName>CUSTOMER - ERE</fullName>
                <isActive>false</isActive>
                <label>CUSTOMER - ERE</label>
            </value>
            <value>
                <fullName>CUSTOMER - Other</fullName>
                <isActive>false</isActive>
                <label>CUSTOMER - Other</label>
            </value>
            <value>
                <fullName>CUSTOMER - Practice Closed</fullName>
                <isActive>false</isActive>
                <label>CUSTOMER - Practice Closed</label>
            </value>
            <value>
                <fullName>CUSTOMER - Price</fullName>
                <isActive>false</isActive>
                <label>CUSTOMER - Price</label>
            </value>
            <value>
                <fullName>Cancel renewal policy FLAT due to no payment of premium</fullName>
                <isActive>false</isActive>
                <label>Cancel renewal policy FLAT due to no payment of premium</label>
            </value>
            <value>
                <fullName>Claims Experience</fullName>
                <isActive>false</isActive>
                <label>Claims Experience</label>
            </value>
            <value>
                <fullName>Disciplinary Issues</fullName>
                <isActive>false</isActive>
                <label>Disciplinary Issues</label>
            </value>
            <value>
                <fullName>Dissolved</fullName>
                <isActive>false</isActive>
                <label>Dissolved</label>
            </value>
            <value>
                <fullName>ERE</fullName>
                <isActive>false</isActive>
                <label>ERE</label>
            </value>
            <value>
                <fullName>IMPORT</fullName>
                <isActive>false</isActive>
                <label>IMPORT</label>
            </value>
            <value>
                <fullName>ISBAM - Claims</fullName>
                <isActive>false</isActive>
                <label>ISBAM - Claims</label>
            </value>
            <value>
                <fullName>ISBAM - Disciplinary Issues</fullName>
                <isActive>false</isActive>
                <label>ISBAM - Disciplinary Issues</label>
            </value>
            <value>
                <fullName>ISBAM - IMPORT</fullName>
                <isActive>false</isActive>
                <label>ISBAM - IMPORT</label>
            </value>
            <value>
                <fullName>ISBAM - Internal Procedures</fullName>
                <isActive>false</isActive>
                <label>ISBAM - Internal Procedures</label>
            </value>
            <value>
                <fullName>Prospective Practice</fullName>
                <isActive>false</isActive>
                <label>Prospective Practice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Lost_Reason_Sub1__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason_Sub1__c</fullName>
    <label>Lost Reason Sub1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lost_Reason__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retirement ERP (Free ERP)</fullName>
            </value>
            <value>
                <fullName>Firm Optional ERP (Bought)</fullName>
            </value>
            <value>
                <fullName>Individual Retirement ERP (Bought)</fullName>
            </value>
            <value>
                <fullName>Deceased/Disability-ERP (Free)</fullName>
            </value>
            <value>
                <fullName>No Cyber</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Bare (no income from business)</fullName>
            </value>
            <value>
                <fullName>Bare (too expensive)</fullName>
            </value>
            <value>
                <fullName>Government Position</fullName>
            </value>
            <value>
                <fullName>In- House</fullName>
            </value>
            <value>
                <fullName>Employed with another Firm</fullName>
            </value>
            <value>
                <fullName>Formed Partnership</fullName>
            </value>
            <value>
                <fullName>Merged with Another Firm (sold business)</fullName>
            </value>
            <value>
                <fullName>Duplicate - set up incorrectly cancelled flat</fullName>
            </value>
            <value>
                <fullName>Cancel Flat - due to non-payment of premium</fullName>
            </value>
            <value>
                <fullName>Retirement</fullName>
            </value>
            <value>
                <fullName>Dissolved</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
            <value>
                <fullName>Moved Out of State</fullName>
                <label>Moved Out Of State</label>
            </value>
            <value>
                <fullName>COI</fullName>
                <isActive>false</isActive>
                <label>COI</label>
            </value>
            <value>
                <fullName>Competition</fullName>
                <isActive>false</isActive>
                <label>Competition</label>
            </value>
            <value>
                <fullName>Cust-Bar membership</fullName>
                <isActive>false</isActive>
                <label>Cust-Bar membership</label>
            </value>
            <value>
                <fullName>DDR</fullName>
                <isActive>false</isActive>
                <label>DDR</label>
            </value>
            <value>
                <fullName>Disbarment</fullName>
                <isActive>false</isActive>
                <label>Disbarment</label>
            </value>
            <value>
                <fullName>Docket</fullName>
                <isActive>false</isActive>
                <label>Docket</label>
            </value>
            <value>
                <fullName>Firm Dissolved (multi lawyer firm)</fullName>
                <isActive>false</isActive>
                <label>Firm Dissolved (multi lawyer firm)</label>
            </value>
            <value>
                <fullName>Increase Policy of Limits of Liability</fullName>
                <isActive>false</isActive>
                <label>Increase Policy of Limits of Liability</label>
            </value>
            <value>
                <fullName>Merged with/joined another Firm</fullName>
                <isActive>false</isActive>
                <label>Merged with/joined another Firm</label>
            </value>
            <value>
                <fullName>Military</fullName>
                <isActive>false</isActive>
                <label>Military</label>
            </value>
            <value>
                <fullName>New Job</fullName>
                <isActive>false</isActive>
                <label>New Job</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Lost_Reason_Sub2__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason_Sub2__c</fullName>
    <label>Lost Reason Sub2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lost_Reason_Sub1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New firm - Potential Prospect</fullName>
            </value>
            <value>
                <fullName>New firm - not a Prospect</fullName>
            </value>
            <value>
                <fullName>ISBA Mutual Insured</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Quitting the Practice of Law</fullName>
            </value>
            <value>
                <fullName>Employment - not private practice</fullName>
            </value>
            <value>
                <fullName>ISBA Membership cost</fullName>
            </value>
            <value>
                <fullName>Other Private Practice</fullName>
                <isActive>false</isActive>
                <label>Other Private Practice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Application_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Business</fullName>
        <default>true</default>
        <label>New Business</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <description>This global list will hold the values of Application type.</description>
    <masterLabel>Application Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Policy_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <label>App Sent</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Requested Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Quoted</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>Lost</label>
    </customValue>
    <customValue>
        <fullName>Bound</fullName>
    </customValue>
    <customValue>
        <fullName>Printed</fullName>
    </customValue>
    <customValue>
        <fullName>Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Pending</fullName>
        <isActive>false</isActive>
        <label>Quote Pending</label>
    </customValue>
    <masterLabel>Policy Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LostApplicationCtrl.cls
public class LostApplicationCtrl {
    
    public class LostApplicationCtrlException extends Exception {}
    
    @AuraEnabled
    public static List<String> getPickListVal(String strObjectName,String recId, String strPicklistField){
        try{
            Policy__c policyRec = new Policy__c();
            if(recId != null &&  recId != ''){
                policyRec = [Select id,Application_Type__c  from Policy__c where id=:recId   limit 1];

            }
            List<String> pickListValuesList= new List<String>();
            Map<String, String> mapPickListValues = new Map<String, String>();
            Schema.SObjectType objSobjectType = Schema.getGlobalDescribe().get(strObjectName);
            Schema.DescribeSObjectResult objDescribeSobject = objSobjectType.getDescribe();
            Map<String, Schema.SObjectField> mapFields = objDescribeSobject.fields.getMap();
            List<Schema.PicklistEntry> lstPickListValues = mapFields.get(strPicklistField).getDescribe().getPickListValues();
            for (Schema.PicklistEntry objPickList : lstPickListValues) {
                if(strPicklistField=='Lost_Reason__c' && (objPickList.getValue() =='Prospective Practice' || objPickList.getValue() == 'Online Inquiry Only' ) ){
                    if(policyRec != null && policyRec.Application_Type__c=='New Business'){
                        pickListValuesList.add(objPickList.getValue());

                    }
                }
                else{
                    pickListValuesList.add(objPickList.getValue());

                }
                    System.debug('Value = ' +objPickList.getValue() +' , Label = ' +objPickList.getLabel());
            
            }
            return pickListValuesList;
        }
        catch(exception e){
            throw new LostApplicationCtrlException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<Wrapper> getPickListSubs(String selectedValue){
        try{
            List<Wrapper> WrapList = new List<Wrapper>();
            Map<String,List<Lost_Application_Config__mdt>> dataMap = new Map<String, List<Lost_Application_Config__mdt>>();
            
            for(Lost_Application_Config__mdt mtd : [SELECT Lost_Reason__c,Description_Required__c,Lost_Reason_Sub1__c, Lost_Reason_Sub2__c, Placeholder__c FROM Lost_Application_Config__mdt WHERE Lost_Reason__c =: selectedValue]){
                List<Lost_Application_Config__mdt> temp = new List<Lost_Application_Config__mdt>();
                if(dataMap.ContainsKey(mtd.Lost_Reason_Sub1__c)){
                    temp = dataMap.get(mtd.Lost_Reason_Sub1__c);
                }
                temp.add(mtd);
                dataMap.put(mtd.Lost_Reason_Sub1__c, temp);
            }
            
            for(String key : dataMap.keySet()){
                Wrapper wrap = new Wrapper();
                wrap.val = key;
                if(dataMap.get(key).size() == 1 && !String.isNotBlank(key)){
                    wrap.isDesRequired = dataMap.get(key)[0].Description_Required__c;
                    wrap.placeholder = dataMap.get(key)[0].Placeholder__c;
                }
                else{
                    wrap.listValues = dataMap.get(key);
                }
                WrapList.add(wrap);
            }
            
            return WrapList;
        }catch(exception e){
            throw new LostApplicationCtrlException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static Boolean save(String recId, String lostReason, String lostReasonSub1, String lostReasonSub2, String discription){
        try{           
            Policy__c p = new Policy__c();
            p.Id = recId;
            p.Lost_Description__c = discription;
            p.Lost_Reason__c = lostReason;
            p.Lost_Reason_Sub1__c = lostReasonSub1;
            p.Lost_Reason_Sub2__c = lostReasonSub2;
            p.Is_Rejected_Confirm__c = true;
            p.Status__c = 'Rejected';
            system.debug(p);
            Update p;
        }
        catch(DmlException e){
            throw new LostApplicationCtrlException(e.getDMLMessage(0));
        }
        catch(exception e){
            throw new LostApplicationCtrlException(e.getMessage());
        }
        return true;
    }
    
    public Class Wrapper{
        @AuraEnabled
        public String val{get;set;}
        @AuraEnabled
        public Boolean isDesRequired{get;set;}
        @AuraEnabled
        public String placeholder{get;set;}
        @AuraEnabled
        public List<Lost_Application_Config__mdt> listValues {get;set;} 
        
        public Wrapper(){
            isDesRequired = false;
            placeholder = null;
        }
    }
    
}