force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ARDC</fullName>
            </value>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Administrative Procedure</fullName>
            </value>
            <value>
                <fullName>Administrative Review</fullName>
            </value>
            <value>
                <fullName>Advice</fullName>
            </value>
            <value>
                <fullName>Bond Work</fullName>
            </value>
            <value>
                <fullName>Bonds</fullName>
            </value>
            <value>
                <fullName>Child Support/Custody</fullName>
            </value>
            <value>
                <fullName>Civil Rights</fullName>
            </value>
            <value>
                <fullName>Class Action</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Collection Practice</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Compliance Advice</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Corporate Takeovers</fullName>
            </value>
            <value>
                <fullName>Distribution of Assets</fullName>
            </value>
            <value>
                <fullName>Document Preparation</fullName>
            </value>
            <value>
                <fullName>Drafting Will</fullName>
            </value>
            <value>
                <fullName>Employee Benefits</fullName>
            </value>
            <value>
                <fullName>Enforcement of Judgement</fullName>
            </value>
            <value>
                <fullName>Equitable Distribution</fullName>
            </value>
            <value>
                <fullName>Establishing Trust</fullName>
            </value>
            <value>
                <fullName>Estate Planning/Financial Advice</fullName>
            </value>
            <value>
                <fullName>Filing Estate or Inheritance Tax Returns</fullName>
            </value>
            <value>
                <fullName>Filing of Documents</fullName>
            </value>
            <value>
                <fullName>Financial Advice</fullName>
            </value>
            <value>
                <fullName>Foreclosures</fullName>
            </value>
            <value>
                <fullName>Forming Partnership/Joint Venture</fullName>
            </value>
            <value>
                <fullName>General Advice to Employer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Allegation__c.field-meta.xml
<CustomField>
    <fullName>Allegation__c</fullName>
    <label>Allegation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Conflict of Interest</fullName>
            </value>
            <value>
                <fullName>Conspiracy</fullName>
            </value>
            <value>
                <fullName>Declining Employment Improperly</fullName>
            </value>
            <value>
                <fullName>Error in Mathematical Calculation</fullName>
            </value>
            <value>
                <fullName>Error in Public Record Search</fullName>
            </value>
            <value>
                <fullName>Error in Service of Process/Give Notice</fullName>
            </value>
            <value>
                <fullName>Failure to Calendar Properly</fullName>
            </value>
            <value>
                <fullName>Failure to Follow Instructions or Obtain Client&apos;s Consent</fullName>
            </value>
            <value>
                <fullName>Failure to Know Where to File a Document/Venue</fullName>
            </value>
            <value>
                <fullName>Failure to Know or Ascertain a Deadline</fullName>
            </value>
            <value>
                <fullName>Failure to Know that a Document Should be Filed</fullName>
            </value>
            <value>
                <fullName>Failure to Know, Ascertain or Properly Apply Law</fullName>
            </value>
            <value>
                <fullName>Failure to Name the Proper Defendant</fullName>
            </value>
            <value>
                <fullName>Failure to Provide Client with Sufficient Information</fullName>
            </value>
            <value>
                <fullName>Failure to React to Calendar</fullName>
            </value>
            <value>
                <fullName>Fraud/Misrepresentation</fullName>
            </value>
            <value>
                <fullName>Improper Withdrawal from Representation</fullName>
            </value>
            <value>
                <fullName>Inadequate Discovery or Investigation</fullName>
            </value>
            <value>
                <fullName>Inadvertent Failure to File a Document</fullName>
            </value>
            <value>
                <fullName>Inadvertent Failure to follow Client Instructions</fullName>
            </value>
            <value>
                <fullName>Inadvertent Filing of Document in Wrong Place</fullName>
            </value>
            <value>
                <fullName>Intentional Breach of Fiduciary Duty</fullName>
            </value>
            <value>
                <fullName>Judgmental Error</fullName>
            </value>
            <value>
                <fullName>Libel, Slander, Defamation of Character</fullName>
            </value>
            <value>
                <fullName>Lost file, Document or Evidence</fullName>
            </value>
            <value>
                <fullName>Malicious Prosecution or Abuse of Process</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Procrastination/Failure to Follow-up</fullName>
            </value>
            <value>
                <fullName>Proofreading or other Clerical Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/AOP_Factor__c.field-meta.xml
<CustomField>
    <fullName>AOP_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area of Law</label>
    <referenceTo>AOP_Factor__c</referenceTo>
    <relationshipName>Policy_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Close_Payment_Resolutions__c.field-meta.xml
<CustomField>
    <fullName>Claim_Close_Payment_Resolutions__c</fullName>
    <label>Claim Close Payment Resolutions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed with no payment:  coverage denied</fullName>
            </value>
            <value>
                <fullName>Closed with no payment: no tender</fullName>
            </value>
            <value>
                <fullName>Closed with no payment:  only potential; claim never advanced</fullName>
            </value>
            <value>
                <fullName>Closed with lae payment only</fullName>
            </value>
            <value>
                <fullName>Closed with indemnity payment only</fullName>
            </value>
            <value>
                <fullName>Closed with both lae and indemnity payment</fullName>
            </value>
            <value>
                <fullName>Close with ULAE payment –disciplinary</fullName>
            </value>
            <value>
                <fullName>Closed with no payment: coverage denied</fullName>
                <isActive>false</isActive>
                <label>Closed with no payment: coverage denied</label>
            </value>
            <value>
                <fullName>Closed with no payment: only potential; claim never advanced</fullName>
                <isActive>false</isActive>
                <label>Closed with no payment: only potential; claim never advanced</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Close_Reasons__c.field-meta.xml
<CustomField>
    <fullName>Claim_Close_Reasons__c</fullName>
    <label>Claim Close Reasons</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Claim not advanced or unlikely to be</fullName>
            </value>
            <value>
                <fullName>No coverage</fullName>
            </value>
            <value>
                <fullName>No tender</fullName>
            </value>
            <value>
                <fullName>Successfully tendered to another carrier</fullName>
            </value>
            <value>
                <fullName>Suit voluntarily dismissed by plaintiff</fullName>
            </value>
            <value>
                <fullName>Suit dismissed on our motion</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Defense verdict at trial or arbitration</fullName>
            </value>
            <value>
                <fullName>Plaintiff verdict at trial or arbitration</fullName>
            </value>
            <value>
                <fullName>ARDC: investigation closed or limits reached</fullName>
            </value>
            <value>
                <fullName>ISBAM - IMPORT</fullName>
            </value>
            <value>
                <fullName>ISBAM - Remove</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Invoice</fullName>
            </value>
            <value>
                <fullName>Pending Close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/ClaimCloseDAte__c.field-meta.xml
<CustomField>
    <fullName>ClaimCloseDAte__c</fullName>
    <label>Claim Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GEO_Factor__c.field-meta.xml
<CustomField>
    <fullName>GEO_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GEO_Factor__c.Master_Factor__r.Default__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GEO_Factor__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Policy_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_2100__c.field-meta.xml
<CustomField>
    <fullName>GL_2100__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 2100</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_2140__c.field-meta.xml
<CustomField>
    <fullName>GL_2140__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 2140</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5010__c.field-meta.xml
<CustomField>
    <fullName>GL_5010__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5010</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Reserve_LAE__c.field-meta.xml
<CustomField>
    <fullName>Reserve_LAE__c</fullName>
    <defaultValue>$Setup.Claim_Setting__c.Open_Reserve_LAE_Value__c</defaultValue>
    <label>zzzOpen Reserve LAE</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Reserve_Loss__c.field-meta.xml
<CustomField>
    <fullName>Reserve_Loss__c</fullName>
    <defaultValue>$Setup.Claim_Setting__c.Open_Reserve_Loss_Value__c</defaultValue>
    <label>zzzOpen Reserve Loss</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Type_of_Error__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Error__c</fullName>
    <label>Type of Error</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admistrative Error</fullName>
            </value>
            <value>
                <fullName>Intentional Wrong</fullName>
            </value>
            <value>
                <fullName>Substantive Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClaimApplicationValidationCtrl.cls
public class ClaimApplicationValidationCtrl {
    
    @AuraEnabled
    public static Policy_Claim__c getPolicyClaim(String policyClaimId){
        Policy_Claim__c objPolicyClaim = [SELECT Id,Claim_Status__c,ClaimCloseDAte__c,Claim_Close_Payment_Resolutions__c,State__c,GEO_Factor__c,AOP_Factor__c, Activity__c, Allegation__c, Type_of_Error__c,
                                          Claim_Close_Reasons__c,Reserve_Loss__c,Reserve_LAE__c,GL_2140__c,GL_2100__c,GL_5010__c,GL_5035__c 
                                          FROM Policy_Claim__c WHERE Id =: policyClaimId];
        system.debug('objPolicyClaim :: ' + objPolicyClaim);
        return objPolicyClaim;
        
    }

}