force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Aggregate_Limit_For_All_Claims__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Limit_For_All_Claims__c</fullName>
    <formula>Aggregate_Limit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aggregate Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Id__c.field-meta.xml
<CustomField>
    <fullName>Claim_Id__c</fullName>
    <externalId>true</externalId>
    <label>Claim Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Incurred__c.field-meta.xml
<CustomField>
    <fullName>Claim_Incurred__c</fullName>
    <formula>GL_5010__c + GL_5000__c + GL_5035__c + GL_5030__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Claim Incurred</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_2120__c.field-meta.xml
<CustomField>
    <fullName>GL_2120__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 2120</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_2160__c.field-meta.xml
<CustomField>
    <fullName>GL_2160__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 2160</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5000__c.field-meta.xml
<CustomField>
    <fullName>GL_5000__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5000</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5010__c.field-meta.xml
<CustomField>
    <fullName>GL_5010__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5010</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5020__c.field-meta.xml
<CustomField>
    <fullName>GL_5020__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5020</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5030__c.field-meta.xml
<CustomField>
    <fullName>GL_5030__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5030</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5035__c.field-meta.xml
<CustomField>
    <fullName>GL_5035__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5035</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incurred_Ceded_LAE__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Ceded_LAE__c</fullName>
    <formula>Unpaid_Reserve_Ceded_LAE__c +
 Payment_Ceded_LAE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incurred Ceded LAE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incurred_Ceded_Loss__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Ceded_Loss__c</fullName>
    <formula>Unpaid_Reserve_Ceded_Loss__c +
 Payment_Ceded_Loss__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incurred Ceded Loss</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incurred_Direct_LAE__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Direct_LAE__c</fullName>
    <formula>Unpaid_Reserves_Direct_LAE__c +
Payment_Direct_LAE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incurred Direct LAE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incurred_Direct_Loss__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Direct_Loss__c</fullName>
    <formula>Unpaid_Reserves_Direct_Loss__c +
Payment_Direct_Loss__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incurred Direct Loss</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incurred_Retained_LAE__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Retained_LAE__c</fullName>
    <formula>Incurred_Direct_LAE__c -
  Incurred_Ceded_LAE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incurred Retained LAE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Incurred_Retained_Loss__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Retained_Loss__c</fullName>
    <formula>Incurred_Direct_Loss__c -
  Incurred_Ceded_Loss__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incurred Retained Loss</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Payment_Ceded_LAE__c.field-meta.xml
<CustomField>
    <fullName>Payment_Ceded_LAE__c</fullName>
    <label>Payment Ceded LAE</label>
    <summarizedField>Policy_Claim_Detail__c.Reinsurance_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Claim_Detail__c.Type__c</field>
        <operation>equals</operation>
        <value>Due from Reins. - LAE</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Claim_Detail__c.Policy_Claim__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Payment_Ceded_Loss__c.field-meta.xml
<CustomField>
    <fullName>Payment_Ceded_Loss__c</fullName>
    <label>Payment Ceded Loss</label>
    <summarizedField>Policy_Claim_Detail__c.Reinsurance_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Claim_Detail__c.Type__c</field>
        <operation>equals</operation>
        <value>Due from Reins. - Loss</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Claim_Detail__c.Policy_Claim__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Payment_Direct_LAE__c.field-meta.xml
<CustomField>
    <fullName>Payment_Direct_LAE__c</fullName>
    <label>Payment Direct LAE</label>
    <summarizedField>Policy_Claim_Detail__c.LAE_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Claim_Detail__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Claim Payment</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Claim_Detail__c.Policy_Claim__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Payment_Direct_Loss__c.field-meta.xml
<CustomField>
    <fullName>Payment_Direct_Loss__c</fullName>
    <label>Payment Direct Loss</label>
    <summarizedField>Policy_Claim_Detail__c.Loss_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Claim_Detail__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Claim Payment</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Claim_Detail__c.Policy_Claim__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Payment_Retained_LAE__c.field-meta.xml
<CustomField>
    <fullName>Payment_Retained_LAE__c</fullName>
    <formula>Payment_Direct_LAE__c -
 Payment_Ceded_LAE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Retained LAE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Payment_Retained_Loss__c.field-meta.xml
<CustomField>
    <fullName>Payment_Retained_Loss__c</fullName>
    <formula>Payment_Direct_Loss__c -
  Payment_Ceded_Loss__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Retained Loss</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Per_Claim_Deductible_Balance__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Deductible_Balance__c</fullName>
    <formula>Per_Claim_Deductible__c -
(Per_Claim_Deductible_Loss_Consumed__c +
Per_Claim_Deductible_LAE_Consumed__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Per Claim Deductible Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Per_Claim_Deductible_Consumed__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Deductible_Consumed__c</fullName>
    <formula>Per_Claim_Deductible_Loss_Consumed__c +
Per_Claim_Deductible_LAE_Consumed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Per Claim Deductible Consumed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Per_Claim_Deductible_formula__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Deductible_formula__c</fullName>
    <formula>Per_Claim_Deductible__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Per Claim Deductible (Formula)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy_Incurred__c.field-meta.xml
<CustomField>
    <fullName>Policy_Incurred__c</fullName>
    <formula>Policy__r.All_Claims_Incurred__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Incurred</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy_Remaining_By_All_Claims__c.field-meta.xml
<CustomField>
    <fullName>Policy_Remaining_By_All_Claims__c</fullName>
    <formula>Aggregate_Limit_For_All_Claims__c -
 Policy_Incurred__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Remaining_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Deductible__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Remaining Deductible</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/ULAE__c.field-meta.xml
<CustomField>
    <fullName>ULAE__c</fullName>
    <label>ULAE</label>
    <summarizedField>Policy_Claim_Detail__c.LAE_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Claim_Detail__c.Type__c</field>
        <operation>equals</operation>
        <value>ARDC Payment</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Policy_Claim_Detail__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Unallocated LAE</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Claim_Detail__c.Policy_Claim__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Unpaid_Reserve_Ceded_LAE__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Reserve_Ceded_LAE__c</fullName>
    <label>Unpaid Reserve Ceded LAE</label>
    <summarizedField>Policy_Claim_Detail__c.Reinsurance_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Claim_Detail__c.Type__c</field>
        <operation>equals</operation>
        <value>Change in Ceded LAE Reserve</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Claim_Detail__c.Policy_Claim__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Unpaid_Reserve_Ceded_Loss__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Reserve_Ceded_Loss__c</fullName>
    <label>Unpaid Reserve Ceded Loss</label>
    <summarizedField>Policy_Claim_Detail__c.Reinsurance_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Claim_Detail__c.Type__c</field>
        <operation>equals</operation>
        <value>Change in Ceded Loss Reserve</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Claim_Detail__c.Policy_Claim__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Unpaid_Reserves_Direct_LAE__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Reserves_Direct_LAE__c</fullName>
    <formula>Total_Reserve_Direct_LAE__c -
  Payment_Direct_LAE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Reserves Direct LAE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Unpaid_Reserves_Direct_Loss__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Reserves_Direct_Loss__c</fullName>
    <formula>Total_Reserve_Direct_Loss__c -
  Payment_Direct_Loss__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Reserves Direct Loss</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Unpaid_Reserves_Retained_LAE__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Reserves_Retained_LAE__c</fullName>
    <formula>Unpaid_Reserves_Direct_LAE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Reserves Retained LAE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Unpaid_Reserves_Retained_Loss__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Reserves_Retained_Loss__c</fullName>
    <formula>Unpaid_Reserves_Direct_Loss__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Reserves Retained Loss</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ClaimSummaryCtrl.cls
public class ClaimSummaryCtrl {
    @AuraEnabled
    public static ClaimSummaryWrapper getClaimDetails(string claimId){
        Map<String,Decimal> claimGLMap = new Map<String,Decimal>();
        Policy_Claim__c objPolicy = [select Id,Name,Claim_Id__c,Unpaid_Reserves_Direct_Loss__c,Unpaid_Reserves_Direct_LAE__c,Payment_Direct_Loss__c,Payment_Direct_LAE__c,Incurred_Direct_Loss__c,Incurred_Direct_LAE__c,
                                     Unpaid_Reserve_Ceded_Loss__c,Unpaid_Reserve_Ceded_LAE__c,Payment_Ceded_Loss__c,Payment_Ceded_LAE__c,Incurred_Ceded_Loss__c,Incurred_Ceded_LAE__c,
                                     Unpaid_Reserves_Retained_Loss__c,Unpaid_Reserves_Retained_LAE__c,Payment_Retained_Loss__c,Payment_Retained_LAE__c,Incurred_Retained_Loss__c,Incurred_Retained_LAE__c,
                                     Per_Claim_Deductible_formula__c,Per_Claim_Deductible_Consumed__c,Per_Claim_Deductible_Balance__c,
                                     Aggregate_Limit_For_All_Claims__c,Policy_Incurred__c,Policy_Remaining_By_All_Claims__c,ULAE__c,
                                     Per_Claim_Limit__c,Claim_Incurred__c,Remaining_Deductible__c,
                                     GL_5010__c,GL_5035__c,GL_2120__c,GL_2160__c,GL_5000__c,GL_5030__c,GL_5020__c,GL_5045__c,GL_5050__c,GL_5031__c,GL_5015__c,GL_5040__c,GL_5051__c
                                     from Policy_Claim__c WHERE Id=: claimId];

        Decimal unpaidReserveDirectLoss = objPolicy.GL_5010__c;
        Decimal unpaidReserveDirectLAE = objPolicy.GL_5035__c; 
        Decimal unpaidReserveCededLoss = objPolicy.GL_5015__c;  
        Decimal unpaidReserveCededLAE = objPolicy.GL_5040__c;   
        Decimal paymentsDirectLoss = objPolicy.GL_5000__c; 
        Decimal paymentsDirectLAE = objPolicy.GL_5030__c; 
        Decimal paymentsCededLoss = objPolicy.GL_5020__c; 
        Decimal paymentsCededLAE = objPolicy.GL_5045__c; 
        
        ClaimSummaryWrapper wrapperObj = new ClaimSummaryWrapper(unpaidReserveDirectLoss,unpaidReserveDirectLAE,unpaidReserveCededLoss,unpaidReserveCededLAE,paymentsDirectLoss,paymentsDirectLAE,paymentsCededLoss,paymentsCededLAE,objPolicy);
        return wrapperObj;
    }
    
    public class ClaimSummaryWrapper {
        @AuraEnabled
        public Decimal unpaidReserveDirectLoss{get;set;}
        @AuraEnabled
        public Decimal paymentsDirectLoss{get;set;}
        @AuraEnabled
        public Decimal incurredDirectLoss{get;set;}
        @AuraEnabled
        public Decimal unpaidReserveDirectLAE{get;set;}
        @AuraEnabled
        public Decimal paymentsDirectLAE{get;set;}
        @AuraEnabled
        public Decimal incurredDirectLAE{get;set;}
        
        @AuraEnabled
        public Decimal unpaidReserveCededLoss{get;set;}
        @AuraEnabled
        public Decimal paymentsCededLoss{get;set;}
        @AuraEnabled
        public Decimal incurredCededLoss{get;set;}
        @AuraEnabled
        public Decimal unpaidReserveCededLAE{get;set;}
        @AuraEnabled
        public Decimal paymentsCededLAE{get;set;}
        @AuraEnabled
        public Decimal incurredCededLAE{get;set;}
        
        @AuraEnabled
        public Decimal unpaidReserveRetainedLoss{get;set;}
        @AuraEnabled
        public Decimal paymentsRetainedLoss{get;set;}
        @AuraEnabled
        public Decimal incurredRetainedLoss{get;set;}
        @AuraEnabled
        public Decimal unpaidReserveRetainedLAE{get;set;}
        @AuraEnabled
        public Decimal paymentsRetainedLAE{get;set;}
        @AuraEnabled
        public Decimal incurredRetainedLAE{get;set;}
        
        @AuraEnabled
        public Policy_Claim__c claimObj{get;set;}
        
        public ClaimSummaryWrapper(Decimal unpaidReserveDirectLoss,Decimal unpaidReserveDirectLAE,Decimal unpaidReserveCededLoss,Decimal unpaidReserveCededLAE,Decimal paymentsDirectLoss,Decimal paymentsDirectLAE,Decimal paymentsCededLoss,Decimal paymentsCededLAE,Policy_Claim__c claimObj){
            this.unpaidReserveDirectLoss = unpaidReserveDirectLoss;
            this.unpaidReserveDirectLAE = unpaidReserveDirectLAE;
            this.unpaidReserveCededLoss = unpaidReserveCededLoss;
            this.unpaidReserveCededLAE = unpaidReserveCededLAE;
            this.paymentsDirectLoss = paymentsDirectLoss;
            this.paymentsDirectLAE = paymentsDirectLAE;
            this.paymentsCededLoss = paymentsCededLoss;
            this.paymentsCededLAE = paymentsCededLAE;
            this.unpaidReserveRetainedLoss  = unpaidReserveDirectLoss + unpaidReserveCededLoss;
            this.paymentsRetainedLoss = paymentsDirectLoss + paymentsCededLoss;
            this.unpaidReserveRetainedLAE = unpaidReserveDirectLAE + unpaidReserveCededLAE;
            this.paymentsRetainedLAE = paymentsDirectLAE + paymentsCededLAE;
            this.incurredDirectLoss = unpaidReserveDirectLoss + paymentsDirectLoss;
            this.incurredDirectLAE = unpaidReserveDirectLAE + paymentsDirectLAE;
            this.incurredCededLoss = unpaidReserveCededLoss + paymentsCededLoss;
            this.incurredCededLAE = unpaidReserveCededLAE + paymentsCededLAE;
            this.incurredRetainedLoss = this.unpaidReserveRetainedLoss + this.paymentsRetainedLoss;
            this.incurredRetainedLAE = this.unpaidReserveRetainedLAE + this.paymentsRetainedLAE;
            
            this.claimObj = claimObj;
        }
    }
}