force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Close_Payment_Resolutions__c.field-meta.xml
<CustomField>
    <fullName>Claim_Close_Payment_Resolutions__c</fullName>
    <label>Claim Close Payment Resolutions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed with no payment:  coverage denied</fullName>
            </value>
            <value>
                <fullName>Closed with no payment: no tender</fullName>
            </value>
            <value>
                <fullName>Closed with no payment:  only potential; claim never advanced</fullName>
            </value>
            <value>
                <fullName>Closed with lae payment only</fullName>
            </value>
            <value>
                <fullName>Closed with indemnity payment only</fullName>
            </value>
            <value>
                <fullName>Closed with both lae and indemnity payment</fullName>
            </value>
            <value>
                <fullName>Close with ULAE payment –disciplinary</fullName>
            </value>
            <value>
                <fullName>Closed with no payment: coverage denied</fullName>
                <isActive>false</isActive>
                <label>Closed with no payment: coverage denied</label>
            </value>
            <value>
                <fullName>Closed with no payment: only potential; claim never advanced</fullName>
                <isActive>false</isActive>
                <label>Closed with no payment: only potential; claim never advanced</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Close_Reasons__c.field-meta.xml
<CustomField>
    <fullName>Claim_Close_Reasons__c</fullName>
    <label>Claim Close Reasons</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Claim not advanced or unlikely to be</fullName>
            </value>
            <value>
                <fullName>No coverage</fullName>
            </value>
            <value>
                <fullName>No tender</fullName>
            </value>
            <value>
                <fullName>Successfully tendered to another carrier</fullName>
            </value>
            <value>
                <fullName>Suit voluntarily dismissed by plaintiff</fullName>
            </value>
            <value>
                <fullName>Suit dismissed on our motion</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Defense verdict at trial or arbitration</fullName>
            </value>
            <value>
                <fullName>Plaintiff verdict at trial or arbitration</fullName>
            </value>
            <value>
                <fullName>ARDC: investigation closed or limits reached</fullName>
            </value>
            <value>
                <fullName>ISBAM - IMPORT</fullName>
            </value>
            <value>
                <fullName>ISBAM - Remove</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Id__c.field-meta.xml
<CustomField>
    <fullName>Claim_Id__c</fullName>
    <externalId>true</externalId>
    <label>Claim Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Invoice</fullName>
            </value>
            <value>
                <fullName>Pending Close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/ClaimCloseDAte__c.field-meta.xml
<CustomField>
    <fullName>ClaimCloseDAte__c</fullName>
    <label>Claim Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5010__c.field-meta.xml
<CustomField>
    <fullName>GL_5010__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5010</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5035__c.field-meta.xml
<CustomField>
    <fullName>GL_5035__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5035</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Reserve_LAE__c.field-meta.xml
<CustomField>
    <fullName>Reserve_LAE__c</fullName>
    <defaultValue>$Setup.Claim_Setting__c.Open_Reserve_LAE_Value__c</defaultValue>
    <label>zzzOpen Reserve LAE</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Reserve_Loss__c.field-meta.xml
<CustomField>
    <fullName>Reserve_Loss__c</fullName>
    <defaultValue>$Setup.Claim_Setting__c.Open_Reserve_Loss_Value__c</defaultValue>
    <label>zzzOpen Reserve Loss</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Policy_Claim_Handler.cls
/*
 * 
 * Created By     : Shoukat Hussain
 * Created Date   : 12/02/2016
 * Purpose        : Trigger Handler for the Policy_claim SObject. This class implements the ITrigger interface to help ensure the trigger code is bulkified and all in one place.
 * Name           : Policy_Claim_Handler
 * Referenced     : Currently at the time of creation this class is referenced by TriggerFactory.
 * 
 *  
 */
public class Policy_Claim_Handler implements ITrigger {
//public with sharing class EndorsementHandler implements ITrigger {
    public Policy_Claim_Handler() {
    }

    public void bulkBefore() {
    }
    
    public void bulkAfter() {
    }
        
    public void beforeInsert(List<SObject> newItems) {
        
        if(Label.Allow_Claim_For_Expired_Policies == 'N'){
            Policy_Claim_Gateway.validateClaimPolicy(newItems);
        }
        
        //Add Claim Ids increament counter
        PolicyClaimCounter.createClaimIds(newItems);
        
          // Update Policy information on new claim
          Policy_Claim_Gateway.UpdatePolicyInfoOnClaim(newItems);
          
          // Udate Claims Check 
          Policy_Claim_Gateway.UpdateClaimCheck(newItems);

          // Update Custom setting [Deductible LAE applied limit ] for claim 
         Policy_Claim_Gateway.UpdateCustomSettingInfoOnClaim(newItems);
        for(SObject sObj : newItems){
            Policy_Claim__c obj = (Policy_Claim__c)sObj;
            if(obj.Claim_Id__c!=null){
                obj.Name = obj.Claim_Id__c;
            }
            if(obj.Reserve_Loss__c==null){
                obj.Reserve_Loss__c=0.0;
            }
            if(obj.Reserve_LAE__c==null){
                obj.Reserve_LAE__c=0.0;
            }
        }

		Policy_Claim_Gateway.UpdateScheduleDate(newItems);	
        
        
        
    }
    
    public void beforeUpdate(Map<Id,SObject> oldItems, Map<Id,SObject> newItems) {
          // Udate Claims Check 
          List<Policy_Claim__c> newItemsLst =  newItems.values(); 
        Map<Id,Policy_Claim__c> oldClaimMap =  (Map<Id,Policy_Claim__c>)oldItems;
          Policy_Claim_Gateway.UpdateClaimCheck(newItemsLst);

        for(Policy_Claim__c obj : newItemsLst){
            if(obj.Claim_Status__c == 'Closed' && oldClaimMap.get(obj.Id).Claim_Status__c!='Closed'){
                if(obj.ClaimCloseDAte__c == null){
                    obj.addError('In order to close the claim Claim close date not empty.');
                } else if(obj.GL_5035__c != 0){
                    obj.addError('In order to close the claim LAE Reserve must be 0.');
                } else if(obj.GL_5010__c !=0 ){
                    obj.addError('In order to close the claim Loss Reserve must be 0.');
                } else if(String.isBlank(obj.Claim_Close_Payment_Resolutions__c)){
                    obj.addError('In order to close the claim Claim Close Payment Resolutions not empty.');
                } else if(String.isBlank(obj.Claim_Close_Reasons__c)){
                    obj.addError('In order to close the claim Claim Close Reasons not empty.');
                }
            }
        }
    }
    
    public void beforeDelete(Map<Id,SObject> oldItems) {
    }
    
    public void afterInsert(Map<Id,SObject> newItems) {
        List<Policy_Claim__c> newItemsLst =  newItems.values();  
        Policy_Claim_Gateway.InsertReserveOpenRecord(newItemsLst);
        Policy_Claim_Gateway.createFollowUpTasks(newItemsLst);    }
    
    public void afterUpdate(Map<Id,SObject> oldItems, Map<Id,SObject> newItems) {
        System.debug(oldItems);
        System.debug(newItems);
        //Policy_Claim_Gateway.InsertReserveRecord((Map<Id,Policy_Claim__c>)oldItems,(Map<Id,Policy_Claim__c>)newItems);
    }
    
    public void afterDelete(Map<Id,SObject> oldItems) {
    }

    public void andFinally() {
    }
}