force-app/main/default/objects/Endorsement_Version__c/Endorsement_Version__c.object-meta.xml
<CustomObject>
    <label>Endorsement Version</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Endorsement Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endorsement Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Firm_Contact__c.field-meta.xml
<CustomField>
    <fullName>Firm_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Firm Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Firm_Contact_Email__c</fullName>
    <description>Related Firm Contact Email</description>
    <formula>Firm_Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Number__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Number__c</fullName>
    <label>Endorsement Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Version__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Version__c</fullName>
    <label>Endorsement Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SendPolicyEndorsementDocument.cls
public class SendPolicyEndorsementDocument implements Queueable, Database.AllowsCallouts {
    public String recId;
    public SendPolicyEndorsementDocument (String recId) {
        this.recId= recId;
    }
    public void execute(QueueableContext context) {
        
        List<EmailTemplate> templateList = new List<EmailTemplate>([Select id,Subject,Body,HtmlValue from EmailTemplate where name ='Endorsement Document']);
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>(); 
        
        String orgWideEmailAddressId = [select Id,Address from OrgWideEmailAddress where Address = 'underwriting@isbamutual.com'].Id;
        
        Policy_Endorsement__c endorsement = [SELECT Id,Endorsement_Version__c,Endorsement_Number__c,Policy__r.Firm_Contact__c, Policy__r.Firm_Contact_Email__c  FROM Policy_Endorsement__c WHERE Id =: recId ];
        
        Messaging.SingleEmailMessage emailMsg = Messaging.renderStoredEmailTemplate(templateList[0].Id,endorsement.Policy__r.Firm_Contact__c,endorsement.Id);
        
        String toEmail = endorsement.Policy__r.Firm_Contact_Email__c ;
        String subject = emailMsg.getSubject();
        String emailBody = emailMsg.getHtmlBody();
        emailBody = emailBody.replaceAll('<p><br></p>','<br><br>');
        emailBody = emailBody.replaceAll('</p><p>','<br/>');
        emailBody = emailBody.replaceAll('</p>','');
        emailBody = emailBody.replaceAll('<p>','');
            
        PageReference pdfPage = new PageReference('/apex/Endorsement_Pdf');
        pdfPage.getParameters().put('id', endorsement.Id);
        pdfPage.getParameters().put('number', endorsement.Endorsement_Number__c);
        pdfPage.getParameters().put('version', endorsement.Endorsement_Version__c);
        
        Blob pdfBlob;
        if (Test.isRunningTest()) {
            pdfBlob = Blob.valueOf('Test PDF Content');
        } else {
            pdfBlob = pdfPage.getContentAsPDF();
        }

        // Create email attachment
        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        attachment.setFileName('Endorsement_Pdf.pdf');
        attachment.setContentType('application/pdf');
        attachment.setBody(pdfBlob);

        // Prepare email
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setOrgWideEmailAddressId(orgWideEmailAddressId);
        email.setToAddresses(new String[] { toEmail });
        email.setSubject(subject);
        email.setPlainTextBody(emailBody);
        email.setFileAttachments(new Messaging.EmailFileAttachment[] { attachment });
        email.setWhatId(endorsement.Id);
        email.setSaveAsActivity(true);

        // Send email
        Messaging.SendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
    }
}