force-app/main/default/objects/Endorsement_Version__c/Endorsement_Version__c.object-meta.xml
<CustomObject>
    <label>Endorsement Version</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Endorsement Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endorsement Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Aggregate_Limit__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Limit__c</fullName>
    <label>Aggregate Limit</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Aggregate_Limit_History__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Limit_History__c</fullName>
    <label>Aggregate Limit History</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Effective_Date_History__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date_History__c</fullName>
    <label>Effective Date History</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Expiration_Date_History__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date_History__c</fullName>
    <label>Expiration Date History</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Firm_Billing_Address__c</fullName>
    <formula>Account__r.BillingStreet + BR() +
Account__r.BillingCity + &apos;, &apos; +  Account__r.BillingState + &apos;  &apos; + Account__r.BillingPostalCode</formula>
    <label>Firm Billing Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Billing_Address_History__c.field-meta.xml
<CustomField>
    <fullName>Firm_Billing_Address_History__c</fullName>
    <formula>SUBSTITUTE(Firm_Billing_Address_History_Intermedia__c, &apos;_BR_ENCODED_&apos;, &apos;&lt;br&gt;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm Billing Address History</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Name__c.field-meta.xml
<CustomField>
    <fullName>Firm_Name__c</fullName>
    <formula>Account__r.Name</formula>
    <label>Firm Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Name_History__c.field-meta.xml
<CustomField>
    <fullName>Firm_Name_History__c</fullName>
    <label>Firm Name History</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Full_Prior_Acts__c.field-meta.xml
<CustomField>
    <fullName>Full_Prior_Acts__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Full Prior Acts</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Issue_Date_History__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date_History__c</fullName>
    <label>Issue Date History</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Per_Claim_Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Deductible_Amount__c</fullName>
    <formula>Deductible_ID__r.Deductible_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Per Claim Deductible Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Per_Claim_Deductible_Amount_History__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Deductible_Amount_History__c</fullName>
    <label>Per Claim Deductible Amount History</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Per_Claim_Limit__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Limit__c</fullName>
    <label>Per Claim Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Per_Claim_Limit_History__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Limit_History__c</fullName>
    <label>Per Claim Limit History</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Number_History__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number_History__c</fullName>
    <label>Policy Number History</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Retroactive_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Retroactive_Date__c</fullName>
    <label>Prior Acts Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Retroactive_Date_History__c.field-meta.xml
<CustomField>
    <fullName>Policy_Retroactive_Date_History__c</fullName>
    <label>Policy Retroactive Date History</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Total Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium_History__c.field-meta.xml
<CustomField>
    <fullName>Premium_History__c</fullName>
    <label>Premium History</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Remove_102_Endorsement__c.field-meta.xml
<CustomField>
    <fullName>Remove_102_Endorsement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remove 102 Endorsement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Aggregate_Limit__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Limit__c</fullName>
    <formula>New_Limits__r.Full_Coverage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aggregate Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Name__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Name__c</fullName>
    <label>Endorsement Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Number__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Number__c</fullName>
    <label>Endorsement Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Version__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Version__c</fullName>
    <label>Endorsement Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Is_Application_Endorsement__c.field-meta.xml
<CustomField>
    <fullName>Is_Application_Endorsement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Application Endorsement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Per_Claim_Limit__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Limit__c</fullName>
    <formula>New_Limits__r.Coverage_Max_Per_Claim__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Per Claim Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Declaration_Page_Template_Ctrl.cls
public class Declaration_Page_Template_Ctrl {
	public String recordId;
    public policyWrapper policy{get;set;}
    public List<Policy_Endorsement__c> endorsements{get;set;}
    public void setrecordId(String recordId){
        Policy__c policyObj = [select id,name,FIRM_NAME_History__C, FIRM_BILLING_ADDRESS_History__C , POLICY_NUMBER_History__C,EFFECTIVE_DATE_History__C,EXPIRATION_DATE_History__C, PER_CLAIM_LIMIT_History__C,Full_Prior_Acts__c,
                  AGGREGATE_LIMIT_History__C ,PER_CLAIM_DEDUCTIBLE_AMOUNT_History__C,POLICY_RETROACTIVE_DATE_History__c,PREMIUM_History__c,ISSUE_DATE_History__c,Remove_102_Endorsement__c,Date_Signed__c,
                  Firm_Billing_Address__c,Firm_Name__c,EFFECTIVE_DATE__c,EXPIRATION_DATE__c,PER_CLAIM_LIMIT__c,AGGREGATE_LIMIT__c,PER_CLAIM_DEDUCTIBLE_AMOUNT__c,
                  POLICY_RETROACTIVE_DATE__c,PREMIUM__c,ISSUE_DATE__c,recordType.Name from Policy__C where id=: recordId];
        
        policy = new policyWrapper();
        policy.recId = policyObj.recordType.Name != 'Application' ? policyObj.Id : policyObj.Id;
        policy.name = policyObj.recordType.Name != 'Application' ? policyObj.Name : policyObj.Name;
        policy.FIRM_NAME_History = policyObj.recordType.Name != 'Application' ? policyObj.FIRM_NAME_History__c : policyObj.Firm_Name__c;
        policy.FIRM_BILLING_ADDRESS_History = policyObj.recordType.Name != 'Application' ? policyObj.FIRM_BILLING_ADDRESS_History__c : policyObj.Firm_Billing_Address__c;
        policy.POLICY_NUMBER_History = policyObj.recordType.Name != 'Application' ? policyObj.POLICY_NUMBER_History__c : policyObj.Name;
        policy.EFFECTIVE_DATE_History = policyObj.recordType.Name != 'Application' ? policyObj.EFFECTIVE_DATE_History__c : policyObj.EFFECTIVE_DATE__c;
        policy.EXPIRATION_DATE_History = policyObj.recordType.Name != 'Application' ? policyObj.EXPIRATION_DATE_History__c : policyObj.EXPIRATION_DATE__c;
        policy.PER_CLAIM_LIMIT_History = policyObj.recordType.Name != 'Application' ? policyObj.PER_CLAIM_LIMIT_History__c : policyObj.PER_CLAIM_LIMIT__c;
        policy.Full_Prior_Acts = policyObj.recordType.Name != 'Application' ? policyObj.Full_Prior_Acts__c : policyObj.Full_Prior_Acts__c;
        policy.AGGREGATE_LIMIT_History = policyObj.recordType.Name != 'Application' ? policyObj.AGGREGATE_LIMIT_History__c : policyObj.AGGREGATE_LIMIT__c;
        policy.PER_CLAIM_DEDUCTIBLE_AMOUNT_History = policyObj.recordType.Name != 'Application' ? policyObj.PER_CLAIM_DEDUCTIBLE_AMOUNT_History__c : policyObj.PER_CLAIM_DEDUCTIBLE_AMOUNT__c;
        policy.POLICY_RETROACTIVE_DATE_History = policyObj.recordType.Name != 'Application' ? policyObj.POLICY_RETROACTIVE_DATE_History__c : policyObj.POLICY_RETROACTIVE_DATE__c;
        policy.PREMIUM_History = policyObj.recordType.Name != 'Application' ? policyObj.PREMIUM_History__c : policyObj.PREMIUM__c;
        policy.ISSUE_DATE_History = policyObj.recordType.Name != 'Application' ? policyObj.ISSUE_DATE_History__c : policyObj.ISSUE_DATE__c;
        policy.Remove_102_Endorsement = policyObj.recordType.Name != 'Application' ? policyObj.Remove_102_Endorsement__c : policyObj.Remove_102_Endorsement__c;
        policy.Date_Signed = policyObj.recordType.Name != 'Application' ? policyObj.Date_Signed__c : policyObj.Date_Signed__c;
        
        String showIL102 = '';
        if(!policyObj.Remove_102_Endorsement__c){
            showIL102 = 'IL 102 PRIOR ACTS EXCLUSION ENDORSEMENT';
        }
    	endorsements = [select id, ENDORSEMENT_NUMBER__C , ENDORSEMENT_VERSION__c,ENDORSEMENT_NAME__C,Name 
                        	from Policy_Endorsement__C 
                        	where Policy__C =: recordId and 
                        		(Is_Application_Endorsement__c = true 
                                 	OR RecordType.Name =: showIL102 
                                 	OR RecordType.Name='IL 302 AMENDMENT OF EXTENDED REPORTING PERIOD OPTIONS ENDORSEMENT'
                                 	OR RecordType.Name='IL 230 ANNUAL AGGREGATE DEDUCTIBLE ENDORSEMENT'
                                 	OR RecordType.Name='IL 234 LOSS ONLY DEDUCTIBLE ENDORSEMENT'
                                 	OR RecordType.Name='IL 261 Claim Expenses Outside the Policy Limits Endorsement') 
                        	order by ENDORSEMENT_NUMBER__C];
    }
    public String getrecordId(){
        return recordId;
    }
    
    public class policyWrapper{
        public String recId {get;set;}
        public String Name {get;set;}
        public String FIRM_NAME_History {get;set;}
        public String FIRM_BILLING_ADDRESS_History  {get;set;}
        public String POLICY_NUMBER_History {get;set;}
        public Date EFFECTIVE_DATE_History {get;set;}
        public Date EXPIRATION_DATE_History {get;set;}
        public Double PER_CLAIM_LIMIT_History {get;set;}
        public Boolean Full_Prior_Acts {get;set;}
        public Double AGGREGATE_LIMIT_History  {get;set;}
        public Double PER_CLAIM_DEDUCTIBLE_AMOUNT_History {get;set;}
        public Date POLICY_RETROACTIVE_DATE_History {get;set;}
        public Double PREMIUM_History {get;set;}
        public Date ISSUE_DATE_History {get;set;}
        public Boolean Remove_102_Endorsement {get;set;}
        public Date Date_Signed {get;set;}
    }
}