force-app/main/default/objects/Endorsement_Version__c/Endorsement_Version__c.object-meta.xml
<CustomObject>
    <label>Endorsement Version</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Endorsement Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endorsement Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Number__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Number__c</fullName>
    <label>Endorsement Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Version__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Version__c</fullName>
    <label>Endorsement Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Event_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Event_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Void</fullName>
        <isActive>false</isActive>
        <label>Void</label>
    </customValue>
    <masterLabel>Event Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PolicyEndorsReject.cls
public class PolicyEndorsReject {
    @AuraEnabled
        public static Policy_Endorsement__c getPolicyEndorse(String policyId){
            Policy_Endorsement__c objPolicyEndorse = [SELECT Id,Name,Event_Status__c,Endorsement_Number__c,Endorsement_Version__c,Policy__c
                                                    FROM Policy_Endorsement__c WHERE Id =: policyId];
            return objPolicyEndorse ;
        }
        @AuraEnabled
        public static void deletePolicy(String policyId){
            Policy_Endorsement__c objPoliceEndor = new Policy_Endorsement__c(id = policyId);             
            delete objPoliceEndor;
        }
}