force-app/main/default/objects/Base_Factor__c/Base_Factor__c.object-meta.xml
<CustomObject>
    <label>Base Factor</label>
    <nameField>
        <label>Base Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Base Value</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Base Factors</relationshipLabel>
    <relationshipName>Base_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim_Setting__c/Claim_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>All default values for Claims</description>
    <label>Claims Settings</label>
</CustomObject>

force-app/main/default/objects/Master_Factor__c/Master_Factor__c.object-meta.xml
<CustomObject>
    <description>Object to hold master records of factors involved in calculations.</description>
    <label>Master Factor</label>
    <nameField>
        <label>Master Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Is_Accepted_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Is_Accepted_Confirm__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Application status = Accepted and Is_Accepted_Confirm=Yes then Opportunity stages would be Accepted.</description>
    <label>Is Accepted Confirm</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Is_Allow_to_Generate_AS__c.field-meta.xml
<CustomField>
    <fullName>Is_Allow_to_Generate_AS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field use for AS (Accounting Seeds)
If yes then AS transaction will be create.</description>
    <label>Is_Allow_to_Generate_AS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Step_Rate_Factor__c/Step_Rate_Factor__c.object-meta.xml
<CustomObject>
    <label>Step Rate Factor</label>
    <nameField>
        <label>Step Rate Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Step Rate Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Step_Rate_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Step Rate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Step Rate Factors</relationshipLabel>
    <relationshipName>Step_Rate_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuickPolicyController_Test.cls
@isTest
public class QuickPolicyController_Test {
    
    @isTest static void TestMethod1() {
        
        Account acc = TestDataFactory.createAccounts('Bucket Account');
        insert acc;
        
        
        Master_Factor__c objMasterFactor = TestDataFactory.createMasterfactor('Test Master Factor','Step rate');
        insert objMasterFactor;
        
        Step_Rate_Factor__c objStep = TestDataFactory.createStepFactor(objMasterFactor.Id);
        insert objStep;     
        
        Master_Factor__c objMasterFactor1 = TestDataFactory.createMasterfactor('Test Master Factor1','Base Value');
        insert objMasterFactor1;
        
        Base_Factor__c objBase = TestDataFactory.createBaseFactor(objMasterFactor1.Id);
        insert objBase;
        
        
        Claim_Setting__c objClaims = TestDataFactory.createClaimSetting();
        insert objClaims;
        
        Policy__c objPol = TestDataFactory.createPolicy(acc.id,null,null,'Application');
        objPol.Is_Accepted_Confirm__c = true;
        objPol.Is_Allow_to_Generate_AS__c = true;
        insert objPol;
        
        QuickPolicyController objQuickPolicy = new QuickPolicyController();
        QuickPolicyController.getPolicy(objPol.id);
        QuickPolicyController.getPolicies(objPol.id);
        QuickPolicyController.updatePolicy(objPol.id);
    }

}