force-app/main/default/objects/Base_Factor__c/Base_Factor__c.object-meta.xml
<CustomObject>
    <label>Base Factor</label>
    <nameField>
        <label>Base Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Factor__c/fields/Base_Amount__c.field-meta.xml
<CustomField>
    <fullName>Base_Amount__c</fullName>
    <label>Base Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Base Value</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Base Factors</relationshipLabel>
    <relationshipName>Base_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deductible_Factor__c/Deductible_Factor__c.object-meta.xml
<CustomObject>
    <label>Deductible Factor</label>
    <nameField>
        <label>Deductible Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deductible Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deductible_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Deductible</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Deductible Factors</relationshipLabel>
    <relationshipName>Deductible_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GEO_Factor__c/GEO_Factor__c.object-meta.xml
<CustomObject>
    <label>GEO Factor</label>
    <nameField>
        <label>GEO Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEO Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GEO_Factor__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>GEO Factors</relationshipLabel>
    <relationshipName>GEO_Factors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GEO_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>GEO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>GEO Factors</relationshipLabel>
    <relationshipName>GEO_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/ILF_Coverage_Factor__c.object-meta.xml
<CustomObject>
    <label>ILF / Limits Factor</label>
    <nameField>
        <label>ILF / Limit Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ILF / Limits Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>ILF / Limits Factors</relationshipLabel>
    <relationshipName>ILF_Coverage_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Base_Amount__c.field-meta.xml
<CustomField>
    <fullName>Base_Amount__c</fullName>
    <label>Base Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>County</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>GEO_Factor__c.Master_Factor__r.Default__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>GEO_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Deductible_ID__c.field-meta.xml
<CustomField>
    <fullName>Deductible_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deductible</label>
    <referenceTo>Deductible_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Mod__c.field-meta.xml
<CustomField>
    <fullName>Firm_Mod__c</fullName>
    <label>Firm Mod</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Limits</label>
    <referenceTo>ILF_Coverage_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/recordTypes/CP_Cancel_Policy_Transaction.recordType-meta.xml
<RecordType>
    <fullName>CP_Cancel_Policy_Transaction</fullName>
    <active>true</active>
    <description>Functional</description>
    <label>IL 190 Cancellation of Coverage</label>
</RecordType>

force-app/main/default/objects/Step_Rate_Factor__c/Step_Rate_Factor__c.object-meta.xml
<CustomObject>
    <label>Step Rate Factor</label>
    <nameField>
        <label>Step Rate Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Step Rate Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Step_Rate_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Step Rate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Step Rate Factors</relationshipLabel>
    <relationshipName>Step_Rate_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Policy_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <label>App Sent</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Requested Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Quoted</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>Lost</label>
    </customValue>
    <customValue>
        <fullName>Bound</fullName>
    </customValue>
    <customValue>
        <fullName>Printed</fullName>
    </customValue>
    <customValue>
        <fullName>Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Pending</fullName>
        <isActive>false</isActive>
        <label>Quote Pending</label>
    </customValue>
    <masterLabel>Policy Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PolicyEndorsReject_Test.cls
@isTest
private class PolicyEndorsReject_Test {
    @isTest static void testMethod1(){
        Test.startTest();
        
        Account acc                   = TestDataFactory.createAccounts('Test Account');
        acc.AccountNumber             = '123456';
        acc.Vendor_Account__c         = true;
        insert acc;
        
        Contact con                   = TestDataFactory.createContact('Test Contact',acc.id);
        insert con;
        
        AccountContactJunction__c acj = TestDataFactory.createAccConJunc(acc.id, con.id);
        acj.Name                      = 'Test Name';
        insert acj;
        
        List<AcctSeed__GL_Account__c> glAccounts = TestDataFactory.createGLAccounts();        
        insert glAccounts;
        
        List<AcctSeed__Billing_Format__c> billingFormats = TestDataFactory.createBillingFormats();        
        insert billingFormats ;
        
        List<AcctSeed__Ledger__c> ledgers = TestDataFactory.createLedgers(glAccounts[0].id,billingFormats[0].id,billingFormats[1].id,billingFormats[2].id,billingFormats[3].id,billingFormats[4].id);
        insert ledgers;
        
        AcctSeed__Accounting_Settings__c settings = TestDataFactory.createAccountsetting(ledgers[0].id,glAccounts[0].Id,glAccounts[1].Id,glAccounts[2].Id,glAccounts[3].Id,glAccounts[4].Id,glAccounts[5].Id,glAccounts[6].Id,billingFormats[0].Id);
        insert settings;
        
        Opportunity opp               = TestDataFactory.createOpp(acc.id);
        opp.StageName                 = 'Application Sent';
        insert opp;
        
        Master_Factor__c mas          = TestDataFactory.createMasterfactor('Test Master Factor1','geo');
        insert mas;
        
        County__c county = TestDataFactory.createCounty();
        insert county ;
        
        Geo_Factor__c geo = TestDataFactory.createGeoFactor(mas.Id,county.Id);
        insert geo;
        
        Master_Factor__c masterFactor = TestDataFactory.createMasterfactor('Test Master Factor','Step rate');
        insert masterFactor;
        
        Step_Rate_Factor__c stepRateFactor = TestDataFactory.createStepFactor(masterFactor.Id);
        insert stepRateFactor;
        
        Master_Factor__c masterFactor1 = TestDataFactory.createMasterfactor('Test Master Factor1','Base Value');
        insert masterFactor1;
        
        Base_Factor__c baseFactor = TestDataFactory.createBaseFactor(masterFactor1.Id);
        insert baseFactor;
        
        Master_Factor__c masterFactor2 = TestDataFactory.createMasterfactor('Test Master Factor0','Coverage');
        insert masterFactor2;
        
        ILF_Coverage_Factor__c ilfCoverageLowest = TestDataFactory.createCoveragefactor(masterFactor2.Id);
        insert ilfCoverageLowest;
        
        Master_Factor__c masterFactorDeductible = TestDataFactory.createMasterfactor('Test Master Factor1','Deductible');
        insert masterFactorDeductible;
        
        Deductible_Factor__c deductibles = TestDataFactory.createDeductiblefactor(masterFactorDeductible.Id);
        insert deductibles;
        
        Policy__c pol                 = TestDataFactory.createPolicy(acc.id,opp.id,geo.id,'Application');
        pol.Status__c                 = 'Application created';
        pol.Base_Amount__c            = 1;
        pol.Firm_Mod__c               = 1;
        pol.Limit__c                  = ilfCoverageLowest.Id;
        pol.Deductible_ID__c          = deductibles.Id;
        pol.Lost_Reason__c            = 'ISBAM - Other';
        pol.Premium__c                = 100;
        insert pol;
        
        Id devRecordEndorseTypeId = [SELECT Id FROM RecordType WHERE DeveloperName='CP_Cancel_Policy_Transaction' LIMIT 1].id;
        
        Endorsement__c endorse191= TestDataFactory.createEndorsement('IL 191','Functional','IL 190 Cancellation of Coverage');
        insert endorse191;
        
        Endorsement_Version__c endorseVersion = TestDataFactory.createEndorsementVersion(endorse191.Id);
        insert endorseVersion;
        
        Endorsement_Version__c endorseVersion2 = TestDataFactory.createEndorsementVersion(endorse191.Id);
        endorseVersion2.Endorsement_Version_Number__c='2';
        insert endorseVersion2;
        
        Policy_Endorsement__c poicyEndorse = TestDataFactory.createPolicyEndorsement(acc.id,pol.id,'IL 190 Cancellation of Coverage');
        insert poicyEndorse;
        
        poicyEndorse.Event_Status__c = 'Complete';
        update poicyEndorse;
        
        // delete poicyEndorse; 
        
        PolicyEndorsReject.getPolicyEndorse(poicyEndorse.id);
        PolicyEndorsReject.deletePolicy(poicyEndorse.id);
        
        Test.stopTest();
    }
}