force-app/main/default/objects/Customer_Application__c/Customer_Application__c.object-meta.xml
<CustomObject>
    <label>Online Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Online NBA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Online Applications</relationshipLabel>
    <relationshipName>Online_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Online_NBA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Contact_E_mail_Address__c.field-meta.xml
<CustomField>
    <fullName>Contact_E_mail_Address__c</fullName>
    <label>Contact E-mail Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Full_Legal_Name_of_the_Firm__c.field-meta.xml
<CustomField>
    <fullName>Full_Legal_Name_of_the_Firm__c</fullName>
    <label>Full Legal Name of the Firm</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/Customer_Application_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Customer Application Lawyer</label>
    <nameField>
        <label>Customer Application Lawyer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Application Lawyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/ARDC_Number__c.field-meta.xml
<CustomField>
    <fullName>ARDC_Number__c</fullName>
    <label>ARDC Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Application Lawyers</relationshipLabel>
    <relationshipName>Customer_Application_Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Customer Application Lawyers</relationshipLabel>
    <relationshipName>Customer_Application_Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/ISBA_Number__c.field-meta.xml
<CustomField>
    <fullName>ISBA_Number__c</fullName>
    <label>ISBA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RetryMatchCtrl.cls
public class RetryMatchCtrl {
    
    public class RetryMatchCtrlException extends Exception {}
    
    @AuraEnabled
    public static string reMatch(String recId){
        try {
            System.debug('recId => ' + recId);
            List<Customer_Application__c> cappList = new List<Customer_Application__c>([
                SELECT Id,
                       Full_Legal_Name_of_the_Firm__c,
                       Contact_E_mail_Address__c,
                       Account__c,
                       Contact__c,
                       (SELECT Id, Contact__c, ARDC_Number__c, ISBA_Number__c FROM Customer_Application_Lawyers__r)
                  FROM Customer_Application__c
                 WHERE Id =:recId
            ]);
            if(!cappList.isEmpty()){
                Customer_Application__c ca = cappList[0];
                Boolean flag = false;
                if(String.isNotBlank(ca.Full_Legal_Name_of_the_Firm__c)){
                    List<Account> accList = new List<Account>([SELECT Id, Name, Phone FROM Account WHERE Name =: ca.Full_Legal_Name_of_the_Firm__c LIMIT 1]);
                    if(!accList.isEmpty()){
                        ca.Account__c = accList[0].Id;
                        flag = true;
                    }
                }
                if(String.isNotBlank(ca.Contact_E_mail_Address__c)){
                    List<Contact> conList = new List<Contact>([SELECT Id, Email FROM Contact WHERE Email =: ca.Contact_E_mail_Address__c]);
                    if(!conList.isEmpty()){
                        ca.Contact__c = conList[0].Id;
                        flag = true;
                    }
                }
                
                if(flag){
                    Update ca;
                }
                
                if(ca.Customer_Application_Lawyers__r != null && !ca.Customer_Application_Lawyers__r.isEmpty()){
                    Set<String> isbaNumberSet = new Set<String>();
                    Set<String> ardcNumberSet = new Set<String>();
                    Map<String,Contact> isbaNumberContactMap = new Map<String,Contact>();
                    Map<String,Contact> ardcNumberContactMap = new Map<String,Contact>();
                    List<Customer_Application_Lawyer__c> updatedLawyers = new List<Customer_Application_Lawyer__c>();

                    for(Customer_Application_Lawyer__c lawyer : ca.Customer_Application_Lawyers__r){
                        if(lawyer.ARDC_Number__c != null){
                            ardcNumberSet.add(lawyer.ARDC_Number__c);
                        }
                        if(lawyer.ISBA_Number__c != null){
                            isbaNumberSet.add(lawyer.ISBA_Number__c);
                        }
                    }

                    if(!ardcNumberSet.isEmpty() || !isbaNumberSet.isEmpty()){
                        for(Contact cont : [select id,Name,ARDC_Number__c,ISBA__c from Contact where ISBA__c in: isbaNumberSet or ARDC_Number__c in: ardcNumberSet]){
                            if(cont.ARDC_Number__c != null){
                                ardcNumberContactMap.put(cont.ARDC_Number__c,cont);
                            }
                            if(cont.ISBA__c != null){
                                isbaNumberContactMap.put(cont.ISBA__c,cont);
                            }
                        }

                        for(Customer_Application_Lawyer__c lawyer : ca.Customer_Application_Lawyers__r){
                            if(lawyer.ARDC_Number__c != null && ardcNumberContactMap.containsKey(lawyer.ARDC_Number__c)){
                                lawyer.Contact__c = ardcNumberContactMap.get(lawyer.ARDC_Number__c).Id;
                                updatedLawyers.add(lawyer);
                            }else if(lawyer.ISBA_Number__c != null && isbaNumberContactMap.containsKey(lawyer.ISBA_Number__c)){
                                lawyer.Contact__c = isbaNumberContactMap.get(lawyer.ISBA_Number__c).Id;
                                updatedLawyers.add(lawyer);
                            }
                        }
                    }

                    if(!updatedLawyers.isEmpty()){
                        Update updatedLawyers;
                    }
                }
                
            }
            return 'success';
        } catch (DmlException e) {
            throw new RetryMatchCtrlException(e.getDmlMessage(0));
        } catch (Exception e) {
            throw new RetryMatchCtrlException(e.getMessage());
        }
    }
}