force-app/main/default/objects/Customer_Application__c/Customer_Application__c.object-meta.xml
<CustomObject>
    <label>Online Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Online NBA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/fields/Highest_Stage__c.field-meta.xml
<CustomField>
    <fullName>Highest_Stage__c</fullName>
    <label>Highest Stage</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/recordTypes/New_Business.recordType-meta.xml
<RecordType>
    <fullName>New_Business</fullName>
    <active>true</active>
    <label>New Business</label>
</RecordType>

force-app/main/default/classes/CreateInternalApplicationCtrl.cls
public class CreateInternalApplicationCtrl {

    @AuraEnabled
    public static Id CreateInternalApp(Customer_Application__c application) {
        
        Id recordTypeId = Schema.SObjectType.Customer_Application__c.getRecordTypeInfosByDeveloperName().get('New_Business').getRecordTypeId();
        
        application.Highest_Stage__c = 'Internal Application';
        application.RecordTypeId = recordTypeId;
        upsert application;
        return application.Id;
    }
}