force-app/main/default/objects/Customer_Application__c/Customer_Application__c.object-meta.xml
<CustomObject>
    <label>Online Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Online NBA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/fields/Is_the_firm_currently_insured__c.field-meta.xml
<CustomField>
    <fullName>Is_the_firm_currently_insured__c</fullName>
    <label>Is the firm currently insured?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unsure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerAppCreationEmail_CtrlTest.cls
@isTest
private class CustomerAppCreationEmail_CtrlTest {
	@isTest static void testCustomerAppCreation(){
        Test.startTest();
        CustomerApplicationCreationEmail_Ctrl cust = new CustomerApplicationCreationEmail_Ctrl();
        Customer_Application__c objCustomerApp = new Customer_Application__c();
        objCustomerApp.Is_the_firm_currently_insured__c = 'No';
        insert objCustomerApp;
        cust.setCustomerAppId(objCustomerApp.Id);
        cust.getCustomerAppId();
        Test.stopTest();
    }
}