force-app/main/default/objects/Customer_Application__c/Customer_Application__c.object-meta.xml
<CustomObject>
    <label>Online Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Online NBA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Online Applications</relationshipLabel>
    <relationshipName>Online_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Close_Description__c.field-meta.xml
<CustomField>
    <fullName>Close_Description__c</fullName>
    <label>Close Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Close_Reason__c.field-meta.xml
<CustomField>
    <fullName>Close_Reason__c</fullName>
    <label>Close Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coverage</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Employment</fullName>
            </value>
            <value>
                <fullName>ISBA Membership Cost</fullName>
            </value>
            <value>
                <fullName>Propestive Practice</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Online_NBA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Effective_Date_Requested__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date_Requested__c</fullName>
    <label>Effective Date Requested</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/Customer_Application_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Customer Application Lawyer</label>
    <nameField>
        <label>Customer Application Lawyer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Application Lawyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Application Lawyers</relationshipLabel>
    <relationshipName>Customer_Application_Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Customer Application Lawyers</relationshipLabel>
    <relationshipName>Customer_Application_Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{0}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Note__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/classes/CloseApplicationCtrl.cls
public class CloseApplicationCtrl{
    public class CloseApplicationCtrlException extends Exception{
    }
    
    @AuraEnabled
    public static List<String> getPickListVal(String strObjectName, String recId, String strPicklistField){
        try{
            List<String> pickListValuesList = new List<String>();
            Schema.SObjectType objSobjectType = Schema.getGlobalDescribe().get(strObjectName);
            Schema.DescribeSObjectResult objDescribeSobject = objSobjectType.getDescribe();
            Map<String, Schema.SObjectField> mapFields = objDescribeSobject.fields.getMap();
            
            List<Schema.PicklistEntry> lstPickListValues = mapFields.get(strPicklistField).getDescribe().getPickListValues();
            
            for (Schema.PicklistEntry objPickList : lstPickListValues){
                pickListValuesList.add(objPickList.getValue());
            }
            
            return pickListValuesList;
            
        } catch (Exception e){
            throw new CloseApplicationCtrlException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static Boolean save(String recId, String closeReason, String closeDescription){
        try{
            Customer_Application__c app = [SELECT Id, Account__c, Contact__c, Account__r.Recent_Application_Lookup__c, Account__r.Recent_Policy_Lookup__r.Active__c, Account__r.Recent_Policy_Lookup__c, Effective_Date_Requested__c, 
                                           (SELECT Id, Contact__c FROM Customer_Application_Lawyers__r)
                                           FROM Customer_Application__c 
                                           WHERE Id = :recId
                                           LIMIT 1];
            
            if (app.Account__c == null){
                throw new CloseApplicationCtrlException('Account not linked.');
            }
            
            if (app.Contact__c == null){
                throw new CloseApplicationCtrlException('Contact not linked.');
            }
            Set<Id> contactIds = new Set<Id>();
            if(app.Contact__c != null){
                contactIds.add(app.Contact__c);
            }
            
            
            Boolean flag = false;
            for (Customer_Application_Lawyer__c lw : app.Customer_Application_Lawyers__r){
                
                if (!String.isNotBlank(lw.Contact__c)){
                    
                    flag = true;
                }else{
                    contactIds.add(lw.Contact__c);
                }
                
            }
            
            if (flag){
                throw new CloseApplicationCtrlException('Lawyer(s) not linked.');
            }
            
            
            /*if ((app.Account__r.Recent_Application_Lookup__c != null) || (app.Account__r.Recent_Policy_Lookup__c != null && app.Account__r.Recent_Policy_Lookup__r.Active__c == true)){
                throw new CloseApplicationCtrlException('Account has existing application or policy');
            }*/
            
            app.Id = recId;
            app.Close_Reason__c = closeReason;
            app.Close_Description__c = closeDescription;
            app.Application_Status__c = 'Closed';
            update app;
            
            List<AccountContactRelation> queryAccountContactRelation = [Select Id,ContactId,AccountId from AccountContactRelation where AccountId =: app.Account__c];
            
            Map<Id, AccountContactRelation> junctionMap = new Map<Id, AccountContactRelation>();
            
            for(AccountContactRelation acr : queryAccountContactRelation){
                junctionMap.put(acr.ContactId, acr);
            }
            List<AccountContactRelation> accountContactList = new List<AccountContactRelation>();
            
            for(Id conId : contactIds){
                if(!junctionMap.containsKey(conId)){
                    
                    AccountContactRelation acr = new AccountContactRelation();
                    acr.AccountId = app.Account__c;
                    acr.ContactId = conId;
                    
                    accountContactList.add(acr);
                }
            }
            
            if(!accountContactList.isEmpty()){
                insert accountContactList;
            }
            
            Account acc = new Account();
            acc.Id = app.Account__c;
            acc.Ex_Date__c = String.valueOf(app.Effective_Date_Requested__c);
            update acc;
            
            List<Note__c> notes = new List<Note__c>([SELECT Id
                                                     FROM Note__c
                                                     WHERE Customer_Application__c = :recId]);
            
            if (!notes.isEmpty()){
                for (Note__c n : notes){
                    n.Account__c = app.Account__c;
                }
                Update notes;
            }
            
            
        } catch (DmlException e){
            System.debug('Error => '+e.getDmlMessage(0)+'\n At => '+e.getLineNumber());
            throw new CloseApplicationCtrlException(e.getDmlMessage(0));
        } catch (Exception e){
            System.debug('Error => '+e.getMessage()+'\n At => '+e.getLineNumber());
            throw new CloseApplicationCtrlException(e.getMessage());
        }
        return true;
    }
    
}