force-app/main/default/objects/Customer_Application__c/Customer_Application__c.object-meta.xml
<CustomObject>
    <label>Online Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Online NBA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Status_Description__c</fullName>
    <label>Status Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/StatusDescriptionCompCtrl.cls
public class StatusDescriptionCompCtrl {
    @AuraEnabled
    public static Policy__c getRecord(string RecordId){
        Policy__c pol = [select Id,Status_Description__c from Policy__c where Id =: RecordId];
        return pol;
    }
    
    @AuraEnabled
    public static string saveRecord(Policy__c pol){
        try{
            update pol;
            return 'Success';
        }catch(Exception e){
            system.debug('e.get'+e.getMessage()+'number::'+e.getLineNumber());
            system.debug('++'+e.getStackTraceString());
            return e.getMessage();
        }
    }
    
        @AuraEnabled
    public static Customer_Application__c getOnlineApp(String RecordId){
        Customer_Application__c app = [
            SELECT Id, Status_Description__c
            FROM Customer_Application__c
            WHERE Id = :RecordId
        ];
        return app;
    }

    @AuraEnabled
    public static String saveOnlineApp(Customer_Application__c app){
        try{
            update app;
            return 'Success';
        }catch(Exception e){
            System.debug('e.get'+e.getMessage()+'number::'+e.getLineNumber());
            System.debug('++'+e.getStackTraceString());
            return e.getMessage();
        }
    }
}