force-app/main/default/objects/Customer_Application__c/Customer_Application__c.object-meta.xml
<CustomObject>
    <label>Online Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Online NBA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Form_Link__c.field-meta.xml
<CustomField>
    <fullName>Form_Link__c</fullName>
    <label>Form Link</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/PolicyId__c.field-meta.xml
<CustomField>
    <fullName>PolicyId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Online_NBA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Underwriter_User__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Underwriter User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Online_Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Firm_Contact_First_Name__c</fullName>
    <formula>Firm_Contact__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm Contact First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Firm_Contact_Last_Name__c</fullName>
    <formula>Firm_Contact__r.LastName</formula>
    <label>Firm Contact Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter_Direct_Phone__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_Direct_Phone__c</fullName>
    <formula>Underwriter_User__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Underwriter Direct Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter_Email__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_Email__c</fullName>
    <formula>Underwriter_User__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Underwriter Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter_User__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Underwriter User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter_User_Title__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_User_Title__c</fullName>
    <formula>Underwriter_User__r.Title</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Underwriter User Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RegularRenewalOnlineApplicationCtrl.cls
public class RegularRenewalOnlineApplicationCtrl {
    
    public String objId {get; set;}
    public String recordId{get;set;}
    
    public RegularRenewalOnlineApplicationCtrl() {
        if (apexpages.currentpage().getparameters().get('id') != null){
            recordId = apexpages.currentpage().getparameters().get('id');
        }else{
            recordId = objId;
        }
        system.debug('recId => '+recordId);
        if(String.isNotBlank(recordId)){
            getObj();
        }
    }
    
    public Wrapper getObj() {
        system.debug('recId => '+recordId);
        Id recId = recordId;
        String sObjName = recId.getSObjectType().getDescribe().getName();
        Wrapper objNew = new Wrapper();
        
        if(sObjName == 'Policy__c'){
            Policy__c pol = [SELECT Id,Firm_Contact_First_Name__c,Firm_Contact_Last_Name__c,Customer_Application__r.Form_Link__c,Underwriter_User__r.Name,Underwriter_User_Title__c,Underwriter_Direct_Phone__c,Underwriter_Email__c FROM Policy__c WHERE Id=: recordId];
            objNew.name = pol.Firm_Contact_First_Name__c;
            objNew.name += String.isNotBlank(pol.Firm_Contact_Last_Name__c) ? ' ' + pol.Firm_Contact_Last_Name__c : '';
            objNew.link = pol.Customer_Application__r.Form_Link__c;
            objNew.underwriter_User = pol.Underwriter_User__r.Name;     
            objNew.underwriter_Title = pol.Underwriter_User_Title__c;   
            objNew.underwriter_Phone = pol.Underwriter_Direct_Phone__c;    
            objNew.underwriter_Email = pol.Underwriter_Email__c;
        }
        else if(sObjName == 'Customer_Application__c'){
            Customer_Application__c app = [SELECT Id,Contact_Name__c,Contact_Last_Name__c,Form_Link__c,PolicyId__r.Underwriter_User__r.Name,PolicyId__r.Underwriter_User_Title__c,PolicyId__r.Underwriter_Direct_Phone__c,PolicyId__r.Underwriter_Email__c FROM Customer_Application__c WHERE Id=: recordId];
            objNew.name = app.Contact_Name__c;
            objNew.name += String.isNotBlank(app.Contact_Last_Name__c) ? ' ' + app.Contact_Last_Name__c : '';
            objNew.link = app.Form_Link__c;
            objNew.underwriter_User = app.PolicyId__r.Underwriter_User__r.Name;     
            objNew.underwriter_Title = app.PolicyId__r.Underwriter_User_Title__c;   
            objNew.underwriter_Phone = app.PolicyId__r.Underwriter_Direct_Phone__c;    
            objNew.underwriter_Email = app.PolicyId__r.Underwriter_Email__c;
        }
        return objNew;
    }
    
    public class Wrapper {
        public String name {get; set;}
        public String link {get; set;}
        public String underwriter_User {get; set;}
        public String underwriter_Title {get; set;}
        public String underwriter_Phone {get; set;}
        public String underwriter_Email {get; set;}
        public Wrapper(){
            name = null;
            link = null;
            underwriter_User = null;
            underwriter_Title = null;
            underwriter_Phone = null;
            underwriter_Email = null;
        }
    }
}