force-app/main/default/objects/AccountContactJunction__c/AccountContactJunction__c.object-meta.xml
<CustomObject>
    <description>Account contact junction object</description>
    <label>Lawyer</label>
    <nameField>
        <label>Lawyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/Customer_Application__c.object-meta.xml
<CustomObject>
    <label>Online Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Online NBA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/fields/PolicyId__c.field-meta.xml
<CustomField>
    <fullName>PolicyId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Online_NBA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Trade_Name_or_D_B_A__c.field-meta.xml
<CustomField>
    <fullName>Trade_Name_or_D_B_A__c</fullName>
    <label>Trade Name or D/B/A</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/Customer_Application_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Customer Application Lawyer</label>
    <nameField>
        <label>Customer Application Lawyer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Application Lawyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/ARDC_Number__c.field-meta.xml
<CustomField>
    <fullName>ARDC_Number__c</fullName>
    <label>ARDC Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Customer Application Lawyers</relationshipLabel>
    <relationshipName>Customer_Application_Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Is_Removed__c.field-meta.xml
<CustomField>
    <fullName>Is_Removed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Removed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Establish_Date__c.field-meta.xml
<CustomField>
    <fullName>Establish_Date__c</fullName>
    <label>xxx-Establish Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Contact__c.field-meta.xml
<CustomField>
    <fullName>Firm_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Firm Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/classes/LawyerAddedFlagCtrlTest.cls
@isTest
public class LawyerAddedFlagCtrlTest {
    
    @isTest
    static void testGetDetails_WithLawyers() {
        Account availableAccount = TestDataFactory.createAccounts('test');
        availableAccount.Trade_Name_or_D_B_A__c = 'Available Trade Name';
        availableAccount.BillingStreet = '123 Main St';
        availableAccount.BillingCity = 'Chicago';
        availableAccount.BillingState = 'IL';
        availableAccount.BillingPostalCode = '60601';
        availableAccount.Phone = '3125550101';
        availableAccount.Website__c = 'https://available.example.com';
        availableAccount.Establish_Date__c = Date.newInstance(2000, 1, 1);
        insert availableAccount;

        Contact availableContact = TestDataFactory.createContact('Available Lawyer', availableAccount.Id);
        availableContact.FirstName = 'Ava';
        availableContact.Phone = '3125550102';
        availableContact.MobilePhone = '3125550103';
        availableContact.Email = 'ava.lawyer@example.com';
        availableContact.Personal_Email__c = 'ava.personal@example.com';
        availableContact.Birthdate = Date.newInstance(1990, 1, 1);
        availableContact.ARDC_Number__c = '10000001';
        availableContact.ISBA__c = 'ISBA-1001';
        insert availableContact;

        AccountContactJunction__c availableJunction = TestDataFactory.createAccConJunc(availableAccount.Id, availableContact.Id);
        availableJunction.Name = 'Available Junction';
        insert availableJunction;

        Opportunity availableOpportunity = TestDataFactory.createOpp(availableAccount.Id);
        insert availableOpportunity;

        Policy__c availableApplication = TestDataFactory.createPolicy(availableAccount.Id, availableOpportunity.Id, null, 'Policy');
        availableApplication.Name = 'APP-AVAILABLE';
        availableApplication.Firm_Contact__c = availableContact.Id;
        insert availableApplication;
        
        Customer_Application__c app = new Customer_Application__c(PolicyId__c = availableApplication.Id);
        insert app;
        
        Customer_Application_Lawyer__c appLawyer = new Customer_Application_Lawyer__c(
            Customer_Application__c = app.Id,
            Is_Removed__c = false,
            Is_New__c = true,
            ARDC_Number__c = 'ARD12345'
        );
        insert appLawyer;
        
        // Test the controller method
        Test.startTest();
        String result = LawyerAddedFlagCtrl.getDetails(app.Id);
        Test.stopTest();
        
    }
    
}