force-app/main/default/objects/AccountContactJunction__c/AccountContactJunction__c.object-meta.xml
<CustomObject>
    <description>Account contact junction object</description>
    <label>Lawyer</label>
    <nameField>
        <label>Lawyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContactJunction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>AccountContactJunction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_AOP__c/Policy_AOP__c.object-meta.xml
<CustomObject>
    <label>Area of Practice</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Area of Practice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Area of Practice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_AOP__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Area of Practice</relationshipLabel>
    <relationshipName>Policy_AOPs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>AccountContactJunction__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>AccountContactJunction__c.Contact__r.Type__c</field>
            <operation>equals</operation>
            <value>Lawyer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AccountContactJunction__c</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy_Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Policy_Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Policy_Lawyer__c.Deleted_Lawyer__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Policy__c</field>
            <operation>equals</operation>
            <valueField>Policy_Lawyer__c.Policy__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Policy_Lawyer__c</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/Policy_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Policy Lawyer</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Lawyer__c/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lawyer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AccountContactJunction__c.Contact__r.Type__c</field>
            <operation>equals</operation>
            <value>Lawyer</value>
        </filterItems>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>AccountContactJunction__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountContactJunction__c</referenceTo>
    <relationshipLabel>Policy Lawyers</relationshipLabel>
    <relationshipName>Policy_Lawyers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Lawyers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/Policy_Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Quote-{000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Policy_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PolicyRelatedObjectOverrideCtrl.cls
public class PolicyRelatedObjectOverrideCtrl {
    @AuraEnabled
    public static PolicyRelatedObjectOverrideCtrlWrapper isOperationAllowed(String recordId,String operation){
        String objName = Id.valueOf(recordId).getSObjectType().getDescribe().getName();
        PolicyRelatedObjectOverrideCtrlWrapper wrapper;
        if(objName == 'Policy_AOP__c'){
            List<Policy_AOP__c> policyAOPs = new List<Policy_AOP__c>([select id,Policy__c,Policy__r.RecordType.Name from Policy_AOP__c where id=: recordId]);
            if(policyAOPs.size()>0 && policyAOPs[0].Policy__r.RecordType.Name == 'Application'){
                wrapper = new PolicyRelatedObjectOverrideCtrlWrapper('Yes','/apex/AreaofPracticeDetailPageEdit_Ltng?id=' + policyAOPs[0].Policy__c +'&showNext=false');
            }else if(policyAOPs.size()>0 && policyAOPs[0].Policy__r.RecordType.Name == 'Policy'){
                wrapper = new PolicyRelatedObjectOverrideCtrlWrapper('No',policyAOPs[0].Policy__c);
            }
        }else if(objName == 'Policy_Quote__c'){
            List<Policy_Quote__c> quotes = new List<Policy_Quote__c>([select id,Policy__c,Policy__r.RecordType.Name from Policy_Quote__c where id=: recordId]);
            if(quotes.size()>0 && quotes[0].Policy__r.RecordType.Name == 'Application'){
                wrapper = new PolicyRelatedObjectOverrideCtrlWrapper('Yes','/apex/QuotesDetailPage?id=' + quotes[0].Policy__c +'&showNext=false');
            }else if(quotes.size()>0 && quotes[0].Policy__r.RecordType.Name == 'Policy'){
                wrapper = new PolicyRelatedObjectOverrideCtrlWrapper('No',quotes[0].Policy__c);
            }
        }else if(objName == 'Policy_Lawyer__c'){
            List<Policy_Lawyer__c> lawyers = new List<Policy_Lawyer__c>([select id,Policy__c,Policy__r.RecordType.Name,Policy__r.Effective_Date__c,Lawyer__r.Contact__c from Policy_Lawyer__c where id=: recordId]);
            if(lawyers.size()>0 && lawyers[0].Policy__r.RecordType.Name == 'Application'){
                wrapper = new PolicyRelatedObjectOverrideCtrlWrapper('Yes','/apex/ContactDetailPageEdit_Ltng?id=' + lawyers[0].Lawyer__r.Contact__c +'&retURL=' + lawyers[0].Policy__c);
            }else if(lawyers.size()>0 && lawyers[0].Policy__r.RecordType.Name == 'Policy'){
                if(operation == 'Delete'){
                    String effectiveDate;
                    RecordType recordType = [SELECT Id, Name FROM RecordType WHERE Name = 'IL 153 Deleting an Attorney Endorsement' and SobjectType = 'Policy_Endorsement__c' LIMIT 1];
                    if (lawyers[0].Policy__r.Effective_Date__c != null) {
                        effectiveDate = String.valueOf(lawyers[0].Policy__r.Effective_Date__c.Month() + '/' + lawyers[0].Policy__r.Effective_Date__c.Day() + '/' + lawyers[0].Policy__r.Effective_Date__c.Year());
                    } else {
                        effectiveDate = String.valueOf(Date.today().Month() + '/' + Date.today().Day() + '/' + Date.today().Year());
                    }
                    wrapper = new PolicyRelatedObjectOverrideCtrlWrapper('Yes','/apex/DeletingAnAttorney?policyId=' + lawyers[0].Policy__c +  '&Name='+recordType.Name+ '&RecordType=' + recordType.Id +'&effectiveDate=' + effectiveDate);
                }else{
                    wrapper = new PolicyRelatedObjectOverrideCtrlWrapper('Yes','/apex/ContactDetailPageEdit_Ltng?id=' + lawyers[0].Lawyer__r.Contact__c +'&retURL=' + lawyers[0].Policy__c);
                }
            }
        }
        return wrapper;
    }
    @TestVisible class PolicyRelatedObjectOverrideCtrlWrapper{
        @AuraEnabled
        public String isOperationAllowed;
        @AuraEnabled
        public String returnURL;
        PolicyRelatedObjectOverrideCtrlWrapper(String isOperationAllowed,String returnURL){
            this.isOperationAllowed = isOperationAllowed;
            this.returnURL = returnURL;
        }
    }
}