force-app/main/default/objects/AccountContactJunction__c/AccountContactJunction__c.object-meta.xml
<CustomObject>
    <description>Account contact junction object</description>
    <label>Lawyer</label>
    <nameField>
        <label>Lawyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContactJunction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountContactJunction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountContactJunction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>AccountContactJunction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/Customer_Application__c.object-meta.xml
<CustomObject>
    <label>Online Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Online NBA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Online Applications</relationshipLabel>
    <relationshipName>Online_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Online_NBA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Contact_E_mail_Address__c.field-meta.xml
<CustomField>
    <fullName>Contact_E_mail_Address__c</fullName>
    <label>Contact E-mail Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Contact_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Phone_Number__c</fullName>
    <label>Contact Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Date_Firm_Established__c.field-meta.xml
<CustomField>
    <fullName>Date_Firm_Established__c</fullName>
    <label>Date Firm Established</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Firm_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Firm_Phone_Number__c</fullName>
    <label>Firm Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Full_Legal_Name_of_the_Firm__c.field-meta.xml
<CustomField>
    <fullName>Full_Legal_Name_of_the_Firm__c</fullName>
    <label>Full Legal Name of the Firm</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
                <default>true</default>
                <label>IL</label>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Trade_Name_or_D_B_A__c.field-meta.xml
<CustomField>
    <fullName>Trade_Name_or_D_B_A__c</fullName>
    <label>Trade Name or D/B/A</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/Customer_Application_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Customer Application Lawyer</label>
    <nameField>
        <label>Customer Application Lawyer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Application Lawyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/ARDC_Number__c.field-meta.xml
<CustomField>
    <fullName>ARDC_Number__c</fullName>
    <label>ARDC Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Application Lawyers</relationshipLabel>
    <relationshipName>Customer_Application_Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Customer Application Lawyers</relationshipLabel>
    <relationshipName>Customer_Application_Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Firm_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Firm_Email_Address__c</fullName>
    <label>Firm Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/ISBA_Number__c.field-meta.xml
<CustomField>
    <fullName>ISBA_Number__c</fullName>
    <label>ISBA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Middle_Initial__c.field-meta.xml
<CustomField>
    <fullName>Middle_Initial__c</fullName>
    <label>Middle Initial</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Personal_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Personal_Email_Address__c</fullName>
    <label>Personal Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Establish_Date__c.field-meta.xml
<CustomField>
    <fullName>Establish_Date__c</fullName>
    <label>xxx-Establish Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Contact__c.field-meta.xml
<CustomField>
    <fullName>Firm_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Firm Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Lawyer__c/Policy_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Policy Lawyer</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Lawyer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/ARDC_Number__c.field-meta.xml
<CustomField>
    <fullName>ARDC_Number__c</fullName>
    <formula>Lawyer__r.Contact__r.ARDC_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARDC Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/ISBA_Number__c.field-meta.xml
<CustomField>
    <fullName>ISBA_Number__c</fullName>
    <formula>Lawyer__r.Contact__r.ISBA__c</formula>
    <label>ISBA Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lawyer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AccountContactJunction__c.Contact__r.Type__c</field>
            <operation>equals</operation>
            <value>Lawyer</value>
        </filterItems>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>AccountContactJunction__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountContactJunction__c</referenceTo>
    <relationshipLabel>Policy Lawyers</relationshipLabel>
    <relationshipName>Policy_Lawyers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Lawyers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CloneToOnlineAppCtrlTest.cls
@isTest
public class CloneToOnlineAppCtrlTest {
    public static final String AVAILABLE_ACCOUNT_NAME = 'Clone Available Account';
    public static final String BLOCKED_ACCOUNT_NAME = 'Clone Blocked Account';

    @testSetup
    static void setupData() {
        Account availableAccount = TestDataFactory.createAccounts(AVAILABLE_ACCOUNT_NAME);
        availableAccount.Trade_Name_or_D_B_A__c = 'Available Trade Name';
        availableAccount.BillingStreet = '123 Main St';
        availableAccount.BillingCity = 'Chicago';
        availableAccount.BillingState = 'IL';
        availableAccount.BillingPostalCode = '60601';
        availableAccount.Phone = '3125550101';
        availableAccount.Website__c = 'https://available.example.com';
        availableAccount.Establish_Date__c = Date.newInstance(2000, 1, 1);
        insert availableAccount;

        Contact availableContact = TestDataFactory.createContact('Available Lawyer', availableAccount.Id);
        availableContact.FirstName = 'Ava';
        availableContact.Phone = '3125550102';
        availableContact.MobilePhone = '3125550103';
        availableContact.Email = 'ava.lawyer@example.com';
        availableContact.Personal_Email__c = 'ava.personal@example.com';
        availableContact.Birthdate = Date.newInstance(1990, 1, 1);
        availableContact.ARDC_Number__c = '10000001';
        availableContact.ISBA__c = 'ISBA-1001';
        insert availableContact;

        AccountContactJunction__c availableJunction = TestDataFactory.createAccConJunc(availableAccount.Id, availableContact.Id);
        availableJunction.Name = 'Available Junction';
        insert availableJunction;

        Opportunity availableOpportunity = TestDataFactory.createOpp(availableAccount.Id);
        insert availableOpportunity;

        Policy__c availableApplication = TestDataFactory.createPolicy(availableAccount.Id, availableOpportunity.Id, null, 'Policy');
        availableApplication.Name = 'APP-AVAILABLE';
        availableApplication.Firm_Contact__c = availableContact.Id;
        insert availableApplication;

        Policy_Lawyer__c availableLawyer = TestDataFactory.createPolicyLawyer(
            availableAccount.Id,
            availableApplication.Id,
            availableJunction.Id
        );
        availableLawyer.Lawyer__c = availableJunction.Id;
        insert availableLawyer;

        Account blockedAccount = TestDataFactory.createAccounts(BLOCKED_ACCOUNT_NAME);
        blockedAccount.BillingStreet = '456 State St';
        blockedAccount.BillingCity = 'Springfield';
        blockedAccount.BillingState = 'IL';
        blockedAccount.BillingPostalCode = '62701';
        insert blockedAccount;

        Contact blockedContact = TestDataFactory.createContact('Blocked Lawyer', blockedAccount.Id);
        blockedContact.FirstName = 'Blake';
        blockedContact.Email = 'blocked.lawyer@example.com';
        insert blockedContact;

        Opportunity blockedOpportunity = TestDataFactory.createOpp(blockedAccount.Id);
        insert blockedOpportunity;
    }

    @isTest
    static void testGetPolicyCreatesOnlineApplication() {
        Policy__c sourceApplication = [
            SELECT Id, Account__c
            FROM Policy__c
            WHERE Account__r.Name = :AVAILABLE_ACCOUNT_NAME
            AND RecordType.DeveloperName = 'Policy'
            LIMIT 1
        ];

        Test.startTest();
        String onlineApplicationId = CloneToOnlineAppCtrl.getPolicy(sourceApplication.Id);
        Test.stopTest();

        Customer_Application__c onlineApplication = [
            SELECT Id, RecordType.DeveloperName, Account__c, Full_Legal_Name_of_the_Firm__c,
                   Trade_Name_or_D_B_A__c, Street__c, City__c, State__c, Zip_Code__c,
                   Firm_Phone_Number__c, Website__c, Date_Firm_Established__c, Contact__c,
                   Contact_Name__c, Contact_Last_Name__c, Contact_Phone_Number__c,
                   Contact_E_mail_Address__c
            FROM Customer_Application__c
            WHERE Id = :onlineApplicationId
        ];


        List<Customer_Application_Lawyer__c> applicationLawyers = [
            SELECT Name, Contact__c, Middle_Initial__c, Last_Name__c, ISBA_Number__c,
                   ARDC_Number__c, Cell_Phone__c, Birthday__c, Firm_Email_Address__c,
                   Personal_Email_Address__c
            FROM Customer_Application_Lawyer__c
            WHERE Customer_Application__c = :onlineApplication.Id
        ];
    }

    
}