force-app/main/default/objects/AccountContactJunction__c/AccountContactJunction__c.object-meta.xml
<CustomObject>
    <description>Account contact junction object</description>
    <label>Lawyer</label>
    <nameField>
        <label>Lawyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContactJunction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountContactJunction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountContactJunction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>AccountContactJunction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLE_Attendance__c/CLE_Attendance__c.object-meta.xml
<CustomObject>
    <label>CLE Attendance</label>
    <nameField>
        <displayFormat>CLE-{00000}</displayFormat>
        <label>CLE Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CLE Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLE_Attendance__c/fields/CLE_Event__c.field-meta.xml
<CustomField>
    <fullName>CLE_Event__c</fullName>
    <label>CLE Event</label>
    <referenceTo>CLE_Event__c</referenceTo>
    <relationshipLabel>CLE Attendances</relationshipLabel>
    <relationshipName>CLE_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLE_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CLE Attendances</relationshipLabel>
    <relationshipName>CLE_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLE_Event__c/CLE_Event__c.object-meta.xml
<CustomObject>
    <label>CLE Event</label>
    <nameField>
        <label>CLE Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CLE Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GEO_Factor__c/GEO_Factor__c.object-meta.xml
<CustomObject>
    <label>GEO Factor</label>
    <nameField>
        <label>GEO Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEO Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GEO_Factor__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>GEO Factors</relationshipLabel>
    <relationshipName>GEO_Factors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GEO_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>GEO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>GEO Factors</relationshipLabel>
    <relationshipName>GEO_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Master_Factor__c/Master_Factor__c.object-meta.xml
<CustomObject>
    <description>Object to hold master records of factors involved in calculations.</description>
    <label>Master Factor</label>
    <nameField>
        <label>Master Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>County</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>GEO_Factor__c.Master_Factor__r.Default__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>GEO_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Lawyer__c/Policy_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Policy Lawyer</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Lawyer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Deleted_Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Deleted_Lawyer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the lawyer is deleted by Delete Lawyer Endorsement then this check will set to true.</description>
    <label>Deleted Lawyer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Is_Application_Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Is_Application_Lawyer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Application Lawyer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lawyer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AccountContactJunction__c.Contact__r.Type__c</field>
            <operation>equals</operation>
            <value>Lawyer</value>
        </filterItems>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>AccountContactJunction__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountContactJunction__c</referenceTo>
    <relationshipLabel>Policy Lawyers</relationshipLabel>
    <relationshipName>Policy_Lawyers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Overriding_Step_Value__c.field-meta.xml
<CustomField>
    <fullName>Overriding_Step_Value__c</fullName>
    <inlineHelpText>Additional Step Value will be added to Calculated Step Rating.</inlineHelpText>
    <label>Additional Step Value</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>-1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Lawyers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Policy_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Effective_Date__c</fullName>
    <formula>Policy__r.Effective_Date__c</formula>
    <label>Policy Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Prior_Act_Date__c.field-meta.xml
<CustomField>
    <fullName>Prior_Act_Date__c</fullName>
    <label>Prior Act Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Rate_At__c.field-meta.xml
<CustomField>
    <fullName>Rate_At__c</fullName>
    <label>Rate At (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PolicyLawyerHandler_Test.cls
@isTest
public class PolicyLawyerHandler_Test {
    
    @testSetUp
    static void testData(){
        
        // Insert Account
        Account acc = TestDataFactory.createAccounts('Test');
        insert acc;
        
        // Insert Contact
        Contact con =  TestDataFactory.createContact('Last Name',acc.id);
        insert con;
        
        // Insert Opportunity
        Opportunity opp = TestDataFactory.createOpp(acc.id);
        insert opp;
        
        // Insert Master Factor
        Master_Factor__c mas          = TestDataFactory.createMasterfactor('Test Master Factor','Step rate');
        insert mas;
        
        // County
        County__c county = TestDataFactory.createCounty();
        insert county ;
        
        // Insert GEO
        Geo_Factor__c geo = TestDataFactory.createGeoFactor(mas.Id,county.Id);
        insert geo;
        
        // Create Policy
        Policy__c policy = TestDataFactory.createPolicy(acc.id,opp.id,geo.id,'Policy');
        Insert policy;
        
        // Accouunt Junction
        AccountContactJunction__c junc = TestDataFactory.createAccConJunc(policy.Account__C, con.Id);
        insert junc;
        
        
        CLE_Attendance__c attendance = new CLE_Attendance__c();
        attendance.Contact__c = junc.Contact__c;
        //attendance.CLE_Event__c  = ; Required
        //insert attendance;
        
        
        List<Policy_Lawyer__c> policyLawyerList = new List<Policy_Lawyer__c>();
        
        // Policy Lawyer
        Policy_Lawyer__c law = TestDataFactory.createPolicyLawyer(policy.Account__c,policy.Id,junc.Id);
        law.Account__c = acc.id;
        law.Is_Application_Lawyer__c = true;
        law.Deleted_Lawyer__c = false;
        policyLawyerList.add(law);
        
        // Policy Lawyer
        Policy_Lawyer__c law1 = TestDataFactory.createPolicyLawyer(policy.Account__c,policy.Id,junc.Id);
        law1.Account__c = acc.id;
        law1.Is_Application_Lawyer__c = true;
        law1.Deleted_Lawyer__c = false;
        policyLawyerList.add(law1);
        
        insert policyLawyerList;
        
    }
    
    @isTest
    static void PolicyLawyerHandler_Test(){
        
        List<Policy_Lawyer__c> policyLawyerList = [SELECT ID,Name,Policy_Effective_Date__c,Is_Application_Lawyer__c,Prior_Act_Date__c, Step__c,Overriding_Step_Value__c,Rate_At__C,Policy__c,Lawyer__c,Deleted_Lawyer__c FROM Policy_Lawyer__c];
        Map<id,Policy_Lawyer__c> policyLawyerMap = new Map<id,Policy_Lawyer__c>([SELECT ID,Name,Policy_Effective_Date__c,Is_Application_Lawyer__c,Prior_Act_Date__c, Step__c,Overriding_Step_Value__c,Rate_At__C,Policy__c,Lawyer__c,Deleted_Lawyer__c FROM Policy_Lawyer__c]);
        PolicyLawyerHandler ctrl = new PolicyLawyerHandler();
        ctrl.beforeInsert(policyLawyerList);
        ctrl.afterDelete(policyLawyerMap);
        ctrl.beforeDelete(policyLawyerMap);
    }
    
}