force-app/main/default/objects/AccountContactJunction__c/AccountContactJunction__c.object-meta.xml
<CustomObject>
    <description>Account contact junction object</description>
    <label>Lawyer</label>
    <nameField>
        <label>Lawyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContactJunction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountContactJunction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AOP_Factor__c/AOP_Factor__c.object-meta.xml
<CustomObject>
    <label>AOP Factor</label>
    <nameField>
        <label>AOP Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOP Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AOP_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>AOP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>AOP Factors</relationshipLabel>
    <relationshipName>AOP_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/Customer_Application__c.object-meta.xml
<CustomObject>
    <label>Online Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Online NBA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Online Applications</relationshipLabel>
    <relationshipName>Online_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Is_the_firm_currently_insured__c.field-meta.xml
<CustomField>
    <fullName>Is_the_firm_currently_insured__c</fullName>
    <label>Is the firm currently insured?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unsure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Application_Status__c )</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_AOP__c/Customer_Application_AOP__c.object-meta.xml
<CustomObject>
    <label>Customer Application AOP</label>
    <nameField>
        <displayFormat>CA-AOP-{000000}</displayFormat>
        <label>Customer Application AOP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Application AOP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application_AOP__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Customer Application AOP</relationshipLabel>
    <relationshipName>Customer_Application_AOP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/Customer_Application_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Customer Application Lawyer</label>
    <nameField>
        <label>Customer Application Lawyer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Application Lawyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/ARDC_Number__c.field-meta.xml
<CustomField>
    <fullName>ARDC_Number__c</fullName>
    <label>ARDC Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Customer Application Lawyers</relationshipLabel>
    <relationshipName>Customer_Application_Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deductible_Factor__c/Deductible_Factor__c.object-meta.xml
<CustomObject>
    <label>Deductible Factor</label>
    <nameField>
        <label>Deductible Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deductible Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deductible_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Deductible</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Deductible Factors</relationshipLabel>
    <relationshipName>Deductible_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/ILF_Coverage_Factor__c.object-meta.xml
<CustomObject>
    <label>ILF / Limits Factor</label>
    <nameField>
        <label>ILF / Limit Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ILF / Limits Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Is_5X5_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Is_5X5_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is 5X5 Coverage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>ILF / Limits Factors</relationshipLabel>
    <relationshipName>ILF_Coverage_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Percentage_5X5_Step_0__c.field-meta.xml
<CustomField>
    <fullName>Percentage_5X5_Step_0__c</fullName>
    <label>Percentage 5X5 Step 0</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Percentage_5X5_Step_1__c.field-meta.xml
<CustomField>
    <fullName>Percentage_5X5_Step_1__c</fullName>
    <label>Percentage 5X5 Step 1</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Percentage_5X5_Step_2__c.field-meta.xml
<CustomField>
    <fullName>Percentage_5X5_Step_2__c</fullName>
    <label>Percentage 5X5 Step 2</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Percentage_5X5_Step_3__c.field-meta.xml
<CustomField>
    <fullName>Percentage_5X5_Step_3__c</fullName>
    <label>Percentage 5X5 Step 3</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Premium_Rate_5X5__c.field-meta.xml
<CustomField>
    <fullName>Premium_Rate_5X5__c</fullName>
    <label>Premium Rate 5X5</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Base_Amount__c.field-meta.xml
<CustomField>
    <fullName>Base_Amount__c</fullName>
    <label>Base Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Deductible_ID__c.field-meta.xml
<CustomField>
    <fullName>Deductible_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deductible</label>
    <referenceTo>Deductible_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Mod__c.field-meta.xml
<CustomField>
    <fullName>Firm_Mod__c</fullName>
    <label>Firm Mod</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Limits</label>
    <referenceTo>ILF_Coverage_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Total Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Total_10x10__c.field-meta.xml
<CustomField>
    <fullName>Total_10x10__c</fullName>
    <label>Total 10x10</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Total_5x5__c.field-meta.xml
<CustomField>
    <fullName>Total_5x5__c</fullName>
    <label>Total 5x5</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Lawyer__c/Policy_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Policy Lawyer</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Lawyer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/ARDC_Number__c.field-meta.xml
<CustomField>
    <fullName>ARDC_Number__c</fullName>
    <formula>Lawyer__r.Contact__r.ARDC_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARDC Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Lawyers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Policy_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <label>App Sent</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Requested Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Quoted</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>Lost</label>
    </customValue>
    <customValue>
        <fullName>Bound</fullName>
    </customValue>
    <customValue>
        <fullName>Printed</fullName>
    </customValue>
    <customValue>
        <fullName>Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Pending</fullName>
        <isActive>false</isActive>
        <label>Quote Pending</label>
    </customValue>
    <masterLabel>Policy Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProcessRegularRenewalCmpCtrlTest.cls
@isTest
public class ProcessRegularRenewalCmpCtrlTest {
    @testSetup
    static void setupTestData() {
        
        Account acc = TestDataFactory.createAccounts(Label.Bucket_Account);
        acc.BillingState = 'Ohio';
        acc.BillingCountry = 'US';
        insert acc;
      
       
        
        
        /*Policy__c policy = new Policy__c(
            Account__c = acc.Id,
            Effective_Date__c = Date.today(),
            Customer_Application__c = objCustomerApp.Id,
            Expiration_Date__c = Date.today().addDays(90)
        );
        insert policy;*/
        Contact con                   = TestDataFactory.createContact('Test Contact',acc.id);
        con.ARDC_Number__c = '12345678';
        insert con;
        Contact con1                  = TestDataFactory.createContact('Test Contact',acc.id);
        //con.ARDC_Number__c = '12345678';
        insert con1;
         
        AccountContactJunction__c acj = TestDataFactory.createAccConJunc(acc.id, con.id);
        acj.Name                      = 'Test Name';
        
        insert acj;
         AccountContactJunction__c acj1 = TestDataFactory.createAccConJunc(acc.id, con1.id);
        acj.Name                      = 'Test Name1';
        
        insert acj1;
        
        Opportunity opp               = TestDataFactory.createOpp(acc.id);
        opp.StageName   = 'Application Sent';
        insert opp;
        Master_Factor__c masterfact =TestDataFactory.createMasterfactor('Coverage 10/1/2016 - 12/31/2016','Coverage');
        insert masterfact;
         Master_Factor__c masterfact1 = TestDataFactory.createMasterfactor('Deductible 10/1/2016 - 12/31/2016','Deductible');
        insert masterfact1;
        
         ILF_Coverage_Factor__c coverFactor = TestDataFactory.createCoveragefactor(masterfact.Id);
        coverFactor.Is_5X5_Coverage__c=true;
        coverFactor.Premium_Rate_5X5__c=1;
        coverFactor.Percentage_5X5_Step_0__c=1;
        coverFactor.Percentage_5X5_Step_1__c=1;
        coverFactor.Percentage_5X5_Step_2__c=1;
        coverFactor.Percentage_5X5_Step_3__c=1;
        insert coverFactor;
        Deductible_Factor__c deductible = TestDataFactory.createDeductiblefactor(masterfact1.Id);
        Insert deductible; 
        
        Policy__c pol = TestDataFactory.createPolicy(acc.id,opp.id,null,'Policy');
        //pol.Status__c = 'Accepted';
        pol.Account__c = acc.Id;
        pol.Limit__c = coverFactor.Id;
        pol.Deductible_ID__c = deductible.Id;
        pol.Firm_Mod__c = 1;
        pol.Base_Amount__c = 1000000;
        pol.Premium__c = 150;
        pol.Total_5x5__c=1;
        pol.Total_10x10__c=1;
        
        insert pol;
        Policy__c poll = TestDataFactory.createPolicy(acc.id,opp.id,null,'Policy');
        //pol.Status__c = 'Accepted';
        poll.Account__c = acc.Id;
        poll.Limit__c = coverFactor.Id;
        poll.Deductible_ID__c = deductible.Id;
        poll.Firm_Mod__c = 1;
        poll.Base_Amount__c = 1000000;
        poll.Premium__c = 150;
        poll.Total_5x5__c=1;
        poll.Total_10x10__c=1;
        
        insert poll;
         AccountContactJunction__c junc = TestDataFactory.createAccConJunc(pol.Account__c, con.Id);
        insert junc;
         AccountContactJunction__c junc1 = TestDataFactory.createAccConJunc(poll.Account__c, con1.Id);
        insert junc1;
        
        Customer_Application__c objCustomerApp = new Customer_Application__c();
        objCustomerApp.Is_the_firm_currently_insured__c = 'No';
        objCustomerApp.Full_Legal_Name_of_the_Firm__c = 'test';
        objCustomerApp.Address_2__c = 'test address';
        objCustomerApp.PolicyId__c = pol.Id;
        insert objCustomerApp; 
        
        Customer_Application__c objCustomerApp1 = new Customer_Application__c();
        objCustomerApp1.Is_the_firm_currently_insured__c = 'No';
        objCustomerApp1.Full_Legal_Name_of_the_Firm__c = 'test1';
        objCustomerApp1.Address_2__c = 'test address';
        objCustomerApp1.PolicyId__c = poll.Id;
        insert objCustomerApp1; 
        Customer_Application_Lawyer__c objCustomerappLay = TestDataFactory.createAppLawyer(objCustomerApp.id);
        objCustomerappLay.Last_Name__c = 'test 1';
        objCustomerappLay.ARDC_Number__c = '12345678';
        objCustomerappLay.Is_Removed__c = false;
        insert objCustomerappLay;
         Master_Factor__c objMasterFactor = TestDataFactory.createMasterfactor('Test Master Factor','AOP');
        insert objMasterFactor;
         
        AOP_Factor__c ObjAOP = TestDataFactory.createAopFactor(objMasterFactor.id);
        ObjAOP.AOP_Mod__c = 100;
        insert ObjAOP;
        Customer_Application_AOP__c aop = new Customer_Application_AOP__c(
            Customer_Application__c = objCustomerApp.Id,
            AOP_Factor__c = ObjAOP.Id,
            Percentage__c = 50
        );
        insert aop;
        test.startTest();
        Policy_Lawyer__c law = TestDataFactory.createPolicyLawyer(pol.Account__c,pol.Id,junc.Id);
        law.Active__c = true;
        law.Deleted_Lawyer__c = false;
        law.Lawyer__c = acj.id;
        insert law;
        
        Policy_Lawyer__c law1 = TestDataFactory.createPolicyLawyer(pol.Account__c,pol.Id,junc.Id);
        law.Active__c = true;
        law.Deleted_Lawyer__c = false;
        
        insert law1;
        test.stopTest();
    }
    
    @isTest
    static void testGetDetails() {
        
        Customer_Application__c testNBA = [SELECT Id FROM Customer_Application__c where Full_Legal_Name_of_the_Firm__c = 'test1' LIMIT 1];
        
        PageReference pageRef = Page.ProcessRegularRenewalPage;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('id',testNBA.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(testNBA);
        
        Test.startTest();
        ProcessRegularRenewalCmpCtrl ctrl = new ProcessRegularRenewalCmpCtrl(sc);
        
        ProcessRegularRenewalCmpCtrl.Wrapper result = ProcessRegularRenewalCmpCtrl.getDetails(testNBA.Id);
        Test.stopTest();
        
        
        
    }
    @isTest
    static void testGetDetails1() {
        
        Customer_Application__c testNBA = [SELECT Id FROM Customer_Application__c LIMIT 1];
        
        Test.startTest();
        ProcessRegularRenewalCmpCtrl.Wrapper result = ProcessRegularRenewalCmpCtrl.getDetails(testNBA.Id);
        Test.stopTest();
        
        
        
    }
}