force-app/main/default/objects/AccountContactJunction__c/AccountContactJunction__c.object-meta.xml
<CustomObject>
    <description>Account contact junction object</description>
    <label>Lawyer</label>
    <nameField>
        <label>Lawyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContactJunction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountContactJunction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AOP_Factor__c/AOP_Factor__c.object-meta.xml
<CustomObject>
    <label>AOP Factor</label>
    <nameField>
        <label>AOP Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOP Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AOP_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>AOP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>AOP Factors</relationshipLabel>
    <relationshipName>AOP_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Base_Factor__c/Base_Factor__c.object-meta.xml
<CustomObject>
    <label>Base Factor</label>
    <nameField>
        <label>Base Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Base Value</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Base Factors</relationshipLabel>
    <relationshipName>Base_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deductible_Factor__c/Deductible_Factor__c.object-meta.xml
<CustomObject>
    <label>Deductible Factor</label>
    <nameField>
        <label>Deductible Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deductible Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deductible_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Deductible</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Deductible Factors</relationshipLabel>
    <relationshipName>Deductible_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GEO_Factor__c/GEO_Factor__c.object-meta.xml
<CustomObject>
    <label>GEO Factor</label>
    <nameField>
        <label>GEO Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEO Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GEO_Factor__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>GEO Factors</relationshipLabel>
    <relationshipName>GEO_Factors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GEO_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>GEO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>GEO Factors</relationshipLabel>
    <relationshipName>GEO_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/ILF_Coverage_Factor__c.object-meta.xml
<CustomObject>
    <label>ILF / Limits Factor</label>
    <nameField>
        <label>ILF / Limit Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ILF / Limits Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>ILF / Limits Factors</relationshipLabel>
    <relationshipName>ILF_Coverage_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>County</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>GEO_Factor__c.Master_Factor__r.Default__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>GEO_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Limits</label>
    <referenceTo>ILF_Coverage_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_AOP__c/Policy_AOP__c.object-meta.xml
<CustomObject>
    <label>Area of Practice</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Area of Practice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Area of Practice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_AOP__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Area of Practice</relationshipLabel>
    <relationshipName>Policy_AOPs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to filter the related lawyers on the basis of related account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/recordTypes/General.recordType-meta.xml
<RecordType>
    <fullName>General</fullName>
    <active>true</active>
    <label>General</label>
</RecordType>

force-app/main/default/objects/Policy_Lawyer__c/Policy_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Policy Lawyer</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Lawyer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Lawyers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Step_Rate_Factor__c/Step_Rate_Factor__c.object-meta.xml
<CustomObject>
    <label>Step Rate Factor</label>
    <nameField>
        <label>Step Rate Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Step Rate Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Step_Rate_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Step Rate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Step Rate Factors</relationshipLabel>
    <relationshipName>Step_Rate_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PolicyLawyersController_Test.cls
@isTest
private class PolicyLawyersController_Test {
    
    @testSetup static void setup() {
        
        Account acc                   = TestDataFactory.createAccounts(Label.Bucket_Account);
        acc.AccountNumber             = '123456';
        acc.Vendor_Account__c         = true;
        insert acc;
        
        Contact con                   = TestDataFactory.createContact('Test Contact',acc.id);
        insert con;
        
        AccountContactJunction__c acj = TestDataFactory.createAccConJunc(acc.id, con.id);
        acj.Name                      = 'Test Name';
        insert acj;
        
        List<AcctSeed__GL_Account__c> glAccounts = TestDataFactory.createGLAccounts();        
        insert glAccounts;
        
        List<AcctSeed__Billing_Format__c> billingFormats = TestDataFactory.createBillingFormats();        
        insert billingFormats ;
        
        List<AcctSeed__Ledger__c> ledgers = TestDataFactory.createLedgers(glAccounts[0].id,billingFormats[0].id,billingFormats[1].id,billingFormats[2].id,billingFormats[3].id,billingFormats[4].id);
        insert ledgers;
        
        AcctSeed__Accounting_Settings__c settings = TestDataFactory.createAccountsetting(ledgers[0].id,glAccounts[0].Id,glAccounts[1].Id,glAccounts[2].Id,glAccounts[3].Id,glAccounts[4].Id,glAccounts[5].Id,glAccounts[6].Id,billingFormats[0].Id);
        insert settings;
        
        Opportunity opp               = TestDataFactory.createOpp(acc.id);
        insert opp;
        
        Master_Factor__c mas          = TestDataFactory.createMasterfactor('Test Master Factor','Step rate');
        insert mas;
        
        County__c county = TestDataFactory.createCounty();
        insert county ;
        
        Geo_Factor__c geo = TestDataFactory.createGeoFactor(mas.Id,county.Id);
        insert geo;
        
        Master_Factor__c masterFactor = TestDataFactory.createMasterfactor('Test Master Factor','Step rate');
        insert masterFactor;
        
        Step_Rate_Factor__c stepRateFactor = TestDataFactory.createStepFactor(masterFactor.Id);
        insert stepRateFactor;
        test.startTest();
        Master_Factor__c masterFactor1 = TestDataFactory.createMasterfactor('Test Master Factor1','Base Value');
        insert masterFactor1;
        
        Base_Factor__c baseFactor = TestDataFactory.createBaseFactor(masterFactor1.Id);
        insert baseFactor;
        
        Map<String,String> mapRecordTypes = new Map<String,String>();
        
        for (RecordType rt : [SELECT DeveloperName,Id FROM RecordType WHERE SobjectType = 'Master_Factor__c']) {
            mapRecordTypes.put(rt.DeveloperName,rt.Id);
        }
        
        Master_Factor__c MasterFactorCoverage = TestDataFactory.createMasterfactor('Coverage','Coverage');
        MasterFactorCoverage.RecordTypeId = mapRecordTypes.get('Limit_Coverage');
        insert MasterFactorCoverage;
        
        ILF_Coverage_Factor__c FactorCoverage = TestDataFactory.createCoveragefactor(MasterFactorCoverage.Id);
        insert FactorCoverage;
        
        Master_Factor__c mas12       = TestDataFactory.createMasterfactor('Test Master Factor1','Deductible');
        insert mas12;
        
        Deductible_Factor__c DedFac = TestDataFactory.createDeductiblefactor(mas12.Id);
        Insert DedFac; 
        
        Master_Factor__c masterFactorNew = TestDataFactory.createMasterfactor('Test Master Factor4','AOP');
        insert masterFactorNew;
        
        ILF_Coverage_Factor__c coverageFactorObj = TestDataFactory.createCoveragefactor(masterFactorNew.Id);
        insert coverageFactorObj;
        
        Deductible_Factor__c dedFactorObj = TestDataFactory.createDeductiblefactor(masterFactorNew.Id);
        insert dedFactorObj;
        
        Policy__c acctivePolicy = TestDataFactory.createActivePolicy(acc.id,opp.id,geo.id,'Policy');
        acctivePolicy.Limit__c = coverageFactorObj.Id;
        acctivePolicy.Deductible_ID__c = dedFactorObj.Id;
        insert acctivePolicy;
        
        Id devRecordTypeId = Schema.SObjectType.Policy_Endorsement__c.getRecordTypeInfosByName().get('General').getRecordTypeId();
        
        Endorsement__c endorse = TestDataFactory.createEndorsement('IL 153','Functional','General');
        insert endorse;
        
        Endorsement_Version__c endorseVersion = TestDataFactory.createEndorsementVersion(endorse.Id);
        insert endorseVersion;
        
        Policy_Endorsement__c poicyEndorse = TestDataFactory.createPolicyEndorsement(acc.id,acctivePolicy.id,'General');
        //insert poicyEndorse;
        
        AOP_Factor__c aopFactor = TestDataFactory.createAopFactor(masterFactorNew.Id);
        insert aopFactor;
        
        Policy_AOP__c aop = TestDataFactory.createPolicyAop(aopFactor.Id,acctivePolicy.id);
        insert aop;
        test.stopTest();
        
    }
    /*
    @isTest static void testMethod1() {
        
        List<Policy__c> policies = [SELECT Id,Account__c FROM Policy__c];
        List<Account> ListAcc=[select id from Account];
        
        Account acc = ListAcc[0];              
        
        Contact con1                   = TestDataFactory.createContact('Test Contact',acc.id);
        insert con1;
        
        Policy__c  policy = policies[0];
        List<AccountContactRelation> lstAccCon = [Select id from AccountContactRelation];
        
        AccountContactJunction__c junc = new AccountContactJunction__c();
        junc.Account__c = policies[0].Account__c;
        junc.Contact__c = con1.Id;
        insert junc;
        
        Policy_Lawyer__c lawyerobj = TestDataFactory.createPolicyLawyer(acc.Id,policies[0].Id,junc.Id);
        lawyerobj.Prior_Act_Date__c =date.today();
        lawyerobj.Rate_At__c =123;
        insert lawyerobj;
        
        PageReference pageRef = Page.PolicyLawyers;
        pageRef.getParameters().put('Id', policy.Id);
        system.Test.setCurrentPage(pageRef);
        
        PolicyLawyersController Ctrl = new PolicyLawyersController();
       
        for(PolicyLawyersController.WrapperClass wrap : Ctrl.modalList){
            wrap.isStatus = true;
            wrap.policyLawyerObj = lawyerobj;
        }
        Ctrl.firstName = 'test12';
        Ctrl.lastName = 'test2';
        Ctrl.AddLawyer();
        Ctrl.insertContact();
      //  Ctrl.contactRec.LastName = 'Test';
        Ctrl.saveContact();
        Ctrl.contactRec.FirstName = 'Test';
        Ctrl.contactRec.LastName = 'Test2';
        Ctrl.selectedContacts = con1.id;
        Ctrl.associateContacts();
        Ctrl.searchContact(); 
        Ctrl.redirectToFirstPage();
        Ctrl.savePolicyLawyer();
        Ctrl.cancelMethod();
        
        Test.startTest();
        
        List<Policy_Lawyer__c> lawList = [SELECT Id FROM Policy_Lawyer__c ];
        
        Ctrl.policyLawyerId = String.valueof(lawList[0].id);
        // Ctrl.removePolicyLawyer();
        Test.stopTest();
        
    }

    */
    
    
    
    
    @isTest static void searchContact_Test() {
             
        Test.startTest();
        List<Policy__c> policies = [SELECT Id,Account__c FROM Policy__c];
        
        List<Account> ListAcc=[select id from Account];
        
        Account acc = ListAcc[0];    
        
        Contact con1                   = TestDataFactory.createContact('Test Contact',acc.id);
        insert con1;
        
        Policy__c  policy = policies[0];
        List<AccountContactRelation> lstAccCon = [Select id from AccountContactRelation];
        
        AccountContactJunction__c junc = new AccountContactJunction__c();
        junc.Account__c = policies[0].Account__c;
        junc.Contact__c = con1.Id;
        insert junc;
        
        Policy_Lawyer__c lawyerobj = TestDataFactory.createPolicyLawyer(acc.Id,policies[0].Id,junc.Id);
        insert lawyerobj;
        
        PageReference pageRef = Page.PolicyLawyers;
        pageRef.getParameters().put('Id', policy.Id);
        system.Test.setCurrentPage(pageRef);
        
        
        PolicyLawyersController Ctrl = new PolicyLawyersController();
        Ctrl.firstName = null;
        Ctrl.lastName = 'Test';
        Ctrl.searchContact();
        Test.stopTest();
        
    }
    
     @isTest static void searchContact_Test_P() {
             
        Test.startTest();
        List<Policy__c> policies = [SELECT Id,Account__c FROM Policy__c];
        
        List<Account> ListAcc=[select id from Account];
        
        Account acc = ListAcc[0];    
        
        Contact con1  = TestDataFactory.createContact('Test Contact2',acc.id);
         con1.Email='test@gmail.com';
        insert con1;
        
        Policy__c  policy = policies[0];
        List<AccountContactRelation> lstAccCon = [Select id from AccountContactRelation];
        
        AccountContactJunction__c junc = new AccountContactJunction__c();
        junc.Account__c = policies[0].Account__c;
        junc.Contact__c = con1.Id;
        insert junc;
        
        Policy_Lawyer__c lawyerobj = TestDataFactory.createPolicyLawyer(acc.Id,policies[0].Id,junc.Id);
        lawyerobj.Prior_Act_Date__c=date.today();
        lawyerobj.Rate_At__c=2;
        insert lawyerobj;
        
        PageReference pageRef = Page.PolicyLawyers;
        pageRef.getParameters().put('Id', policy.Id);
        system.Test.setCurrentPage(pageRef);
         
         
        PolicyLawyersController.WrapperClass MyWrapper = new PolicyLawyersController.WrapperClass(true,junc,junc.Id);
        MyWrapper.policyLawyerObj=lawyerobj;
         
        List< PolicyLawyersController.WrapperClass> WrapList = new  List< PolicyLawyersController.WrapperClass>();
        WrapList.add(MyWrapper);
         
        List<Policy_Lawyer__c> LawList = new List<Policy_Lawyer__c>();
        LawList.add(lawyerobj);
        
        
        PolicyLawyersController Ctrl = new PolicyLawyersController();
        Ctrl.modalList=WrapList;
        Ctrl.firstName = 'test';
        Ctrl.lastName = 'Test';
        Ctrl.status=true;
        Ctrl.indexPolicyLawyer=0;
        Ctrl.policyLawyerList =LawList;
        Ctrl.searchContact();
        Ctrl.AddLawyer();
        Ctrl.insertContact();
        Ctrl.selectedContacts = con1.id;
        Ctrl.saveContact();
        Ctrl.savePolicyLawyer();
        Ctrl.redirectToFirstPage();
        //Ctrl.removePolicyLawyer();
        Ctrl.cancelMethod();
        Test.stopTest();
        
    }
    
     @isTest static void searchContact_Test_1() {
             
        Test.startTest();
        List<Policy__c> policies = [SELECT Id,Account__c FROM Policy__c];
        List<Account> ListAcc=[select id from Account];
        
        Account acc = ListAcc[0];    
        
        Contact con1                   = TestDataFactory.createContact('Test Contact',acc.id);
        insert con1;
        
        Policy__c  policy = policies[0];
        List<AccountContactRelation> lstAccCon = [Select id from AccountContactRelation];
        
        AccountContactJunction__c junc = new AccountContactJunction__c();
        junc.Account__c = policies[0].Account__c;
        junc.Contact__c = con1.Id;
        insert junc;
        
        Policy_Lawyer__c lawyerobj = TestDataFactory.createPolicyLawyer(acc.Id,policies[0].Id,junc.Id);
        insert lawyerobj;
        
        PageReference pageRef = Page.PolicyLawyers;
        pageRef.getParameters().put('Id', policy.Id);
        system.Test.setCurrentPage(pageRef);
        
        
        PolicyLawyersController Ctrl = new PolicyLawyersController();
        Ctrl.firstName = null;
        Ctrl.lastName = 'Test';
        Ctrl.ardcNumber = '123456789';
        Ctrl.searchContact();
        Test.stopTest();
        
    }

    
     @isTest static void searchContact_Test_2() {
             
        Test.startTest();
        List<Policy__c> policies = [SELECT Id,Account__c FROM Policy__c];
        List<Account> ListAcc=[select id from Account];
        
        Account acc = ListAcc[0];    
        
        Contact con1                   = TestDataFactory.createContact('Test Contact',acc.id);
        insert con1;
        
        Policy__c  policy = policies[0];
        List<AccountContactRelation> lstAccCon = [Select id from AccountContactRelation];
        
        AccountContactJunction__c junc = new AccountContactJunction__c();
        junc.Account__c = policies[0].Account__c;
        junc.Contact__c = con1.Id;
        insert junc;
        
        Policy_Lawyer__c lawyerobj = TestDataFactory.createPolicyLawyer(acc.Id,policies[0].Id,junc.Id);
        insert lawyerobj;
        
        PageReference pageRef = Page.PolicyLawyers;
        pageRef.getParameters().put('Id', policy.Id);
        system.Test.setCurrentPage(pageRef);
        
        
        PolicyLawyersController Ctrl = new PolicyLawyersController();
        Ctrl.indexPolicyLawyer = 1;
        Ctrl.firstName = null;
        Ctrl.lastName = null;
        Ctrl.ardcNumber = '123456789';
        Ctrl.searchContact();
        Ctrl.removePolicyLawyer();
        Test.stopTest();
        
    }


}