force-app/main/default/objects/AccountContactJunction__c/AccountContactJunction__c.object-meta.xml
<CustomObject>
    <description>Account contact junction object</description>
    <label>Lawyer</label>
    <nameField>
        <label>Lawyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContactJunction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountContactJunction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountContactJunction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>AccountContactJunction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPolicyJunction__c/ContactPolicyJunction__c.object-meta.xml
<CustomObject>
    <label>Record</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>ContactPolicyJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ContactPolicyJunction</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactPolicyJunction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policy</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPolicyJunction__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/Customer_Application__c.object-meta.xml
<CustomObject>
    <label>Online Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Online NBA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Online Applications</relationshipLabel>
    <relationshipName>Online_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Online_NBA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipName>Customer_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Effective_Date_Requested__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date_Requested__c</fullName>
    <label>Effective Date Requested</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Full_Legal_Name_of_the_Firm__c.field-meta.xml
<CustomField>
    <fullName>Full_Legal_Name_of_the_Firm__c</fullName>
    <label>Full Legal Name of the Firm</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Trade_Name_or_D_B_A__c.field-meta.xml
<CustomField>
    <fullName>Trade_Name_or_D_B_A__c</fullName>
    <label>Trade Name or D/B/A</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/Customer_Application_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Customer Application Lawyer</label>
    <nameField>
        <label>Customer Application Lawyer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Application Lawyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/ARDC_Number__c.field-meta.xml
<CustomField>
    <fullName>ARDC_Number__c</fullName>
    <label>ARDC Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Application Lawyers</relationshipLabel>
    <relationshipName>Customer_Application_Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Customer Application Lawyers</relationshipLabel>
    <relationshipName>Customer_Application_Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/ISBA_Number__c.field-meta.xml
<CustomField>
    <fullName>ISBA_Number__c</fullName>
    <label>ISBA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>County</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>GEO_Factor__c.Master_Factor__r.Default__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>GEO_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Establish_Date__c.field-meta.xml
<CustomField>
    <fullName>Establish_Date__c</fullName>
    <label>xxx-Establish Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Contact__c.field-meta.xml
<CustomField>
    <fullName>Firm_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Firm Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/Policy_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Policy Lawyer</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Lawyer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/ARDC_Number__c.field-meta.xml
<CustomField>
    <fullName>ARDC_Number__c</fullName>
    <formula>Lawyer__r.Contact__r.ARDC_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARDC Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <description>Email from Contact Lookup</description>
    <formula>Lawyer__r.Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/First_Name_Contact__c.field-meta.xml
<CustomField>
    <fullName>First_Name_Contact__c</fullName>
    <description>First Name from Contact Record</description>
    <formula>Lawyer__r.Contact__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Name (Contact)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/ISBA_Number__c.field-meta.xml
<CustomField>
    <fullName>ISBA_Number__c</fullName>
    <formula>Lawyer__r.Contact__r.ISBA__c</formula>
    <label>ISBA Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Last_Name_Contact__c.field-meta.xml
<CustomField>
    <fullName>Last_Name_Contact__c</fullName>
    <description>Last Name from Contact Record</description>
    <formula>Lawyer__r.Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name (Contact)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lawyer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AccountContactJunction__c.Contact__r.Type__c</field>
            <operation>equals</operation>
            <value>Lawyer</value>
        </filterItems>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>AccountContactJunction__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountContactJunction__c</referenceTo>
    <relationshipLabel>Policy Lawyers</relationshipLabel>
    <relationshipName>Policy_Lawyers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Middle_Name_Contact__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name_Contact__c</fullName>
    <description>Middle Name from Contact Record</description>
    <formula>Lawyer__r.Contact__r.Middle_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Middle Name (Contact)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Lawyers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/Policy_Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Quote-{000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Quote__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Policy_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RegenerateCustomerApplicationCtrl.cls
public with sharing class RegenerateCustomerApplicationCtrl {
    
    public class RegenerateCustomerApplicationCtrlException extends Exception{}
    
    @auraEnabled
    public Static boolean updateDetails(String recId){
        try{
            if(String.isNotBlank(recId)){
                PolicyTriggerHandler.changeToRegularRenewal(new Set<String>{recId});//updated on Jan 8 2026
            }
            else{
                throw new RegenerateCustomerApplicationCtrlException('Record Not Found.');
            }
            /**Policy__c pol = [SELECT Id, Customer_Application__c, Effective_Date__c, Account__r.Name, Account__r.Trade_Name_or_D_B_A__c, Account__r.BillingStreet, Account__r.BillingCity, Account__r.BillingState, Account__r.BillingPostalCode, Account__r.Billing_Address_County__c, Account__r.Phone, Account__r.Website__c, Account__r.Establish_Date__c, Firm_Contact__r.FirstName, Firm_Contact__r.LastName, Firm_Contact__r.Phone, Firm_Contact__r.Email,
                             (SELECT First_Name_Contact__c, Middle_Name_Contact__c, Last_Name_Contact__c, ISBA_Number__c , ARDC_Number__c, Lawyer__r.Contact__r.Cell_Phone__c, Lawyer__r.Contact__r.Birthdate, Contact_Email__c, Lawyer__r.Contact__r.Personal_Email__c FROM Policy_Lawyers__r),//lawyer
                             (SELECT Id FROM Policy_Quotes__r WHERE Customer_Application__c = null)//quotes
                             FROM Policy__c WHERE Id=:recId LIMIT 1];
            
            
            Customer_Application__c  capp = new Customer_Application__c();
            
            List<Customer_Application__c> cappList = new List<Customer_Application__c>();
            
            
            if(String.isNotBlank(pol.Customer_Application__c)){
                cappList = [SELECT Id, 
                            (SELECT Id FROM Customer_Application_Lawyers__r), 
                            (SELECT Id FROM Quotes__r WHERE Policy__c !=: recId) 
                            FROM Customer_Application__c WHERE Id=: pol.Customer_Application__c LIMIT 1];
            }
            
            
            if(!cappList.isEmpty()){
               capp.Id = cappList[0].Id;
            }
            else{
                String customerAppRecordTypeId = [SELECT Id,Name,SObjectType FROM RecordType where SObjectType='Customer_Application__c' AND Name = 'Regular Renewal' Limit 1].Id;
                capp.RecordTypeId = customerAppRecordTypeId;
            }
            List<Customer_Application_Lawyer__c> lawyersToDelete = new List<Customer_Application_Lawyer__c>();
            List<Customer_Application_Lawyer__c> lawyersToInsert = new List<Customer_Application_Lawyer__c>();
            
            List<Policy_Quote__c> quotesToDelete = new List<Policy_Quote__c>();
            List<Policy_Quote__c> quotesToUpdate = new List<Policy_Quote__c>();
            
            capp.Effective_Date_Requested__c  = pol.Effective_Date__c;
            capp.Full_Legal_Name_of_the_Firm__c = pol.Account__r.Name;
            capp.Trade_Name_or_D_B_A__c = pol.Account__r.Trade_Name_or_D_B_A__c;
            capp.Street__c = pol.Account__r.BillingStreet;
            capp.City__c = pol.Account__r.BillingCity;
            capp.State__c = pol.Account__r.BillingState;
            capp.Zip_Code__c = pol.Account__r.BillingPostalCode;
            capp.County__c = pol.Account__r.Billing_Address_County__c;
            capp.Firm_Phone_Number__c = pol.Account__r.Phone;
            capp.Website__c = pol.Account__r.Website__c;
            capp.Date_Firm_Established__c = pol.Account__r.Establish_Date__c;
            capp.Contact_Name__c = pol.Firm_Contact__r.FirstName;
            capp.Contact_Last_Name__c = pol.Firm_Contact__r.LastName;
            capp.Contact_Phone_Number__c = pol.Firm_Contact__r.Phone;
            capp.Contact_E_mail_Address__c = pol.Firm_Contact__r.Email;
            capp.PolicyId__c = pol.Id;
            upsert capp;
            
            
            if(cappList.isEmpty()){
                Site mySite = [select Id from Site where Name = 'Customer_Application'];
                SiteDetail mySiteDetail = [select SecureURL from SiteDetail where DurableId = :mySite.Id];
                pol.Customer_Application__c = capp.Id;
                capp.Form_Link__c = mySiteDetail.SecureURL + '?id=' + EncodingUtil.urlEncode(PaymentGateway_Ctrl.processEncryption(capp.Id,Label.Encryption_Key_Payment_Id),'UTF-8'); 
                Update pol;
                Update capp;
            }
            
            for(Policy_Lawyer__c law : pol.Policy_Lawyers__r){
                Customer_Application_Lawyer__c applicationLawyer = new Customer_Application_Lawyer__c();
                applicationLawyer.Name = law.First_Name_Contact__c;
                applicationLawyer.Middle_Initial__c  = law.Middle_Name_Contact__c ;
                applicationLawyer.Last_Name__c  = law.Last_Name_Contact__c;
                applicationLawyer.ISBA_Number__c = law.ISBA_Number__c; 
                applicationLawyer.ARDC_Number__c = law.ARDC_Number__c;
                applicationLawyer.Cell_Phone__c = law.Lawyer__r.Contact__r.Cell_Phone__c;
                applicationLawyer.Birthday__c = law.Lawyer__r.Contact__r.Birthdate;
                applicationLawyer.Firm_Email_Address__c = law.Contact_Email__c;
                applicationLawyer.Personal_Email_Address__c = law.Lawyer__r.Contact__r.Personal_Email__c;
                applicationLawyer.Customer_Application__c = pol.Customer_Application__c;
                lawyersToInsert.add(applicationLawyer);
            }
            
            if(!lawyersToInsert.isEmpty()){
                Insert lawyersToInsert;
            }
            
            if(!cappList.isEmpty()){
				system.debug('deleting lawyer and qoutes');
                system.debug('Lawyers =>'+ cappList[0].Customer_Application_Lawyers__r);
                
                if(!cappList[0].Customer_Application_Lawyers__r.isEmpty()){                    
                    lawyersToDelete.addAll(cappList[0].Customer_Application_Lawyers__r);
                    system.debug('deleting lawyers =>'+lawyersToDelete);
                    Delete lawyersToDelete;
                }
                system.debug('Quotes => '+cappList[0].Quotes__r);
                if(!cappList[0].Quotes__r.isEmpty()){
                    quotesToDelete.addAll(cappList[0].Quotes__r);
                    system.debug('deleting Quotes => '+quotesToDelete);
                    Delete quotesToDelete;
                }
            }
            if(!pol.Policy_Quotes__r.isEmpty()){
                List<Policy__c> bucketAccountPolicies = new List<Policy__c>([select id from Policy__c where Account__r.Name=: Label.Online_NBA_Account ]);
                List<String> fieldNames = new List<String>( Schema.getGlobalDescribe().get('Policy_Quote__c').getDescribe().fields.getMap().keySet() );
                String query =' SELECT ' +String.join( fieldNames, ',' ) +' FROM Policy_Quote__c'  +' WHERE ' +' Policy__c =: recId ';
                for (Policy_Quote__c quo : Database.query(query)) {
                    Policy_Quote__c newQuote = new Policy_Quote__c();
                    newQuote = quo.Clone(false, true);
                    newQuote.Policy__c = bucketAccountPolicies[0].Id;
                    newQuote.Customer_Application__c = pol.Customer_Application__c;
                    quotesToUpdate.add(newQuote);
                }
                Insert quotesToUpdate;
            }/**/
            return true;
        } 
        catch(exception e){
            system.debug('Error => '+e.getMessage()+' => '+ e.getLineNumber());
            throw new RegenerateCustomerApplicationCtrlException(e.getMessage());
        }
    }
    
}