force-app/main/default/objects/AccountContactJunction__c/AccountContactJunction__c.object-meta.xml
<CustomObject>
    <description>Account contact junction object</description>
    <label>Lawyer</label>
    <nameField>
        <label>Lawyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContactJunction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountContactJunction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountContactJunction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>AccountContactJunction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/Customer_Application__c.object-meta.xml
<CustomObject>
    <label>Online Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Online NBA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Online Applications</relationshipLabel>
    <relationshipName>Online_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Online_NBA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipName>Customer_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Effective_Date_Requested__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date_Requested__c</fullName>
    <label>Effective Date Requested</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Full_Legal_Name_of_the_Firm__c.field-meta.xml
<CustomField>
    <fullName>Full_Legal_Name_of_the_Firm__c</fullName>
    <label>Full Legal Name of the Firm</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/PolicyId__c.field-meta.xml
<CustomField>
    <fullName>PolicyId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Online_NBA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
                <default>true</default>
                <label>IL</label>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Application_Status__c )</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Trade_Name_or_D_B_A__c.field-meta.xml
<CustomField>
    <fullName>Trade_Name_or_D_B_A__c</fullName>
    <label>Trade Name or D/B/A</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/Customer_Application_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Customer Application Lawyer</label>
    <nameField>
        <label>Customer Application Lawyer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Application Lawyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Average_Number_of_Hours_Worked__c.field-meta.xml
<CustomField>
    <fullName>Average_Number_of_Hours_Worked__c</fullName>
    <label>Average Number of Hours Worked</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Application Lawyers</relationshipLabel>
    <relationshipName>Customer_Application_Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Customer Application Lawyers</relationshipLabel>
    <relationshipName>Customer_Application_Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>County</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>GEO_Factor__c.Master_Factor__r.Default__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>GEO_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/Policy_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Policy Lawyer</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Lawyer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Lawyers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Policy_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <label>App Sent</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Requested Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Quoted</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>Lost</label>
    </customValue>
    <customValue>
        <fullName>Bound</fullName>
    </customValue>
    <customValue>
        <fullName>Printed</fullName>
    </customValue>
    <customValue>
        <fullName>Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Pending</fullName>
        <isActive>false</isActive>
        <label>Quote Pending</label>
    </customValue>
    <masterLabel>Policy Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NBAConversionControllerTest.cls
@IsTest
public class NBAConversionControllerTest {
    
    @TestSetup
    static void setupData() {
        
        County__c county = new County__c(Name = 'Cook');
        insert county;
        Account bucketAcc = new Account(Name = Label.Bucket_Account);
        insert bucketAcc;
        
        Account acc = new Account(
            Name = 'Test Account',
            BillingStreet = '123 Main St',
            BillingCity = 'Chicago',
            BillingState = 'IL',
            BillingPostalCode = '60601',
            Billing_Address_County__c = county.Id
        );
        insert acc;
        Contact con = new Contact(
            FirstName = 'John',
            LastName = 'Doe',
            AccountId = acc.Id
        );
        insert con;
        
        Customer_Application__c app = new Customer_Application__c(
            Full_Legal_Name_of_the_Firm__c = 'Test Firm',
            Trade_Name_or_D_B_A__c = 'Test DBA',
            Street__c = '123 Main St',
            City__c = 'Chicago',
            State__c = 'IL',
            Zip_Code__c = '60601',
            County__c = county.Id,
            Application_Status__c = 'New',
            Signed_Date__c = Date.today(),
            Effective_Date_Requested__c = Date.today().addDays(10)
        );
        insert app;
        
        Customer_Application_Lawyer__c lawyer = new Customer_Application_Lawyer__c(
            Customer_Application__c = app.Id,
            Name = 'John',
            Last_Name__c = 'Doe',
            Average_Number_of_Hours_Worked__c = 40,
            Date_of_Hire__c = Date.today().addYears(-5),
            Contact__c = con.Id
        );
        insert lawyer;
    }
    
    
    @IsTest
    static void testGetMethods() {
        
        Customer_Application__c app =[SELECT Id FROM Customer_Application__c LIMIT 1];
        
        Test.startTest();
        NBAConversionController.getAccount();
        NBAConversionController.getContact();
        NBAConversionController.getcurentNBA(app.Id);
        NBAConversionController.getCustomerApplication(app.Id);
        Test.stopTest();
        System.assert(true);
    }
    
    @IsTest
    static void testCreateObject_WithExistingContact() {
        
        Customer_Application__c app =[SELECT Id FROM Customer_Application__c LIMIT 1];
        
        Account acc =[SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        
        List<Customer_Application_Lawyer__c> lawyers =[SELECT Id, Contact__c FROM Customer_Application_Lawyer__c];
        
        List<String> oldContacts = new List<String>();
        for (Customer_Application_Lawyer__c l : lawyers) {
            oldContacts.add(l.Contact__c);
        }
        
        Map<String, String> lawyerContactMap = new Map<String, String>();
        lawyerContactMap.put(lawyers[0].Id, lawyers[0].Contact__c);
        
        Test.startTest();
        Id policyId = NBAConversionController.createObject(app.Id,new List<String>(),acc.Id,oldContacts,lawyerContactMap);
        Test.stopTest();
        
        System.assertNotEquals(null, policyId);
        
        Customer_Application__c updatedApp =[SELECT Application_Status__c, PolicyId__c FROM Customer_Application__c WHERE Id = :app.Id];
        System.assertEquals('Converted', updatedApp.Application_Status__c);
        System.assertEquals(policyId, updatedApp.PolicyId__c);
        
        List<Policy_Lawyer__c> polLawyers =[SELECT Id FROM Policy_Lawyer__c WHERE Policy__c = :policyId];
        System.assertEquals(1, polLawyers.size());
    }
    
    @IsTest
    static void testCheckRecord_NoPolicy() {
        
        Customer_Application__c app =[SELECT Id FROM Customer_Application__c LIMIT 1];
        
        Test.startTest();
        Boolean result = NBAConversionController.checkRecord(app.Id);
        Test.stopTest();
        
        System.assertEquals(true, result);
    }
    
    @IsTest
    static void testCheckRecord_WithPolicy() {
        
        Customer_Application__c app =[SELECT Id FROM Customer_Application__c LIMIT 1];
        
        Policy__c pol = new Policy__c(
            Account__c = [SELECT Id FROM Account LIMIT 1].Id,
            Effective_Date__c = Date.today(),
            Status__c = 'Inquiry'
        );
        insert pol;
        
        app.PolicyId__c = pol.Id;
        update app;
        
        Test.startTest();
        Boolean result = NBAConversionController.checkRecord(app.Id);
        Test.stopTest();
        
        System.assertEquals(false, result);
        
        Customer_Application__c refreshed =[SELECT Application_Status__c FROM Customer_Application__c WHERE Id = :app.Id];
        System.assertEquals('Converted', refreshed.Application_Status__c);
    }
    @IsTest
    static void testCreateObject_WithNewContact() {
        
        Customer_Application__c app = [SELECT Id FROM Customer_Application__c LIMIT 1];
        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Customer_Application_Lawyer__c lawyer = [SELECT Id, Contact__c FROM Customer_Application_Lawyer__c LIMIT 1];
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        lawyer.Contact__c = con.Id;
        update lawyer;
        AccountContactJunction__c acj = new AccountContactJunction__c(
            Account__c = acc.Id,
            Contact__c = con.Id
        );
        insert acj;
        List<String> newContacts = new List<String>{ lawyer.Id };
            List<String> oldContacts = new List<String>{ con.Id };                
                Test.startTest();
        Id policyId = NBAConversionController.createObject(
            app.Id,
            newContacts,
            acc.Id,
            oldContacts,               
            new Map<String, String>()  
        );
        
        Test.stopTest();
        
        System.assertNotEquals(null, policyId);
        List<Policy_Lawyer__c> polLawyers = [SELECT Id FROM Policy_Lawyer__c WHERE Policy__c = :policyId];
        System.assertEquals(1, polLawyers.size());
    }
    
}