force-app/main/default/objects/AccountContactJunction__c/AccountContactJunction__c.object-meta.xml
<CustomObject>
    <description>Account contact junction object</description>
    <label>Lawyer</label>
    <nameField>
        <label>Lawyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContactJunction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountContactJunction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPolicyJunction__c/ContactPolicyJunction__c.object-meta.xml
<CustomObject>
    <label>Record</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>ContactPolicyJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ContactPolicyJunction</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactPolicyJunction__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deductible_Factor__c/Deductible_Factor__c.object-meta.xml
<CustomObject>
    <label>Deductible Factor</label>
    <nameField>
        <label>Deductible Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deductible Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deductible_Factor__c/fields/Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount__c</fullName>
    <label>Deductible Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GEO_Factor__c/GEO_Factor__c.object-meta.xml
<CustomObject>
    <label>GEO Factor</label>
    <nameField>
        <label>GEO Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEO Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GEO_Factor__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>GEO Factors</relationshipLabel>
    <relationshipName>GEO_Factors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/ILF_Coverage_Factor__c.object-meta.xml
<CustomObject>
    <label>ILF / Limits Factor</label>
    <nameField>
        <label>ILF / Limit Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ILF / Limits Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Coverage_Max_Per_Claim__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Max_Per_Claim__c</fullName>
    <label>Coverage Max Per Claim</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Full_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Full_Coverage__c</fullName>
    <label>Aggregate Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>County</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>GEO_Factor__c.Master_Factor__r.Default__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>GEO_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount__c</fullName>
    <label>Deductible Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Deductible_ID__c.field-meta.xml
<CustomField>
    <fullName>Deductible_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deductible</label>
    <referenceTo>Deductible_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Per_Claim_Limit__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Limit__c</fullName>
    <label>Per Claim Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Total Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Lawyer__c/Policy_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Policy Lawyer</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Lawyer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lawyer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AccountContactJunction__c.Contact__r.Type__c</field>
            <operation>equals</operation>
            <value>Lawyer</value>
        </filterItems>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>AccountContactJunction__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountContactJunction__c</referenceTo>
    <relationshipLabel>Policy Lawyers</relationshipLabel>
    <relationshipName>Policy_Lawyers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Lawyers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Policy_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Effective_Date__c</fullName>
    <formula>Policy__r.Effective_Date__c</formula>
    <label>Policy Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/Policy_Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Quote-{000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Quote__c/fields/Coverage_Max_Per_Claim__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Max_Per_Claim__c</fullName>
    <label>Per Claim Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount__c</fullName>
    <label>Deductible Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_BillingCity__c.field-meta.xml
<CustomField>
    <fullName>Firm_BillingCity__c</fullName>
    <formula>Policy__r.Account__r.BillingCity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm BillingCity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_BillingState__c.field-meta.xml
<CustomField>
    <fullName>Firm_BillingState__c</fullName>
    <formula>Policy__r.Account__r.BillingState</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm BillingState</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_BillingStreet__c.field-meta.xml
<CustomField>
    <fullName>Firm_BillingStreet__c</fullName>
    <formula>Policy__r.Account__r.BillingStreet</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm BillingStreet</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_BillingZIP__c.field-meta.xml
<CustomField>
    <fullName>Firm_BillingZIP__c</fullName>
    <formula>Policy__r.Account__r.BillingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm BillingZIP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_Prior_Acts_Date__c.field-meta.xml
<CustomField>
    <fullName>Firm_Prior_Acts_Date__c</fullName>
    <formula>Policy__r.Policy_Retroactive_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm Prior Acts Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Full_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Full_Coverage__c</fullName>
    <label>Aggregate Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Policy_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Policy_Firm__c.field-meta.xml
<CustomField>
    <fullName>Policy_Firm__c</fullName>
    <formula>Policy__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Firm</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Quote_Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_Expire_Date__c</fullName>
    <defaultValue>TODAY() + 30</defaultValue>
    <label>Quote Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Quote_Final_Premium__c.field-meta.xml
<CustomField>
    <fullName>Quote_Final_Premium__c</fullName>
    <formula>(Quote_Premium_Amount__c + Additional_Premium__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Quote_Final_Premium_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Quote_Final_Premium_Monthly__c</fullName>
    <formula>Quote_Final_Premium__c / 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Final Premium Monthly</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Quote_Final_Premium_Qrtly__c.field-meta.xml
<CustomField>
    <fullName>Quote_Final_Premium_Qrtly__c</fullName>
    <formula>Quote_Final_Premium__c * 0.25</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Final Premium Qrtly</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RegularRenewalDoc_Ctrl.cls
public class RegularRenewalDoc_Ctrl {
    public String recordId{get;set;}
    public String policyId {get; set;}
    public AccountContactRelation primaryConRole {get; set;}
    public Policy__c policy {get; set;}
    public List<Policy_Lawyer__c> policyLawyers {get; set;}
    public Policy_Quote__c quote{get;set;}
    public List<Policy_Quote__c> quoteList{get;set;}
    public Date tenDayPriorEffectiveDt{get; set;}
    
    public Map<String, String> contactRoles {get; set;}
    public Date expirationDate{get;set;}
    public Date dividendYear{get;set;}
    public Date EffectiveDatePlus60{get; set;}
    
    public RegularRenewalDoc_Ctrl(){
        if (apexpages.currentpage().getparameters().get('id') != null){
            recordId = apexpages.currentpage().getparameters().get('id'); 
        }else{
            recordId = policyId;
        }
        if(String.isNotBlank(recordId)){
            setrecordId(recordId);
            getPolicyRec();
        }
    }
    
    
    
    public void setrecordId(String recordId){
        
        policyLawyers = new List<Policy_Lawyer__c>();
        contactRoles = new Map<String, String>{'Owner' => 'O', 'Officer' => 'OF', 'Partner' => 'P', 'Employee' => 'E', 'Associate' => 'A', 'Shareholder' => 'SH', 
            'Member' => 'M', 'Director' => 'D', 'Independent Contractor' => 'IC', 'Of Counsel' => 'OC', 'Contract Employee' => 'CE',
            'Temporary Staff Lawyer' => 'TSL'};
                
                
                System.debug('recordId-----'+recordId);
        
        quoteList = [select id,name,POLICY_EFFECTIVE_DATE__C,POLICY_FIRM__C,FIRM_BILLINGSTREET__C,FIRM_BILLINGCITY__C,FIRM_BILLINGSTATE__C,FIRM_BILLINGZIP__C,CREATEDDATE,QUOTE_EXPIRE_DATE__C,Policy__C,
                     FIRM_PRIOR_ACTS_DATE__c,COVERAGE_MAX_PER_CLAIM__c,FULL_COVERAGE__C,DEDUCTIBLE_AMOUNT__C,QUOTE_FINAL_PREMIUM__c,QUOTE_FINAL_PREMIUM_QRTLY__c,QUOTE_FINAL_PREMIUM_MONTHLY__c from Policy_Quote__c where Policy__c=: recordId Order By QUOTE_FINAL_PREMIUM__c ASC];
        
        System.debug('quoteList-----'+quoteList);
        
        if(!quoteList.isEmpty()){
            quote = quoteList[0];
        }
        
        policy = [SELECT Name, Account__c, Effective_Date__c, County__r.Name, Account__r.Account_Number_External_ID__c, Account__r.Name, 
                  Account__r.Phone, Account__r.Fax, Expiration_Date__c, Per_Claim_Limit__c, Deductible_ID__r.Name, Premium__c,Policy_Effective_Year__c,
                  Aggregate_Limit__c,Account__r.BillingStreet,Account__r.BillingCity,Account__r.BillingState,Account__r.BillingPostalCode,Firm_Contact__r.Email,
                  Firm_Contact__r.Name,Firm_Contact__r.FirstName,Firm_Contact__r.Website__c,Firm_Contact__r.Title,Account__r.Website__c,Firm_Contact__r.Contact_Role__c,Total_CLE_Credit__c,DataLoader__c,Underwriter_User__r.FirstName,Underwriter_User__r.LastName,Dividend_Credit__c,Total_Credit__c,
                  Underwriter_User__r.Title,Underwriter_User__r.Phone,Underwriter_User__r.Email, ISBAM_policy_dividend__c,
                  Previous_Policy__r.Name, Previous_Policy__r.Expiration_Date__c, Firm_Contact__r.LastName
                  FROM Policy__c WHERE Id =: recordId];
        
        policy.DataLoader__c = false;
        
        tenDayPriorEffectiveDt = policy.Effective_Date__c.addDays(-10);
        
        //if(!Test.isRunningTest()){
        policyLawyers = [SELECT Lawyer__r.Name, Prior_Act_Date__c, Lawyer__r.Contact__r.ARDC_Number__c, Lawyer__r.Contact__r.ISBA__c,
                         Lawyer__r.Contact__r.Contact_Role__c,Contact_Role__c,Lawyer__r.Contact__r.Email
                         FROM Policy_Lawyer__c WHERE Policy__c =: policy.Id order by Lawyer__r.Contact__r.LastName ASC];  
        
        for(AccountContactRelation accConRole: [SELECT AccountId, Account.Name, Account.BillingCity, Account.BillingStreet, Account.BillingState,
                                                Contact.Email, Contact.Website__c,
                                                Account.BillingCountry, Account.BillingPostalCode, ContactId, Contact.Name  
                                                FROM AccountContactRelation 
                                                WHERE AccountId =: policy.Account__c AND Contact.Primary_Contact__c = true LIMIT 1])
        {
            primaryConRole = accConRole;
        }
        expirationDate = policy.Effective_Date__c.addYears(1);
        dividendYear =  policy.Effective_Date__c.AddYears(-1);
        EffectiveDatePlus60 = policy.Effective_Date__c.AddDays(60);
        
        
        system.debug('policy -- > ' + policy);
        // }
    }
    
    public String getrecordId(){
        return recordId;
    }
    public Policy__c getPolicyRec(){
        System.debug('Testing for recordid::'+recordId);
        return [SELECT Name, Account__c, Effective_Date__c, County__r.Name, Account__r.Account_Number_External_ID__c, Account__r.Name, 
                Account__r.Phone, Account__r.Fax, Expiration_Date__c, Per_Claim_Limit__c, Deductible_ID__r.Name, Premium__c,
                Aggregate_Limit__c,Account__r.BillingStreet,Account__r.BillingCity,Account__r.BillingState,Account__r.BillingPostalCode,Firm_Contact__r.Email,
                Firm_Contact__r.Name,Firm_Contact__r.FirstName,Firm_Contact__r.Website__c,Firm_Contact__r.Title,Account__r.Website__c,Firm_Contact__r.Contact_Role__c,Total_CLE_Credit__c,DataLoader__c,Underwriter_User__r.FirstName,Underwriter_User__r.LastName,Dividend_Credit__c,Total_Credit__c,
                Underwriter_User__r.Title,Underwriter_User__r.Phone,Underwriter_User__r.Email, ISBAM_policy_dividend__c,
                Previous_Policy__r.Name, Previous_Policy__r.Expiration_Date__c, Firm_Contact__r.LastName
                FROM Policy__c WHERE Id =: recordId];
    }
    
    public List<String> getPolicyLimit () {
        List<String> options = new List<String>();
        options.add('Same As Expiring');
        //if(!Test.isRunningTest()){
        ILF_Coverage_Factor__c[] threatMappings = [SELECT Id, Name, Coverage_Max_Per_Claim__c 
                                                   FROM ILF_Coverage_Factor__c WHERE OldLimit__c = false ORDER BY Coverage_Max_Per_Claim__c,Full_Coverage__c ASC LIMIT 1000];
        for (ILF_Coverage_Factor__c threatMapping : threatMappings) {
            if(threatMapping.Coverage_Max_Per_Claim__c <= 7000000){
                options.add(threatMapping.Name);
            }
        }
        options.add('Higher $______');
        //}
        return options;
    }
    
    public List<String> getPolicyDeductible () {
        List<String> options = new List<String>();
        //if(!Test.isRunningTest()){
        Deductible_Factor__c[] threatMappings = [SELECT Id, Name, Deductible_Amount__c FROM Deductible_Factor__c ORDER BY Deductible_Amount__c ASC LIMIT 1000];
        for (Deductible_Factor__c threatMapping : threatMappings) {
            if(threatMapping.Deductible_Amount__c <= 35000){
                options.add(threatMapping.Name);
            }
        }
        options.add('Higher $______');
        //}
        return options;
    }
    
}