force-app/main/default/objects/AccountContactJunction__c/AccountContactJunction__c.object-meta.xml
<CustomObject>
    <description>Account contact junction object</description>
    <label>Lawyer</label>
    <nameField>
        <label>Lawyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContactJunction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountContactJunction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deductible_Factor__c/Deductible_Factor__c.object-meta.xml
<CustomObject>
    <label>Deductible Factor</label>
    <nameField>
        <label>Deductible Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deductible Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deductible_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Deductible</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Deductible Factors</relationshipLabel>
    <relationshipName>Deductible_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/ILF_Coverage_Factor__c.object-meta.xml
<CustomObject>
    <label>ILF / Limits Factor</label>
    <nameField>
        <label>ILF / Limit Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ILF / Limits Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>ILF / Limits Factors</relationshipLabel>
    <relationshipName>ILF_Coverage_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>if(AND(RecordType.DeveloperName = &apos;Policy&apos; ,Expiration_Date__c &gt; TODAY(), Effective_Date__c &lt;= TODAY(),OR(ISNULL(Cancel_Date__c),Cancel_Date__c&gt; TODAY())),true,false )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Base_Amount__c.field-meta.xml
<CustomField>
    <fullName>Base_Amount__c</fullName>
    <label>Base Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Deductible_ID__c.field-meta.xml
<CustomField>
    <fullName>Deductible_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deductible</label>
    <referenceTo>Deductible_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Mod__c.field-meta.xml
<CustomField>
    <fullName>Firm_Mod__c</fullName>
    <label>Firm Mod</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Limits</label>
    <referenceTo>ILF_Coverage_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Total Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to filter the related lawyers on the basis of related account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Version__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Version__c</fullName>
    <label>Endorsement Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Event_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>AccountContactJunction__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>AccountContactJunction__c.Contact__r.Type__c</field>
            <operation>equals</operation>
            <value>Lawyer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AccountContactJunction__c</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy_Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Policy_Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Policy_Lawyer__c.Deleted_Lawyer__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Policy__c</field>
            <operation>equals</operation>
            <valueField>Policy_Lawyer__c.Policy__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Policy_Lawyer__c</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Refund_Amount__c.field-meta.xml
<CustomField>
    <fullName>Refund_Amount__c</fullName>
    <description>The amount that is to be returned to the policy holder if the policy is cancelled before expiration.</description>
    <label>Return Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/recordTypes/General.recordType-meta.xml
<RecordType>
    <fullName>General</fullName>
    <active>true</active>
    <label>General</label>
</RecordType>

force-app/main/default/objects/Policy_Lawyer__c/Policy_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Policy Lawyer</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Lawyer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This checkbox is for the lawyer to be added in the Policy Calculations, if this checkbox is true then the lawyer is bound in the Policy.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Deleted_Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Deleted_Lawyer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the lawyer is deleted by Delete Lawyer Endorsement then this check will set to true.</description>
    <label>Deleted Lawyer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lawyer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AccountContactJunction__c.Contact__r.Type__c</field>
            <operation>equals</operation>
            <value>Lawyer</value>
        </filterItems>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>AccountContactJunction__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountContactJunction__c</referenceTo>
    <relationshipLabel>Policy Lawyers</relationshipLabel>
    <relationshipName>Policy_Lawyers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Lawyers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Event_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Void</fullName>
        <isActive>false</isActive>
        <label>Void</label>
    </customValue>
    <masterLabel>Event Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Policy_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <label>App Sent</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Requested Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Quoted</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>Lost</label>
    </customValue>
    <customValue>
        <fullName>Bound</fullName>
    </customValue>
    <customValue>
        <fullName>Printed</fullName>
    </customValue>
    <customValue>
        <fullName>Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Pending</fullName>
        <isActive>false</isActive>
        <label>Quote Pending</label>
    </customValue>
    <masterLabel>Policy Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ManageEndorsementsExt_Test.cls
@isTest
public class ManageEndorsementsExt_Test {
    @testSetup static void setup() {
        Account acc                   = TestDataFactory.createAccounts('Test Account');
        acc.AccountNumber             = '123456';
        acc.Vendor_Account__c         = true;
        insert acc;
        
        Contact con                   = TestDataFactory.createContact('Test Contact',acc.id);
        insert con;
        
        Opportunity opp               = TestDataFactory.createOpp(acc.id);
        opp.StageName   = 'Application Sent';
        insert opp;
        
        Master_Factor__c masterfact =TestDataFactory.createMasterfactor('Coverage 10/1/2016 - 12/31/2016','Coverage');
        insert masterfact;
        
        ILF_Coverage_Factor__c coverFactor = TestDataFactory.createCoveragefactor(masterfact.Id);
        insert coverFactor;
        
        Master_Factor__c masterfact1 = TestDataFactory.createMasterfactor('Deductible 10/1/2016 - 12/31/2016','Deductible');
        insert masterfact1;
        
        Deductible_Factor__c deductible = TestDataFactory.createDeductiblefactor(masterfact1.Id);
        Insert deductible; 
        
        Policy__c pol = TestDataFactory.createPolicy(acc.id,opp.id,null,'Policy');
        //pol.Status__c = 'Accepted';
        pol.Account__c = acc.Id;
        pol.Limit__c = coverFactor.Id;
        pol.Deductible_ID__c = deductible.Id;
        pol.Firm_Mod__c = 1;
        pol.Base_Amount__c = 1000000;
        pol.Premium__c = 150;
        insert pol;
        
        List<Endorsement__c> objEndorsementList = new List<Endorsement__c>();
        Endorsement__c endorse = TestDataFactory.createEndorsement('IL 152','Functional','General');
     
        objEndorsementList.add(endorse);
       
        insert objEndorsementList;
        
        
        
        
        
        
        Endorsement_Version__c endorseVersion = TestDataFactory.createEndorsementVersion(endorse.Id);
        insert endorseVersion;
       
        
        Attachment attach = new Attachment(Name='Test Attach', Body= Blob.valueOf('test'), ParentId=pol.Id);
        insert attach;
        List<Policy__c> policies = [SELECT Id,Account__c FROM Policy__c];
        List<Contact> conList = [SELECT Id FROM Contact];
        
        Test.startTest();
        
        Policy__c  policy = policies[0];
        
        AccountContactJunction__c junc = TestDataFactory.createAccConJunc(policies[0].Account__c, conList[0].Id);
        insert junc;
        
        Policy_Lawyer__c law = TestDataFactory.createPolicyLawyer(policies[0].Account__c,policies[0].Id,junc.Id);
        law.Active__c = true;
        law.Deleted_Lawyer__c = false;
        insert law;
        
        List<Policy_Endorsement__c> lstPolicyEndorsements = new List<Policy_Endorsement__c>();
        
        Policy_Endorsement__c policyEnd = TestDataFactory.createPolicyEndorsement(acc.id,policies[0].Id,'General');
        policyEnd.Event_Status__c = 'Pending';
        policyEnd.Lawyer__c = junc.id;
        policyEnd.Refund_Amount__c = 10;
        policyEnd.Additional_Premium__c = 100;
        
        lstPolicyEndorsements.add(policyEnd);
        
        insert lstPolicyEndorsements;
        
        AS_Transaction__c as_trans = TestDataFactory.createTransaction(lstPolicyEndorsements[0].Id,'Add Lawyer',100,pol.Id,null,pol.account__c,null,'Add Lawyer');
        insert as_trans;    
    }
    
    @isTest static void unitTest(){
        List<Endorsement__c> LstEnd = [select id,Endorsement_Record_Type_ID__c from Endorsement__c LIMIT 2];
    Endorsement__c endObj = new Endorsement__c();
        Test.startTest();
        List<Policy__c> Pollst = [Select id from Policy__c ];
        ApexPages.StandardController sc = new ApexPages.StandardController(LstEnd[0]);
            PageReference myVfPage = Page.ManageEndorsements;
           Test.setCurrentPage(myVfPage);
       String RecId = Schema.SObjectType.Policy_Endorsement__c.getRecordTypeInfosByName().get('General').getRecordTypeId();
        ApexPages.currentPage().getParameters().put('origin','true');
         ApexPages.currentPage().getParameters().put('relatedId',Pollst[0].id);
        ManageEndorsementsExt Obj = new ManageEndorsementsExt(sc);
        obj.recordTypeId = RecId;
        obj.endorsementId = LstEnd[0].id;
        obj.addEndorsementFunc();
        obj.getRecordTypeNames();
        obj.removeEndorsementFunc(); 
        Test.stopTest();
    }
    
    
     
    @isTest static void unitTest1(){
        List<Endorsement__c> LstEnd = [select id,Endorsement_Record_Type_ID__c from Endorsement__c LIMIT 2];
        
        
    	Endorsement__c endObj = new Endorsement__c();
        Test.startTest();
        List<Policy__c> Pollst = [Select id from Policy__c ];
        Policy__c myPol = Pollst[0];
        myPol.Cancel_Date__c =null;
        upsert myPol;
        
        Endorsement__c myEnd =LstEnd[0];
        myEnd.Endorsement_Sub_Type__c='IL 102';
        upsert myEnd;
        
        List<Policy_Endorsement__c> PolEnd = [Select id from Policy_Endorsement__c];
        Policy_Endorsement__c myPolEnd = PolEnd[0];
        myPolEnd.Endorsement_Number__c ='IL 102';
        upsert myPolEnd;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(LstEnd[0]);
            PageReference myVfPage = Page.ManageEndorsements;
           Test.setCurrentPage(myVfPage);
           String RecId = Schema.SObjectType.Policy_Endorsement__c.getRecordTypeInfosByName().get('General').getRecordTypeId();
        ApexPages.currentPage().getParameters().put('origin','false');
         ApexPages.currentPage().getParameters().put('relatedId',Pollst[0].id);
        ManageEndorsementsExt Obj = new ManageEndorsementsExt(sc);
        obj.recordTypeId = RecId;
        obj.endorsementId = LstEnd[0].id;
        obj.addEndorsementFunc();
        obj.getRecordTypeNames();
        obj.removeEndorsementFunc(); 
        
        
        myPolEnd.Endorsement_Number__c ='IL 153';
        upsert myPolEnd;
        
        myEnd.Endorsement_Sub_Type__c='IL 153';
        
        upsert myEnd;
        
        ApexPages.currentPage().getParameters().put('origin','false');
         ApexPages.currentPage().getParameters().put('relatedId',Pollst[0].id);
        ManageEndorsementsExt Obj2 = new ManageEndorsementsExt(sc);
        obj2.recordTypeId = RecId;
        obj2.endorsementId = LstEnd[0].id;
        obj2.index=0;
        obj2.addEndorsementFunc();
        obj2.removeEndorsementFunc();
        Test.stopTest();
    }
     
    @isTest static void unitTest2(){
         Endorsement__c endorse = TestDataFactory.createEndorsement('IL 153','Functional','General');
         insert endorse;
    Endorsement__c endObj = new Endorsement__c();
        Test.startTest();
        List<Policy__c> Pollst = [Select id from Policy__c ];
        ApexPages.StandardController sc = new ApexPages.StandardController(endorse);
            PageReference myVfPage = Page.ManageEndorsements;
           Test.setCurrentPage(myVfPage);
       String RecId = Schema.SObjectType.Policy_Endorsement__c.getRecordTypeInfosByName().get('General').getRecordTypeId();
        ApexPages.currentPage().getParameters().put('origin','true');
         ApexPages.currentPage().getParameters().put('relatedId',Pollst[0].id);
        ManageEndorsementsExt Obj = new ManageEndorsementsExt(sc);
       // obj.recordTypeId = RecId;
        obj.endorsementId = endorse.id;
        obj.addEndorsementFunc();
        obj.getRecordTypeNames();
        obj.removeEndorsementFunc(); 
        Test.stopTest();
    }


}