force-app/main/default/objects/AccountContactJunction__c/AccountContactJunction__c.object-meta.xml
<CustomObject>
    <description>Account contact junction object</description>
    <label>Lawyer</label>
    <nameField>
        <label>Lawyer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContactJunction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>AccountContactJunction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Invoice</fullName>
            </value>
            <value>
                <fullName>Pending Close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Claimant__c.field-meta.xml
<CustomField>
    <fullName>Claimant__c</fullName>
    <label>Claimant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incident</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Suit</fullName>
            </value>
            <value>
                <fullName>ARDC Complaint</fullName>
            </value>
            <value>
                <fullName>Memo</fullName>
            </value>
            <value>
                <fullName>Supoena</fullName>
                <label>Subpoena</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_2100__c.field-meta.xml
<CustomField>
    <fullName>GL_2100__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 2100</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_2140__c.field-meta.xml
<CustomField>
    <fullName>GL_2140__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 2140</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5000__c.field-meta.xml
<CustomField>
    <fullName>GL_5000__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5000</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5010__c.field-meta.xml
<CustomField>
    <fullName>GL_5010__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5010</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5030__c.field-meta.xml
<CustomField>
    <fullName>GL_5030__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5030</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5035__c.field-meta.xml
<CustomField>
    <fullName>GL_5035__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5035</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/LawyerNew__c.field-meta.xml
<CustomField>
    <fullName>LawyerNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer New</label>
    <referenceTo>AccountContactJunction__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp;   Policy__c  , Policy__r.Policy_Number__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <label>Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ContactClaimsComponentHandler.cls
public class ContactClaimsComponentHandler {
	@AuraEnabled
    public static List<Policy_Claim__c> getClaims(String recordId, boolean allRecords){
        String sObjName = ((Id)recordId).getSObjectType().getDescribe().getName();
        if(sObjName == 'Contact'){
            List<Policy_Claim__c> policyClaims = new List<Policy_Claim__c>();
            for(Policy_Claim__c claim : [select id,Name,Policy_Number__c,Claimant__c,File_Type__c,Report_Date__c,Claim_Status__c,Policy__r.Name,GL_2100__c,GL_2140__c,GL_5000__c,GL_5030__c,GL_5010__c,GL_5035__c from Policy_Claim__c where LawyerNew__r.Contact__c =: recordId order by Name desc ]){
                policyClaims.add(claim);
            }
            return policyClaims;
        }else{
            List<Policy_Claim__c> policyClaims = new List<Policy_Claim__c>();
            return policyClaims;
        }
    }
}