force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deductible_Factor__c/Deductible_Factor__c.object-meta.xml
<CustomObject>
    <label>Deductible Factor</label>
    <nameField>
        <label>Deductible Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deductible Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deductible_Factor__c/fields/Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount__c</fullName>
    <label>Deductible Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GEO_Factor__c/GEO_Factor__c.object-meta.xml
<CustomObject>
    <label>GEO Factor</label>
    <nameField>
        <label>GEO Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEO Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GEO_Factor__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>GEO Factors</relationshipLabel>
    <relationshipName>GEO_Factors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Aggregate_Limit__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Limit__c</fullName>
    <label>Aggregate Limit</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <description>Type of application that is being created.</description>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>County</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>GEO_Factor__c.Master_Factor__r.Default__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>GEO_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/DataLoader__c.field-meta.xml
<CustomField>
    <fullName>DataLoader__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DataLoader</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount__c</fullName>
    <label>Deductible Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Deductible_ID__c.field-meta.xml
<CustomField>
    <fullName>Deductible_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deductible</label>
    <referenceTo>Deductible_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Dividend_Credit__c.field-meta.xml
<CustomField>
    <fullName>Dividend_Credit__c</fullName>
    <label>XXX Dividend Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Contact__c.field-meta.xml
<CustomField>
    <fullName>Firm_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Firm Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/ISBAM_policy_dividend__c.field-meta.xml
<CustomField>
    <fullName>ISBAM_policy_dividend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Dividend value calculated when application was created</description>
    <label>ISBAM Policy Dividend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Latest_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Latest_Activity_Date__c</fullName>
    <label>Latest Activity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Per_Claim_Limit__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Limit__c</fullName>
    <label>Per Claim Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Total Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Previous_Policy__c.field-meta.xml
<CustomField>
    <fullName>Previous_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Total_CLE_Credit__c.field-meta.xml
<CustomField>
    <fullName>Total_CLE_Credit__c</fullName>
    <label>Total CLE Credit</label>
    <summarizedField>Policy_Lawyer__c.CLE_Credit__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Lawyer__c.Is_Application_Lawyer__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Lawyer__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Total_Credit__c.field-meta.xml
<CustomField>
    <fullName>Total_Credit__c</fullName>
    <formula>if (Effective_Date__c &lt; DATE(2023,1,1),
0,
Total_CLE_Credit__c + ISBAM_policy_dividend__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter_User__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Underwriter User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Quote__c/Policy_Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Quote-{000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Quote__c/fields/Coverage_Max_Per_Claim__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Max_Per_Claim__c</fullName>
    <label>Per Claim Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount__c</fullName>
    <label>Deductible Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_BillingCity__c.field-meta.xml
<CustomField>
    <fullName>Firm_BillingCity__c</fullName>
    <formula>Policy__r.Account__r.BillingCity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm BillingCity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_BillingState__c.field-meta.xml
<CustomField>
    <fullName>Firm_BillingState__c</fullName>
    <formula>Policy__r.Account__r.BillingState</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm BillingState</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_BillingStreet__c.field-meta.xml
<CustomField>
    <fullName>Firm_BillingStreet__c</fullName>
    <formula>Policy__r.Account__r.BillingStreet</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm BillingStreet</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_BillingZIP__c.field-meta.xml
<CustomField>
    <fullName>Firm_BillingZIP__c</fullName>
    <formula>Policy__r.Account__r.BillingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm BillingZIP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Firm_Prior_Acts_Date__c.field-meta.xml
<CustomField>
    <fullName>Firm_Prior_Acts_Date__c</fullName>
    <formula>Policy__r.Policy_Retroactive_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm Prior Acts Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Full_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Full_Coverage__c</fullName>
    <label>Aggregate Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Policy_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Policy_Firm__c.field-meta.xml
<CustomField>
    <fullName>Policy_Firm__c</fullName>
    <formula>Policy__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Firm</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <formula>If( 
Or(ISNULL(Policy__r.Policy_Number__c),ISBLANK(Policy__r.Policy_Number__c)) , 
Policy__r.Name, 
Policy__r.Policy_Number__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Quote_Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_Expire_Date__c</fullName>
    <defaultValue>TODAY() + 30</defaultValue>
    <label>Quote Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Quote_Final_Premium__c.field-meta.xml
<CustomField>
    <fullName>Quote_Final_Premium__c</fullName>
    <formula>(Quote_Premium_Amount__c + Additional_Premium__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Quote_Final_Premium_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Quote_Final_Premium_Monthly__c</fullName>
    <formula>Quote_Final_Premium__c / 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Final Premium Monthly</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Quote_Final_Premium_Qrtly__c.field-meta.xml
<CustomField>
    <fullName>Quote_Final_Premium_Qrtly__c</fullName>
    <formula>Quote_Final_Premium__c * 0.25</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Final Premium Qrtly</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Application_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Business</fullName>
        <default>true</default>
        <label>New Business</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <description>This global list will hold the values of Application type.</description>
    <masterLabel>Application Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Billing_Policy_Ctrl.cls
public class Billing_Policy_Ctrl {
    
    // variables
    public String billId {get; set;}
    public String recordId{get;set;}
    public AcctSeed__Billing__c billing {get; set;}
    public Policy__c policy {get; set;}
    public Policy_Quote__c quote{get;set;}
    public EmailMessage latest_invoice_activity{get;set;}
    public List<Policy_Quote__c> quoteList{get;set;}    
    
    // constructor
    public Billing_Policy_Ctrl(){
        if (apexpages.currentpage().getparameters().get('id') != null){
            recordId = apexpages.currentpage().getparameters().get('id');
        }else{
            recordId = billId;
        }
        if(String.isNotBlank(recordId)){
            setrecordId(recordId);
            getPolicyRec();
            getInvoiceActivity();
        }
    }
    //System.debug('recordId-----'+recordId);
    
    
    public static string insertBreak(String hyperLink) { // hyperLink is the URL
        final Integer linkLength = hyperLink.length();
        final Integer maxLength = Math.min(100,linkLength);
        Integer varCount = (linkLength/maxLength);
        
        if (math.mod(linkLength, maxLength) > 0)
            varCount++;
        
        String fullLink = '';
        integer startValue = 0;
        integer endValue = maxLength;
        for (Integer i = varCount; i >= 0; i--) { 
            fullLink += hyperLink.substring(startValue, endValue) + ' ';
            startValue = endValue;
            endValue = (endValue + maxLength) > linkLength ? linkLength : (endValue + maxLength);
        }
        return fullLink;
    }
    
    // instantiate record id
    public void setrecordId(String recordId){
        
        // get billing
        // https://isbamutual--beta--c.sandbox.vf.force.com/apex/NOC_PDF?id=a1f050000016RiFAAU
        billing = [
            SELECT 
            Name
            , Payment_Link__c
            , Policy__c
            , AcctSeed__Billing_Contact__r.Name
            , AcctSeed__Billing_Contact__r.email
            , AcctSeed__Billing_Contact__r.FirstName
            , AcctSeed__Billing_Contact__r.LastName
            , ISBAM_Overdue_Date__c 
            , Past_Due_Amount__c,Policy_Number__c,Latest_Activity_Date__c
            FROM AcctSeed__Billing__c 
            WHERE Id =: recordId
        ];
        System.debug('billing: '+billing);    
        
        
        
        // get latest invoice activity
       
                
        // get policy
        policy = [
            SELECT 
            Name
            , Account__c
            , Effective_Date__c
            , County__r.Name
            , Account__r.Account_Number_External_ID__c, Account__r.Name
            , Account__r.Phone
            , Account__r.Fax
            , Expiration_Date__c
            , Per_Claim_Limit__c
            , Deductible_ID__r.Name, Premium__c
            , Aggregate_Limit__c
            , Account__r.BillingStreet
            , Account__r.BillingCity
            , Account__r.BillingState
            , Account__r.BillingPostalCode
            , Latest_Activity_Date__c
            , Application_Type__c
            , Firm_Contact__r.Email
            , Firm_Contact__r.Name
            , Firm_Contact__r.FirstName
            , Firm_Contact__r.LastName
            , Firm_Contact__r.Website__c
            , Firm_Contact__r.Title
            , Account__r.Website__c
            , Firm_Contact__r.Contact_Role__c
            , Total_CLE_Credit__c
            , DataLoader__c
            , Underwriter_User__r.FirstName
            , Underwriter_User__r.LastName
            , Dividend_Credit__c
            , Total_Credit__c
            , Underwriter_User__r.Title,Underwriter_User__r.Phone,Underwriter_User__r.Email
            , ISBAM_policy_dividend__c
            , Previous_Policy__r.Name
            FROM Policy__c 
            WHERE Id =: billing.Policy__c
        ];
        
        
        // get quote
        quoteList = [
            SELECT id,
            name
            , POLICY_EFFECTIVE_DATE__C
            , POLICY_FIRM__C
            , FIRM_BILLINGSTREET__C
            , FIRM_BILLINGCITY__C
            , FIRM_BILLINGSTATE__C
            , FIRM_BILLINGZIP__C
            , CREATEDDATE,QUOTE_EXPIRE_DATE__C
            , Policy__C
            , FIRM_PRIOR_ACTS_DATE__c
            , COVERAGE_MAX_PER_CLAIM__c
            , FULL_COVERAGE__C
            , DEDUCTIBLE_AMOUNT__C
            , QUOTE_FINAL_PREMIUM__c
            , QUOTE_FINAL_PREMIUM_QRTLY__c
            , QUOTE_FINAL_PREMIUM_MONTHLY__c 
            FROM Policy_Quote__c 
            WHERE Policy__c=: billing.Policy__c
            ORDER BY QUOTE_FINAL_PREMIUM__c ASC
        ];
        System.debug('quoteList-----'+quoteList);  
        if(!quoteList.isEmpty()){
            quote = quoteList[0];
        }
        
        
        
    }
    
    public EmailMessage getInvoiceActivity() {
        system.debug('recordId  - > ' + recordId);
        List<EmailMessage> emailMessages = [SELECT
                Name
                , Status
                , Subject
                , MessageDate 
                FROM EmailMessage 
                WHERE RelatedToId =: recordId AND Subject Like '%Invoice%'
                ORDER BY MessageDate DESC
                LIMIT 1
               ];
        if(!emailMessages.isEmpty()){
            return emailMessages[0];
        }else{
            return null;
        }
        
    }
        
    public AcctSeed__Billing__c getbillingRec(){
        AcctSeed__Billing__c bill = [
            SELECT id,
            Name
            , Payment_Link__c
            , Policy__c
            , AcctSeed__Billing_Contact__r.Name
            , AcctSeed__Billing_Contact__r.email
            , AcctSeed__Billing_Contact__r.FirstName
            , AcctSeed__Billing_Contact__r.LastName
            , ISBAM_Overdue_Date__c 
            , Past_Due_Amount__c,Policy_Number__c,Latest_Activity_Date__c
            FROM AcctSeed__Billing__c 
            WHERE Id =: recordId
            LIMIT 1
        ];
        bill.Payment_Link__c = insertBreak(bill.Payment_Link__c);
        return bill;
    }  
    
    public Policy__c getPolicyRec(){
        system.debug('recordId -- > ' + recordId);
        
        List<AcctSeed__Billing__c> billingRecList = new List<AcctSeed__Billing__c>();
        billingRecList = [
            SELECT 
            id
            , Policy__c,Policy_Number__c 
            FROM AcctSeed__Billing__c 
            WHERE Id =: recordId
            LIMIT 1
        ];
        
        if(!billingRecList.isEmpty()){ 
            return  [
                SELECT 
                Name
                , Account__c
                , Effective_Date__c
                , County__r.Name
                , Account__r.Account_Number_External_ID__c, Account__r.Name
                , Account__r.Phone
                , Account__r.Fax
                , Expiration_Date__c
                , Per_Claim_Limit__c
                , Deductible_ID__r.Name, Premium__c
                , Aggregate_Limit__c
                , Account__r.BillingStreet
                , Account__r.BillingCity
                , Account__r.BillingState
                , Account__r.BillingPostalCode
                , Account__r.ShippingStreet
                , Account__r.ShippingCity
                , Account__r.ShippingState
                , Account__r.ShippingPostalCode
                , Latest_Activity_Date__c
                , Application_Type__c
                , Firm_Contact__r.Email
                , Firm_Contact__r.Name
                , Firm_Contact__r.FirstName
                , Firm_Contact__r.LastName
                , Firm_Contact__r.Website__c
                , Firm_Contact__r.Title
                , Account__r.Website__c
                , Firm_Contact__r.Contact_Role__c
                , Total_CLE_Credit__c
                , DataLoader__c
                , Underwriter_User__r.FirstName
                , Underwriter_User__r.LastName
                , Dividend_Credit__c
                , Total_Credit__c
                , Underwriter_User__r.Title,Underwriter_User__r.Phone,Underwriter_User__r.Email
                , ISBAM_policy_dividend__c
                , Previous_Policy__r.Name
                FROM Policy__c 
                WHERE Id =: billingRecList[0].Policy__c
            ];
        }
        else{
            return new Policy__c();
        }
    }
}