force-app/main/default/objects/Policy_Claim_Detail__c/Policy_Claim_Detail__c.object-meta.xml
<CustomObject>
    <label>Policy Claim Detail</label>
    <nameField>
        <displayFormat>Claim-{0000000}</displayFormat>
        <label>Claim Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Claims Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reserve_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/recordTypes/Deductible.recordType-meta.xml
<RecordType>
    <fullName>Deductible</fullName>
    <active>true</active>
    <description>1) Allocate Deductible Loss/LAE. 2) Cash Received / Write-off against Deductible.</description>
    <label>Deductible</label>
</RecordType>

force-app/main/default/objects/Policy_Claim_Detail__c/recordTypes/Reserve.recordType-meta.xml
<RecordType>
    <fullName>Reserve</fullName>
    <active>true</active>
    <description>1) Increase Reserve(User Reserve)  2) Close/Re-Open Reserve</description>
    <label>Reserve</label>
</RecordType>

force-app/main/default/globalValueSets/Reserve_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>User Reserve</fullName>
        <label>Change Reserve</label>
    </customValue>
    <customValue>
        <fullName>Close Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Reopen Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Loss Payment</fullName>
    </customValue>
    <customValue>
        <fullName>LAE Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Deductible Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Deductible Expense</fullName>
    </customValue>
    <customValue>
        <fullName>Change in Ceded Loss Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Change in Ceded LAE Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Due from Reins. - Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Due from Reins. - LAE</fullName>
    </customValue>
    <customValue>
        <fullName>Open Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Claim Coverage - ARDC</fullName>
        <label>ARDC Payment</label>
    </customValue>
    <customValue>
        <fullName>Unallocated LAE Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Deductible Expense New</fullName>
    </customValue>
    <customValue>
        <fullName>SBL</fullName>
    </customValue>
    <customValue>
        <fullName>CPSBL</fullName>
    </customValue>
    <customValue>
        <fullName>CPSBE</fullName>
    </customValue>
    <masterLabel>Reserve Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Policy_Claim_Detail_Handler.cls
/*
 * 
 * Created By     : Shoukat Hussain
 * Created Date   : 12/28/2016
 * Purpose        : Trigger Handler for the Policy_claim_Detail SObject. This class implements the ITrigger interface to help ensure the trigger code is bulkified and all in one place.
 * Name           : Policy_Claim_Detail_Handler
 * Referenced     : Currently at the time of creation this class is referenced by TriggerFactory.
 * 
 *  
 */
public class Policy_Claim_Detail_Handler implements ITrigger {
//public with sharing class EndorsementHandler implements ITrigger {
	public Policy_Claim_Detail_Handler() {
	}

	public void bulkBefore() {
	}
	
	public void bulkAfter() {
	}
		
	public void beforeInsert(List<SObject> newItems) {} public void beforeUpdate(Map<Id,SObject> oldItems, Map<Id,SObject> newItems) {} 	public void beforeDelete(Map<Id,SObject> oldItems) {}
	
	public void afterInsert(Map<Id,SObject> newItems) {
        List<Policy_Claim_Detail__c> newItemsLst =  newItems.values();  
        // Create All list which will use for different purposes
        List<Policy_Claim_Detail__c> CreateAccountingSeeds = new List<Policy_Claim_Detail__c>();
        List<Policy_Claim_Detail__c> CreateAutoDeductible  = new List<Policy_Claim_Detail__c>();
        
        //Data segrigate 
        for(Policy_Claim_Detail__c pcd : newItemsLst){
            
			If(pcd.Type__c == 'Open Reserve' || pcd.Type__c == 'User Reserve' || pcd.Type__c == 'Close Reserve' 	 || pcd.Type__c == 'Reopen Reserve' ||pcd.Type__c == 'LAE Payment'  || pcd.Type__c == 'Loss Payment' || pcd.Type__c == 'Deductible Expense' || pcd.Type__c == 'Deductible Loss' || pcd.Type__c == 'Deductible Expense New' ||pcd.Type__c == 'Change in Ceded LAE Reserve' || pcd.Type__c == 'Change in Ceded Loss Reserve' || pcd.Type__c == 'Due from Reins. - LAE' ||pcd.Type__c == 'Due from Reins. - Loss' 		|| pcd.Type__c == 'Unallocated LAE Payment' 	 || pcd.Type__c == 'Claim Coverage - ARDC' ){
				CreateAccountingSeeds.add(pcd);
               }                        

            If(pcd.Type__c=='Loss Payment' || pcd.Type__c=='LAE Payment' ){
                CreateAutoDeductible.add(pcd);
            }
        }
          System.debug(CreateAccountingSeeds.size()+'<===CreateAccountingSeeds===>'+CreateAccountingSeeds.size());      
		//Create Accounting Seeds transaction 
        If(CreateAccountingSeeds.size()>0){
        	Policy_Claim_Detail_Gateway.CreateAccountingSeedsTransaction(CreateAccountingSeeds);    
        }
          System.debug(CreateAutoDeductible.size()+'<===CreateAccountingSeeds===>'+CreateAutoDeductible.size());            
        //Create Auto deductible transaction
        if(CreateAutoDeductible.size()>0){
        	Policy_Claim_Detail_Gateway.CreateAutoDedcutibleRecord(CreateAutoDeductible);    
        }
       
	}
	
	public void afterUpdate(Map<Id,SObject> oldItems, Map<Id,SObject> newItems) {} public void afterDelete(Map<Id,SObject> oldItems) {} public void andFinally() {}
}