force-app/main/default/objects/ILF_Coverage_Factor__c/ILF_Coverage_Factor__c.object-meta.xml
<CustomObject>
    <label>ILF / Limits Factor</label>
    <nameField>
        <label>ILF / Limit Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ILF / Limits Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <description>Type of application that is being created.</description>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Limits</label>
    <referenceTo>ILF_Coverage_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Old_Policy__c.field-meta.xml
<CustomField>
    <fullName>Old_Policy__c</fullName>
    <externalId>true</externalId>
    <label>Old Policy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Renew_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Renew_Status__c</fullName>
    <label>Policy Renew Status</label>
    <length>80000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Total Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/globalValueSets/Application_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Business</fullName>
        <default>true</default>
        <label>New Business</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <description>This global list will hold the values of Application type.</description>
    <masterLabel>Application Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/searchPolicyController.cls
public class searchPolicyController{

public Date startExpirDate {get;set;}
public Date endExpirDate {get;set;}
public string renwalIds{get;set;}
public Policy__c policysearch{get;set;}
public Map<Id,Policy__c> newRenewalMap; 

public List<policyWrapper> searchPolicyList{get;set;}

    public searchPolicyController(){
        policysearch = new Policy__c();
        searchPolicyList = New List<policyWrapper>();
        fatchPolicy();
    }
    
    public void fatchPolicy(){
    
        searchPolicyList = New List<policyWrapper>();
        string recordtype = 'Policy';
        
        String query = 'SELECT Id,Name,Account__r.Name,Policy_Renew_Status__c,RecordType.Name,Expiration_Date__c,Application_Type__c,Limit__r.Name,Premium__c '
                       +' FROM Policy__c WHERE RecordType.Name =: recordtype ';
        String Filter = '';
        String strType = policysearch.Application_Type__c;
        
        if(startExpirDate != null){
        
            Filter += ' AND Expiration_Date__c >= :startExpirDate ';
        }
        if(endExpirDate != null){
        
            if(String.IsNotBlank(Filter)){
                
                Filter += 'AND Expiration_Date__c <= :endExpirDate';
            }else{
                
                Filter += ' AND Expiration_Date__c <= :endExpirDate ';
            }
        }
        
        if( strType != null && strType != ''){
            
            Filter += ' AND Application_Type__c = :strType';
        }
        
        if(String.IsNotBlank(Filter)){
            query = query+''+Filter+' LIMIT 1000';
            system.debug('========query========'+query);
            List<Policy__c> lstOfPolicys = database.query(query);
            system.debug('========lstOfPolicys========'+lstOfPolicys);
            set<Id> ids = new set<Id>();
            
            for(Policy__c Obj : lstOfPolicys){
                ids.add(Obj.Id);
            }
                
            newRenewalMap = new Map<Id,Policy__c>(); 
            
            for(Policy__c pol : [SELECT Id,Name,Old_Policy__c FROM Policy__c WHERE Old_Policy__c IN: ids]){
                
                newRenewalMap.put(pol.Old_Policy__c,pol);
                
            }
             
            if(!lstOfPolicys.IsEmpty()){
            
                for(Policy__c Obj : lstOfPolicys){
                    
                    if(newRenewalMap.containsKey(Obj.Id)){
                    
                        Policy__c newPolicy = newRenewalMap.get(Obj.Id);
                        
                        searchPolicyList.add(new policyWrapper(obj,newPolicy));
                    
                    } else {
                        searchPolicyList.add(new policyWrapper(obj,null));                    
                    }
                    
                }
            }
        }else{
            searchPolicyList = New List<policyWrapper>();
        }
    }
    
    public void renewal(){
        
        List<string> ids = new List<string>();
        
        if(renwalIds != null && renwalIds != ''){
            
            for(string str : renwalIds.split(',')){
                ids.add(str);
            }
            
            List<string> result = CloneAndRenewalUtilities.renewMassPolicyManually(ids);
            renwalIds = '';
            fatchPolicy();
        }
        
    }
    
    
    public class policyWrapper{
        //public Boolean isSelected{get;set;}
        public Policy__c policyobj{get;set;}
        public Policy__c newPolicy{get;set;}
        public policyWrapper(Policy__c policy,Policy__c newpolicy){
            
            this.policyobj = policy;
            this.newPolicy = newpolicy;
           // this.isSelected = sel;
        }
    }
}