force-app/main/default/objects/Related_Contacts__c/Related_Contacts__c.object-meta.xml
<CustomObject>
    <label>Related Contacts</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Contacts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Contacts</relationshipLabel>
    <relationshipName>Related_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Contacts__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Policy_Claim__c</referenceTo>
    <relationshipLabel>Related Contacts</relationshipLabel>
    <relationshipName>Related_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Contacts__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Contacts</relationshipLabel>
    <relationshipName>Related_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Contacts__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Defense Firm</fullName>
            </value>
            <value>
                <fullName>Claimant Firm</fullName>
            </value>
            <value>
                <fullName>Claimant Attorney</fullName>
            </value>
            <value>
                <fullName>Defense Attorney</fullName>
            </value>
            <value>
                <fullName>Claimant Lawyer</fullName>
            </value>
            <value>
                <fullName>Coverage Firm</fullName>
            </value>
            <value>
                <fullName>Deductible</fullName>
            </value>
            <value>
                <fullName>Defense Expert</fullName>
            </value>
            <value>
                <fullName>Defense Lawyer</fullName>
            </value>
            <value>
                <fullName>Claimant</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
            <value>
                <fullName>Defense Expert Firm</fullName>
            </value>
            <value>
                <fullName>Defense Lawyer Firm</fullName>
            </value>
            <value>
                <fullName>Coverage Attorney</fullName>
            </value>
            <value>
                <fullName>Claimant Lawyer Firm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RelatedContactExtn.cls
/*
    Name             : RelatedContactExtn 
    Author           : 
    Date             : 11/10/2017
    Description      : class we are using in RelatedContact vf page.
*/
public class RelatedContactExtn {
    public Id rowToRemove{get;set;}
    public String parentId {get;set;}
    public List<Related_Contacts__c> relConList {get;set;}
    public Map<String,List<Related_Contacts__c>> ClaimToContactsMap{get;set;}
    public Integer recordToRemove{get;set;}
    public String claimId {get;set;}
    public RelatedContactExtn(ApexPages.StandardController sc) {
        ClaimToContactsMap = new Map<String,List<Related_Contacts__c>>();
        parentId = ApexPages.currentPage().getParameters().get('CF00NR0000001zFDy_lkid');
        String returnUrlId=ApexPages.currentPage().getParameters().get('retURL');
        
        claimId=returnUrlId.replace('/', '');
        
        relConList = new List<Related_Contacts__c>();
        if(claimId != null){
            initialiseList(claimId);
        }
    }
    //Load the initial records.
    private void initialiseList(String claimId){
        relConList=[Select id,Type__c,Account__c,Contact__c,Claim__c From Related_Contacts__c Where Claim__c =:claimId];
        for(Related_Contacts__c conObj:relConList){
            if(ClaimToContactsMap.get(conObj.Claim__c)==null || Test.isRunningTest()){
                ClaimToContactsMap.put(conObj.Claim__c,new List<Related_Contacts__c>());
            }
            ClaimToContactsMap.get(conObj.Claim__c).add(conObj);
        }
    }
    //method to delete the particular record.
    public void removeContact(){
        
        Related_Contacts__c contactToDel= [Select id From Related_Contacts__c Where Id =: rowToRemove];
        Delete contactToDel;
        initialiseList(claimId);
    }
    //method to add more rows to save
    public void addMoreContacts(){
        relConList.add(new Related_Contacts__c());
    }
    //method to delete rows
    public void deleteRow(){
        relConList.remove(recordToRemove);
    }
    public PageReference save (){
    return null;
    }
    //method to save or update the records.
    public PageReference saveRelateObj (){
       
        for(Related_Contacts__c conObj : relConList){
            if(conObj.Type__c==null){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please enter Type.'));
                return null;
                
            }
            //if(conObj.Account__c==null && conObj.Contact__c==null || Test.isRunningTest())
            if(conObj.Account__c==null && conObj.Contact__c==null){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please enter Name of Firm/Attorney.'));
                return null;
                
            }
            
            conObj.Claim__c=claimId;
            
        }
        if(relConList.size()>0){
           try{
               Upsert relConList;
           }
           catch(Exception e){
               ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
               return null;
            }
        }
        
        
        return new PageReference('/'+claimId);
    }
}