force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{00}</displayFormat>
        <label>Payment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Schedule__c/fields/Billing__c.field-meta.xml
<CustomField>
    <fullName>Billing__c</fullName>
    <label>Billing</label>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Cash_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Cash_Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cash Receipt</label>
    <referenceTo>AcctSeed__Cash_Receipt__c</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Due_Amount__c.field-meta.xml
<CustomField>
    <fullName>Due_Amount__c</fullName>
    <formula>Amount__c  -  Paid_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Quaterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Payment_Reference__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference__c</fullName>
    <label>Payment Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Settled_Date__c.field-meta.xml
<CustomField>
    <fullName>Settled_Date__c</fullName>
    <label>Settled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CashReceiptTriggerHandler.cls
public class CashReceiptTriggerHandler {
	
    public static void onAfterInsert(List<AcctSeed__Cash_Receipt__c> newList){
        Map<String, String> transactionIdMap = new Map<String, String>();
        
        for(AcctSeed__Cash_Receipt__c cr: newList){
            transactionIdMap.put(cr.AcctSeed__Payment_Reference__c, cr.Id);
        }
        
        List<Payment_Schedule__c> paymentSchedules= [SELECT Id, Billing__c, Payment_Reference__c, Frequency__c, Due_Amount__c, Amount__c, Due_Date__c FROM Payment_Schedule__c WHERE Status__c = 'Pending' AND Payment_Reference__c IN: transactionIdMap.keySet()];
        for(Payment_Schedule__c ps: paymentSchedules){
            ps.Status__c = 'Paid';
            ps.Cash_Receipt__c = transactionIdMap.get(ps.Payment_Reference__c);
        }
        Update paymentSchedules;
    }
    
    public static void onAfterUpdate(List<AcctSeed__Cash_Receipt__c> newList, Map<Id, AcctSeed__Cash_Receipt__c> oldMap){
        Set<String> transactionIds = new Set<String>();
        
        for(AcctSeed__Cash_Receipt__c cr: newList){
            if(oldMap.containsKey(cr.Id)&& String.isNotBlank(cr.AcctSeed__Payment_Reference__c) && oldMap.get(cr.Id).AcctSeed__Void__c == false && cr.AcctSeed__Void__c == true){
                transactionIds.add(cr.AcctSeed__Payment_Reference__c);
            }
        }
        
        
        List<Payment_Schedule__c> paymentSchedules = new List<Payment_Schedule__c>([SELECT Id, Cash_Receipt__c FROM Payment_Schedule__c WHERE Payment_Reference__c IN: transactionIds]);
        for(Payment_Schedule__c ps: paymentSchedules){
            ps.Status__c = 'Rejected';
            ps.Settled_Date__c = null;
            ps.Cash_Receipt__c = null;
            ps.Paid_Amount__c = 0;
        }
        Update paymentSchedules;
    }
}