force-app/main/default/objects/CLE_Attendance__c/CLE_Attendance__c.object-meta.xml
<CustomObject>
    <label>CLE Attendance</label>
    <nameField>
        <displayFormat>CLE-{00000}</displayFormat>
        <label>CLE Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CLE Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLE_Attendance__c/fields/Certificate_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Send_Date__c</fullName>
    <label>Certificate Send Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLE_Attendance__c/fields/CLE_Event__c.field-meta.xml
<CustomField>
    <fullName>CLE_Event__c</fullName>
    <label>CLE Event</label>
    <referenceTo>CLE_Event__c</referenceTo>
    <relationshipLabel>CLE Attendances</relationshipLabel>
    <relationshipName>CLE_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLE_Attendance__c/fields/CLE_Event_Date__c.field-meta.xml
<CustomField>
    <fullName>CLE_Event_Date__c</fullName>
    <label>CLE Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLE_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CLE Attendances</relationshipLabel>
    <relationshipName>CLE_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLE_Event__c/CLE_Event__c.object-meta.xml
<CustomObject>
    <label>CLE Event</label>
    <nameField>
        <label>CLE Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CLE Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SendAttendanceCertificateBatch.cls
global class SendAttendanceCertificateBatch implements Database.Batchable<Sobject>, Database.Stateful{
    
    global String eventId;
    
    global SendAttendanceCertificateBatch(String eventId){
        this.eventId = eventId;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Email__c, CLE_Event__c, CLE_Event_Date__c, Contact__c, Contact__r.Email,Contact__r.FirstName, Contact__r.LastName FROM CLE_Attendance__c WHERE CLE_Event__c=:eventId AND Certificate_Send_Date__c = null';
        return database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<CLE_Attendance__c> attendanceList) {
        List<Messaging.SingleEmailMessage> allMails = new List<Messaging.SingleEmailMessage>();
        List<EmailTemplate> templateList = new List<EmailTemplate>([Select id,Subject,Body,HtmlValue from EmailTemplate where name = 'CLEAttendanceCertificateTemplate']);
        String oweId =[select Id,Address from OrgWideEmailAddress where Address = 'lossprevention@isbamutual.com' LIMIT 1].Id;
        for(CLE_Attendance__c atd: attendanceList){
            List<Messaging.EmailFileAttachment> emailFileAttachments = new List<Messaging.EmailFileAttachment>();
            
            PageReference pg = Page.AttendanceCertificatePdf;
            pg.getParameters().put('id',(String)atd.Id);
            Blob body;
            if(!test.isRunningTest())
                body= pg.getContent();
            else
                body = Blob.valueOf('test');
            
            Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
            efa.body = body;
            String dateString = atd.CLE_Event_Date__c.Month()+'-'+atd.CLE_Event_Date__c.Day()+'-'+String.valueOf(atd.CLE_Event_Date__c.Year()).substring(2, 4);
            efa.fileName = atd.Contact__r.FirstName+' '+atd.Contact__r.LastName+' MCLE '+dateString+'.pdf';
            emailFileAttachments.add(efa);
            
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            Messaging.SingleEmailMessage tempEmail = Messaging.renderStoredEmailTemplate(templateList[0].Id,atd.Contact__c,atd.CLE_Event__c);
            List<String> toAddressList = new List<String>();
            
            if(String.isNotBlank(atd.Contact__r.Email)){
                toAddressList.add(atd.Contact__r.Email);
            }
            if(String.isNotBlank(atd.Email__c)){
                toAddressList.add(atd.Email__c);
            }
            if(!emailFileAttachments.isEmpty()){
                email.setFileAttachments(emailFileAttachments);
            }
            email.setOrgWideEmailAddressId(oweId);
            email.setSubject(tempEmail.getSubject());
            email.setToAddresses(toAddressList);
            String emailBody = String.valueOf(tempEmail.getHtmlBody());
            email.setHtmlBody(emailBody);
            allMails.add(email);
        }
        
        if(!allMails.isEmpty()){
            Messaging.SendEmailResult [] r = Messaging.sendEmail(allMails,false);
            for(CLE_Attendance__c atd: attendanceList){
                atd.Certificate_Send_Date__c = system.today();
            }
            Update attendanceList;
        }
    }
    global void finish(Database.BatchableContext BC) { 
    }
}