force-app/main/default/objects/CLE_Attendance__c/CLE_Attendance__c.object-meta.xml
<CustomObject>
    <label>CLE Attendance</label>
    <nameField>
        <displayFormat>CLE-{00000}</displayFormat>
        <label>CLE Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CLE Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLE_Attendance__c/fields/CLE_Event__c.field-meta.xml
<CustomField>
    <fullName>CLE_Event__c</fullName>
    <label>CLE Event</label>
    <referenceTo>CLE_Event__c</referenceTo>
    <relationshipLabel>CLE Attendances</relationshipLabel>
    <relationshipName>CLE_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLE_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CLE Attendances</relationshipLabel>
    <relationshipName>CLE_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLE_Event__c/CLE_Event__c.object-meta.xml
<CustomObject>
    <label>CLE Event</label>
    <nameField>
        <label>CLE Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CLE Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SendAttendanceCertificateCtrlTest.cls
@isTest
public class SendAttendanceCertificateCtrlTest {
    @isTest
    public static void testmethod1(){
        CLE_Event__c e= new CLE_Event__c();
        e.Name = 'test';
        e.Date__c = system.today();
        Insert e;
        
        Account acc                   = TestDataFactory.createAccounts('Dummy Billing Account');
        acc.AccountNumber             = '123456';
        acc.Vendor_Account__c         = true;
        acc.Payment_Link_Activation_Started_at__c = system.today();
        insert acc;
        
        Contact con = new Contact(
            FirstName = 'APPROVED',
            LastName = 'TEST',
            AccountId = acc.Id,
            Email = 'test@Cmentor.com'
        );
        Insert con;
        
        CLE_Attendance__c attendee = new CLE_Attendance__c();
        attendee.CLE_Event__c = e.Id;
        attendee.Contact__c = con.Id;
        Insert attendee;
			
        SendAttendanceCertificateCtrl.callBatch(e.Id);
        PageReference pageRef = Page.AttendanceCertificatePdf;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('id',attendee.Id);
        AttendanceCertificatePdfController cls = new AttendanceCertificatePdfController();
    }
}