force-app/main/default/objects/CLE_Attendance__c/CLE_Attendance__c.object-meta.xml
<CustomObject>
    <label>CLE Attendance</label>
    <nameField>
        <displayFormat>CLE-{00000}</displayFormat>
        <label>CLE Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CLE Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLE_Attendance__c/fields/CLE_Event__c.field-meta.xml
<CustomField>
    <fullName>CLE_Event__c</fullName>
    <label>CLE Event</label>
    <referenceTo>CLE_Event__c</referenceTo>
    <relationshipLabel>CLE Attendances</relationshipLabel>
    <relationshipName>CLE_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLE_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CLE Attendances</relationshipLabel>
    <relationshipName>CLE_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLE_Event__c/CLE_Event__c.object-meta.xml
<CustomObject>
    <label>CLE Event</label>
    <nameField>
        <label>CLE Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CLE Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Account_CLE_AttendancesCtrl.cls
public class Account_CLE_AttendancesCtrl {
	@AuraEnabled
    public static Wrapper getCLE_Attendances(String recId){
        Wrapper wrap = new Wrapper();
        system.debug(recId);
        List<CLE_Attendance__c> cleAttendees = new List<CLE_Attendance__c>();
        List<AccountContactRelation> accConRelations = new List<AccountContactRelation>([SELECT Id, ContactId, Account.Name FROM AccountContactRelation WHERE AccountId =: recId]);
        if(!accConRelations.isEmpty()){
            Set<String> conIds = new Set<String>();
            for(AccountContactRelation acr: accConRelations){
                conIds.add(acr.ContactId);
            }
            wrap.recName = accConRelations[0].Account.Name;
            
            system.debug(conIds);
            cleAttendees = [SELECT Id, Name, Contact__c, Contact__r.Name, CLE_Event__c, CLE_Event__r.Name,CLE_Event__r.Hours__c, CLE_Event__r.Date__c FROM CLE_Attendance__c WHERE Contact__c IN: conIds];
        }
        wrap.cleAttendees = cleAttendees;
        return wrap;
    }
    public Class Wrapper{
        @AuraEnabled public string recName{get;set;}
        @AuraEnabled public List<CLE_Attendance__c> cleAttendees{get;set;}
    }
}