force-app/main/default/objects/CLE_Attendance__c/CLE_Attendance__c.object-meta.xml
<CustomObject>
    <label>CLE Attendance</label>
    <nameField>
        <displayFormat>CLE-{00000}</displayFormat>
        <label>CLE Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CLE Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLE_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CLE Attendances</relationshipLabel>
    <relationshipName>CLE_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLE_Attendance__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <formula>CLE_Event__r.Date__c</formula>
    <label>Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLE_Attendance__c/fields/Event_Hours__c.field-meta.xml
<CustomField>
    <fullName>Event_Hours__c</fullName>
    <formula>CLE_Event__r.Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLE_Attendance__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>CLE Attendances</relationshipLabel>
    <relationshipName>CLE_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandler.cls
public class LeadTriggerHandler{
    public static void onAfterUpdate(List<Lead> newList){
        Set<Id> convertedContactId = new Set<Id>();
        Map<String, String> leadWithConIdMap = new Map<String, String>();
        for(Lead objLead : newList) {
            if(objLead.IsConverted){
                convertedContactId.add(objLead.ConvertedContactId);
                leadWithConIdMap.put(objLead.Id, objLead.ConvertedContactId);
            }   
        }
        
        ID accountId = [select id,name from Account where name =: Label.Bucket_Account limit 1].id;
        List<Contact> conList = [select id,AccountId from contact where id in : convertedContactId];
        system.debug('conList'+conList);
        For(Contact con : conList) {
            con.AccountId = accountId;
        }
        
        List<CLE_Attendance__c> attenedanceList = [SELECT Id, Lead__c, Contact__c, Event_Hours__c, Event_Date__c FROM CLE_Attendance__c WHERE Lead__c IN: leadWithConIdMap.keySet() AND Contact__c = null];
        system.debug('attenedanceList => '+attenedanceList);
        
        if(!attenedanceList.isEmpty()){
            for(CLE_Attendance__c att: attenedanceList){
                att.Contact__c = leadWithConIdMap.get(att.Lead__c);
            }
            
            Update attenedanceList;
            CLEAttendanceTriggerHandler.updateLawyersCredit(attenedanceList);
        }
        
        if(! conList.isEmpty()) {
            update conList;
        }
    }
}