force-app/main/default/objects/CLE_Attendance__c/CLE_Attendance__c.object-meta.xml
<CustomObject>
    <label>CLE Attendance</label>
    <nameField>
        <displayFormat>CLE-{00000}</displayFormat>
        <label>CLE Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CLE Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLE_Attendance__c/fields/Attorney_Attended__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Attended__c</fullName>
    <formula>IF( CLE_Event__r.General_Credit__c ==  General_Credit__c , &quot;Entire Course Attendance&quot;, &quot;Partial Course Attendance (only actual attendance or participation earns credits)&quot;)</formula>
    <label>Attorney Attended</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLE_Attendance__c/fields/CLE_Event__c.field-meta.xml
<CustomField>
    <fullName>CLE_Event__c</fullName>
    <label>CLE Event</label>
    <referenceTo>CLE_Event__c</referenceTo>
    <relationshipLabel>CLE Attendances</relationshipLabel>
    <relationshipName>CLE_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLE_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CLE Attendances</relationshipLabel>
    <relationshipName>CLE_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLE_Attendance__c/fields/General_Credit__c.field-meta.xml
<CustomField>
    <fullName>General_Credit__c</fullName>
    <description>CLE General Credit</description>
    <inlineHelpText>CLE General Credit</inlineHelpText>
    <label>General Credit</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLE_Attendance__c/fields/Lawyer_Participation_Method__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Participation_Method__c</fullName>
    <label>Lawyer Participation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LVA</fullName>
                <label>Live - Technology</label>
            </value>
            <value>
                <fullName>FIRWP</fullName>
                <label>Faculty in room with participants</label>
            </value>
            <value>
                <fullName>RVA</fullName>
                <label>Recorded - Technology</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLE_Event__c/CLE_Event__c.object-meta.xml
<CustomObject>
    <label>CLE Event</label>
    <nameField>
        <label>CLE Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CLE Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLE_Event__c/fields/Event_Location__c.field-meta.xml
<CustomField>
    <fullName>Event_Location__c</fullName>
    <label>Event Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLE_Event__c/fields/General_Credit__c.field-meta.xml
<CustomField>
    <fullName>General_Credit__c</fullName>
    <label>General Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLE_Event__c/fields/PR_DIV__c.field-meta.xml
<CustomField>
    <fullName>PR_DIV__c</fullName>
    <label>PR DIV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLE_Event__c/fields/PR_MHSA__c.field-meta.xml
<CustomField>
    <fullName>PR_MHSA__c</fullName>
    <label>PR MHSA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLE_Event__c/fields/PR_OTHER__c.field-meta.xml
<CustomField>
    <fullName>PR_OTHER__c</fullName>
    <label>PR OTHER</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AttendanceCertificatePdfController.cls
public class AttendanceCertificatePdfController {
    
    
    public decimal PR_MHSA{get;Set;}
	public decimal PR_DIV{get;Set;}
    public decimal PR_OTHER{get;Set;}
    public decimal PR_Total{get;Set;}
    public decimal General_Credit{get;Set;}
    
    public CLE_Attendance__c attendance{get;set;}
    
    public AttendanceCertificatePdfController(){
        String recId = '';
        if(Apexpages.currentpage().getparameters().get('id') != null){
            recId = Apexpages.currentpage().getparameters().get('id');
            system.debug('recId => '+recId);
        }
        
        if(String.isNotBlank(recId)){
            List<CLE_Attendance__c> CLE_AttList = new List<CLE_Attendance__c>([SELECT Id,CLE_Event__c,CLE_Event__r.General_Credit__c,CLE_Event__r.Event_Title__c,CLE_Event__r.Event_Location__c,CLE_Event__r.Date__c,PR_OTHER__c,PR_MHSA__c,PR_DIV__c,General_Credit__c,Lawyer_Participation_Method__c,Attorney_Attended__c,Contact__r.Name, Contact__r.ARDC_Number__c FROM CLE_Attendance__c WHERE Id=: recId limit 1]);
            attendance = new CLE_Attendance__c();
            if(!CLE_AttList.isEmpty()){
                attendance = CLE_AttList[0];
            }
            General_Credit = CLE_AttList[0].General_Credit__c != null ? CLE_AttList[0].General_Credit__c : 0.00;
            PR_MHSA = CLE_AttList[0].PR_MHSA__c != null ? CLE_AttList[0].PR_MHSA__c : 0.00;
            PR_DIV = CLE_AttList[0].PR_DIV__c != null ? CLE_AttList[0].PR_DIV__c : 0.00;
            PR_OTHER = CLE_AttList[0].PR_OTHER__c != null ? CLE_AttList[0].PR_OTHER__c : 0.00;
            PR_Total = PR_MHSA + PR_DIV + PR_OTHER;
            
            system.debug('attendance => '+attendance);
        }
    }

}