force-app/main/default/objects/AS_Transaction__c/AS_Transaction__c.object-meta.xml
<CustomObject>
    <description>This is the intermediate object that will hold the entries for Accounting Seed.</description>
    <label>AS_Transaction</label>
    <nameField>
        <displayFormat>AST-{0000000}</displayFormat>
        <label>AS_Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AS_Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AS_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>This value hold the Amount that is to be transacted based on the transaction type.</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AS_Transaction__c/fields/Claim_Id__c.field-meta.xml
<CustomField>
    <fullName>Claim_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field holds the reference for the claim record that the transaction belongs to.</description>
    <label>Claim Id</label>
    <referenceTo>Policy_Claim__c</referenceTo>
    <relationshipLabel>AS_Transactions</relationshipLabel>
    <relationshipName>AS_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AS_Transaction__c/fields/Firm_Id__c.field-meta.xml
<CustomField>
    <fullName>Firm_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field holds the reference to the Firm that transaction belongs to.</description>
    <label>Firm Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AS_Transactions</relationshipLabel>
    <relationshipName>AS_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AS_Transaction__c/fields/GL_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Name__c</fullName>
    <label>GL Account Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AS_Transaction__c/fields/Policy_Claim_Detail__c.field-meta.xml
<CustomField>
    <fullName>Policy_Claim_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy Claim Detail</label>
    <referenceTo>Policy_Claim_Detail__c</referenceTo>
    <relationshipLabel>AS_Transactions</relationshipLabel>
    <relationshipName>AS_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AS_Transaction__c/fields/Policy_Id__c.field-meta.xml
<CustomField>
    <fullName>Policy_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference of the Policy that the transactions belongs to.</description>
    <label>Policy Id</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>AS_Transactions</relationshipLabel>
    <relationshipName>AS_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AS_Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>This field is to identify the transaction type, it is the parent field of the transaction sub type field that is used to identify sub types in the claim transactions.</description>
    <label>Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add Lawyer</fullName>
            </value>
            <value>
                <fullName>Cancel Policy</fullName>
            </value>
            <value>
                <fullName>Change Coverage</fullName>
            </value>
            <value>
                <fullName>Change Lawyer</fullName>
            </value>
            <value>
                <fullName>Close Reserve</fullName>
            </value>
            <value>
                <fullName>Deductible Expense</fullName>
            </value>
            <value>
                <fullName>Delete Lawyer</fullName>
            </value>
            <value>
                <fullName>ERE</fullName>
            </value>
            <value>
                <fullName>LAE Payment</fullName>
            </value>
            <value>
                <fullName>Loss Payment</fullName>
            </value>
            <value>
                <fullName>Open Reserve</fullName>
            </value>
            <value>
                <fullName>Reinstate Policy</fullName>
            </value>
            <value>
                <fullName>Reopen Reserve</fullName>
            </value>
            <value>
                <fullName>User Reserve</fullName>
                <label>Change Reserve</label>
            </value>
            <value>
                <fullName>Deductible Loss</fullName>
            </value>
            <value>
                <fullName>Change in Ceded LAE Reserve</fullName>
            </value>
            <value>
                <fullName>Change in Ceded Loss Reserve</fullName>
            </value>
            <value>
                <fullName>Due from Reins. - LAE</fullName>
            </value>
            <value>
                <fullName>Due from Reins. - Loss</fullName>
            </value>
            <value>
                <fullName>Claim Coverage - ARDC</fullName>
            </value>
            <value>
                <fullName>Issue Policy</fullName>
            </value>
            <value>
                <fullName>Adjust Premium</fullName>
            </value>
            <value>
                <fullName>Unallocated LAE Payment</fullName>
            </value>
            <value>
                <fullName>Deductible Expense New</fullName>
            </value>
            <value>
                <fullName>Cash Payment</fullName>
                <isActive>false</isActive>
                <label>Cash Payment</label>
            </value>
            <value>
                <fullName>Claim Coverage - Memo</fullName>
                <isActive>false</isActive>
                <label>Claim Coverage - Memo</label>
            </value>
            <value>
                <fullName>Claims Coverage</fullName>
                <isActive>false</isActive>
                <label>Claims Coverage</label>
            </value>
            <value>
                <fullName>New Policy</fullName>
                <isActive>false</isActive>
                <label>New Policy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Id__c.field-meta.xml
<CustomField>
    <fullName>Claim_Id__c</fullName>
    <externalId>true</externalId>
    <label>Claim Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Deductible_LAE_Applied_Limit__c.field-meta.xml
<CustomField>
    <fullName>Deductible_LAE_Applied_Limit__c</fullName>
    <label>Deductible LAE Applied Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Deductible_LAE_Applied_Limit_Consumed__c.field-meta.xml
<CustomField>
    <fullName>Deductible_LAE_Applied_Limit_Consumed__c</fullName>
    <label>Deductible LAE Applied Limit Consumed</label>
    <summarizedField>Policy_Claim_Detail__c.LAE_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Claim_Detail__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Deductible</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Policy_Claim_Detail__c.Type__c</field>
        <operation>equals</operation>
        <value>Deductible Expense New</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Claim_Detail__c.Policy_Claim__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5001__c.field-meta.xml
<CustomField>
    <fullName>GL_5001__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5001</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5030__c.field-meta.xml
<CustomField>
    <fullName>GL_5030__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5030</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/GL_5031__c.field-meta.xml
<CustomField>
    <fullName>GL_5031__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GL 5031</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Per_Claim_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Per_Claim_Deductible__c</fullName>
    <label>Per Claim Deductible</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/Policy_Claim_Detail__c.object-meta.xml
<CustomObject>
    <label>Policy Claim Detail</label>
    <nameField>
        <displayFormat>Claim-{0000000}</displayFormat>
        <label>Claim Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Claims Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <formula>Policy_Claim__r.Policy__r.Account__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/LAE_Amount__c.field-meta.xml
<CustomField>
    <fullName>LAE_Amount__c</fullName>
    <label>LAE Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Loss_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loss_Amount__c</fullName>
    <label>Loss Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Policy_Claim__c.field-meta.xml
<CustomField>
    <fullName>Policy_Claim__c</fullName>
    <label>Policy Claim</label>
    <referenceTo>Policy_Claim__c</referenceTo>
    <relationshipLabel>Claims Detail</relationshipLabel>
    <relationshipName>Policy_Claims_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Policy_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Policy_Record_ID__c</fullName>
    <formula>Policy_Claim__r.Policy__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Record ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Total_Deductible_Used__c.field-meta.xml
<CustomField>
    <fullName>Total_Deductible_Used__c</fullName>
    <label>Total Deductible Used</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reserve_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>equals</operation>
            <value>Vendor, Customer and Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policy Claims Detail</relationshipLabel>
    <relationshipName>Policy_Claims_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Claim_Detail__c/recordTypes/Deductible.recordType-meta.xml
<RecordType>
    <fullName>Deductible</fullName>
    <active>true</active>
    <description>1) Allocate Deductible Loss/LAE. 2) Cash Received / Write-off against Deductible.</description>
    <label>Deductible</label>
</RecordType>

force-app/main/default/objects/Policy_Claim_Detail__c/recordTypes/Reinsurance.recordType-meta.xml
<RecordType>
    <fullName>Reinsurance</fullName>
    <active>true</active>
    <description>1) Create Due from Reinsurance Loss/LAE. 2) Change in Ceded Reserve for Loss/LAE.</description>
    <label>Reinsurance</label>
</RecordType>

force-app/main/default/objects/Policy_Claim_Detail__c/recordTypes/Reserve.recordType-meta.xml
<RecordType>
    <fullName>Reserve</fullName>
    <active>true</active>
    <description>1) Increase Reserve(User Reserve)  2) Close/Re-Open Reserve</description>
    <label>Reserve</label>
</RecordType>

force-app/main/default/globalValueSets/Reserve_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>User Reserve</fullName>
        <label>Change Reserve</label>
    </customValue>
    <customValue>
        <fullName>Close Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Reopen Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Loss Payment</fullName>
    </customValue>
    <customValue>
        <fullName>LAE Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Deductible Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Deductible Expense</fullName>
    </customValue>
    <customValue>
        <fullName>Change in Ceded Loss Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Change in Ceded LAE Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Due from Reins. - Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Due from Reins. - LAE</fullName>
    </customValue>
    <customValue>
        <fullName>Open Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Claim Coverage - ARDC</fullName>
        <label>ARDC Payment</label>
    </customValue>
    <customValue>
        <fullName>Unallocated LAE Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Deductible Expense New</fullName>
    </customValue>
    <customValue>
        <fullName>SBL</fullName>
    </customValue>
    <customValue>
        <fullName>CPSBL</fullName>
    </customValue>
    <customValue>
        <fullName>CPSBE</fullName>
    </customValue>
    <masterLabel>Reserve Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Policy_Claim_Detail_Gateway.cls
public class Policy_Claim_Detail_Gateway {
/*
//Created By	: 	Shoukat Hussain
//Created Date	: 	12/28/2016
//Purpose		: 	Create Accounting Seeds Transaction
//				:	Create Auto Dedcutible entries
*/

    
    // Public static record type
    public static ID ReserveRTID 	= Schema.SObjectType.Policy_Claim_Detail__C.getRecordTypeInfosByName().get('Reserve').getRecordTypeId();
    public static ID DeductibleRTID = Schema.SObjectType.Policy_Claim_Detail__C.getRecordTypeInfosByName().get('Deductible').getRecordTypeId();

    public static void CreateAutoDedcutibleRecord(list<Policy_Claim_Detail__c> PCDData){
        Set<ID> PolicyClaimID = new Set<ID>();
        List<Policy_Claim_Detail__c> PolicyClaimDtlLst = new List<Policy_Claim_Detail__c>();
        List<Policy_Claim_Detail__c> PolicyClaimDtlLstToUpdate = new List<Policy_Claim_Detail__c>();
        // map are for maintain or get information from master claim 
        Map<ID,Decimal> PerClaimDeductible_Map = new Map<ID,Decimal>();
        Map<ID,Decimal> PerClaimDeductibleConsumed_Map = new Map<ID,Decimal>();
        Map<ID,Decimal> DedLAEAppliedISBALimit_Map = new Map<ID,Decimal>();        
        Map<ID,Decimal> DedLAEAppliedISBALimitConsumed_Map =  new Map<ID,Decimal>();
        Map<Id,Policy_Claim__c> claimMap = new Map<Id,Policy_Claim__c>();
        List<Policy_Claim__c> PolicyClaim_Lst = new List<Policy_Claim__c>();
		
        For(Policy_Claim_Detail__c PCDLoop : PCDData){
            PolicyClaimID.add(PCDLoop.Policy_Claim__c);
        }
        
        //Get LAE/Loss Consumed amount and put into Map
        If(PolicyClaimID.size()>0){
            PolicyClaim_Lst = [select ID,Per_Claim_Deductible__c,GL_5031__c,GL_5001__c,GL_5030__c,
                               Deductible_LAE_Applied_Limit__c,Deductible_LAE_Applied_Limit_Consumed__c 
                               from Policy_Claim__C where ID in :PolicyClaimID];
            If(PolicyClaim_Lst.size()>0){
                For(Policy_Claim__c PCdata :PolicyClaim_Lst){
                    PerClaimDeductible_Map.put(PCdata.ID, PCdata.Per_Claim_Deductible__c);
                    PerClaimDeductibleConsumed_Map.put(PCdata.ID,PCdata.GL_5031__c+PCdata.GL_5001__c);
                    //DedLAEAppliedISBALimit_Map.put(PCdata.ID,PCdata.Deductible_LAE_Applied_Limit__c);
                    DedLAEAppliedISBALimit_Map.put(PCdata.ID,Math.abs(PCdata.GL_5030__c));
                    DedLAEAppliedISBALimitConsumed_Map.put(PCdata.ID,PCdata.Deductible_LAE_Applied_Limit_Consumed__c);
                    claimMap.put(PCdata.ID,PCdata);
                }
            }
        }

        // Create Auto record 
        For(Policy_Claim_Detail__c PCDDataLoop : PCDData){  
            System.debug('$1Policy_Claim__c)'+PerClaimDeductible_Map.get(PCDDataLoop.Policy_Claim__c));
             System.debug('$2Policy_Claim__c)'+ PerClaimDeductibleConsumed_Map.get(PCDDataLoop.Policy_Claim__c));
            Decimal PerClaimDedBalance 		=  PerClaimDeductible_Map.get(PCDDataLoop.Policy_Claim__c)  - PerClaimDeductibleConsumed_Map.get(PCDDataLoop.Policy_Claim__c) ;
            Decimal DedAppliedLAEBalance  	=  DedLAEAppliedISBALimit_Map.get(PCDDataLoop.Policy_Claim__c)  - claimMap.get(PCDDataLoop.Policy_Claim__c).GL_5031__c;
            if(DedAppliedLAEBalance < 0){
                DedAppliedLAEBalance = 0;
            }
            Decimal Loss_Amt_2b_CreateRcd = 0;
            Decimal LAE_Amt_2b_CreateRcd = 0;
            Decimal LAE_AmtISBAExp_2b_CreateRcd = 0;
            // In case of Loss payment auto deductible record will be generate with respect to " balance available"
            // In case balance available then create record auto, otherwise we can not create auto record 
            If(PCDDataLoop.Type__c=='Loss Payment'){                
                If(PerClaimDedBalance > 0){ 
                    System.debug('PerClaimDedBalance---'+PerClaimDedBalance);
                    // incase balance is enough for payment then fully amount will be deductible.
                    If(PerClaimDedBalance >= PCDDataLoop.Loss_Amount__c) {
                        Loss_Amt_2b_CreateRcd =   PCDDataLoop.Loss_Amount__c;
                    System.debug('@If--Loss_Amt_2b_CreateRcd=====>'+Loss_Amt_2b_CreateRcd);     
                    }
                    // incase balance is not enough for payment then available amount will be deductible.
                    Else If(PerClaimDedBalance < PCDDataLoop.Loss_Amount__c){
                        Loss_Amt_2b_CreateRcd =   PerClaimDedBalance;  
                        System.debug('@Else--Loss_Amt_2b_CreateRcd=====>'+Loss_Amt_2b_CreateRcd);
                    }
                    Else{
                        //nothing
                    }                    
                    // Update Map for consumed and Create Entry for deductible
                    If (Loss_Amt_2b_CreateRcd<>0){
                        System.debug('@Loss_Amt_2b_CreateRcd=====>'+Loss_Amt_2b_CreateRcd);
                        PerClaimDeductibleConsumed_Map.put(PCDDataLoop.Policy_Claim__c, PerClaimDeductibleConsumed_Map.get(PCDDataLoop.Policy_Claim__c) + Loss_Amt_2b_CreateRcd);
                        // Create Entry For Loss                        
                        PolicyClaimDtlLst.add(  new Policy_Claim_Detail__c(
                                                    Policy_Claim__c = PCDDataLoop.Policy_claim__c,
                                                    Loss_Amount__c	= Loss_Amt_2b_CreateRcd,
                                                    Date__c			= PCDDataLoop.Date__c,
                                                    Type__c			= 'Deductible Loss',
                                                    RecordTypeId	=  DeductibleRTID) );
                        
                        PolicyClaimDtlLstToUpdate.add(new Policy_Claim_Detail__c(
                                                    Id = PCDDataLoop.Id,
                                                    Total_Deductible_Used__c	= Loss_Amt_2b_CreateRcd) );

                   	}
                }                
            } 

            // In case of LAE payment auto deductible record will be generate with respect to " balance available"
            // In case balance available then create record auto, otherwise we can not create auto record 
            If(PCDDataLoop.Type__c=='LAE Payment'){                
                // Incase not balance is available in DeductibleLAEIBSABalance then system will use Per claim deductible balance
                system.debug('AutoDed DedAppliedLAEBalance : '+DedAppliedLAEBalance);
                If(DedAppliedLAEBalance >= 0){ 
                     system.debug('AutoDed DedAppliedLAEBalance>=0 : '+DedAppliedLAEBalance);
                    // incase balance is enough for payment then fully amount will be deductible.
                    If(DedAppliedLAEBalance >= PCDDataLoop.LAE_Amount__c) {
                        LAE_AmtISBAExp_2b_CreateRcd =   PCDDataLoop.LAE_Amount__c;
                        // Update Map and create entry
                        DedLAEAppliedISBALimit_Map.put(PCDDataLoop.Policy_Claim__c, DedLAEAppliedISBALimit_Map.get(PCDDataLoop.Policy_Claim__c) + LAE_AmtISBAExp_2b_CreateRcd);
                        // Create Entry For LAE                        
                        PolicyClaimDtlLst.add(  new Policy_Claim_Detail__c(
                            Policy_Claim__c = PCDDataLoop.Policy_claim__c,
                            LAE_Amount__c	= LAE_AmtISBAExp_2b_CreateRcd,
                            Date__c			= PCDDataLoop.Date__c,
                            Type__c			= 'Deductible Expense New',
                            RecordTypeId	=  DeductibleRTID) );
                        
                    }
                    // incase balance is not enough for payment then available amount will be deductible.
                    Else If(DedAppliedLAEBalance < PCDDataLoop.LAE_Amount__c){
                        system.debug('AutoDed DedAppliedLAEBalance<lae amt : '+PCDDataLoop.LAE_Amount__c);
                        LAE_AmtISBAExp_2b_CreateRcd =   DedAppliedLAEBalance;
                        // Update Map for consumed and Create Entry for deductible
                        If (LAE_AmtISBAExp_2b_CreateRcd<>0){
                            DedLAEAppliedISBALimit_Map.put(PCDDataLoop.Policy_Claim__c, DedLAEAppliedISBALimit_Map.get(PCDDataLoop.Policy_Claim__c) + LAE_AmtISBAExp_2b_CreateRcd);
                            // Create Entry For LAE                        
                            PolicyClaimDtlLst.add(  new Policy_Claim_Detail__c(
                                Policy_Claim__c = PCDDataLoop.Policy_claim__c,
                                LAE_Amount__c	= LAE_AmtISBAExp_2b_CreateRcd,
                                Date__c			= PCDDataLoop.Date__c,
                                Type__c			= 'Deductible Expense New',
                                RecordTypeId	=  DeductibleRTID) );
                        }

                        // Get further payment amount by ISBA 
                        Decimal  RemLAEAmt_2b_pay = PCDDataLoop.LAE_Amount__c - LAE_AmtISBAExp_2b_CreateRcd;
                        system.debug('AutoDed RemLAEAmt_2b_pay : '+RemLAEAmt_2b_pay);
                        ///////////////////                        
                        // Incase balance is not available in DeductibleLAEIBSABalance then system will use Per claim deductible balance
                        system.debug('AutoDed1 PerClaimDedBalance>0 : '+PerClaimDedBalance);
                        If(PerClaimDedBalance > 0){                             
                            // incase balance is enough for payment then fully amount will be deductible.
                            system.debug('AutoDed2 PerClaimDedBalance>=RemLAEAmt_2b_pay : '+RemLAEAmt_2b_pay);
                            If(PerClaimDedBalance >= RemLAEAmt_2b_pay) {
                                system.debug('AutoDed3 PerClaimDedBalance>0 : '+PerClaimDedBalance);
                                LAE_Amt_2b_CreateRcd =   RemLAEAmt_2b_pay;
                            }
                            // incase balance is not enough for payment then available amount will be deductible.                            
                            Else If(PerClaimDedBalance < RemLAEAmt_2b_pay){
                                system.debug('AutoDed4 PerClaimDedBalance < RemLAEAmt_2b_pay : '+ RemLAEAmt_2b_pay);
                                LAE_Amt_2b_CreateRcd =   PerClaimDedBalance;   
                            }
                            Else{
                                //nothing
                                system.debug('AutoDed5');
                            }                    
                            // Update Map for consumed and Create Entry for deductible
                            If (LAE_Amt_2b_CreateRcd<>0){
                                PerClaimDeductibleConsumed_Map.put(PCDDataLoop.Policy_Claim__c, PerClaimDeductibleConsumed_Map.get(PCDDataLoop.Policy_Claim__c) + LAE_Amt_2b_CreateRcd);
                                // Create Entry For LAE                        
                                PolicyClaimDtlLst.add(  new Policy_Claim_Detail__c(
                                    Policy_Claim__c = PCDDataLoop.Policy_claim__c,
                                    LAE_Amount__c	= LAE_Amt_2b_CreateRcd,
                                    Date__c			= PCDDataLoop.Date__c,
                                    Type__c			= 'Deductible Expense',
                                    RecordTypeId	=  DeductibleRTID) );
                            }
                        }                
						
                    }
                }                
            }
            
            
        }     
        
        // Create Auto Record
            if(PolicyClaimDtlLst.size()>0){  
                System.debug('#PolicyClaimDtlLst===>'+PolicyClaimDtlLst);
             Insert(PolicyClaimDtlLst);
            }
        if(PolicyClaimDtlLstToUpdate.size()>0){
            update PolicyClaimDtlLstToUpdate;
        }     
   /*     
        Try{
            if(PolicyClaimDtlLst.size()>0){
             //Database.insert(PolicyClaimDtlLst);             
             Insert(PolicyClaimDtlLst);
            }
        }
        Catch(system.DmlException e){       	
            system.debug('Error: '+e.getMessage());
        }
*/
        
        
  }
        
    public static AS_Transaction__c Initiate_AS_entry(Policy_Claim_Detail__c PCDEntry){
         AS_Transaction__c AS_SingleEntry = new AS_Transaction__c();
        If(PCDEntry.Vendor__c!=null){
            AS_SingleEntry.Firm_Id__c = PCDEntry.Vendor__c;
        }
        Else{
            AS_SingleEntry.Firm_Id__c = PCDEntry.Account_ID__c;
        }

         AS_SingleEntry.Policy_Claim_Detail__c 	= PCDEntry.Id;
         AS_SingleEntry.Policy_Id__c 			= PCDEntry.Policy_record_id__c;
         AS_SingleEntry.Transaction_Type__c 	= PCDEntry.Type__c;
         AS_SingleEntry.Invoice_Number__c 		= PCDEntry.Invoice_Number__c;
         AS_SingleEntry.Claim_Id__c 			= PCDEntry.Policy_Claim__c;
        AS_SingleEntry.GL_Account_Name__c 			= PCDEntry.GL_Account_Name__c;

        Return AS_SingleEntry;
    }
    
    public static void CreateAccountingSeedsTransaction(list<Policy_Claim_Detail__c> PCDData){
      system.debug('CreateAccountingSeedsTransaction start procedure'+PCDData);
      List<AS_Transaction__c> lstASTransaction = new List<AS_Transaction__c>();
      For(Policy_Claim_Detail__C PCDLoopData : PCDData) {     
            //Initial object for Account Seeds (AS) 
            AS_Transaction__c asTransaction = new AS_Transaction__c(); 

            // Set AS transaction as per Claim File type and Claim detail type
            System.debug('PCDLoopData.Type__c;===>'+PCDLoopData.Type__c);
          System.debug('PCDLoopData.Loss_Amount__c;===>'+PCDLoopData.Loss_Amount__c);
            // Claim File Type "Reserve"
            If  (PCDLoopData.Type__c=='Open Reserve'){
               // no need "if condition" becuase open reserve should be create as per FW+ (Framework)
                               
               asTransaction = Initiate_AS_entry(PCDLoopData);           
               asTransaction.Transaction_Sub_Type__c = 'Open Reserve LAE';
               asTransaction.Amount__c = PCDLoopData.LAE_Amount__c;
               lstASTransaction.add(asTransaction);
               asTransaction = Initiate_AS_entry(PCDLoopData);            
               asTransaction.Transaction_Sub_Type__c = 'Open Reserve Loss';                
               asTransaction.Amount__c = PCDLoopData.Loss_Amount__c;
               lstASTransaction.add(asTransaction);     
               
            }Else if(PCDLoopData.Type__c=='User Reserve'){
               If(PCDLoopData.LAE_Amount__c!=null){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'User Reserve LAE';                
                    asTransaction.Amount__c = PCDLoopData.LAE_Amount__c;
                    lstASTransaction.add(asTransaction);                               
               }
               If(PCDLoopData.Loss_Amount__c!=null){

                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'User Reserve Loss';                
                    asTransaction.Amount__c = PCDLoopData.Loss_Amount__c;
                    lstASTransaction.add(asTransaction);                               
               }

            }Else if(PCDLoopData.Type__c=='Close Reserve'){

               If(PCDLoopData.LAE_Amount__c!=null){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'Close Reserve LAE';                
                    asTransaction.Amount__c = PCDLoopData.LAE_Amount__c;
                    lstASTransaction.add(asTransaction);                               
               }
               If(PCDLoopData.Loss_Amount__c!=null){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'Close Reserve Loss';                
                    asTransaction.Amount__c = PCDLoopData.Loss_Amount__c;
                    lstASTransaction.add(asTransaction);                               
               }

            }Else if(PCDLoopData.Type__c=='Reopen Reserve'){

               If(PCDLoopData.LAE_Amount__c!=null){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'Re-Open Reserve LAE';                
                    asTransaction.Amount__c = PCDLoopData.LAE_Amount__c;
                    lstASTransaction.add(asTransaction);                               
               }
               If(PCDLoopData.Loss_Amount__c!=null){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'Re-Open Reserve Loss';                
                    asTransaction.Amount__c = PCDLoopData.Loss_Amount__c;
                    lstASTransaction.add(asTransaction);                               
               }
                
            // Claim File Type "Claim Payment"
            }Else if(PCDLoopData.Type__c=='LAE Payment'){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = PCDLoopData.Type__c;                
                    asTransaction.Amount__c = PCDLoopData.LAE_Amount__c;
                    lstASTransaction.add(asTransaction);                               
                
            }Else if(PCDLoopData.Type__c=='Loss Payment'){
                asTransaction = Initiate_AS_entry(PCDLoopData);            
                asTransaction.Transaction_Sub_Type__c = PCDLoopData.Type__c;                
                asTransaction.Amount__c = PCDLoopData.Loss_Amount__c;
                lstASTransaction.add(asTransaction);                               

            }Else if(PCDLoopData.Type__c=='Deductible Expense'){
                asTransaction = Initiate_AS_entry(PCDLoopData);            
                asTransaction.Transaction_Sub_Type__c = 'LAE Deductible';                
                asTransaction.Amount__c = PCDLoopData.LAE_Amount__c;
                lstASTransaction.add(asTransaction);                               
            }Else if(PCDLoopData.Type__c=='Deductible Expense New'){
                asTransaction = Initiate_AS_entry(PCDLoopData);            
                asTransaction.Transaction_Sub_Type__c = 'Deductible Expense New';                
                asTransaction.Amount__c = PCDLoopData.LAE_Amount__c;
                lstASTransaction.add(asTransaction);                               
            }Else if(PCDLoopData.Type__c=='Deductible Loss'){
                asTransaction = Initiate_AS_entry(PCDLoopData);            
                asTransaction.Transaction_Sub_Type__c = 'Loss Deductible';                
                asTransaction.Amount__c = PCDLoopData.Loss_Amount__c;
                lstASTransaction.add(asTransaction);                               
            }
          /*  
          Else if(PCDLoopData.Type__c=='Cash Payment'){
                If(PCDLoopData.Reimburse_Amount__c!=null){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'The PrivateBank-Main';                
                    asTransaction.Amount__c = PCDLoopData.Reimburse_Amount__c;
                    lstASTransaction.add(asTransaction);                               
                    
                }
                Else if(PCDLoopData.Write_Off_Amount__c!=null){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'Other Income/Expense';                
                    asTransaction.Amount__c = PCDLoopData.Write_Off_Amount__c;
                    lstASTransaction.add(asTransaction);                               
                    
                }
            }
          */
          // Claim File Type "Reinsurance"
            Else if(PCDLoopData.Type__c=='Change in Ceded LAE Reserve'){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'Change in Ceded LAE Reserve';                
                    asTransaction.Amount__c = PCDLoopData.Reinsurance_Amount__c;
                    lstASTransaction.add(asTransaction); 
            }Else if(PCDLoopData.Type__c=='Change in Ceded Loss Reserve'){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'Change in Ceded Loss Reserve';                
                    asTransaction.Amount__c = PCDLoopData.Reinsurance_Amount__c;
                    lstASTransaction.add(asTransaction);                                              
            }Else if(PCDLoopData.Type__c=='Due from Reins. - LAE'){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'Reins. Recoverable-LAE';                
                    asTransaction.Amount__c = PCDLoopData.Reinsurance_Amount__c;
                    lstASTransaction.add(asTransaction);                                              
            }Else if(PCDLoopData.Type__c=='Due from Reins. - Loss'){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'Reins. Recoverable-Loss';                
                    asTransaction.Amount__c = PCDLoopData.Reinsurance_Amount__c;
                    lstASTransaction.add(asTransaction);                   
            // Type "Unallocated LAE Payment"
            }Else if(PCDLoopData.Type__c=='Unallocated LAE Payment'){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'Unallocated LAE Payment';                
                    asTransaction.Amount__c = PCDLoopData.LAE_Amount__c;
                    lstASTransaction.add(asTransaction);                   
            // Claim File Type "Unallocated LAE"
            }Else if(PCDLoopData.Type__c=='Claim Coverage - ARDC'){
                If(PCDLoopData.ISBA_First_Payment__c!=null){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'Claim Coverage - ARDC';                
                    asTransaction.Amount__c = PCDLoopData.ISBA_First_Payment__c;
                    lstASTransaction.add(asTransaction);                    
                }
                If(PCDLoopData.ISBA_Contribution__c!=null){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'Claim Coverage - ARDC';                
                    asTransaction.Amount__c = PCDLoopData.ISBA_Contribution__c;
                    lstASTransaction.add(asTransaction);                    
                }
               /* If(PCDLoopData.Lawyer_Contribution__c!=null){
                    asTransaction = Initiate_AS_entry(PCDLoopData);            
                    asTransaction.Transaction_Sub_Type__c = 'Claim Coverage - ARDC';                
                    asTransaction.Amount__c = PCDLoopData.Lawyer_Contribution__c;
                    lstASTransaction.add(asTransaction);                    
                }*/

            }Else{               
            }           
      }
        Try{
            if(lstASTransaction.size()>0){
             system.debug('start insertion of AS-->'+lstASTransaction);
             Database.insert(lstASTransaction);
            }
        }
        Catch(system.DmlException e){
            system.debug('Error: '+e.getMessage());
            system.debug('Error Line : '+e.getLineNumber());
        }
  }
}