force-app/main/default/objects/AS_Transaction__c/AS_Transaction__c.object-meta.xml
<CustomObject>
    <description>This is the intermediate object that will hold the entries for Accounting Seed.</description>
    <label>AS_Transaction</label>
    <nameField>
        <displayFormat>AST-{0000000}</displayFormat>
        <label>AS_Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AS_Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AS_Transaction__c/fields/Policy_Id__c.field-meta.xml
<CustomField>
    <fullName>Policy_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference of the Policy that the transactions belongs to.</description>
    <label>Policy Id</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>AS_Transactions</relationshipLabel>
    <relationshipName>AS_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Policy_ID__c.field-meta.xml
<CustomField>
    <fullName>Policy_ID__c</fullName>
    <label>Policy ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_DeletePolicyBoundTransactions.cls
public class Batch_DeletePolicyBoundTransactions implements Database.Batchable<Sobject>{
    public String soql;
    public Batch_DeletePolicyBoundTransactions(String soql){
        this.soql = soql;
    }
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(soql);
    }
    public void execute(Database.BatchableContext BC, List<Policy__c> batch) {
        List<AS_Transaction__c> asTransactions = new List<AS_Transaction__c>([select id from AS_Transaction__c where Policy_Id__c=: batch]);
        List<AcctSeed__Billing__c> billings = new List<AcctSeed__Billing__c>([select id from AcctSeed__Billing__c where Policy__c =: batch]);
        List<AcctSeed__Journal_Entry__c> jes = new List<AcctSeed__Journal_Entry__c>([select id from AcctSeed__Journal_Entry__c where Policy__c =: batch]);
        List<AcctSeed__Scheduled_Revenue_Expense__c> amortization = new List<AcctSeed__Scheduled_Revenue_Expense__c>([select id from AcctSeed__Scheduled_Revenue_Expense__c where Policy__c =: batch]);
        
        AcctSeed.PostResult[] postResults = AcctSeed.BillingPostService.unpostBillings(billings);
        postResults = AcctSeed.JournalEntryPostService.unpostJournalEntries(jes);
        postResults = AcctSeed.ScheduledRevenueExpensePostService.unpostScheduledRevenueExpenses(amortization);
        
        delete asTransactions;
        
        delete jes;
        delete amortization;
        delete billings;
    }
    public void finish(Database.BatchableContext BC) {
        
    }
}