force-app/main/default/objects/AS_Transaction__c/AS_Transaction__c.object-meta.xml
<CustomObject>
    <description>This is the intermediate object that will hold the entries for Accounting Seed.</description>
    <label>AS_Transaction</label>
    <nameField>
        <displayFormat>AST-{0000000}</displayFormat>
        <label>AS_Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AS_Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AS_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>This value hold the Amount that is to be transacted based on the transaction type.</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AS_Transaction__c/fields/Firm_Id__c.field-meta.xml
<CustomField>
    <fullName>Firm_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field holds the reference to the Firm that transaction belongs to.</description>
    <label>Firm Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AS_Transactions</relationshipLabel>
    <relationshipName>AS_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AS_Transaction__c/fields/Policy_Id__c.field-meta.xml
<CustomField>
    <fullName>Policy_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference of the Policy that the transactions belongs to.</description>
    <label>Policy Id</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>AS_Transactions</relationshipLabel>
    <relationshipName>AS_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AS_Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>This field is to identify the transaction type, it is the parent field of the transaction sub type field that is used to identify sub types in the claim transactions.</description>
    <label>Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add Lawyer</fullName>
            </value>
            <value>
                <fullName>Cancel Policy</fullName>
            </value>
            <value>
                <fullName>Change Coverage</fullName>
            </value>
            <value>
                <fullName>Change Lawyer</fullName>
            </value>
            <value>
                <fullName>Close Reserve</fullName>
            </value>
            <value>
                <fullName>Deductible Expense</fullName>
            </value>
            <value>
                <fullName>Delete Lawyer</fullName>
            </value>
            <value>
                <fullName>ERE</fullName>
            </value>
            <value>
                <fullName>LAE Payment</fullName>
            </value>
            <value>
                <fullName>Loss Payment</fullName>
            </value>
            <value>
                <fullName>Open Reserve</fullName>
            </value>
            <value>
                <fullName>Reinstate Policy</fullName>
            </value>
            <value>
                <fullName>Reopen Reserve</fullName>
            </value>
            <value>
                <fullName>User Reserve</fullName>
                <label>Change Reserve</label>
            </value>
            <value>
                <fullName>Deductible Loss</fullName>
            </value>
            <value>
                <fullName>Change in Ceded LAE Reserve</fullName>
            </value>
            <value>
                <fullName>Change in Ceded Loss Reserve</fullName>
            </value>
            <value>
                <fullName>Due from Reins. - LAE</fullName>
            </value>
            <value>
                <fullName>Due from Reins. - Loss</fullName>
            </value>
            <value>
                <fullName>Claim Coverage - ARDC</fullName>
            </value>
            <value>
                <fullName>Issue Policy</fullName>
            </value>
            <value>
                <fullName>Adjust Premium</fullName>
            </value>
            <value>
                <fullName>Unallocated LAE Payment</fullName>
            </value>
            <value>
                <fullName>Deductible Expense New</fullName>
            </value>
            <value>
                <fullName>Cash Payment</fullName>
                <isActive>false</isActive>
                <label>Cash Payment</label>
            </value>
            <value>
                <fullName>Claim Coverage - Memo</fullName>
                <isActive>false</isActive>
                <label>Claim Coverage - Memo</label>
            </value>
            <value>
                <fullName>Claims Coverage</fullName>
                <isActive>false</isActive>
                <label>Claims Coverage</label>
            </value>
            <value>
                <fullName>New Policy</fullName>
                <isActive>false</isActive>
                <label>New Policy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Is_Accepted_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Is_Accepted_Confirm__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Application status = Accepted and Is_Accepted_Confirm=Yes then Opportunity stages would be Accepted.</description>
    <label>Is Accepted Confirm</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Is_Allow_to_Generate_AS__c.field-meta.xml
<CustomField>
    <fullName>Is_Allow_to_Generate_AS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field use for AS (Accounting Seeds)
If yes then AS transaction will be create.</description>
    <label>Is_Allow_to_Generate_AS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_ID__c.field-meta.xml
<CustomField>
    <fullName>Policy_ID__c</fullName>
    <label>Policy ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Total Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to filter the related lawyers on the basis of related account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Effective_Date__c</fullName>
    <label>Endorsement Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Version__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Version__c</fullName>
    <label>Endorsement Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Event_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Lawyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Name__c</fullName>
    <formula>IF(Lawyer__c &lt;&gt; null, Lawyer__r.Lawyer_Name__c,  IF( Policy_Lawyer__c &lt;&gt; null, Policy_Lawyer__r.Lawyer__r.Lawyer_Name__c,  IL_152_First_Name__c+ IF(IL_152_Middle_Name__c &lt;&gt; null, &apos; &apos;+ IL_152_Middle_Name__c , &apos;&apos;)  +&apos; &apos;+  IL_152_Last_Name__c ) )</formula>
    <label>Lawyer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy_Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Policy_Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Policy_Lawyer__c.Deleted_Lawyer__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Policy__c</field>
            <operation>equals</operation>
            <valueField>Policy_Lawyer__c.Policy__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Policy_Lawyer__c</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy_Lawyer_Json__c.field-meta.xml
<CustomField>
    <fullName>Policy_Lawyer_Json__c</fullName>
    <label>Policy Lawyer Json</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Prior_Act_Date__c.field-meta.xml
<CustomField>
    <fullName>Prior_Act_Date__c</fullName>
    <label>Prior Act Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/Policy_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Policy Lawyer</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Lawyer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/ARDC_Number__c.field-meta.xml
<CustomField>
    <fullName>ARDC_Number__c</fullName>
    <formula>Lawyer__r.Contact__r.ARDC_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARDC Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Firm_Id__c.field-meta.xml
<CustomField>
    <fullName>Firm_Id__c</fullName>
    <formula>Account__r.AccountNumber</formula>
    <label>Firm Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Lawyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Name__c</fullName>
    <formula>Lawyer__r.Contact__r.FirstName &amp; &quot; &quot;  &amp; Lawyer__r.Contact__r.Middle_Name__c &amp; &quot; &quot; &amp;   Lawyer__r.Contact__r.LastName &amp; &quot; &quot; &amp;   Lawyer__r.Contact__r.Suffix__c</formula>
    <label>Lawyer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Lawyers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Prior_Act_Date__c.field-meta.xml
<CustomField>
    <fullName>Prior_Act_Date__c</fullName>
    <label>Prior Act Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Event_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Void</fullName>
        <isActive>false</isActive>
        <label>Void</label>
    </customValue>
    <masterLabel>Event Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PolicyDocumentsUtility.cls
global without sharing class PolicyDocumentsUtility {
    webservice static void createCertificationOfInsurance(String policyId,String docVersion,String accountId,Id documentId) {
        try{
            PageReference pageRef = Page.CERTIFICATION_OF_INSURANCE_Pdf;
            pageRef.getParameters().put('id',(String)policyId);
            pageRef.getParameters().put('version',(String)docVersion);
            Blob body ;
            if (Test.IsRunningTest()){
                body = Blob.valueOf('UNIT.TEST');
            } else {
                body = pageRef.getContentAsPDF();
            }
            createContentVersion(body,'Certification Of Insurance - '+ policyId+'.pdf',policyId,accountId,'Certificate Of Insurance',documentId,null,false);
        }catch(Exception e){
            System.debug('Error Message:'+e.getMessage());
        }
    }
    webservice static void createNASEOC(String policyId,String docVersion,String accountId,Id documentId) {
        try{
            PageReference pageRef = Page.NAS_EOC_Pdf;
            pageRef.getParameters().put('id',(String)policyId);
            pageRef.getParameters().put('version',(String)docVersion);
            Blob body ;
            if (Test.IsRunningTest()){
                body = Blob.valueOf('UNIT.TEST');
            } else {
                body = pageRef.getContentAsPDF();
            }
            createContentVersion(body,'NAS EOC - '+ policyId+'.pdf',policyId,accountId,'NAS EOC',documentId,null,false);
        }catch(Exception e){
            System.debug('Error Message:'+e.getMessage());
        }
    }
    webservice static void createDeclarationPage(String policyId,String docVersion,String accountId,Id documentId) {
        try{
            PageReference pageRef = Page.Declaration_Page_Pdf;
            pageRef.getParameters().put('id',(String)policyId);
            pageRef.getParameters().put('version',(String)docVersion);
            Blob body ;
            if (Test.IsRunningTest()){
                body = Blob.valueOf('UNIT.TEST');
            } else {
                body = pageRef.getContentAsPDF();
            }
            createContentVersion(body,'Declaration Page - '+ policyId+'.pdf',policyId,accountId,'Declaration Page',documentId,null,false);
        }catch(Exception e){
            System.debug('Error Message:'+e.getMessage());
        }
    }
    webservice static void createPolicyLetter(String policyId,String docVersion,String accountId,Id documentId) {
        try{
            PageReference pageRef = Page.Policy_Letter_Pdf;
            pageRef.getParameters().put('id',(String)policyId);
            pageRef.getParameters().put('version',(String)docVersion);
            Blob body;
            if (Test.IsRunningTest()){
                body = Blob.valueOf('UNIT.TEST');
            } else {
                body = pageRef.getContentAsPDF();
            }
            createContentVersion(body,'Policy Letter - '+ policyId+'.pdf',policyId,accountId,'Policy Letter',documentId,null,false);
        }catch(Exception e){
            System.debug('Error Message:'+e.getMessage());
        }
    }
    webservice static void createQuote(String quoteId,String policyId,String pdfname,String accountId,Id documentId) {
        try{
            PageReference pageRef = Page.Quote_Pdf;
            pageRef.getParameters().put('id',(String)quoteId);
            Blob body;
            if (Test.IsRunningTest()){
                body = Blob.valueOf('UNIT.TEST');
            } else {
                body = pageRef.getContentAsPDF();
            }
            createContentVersion(body,pdfname+'.pdf',policyId,accountId,'Quote',documentId);
        }catch(Exception e){
            System.debug('Error Message:'+e.getMessage());
        }
    }
    webservice static void createIL230_234_261(String policyId,String docVersion,Policy__c policy,boolean IL_230,boolean IL_234,boolean IL_261){
        /*Policy__c policy = [select id,Account__c,Effective_Date__c from Policy__c where id =: policyId];
        system.debug('policy :: ' + policy);*/
        List<Policy_Endorsement__c> endorsementList = new List<Policy_Endorsement__c>();
        Policy_Endorsement__c endorsementIL230 = new Policy_Endorsement__c();
        Policy_Endorsement__c endorsementIL234 = new Policy_Endorsement__c();
        Policy_Endorsement__c endorsementIL261 = new Policy_Endorsement__c();
        if(IL_230){
            endorsementIL230.Account__c = policy.Account__c;
            endorsementIL230.RecordTypeId = Schema.getGlobalDescribe().get('Policy_Endorsement__c').getDescribe().getRecordTypeInfosByName().get('IL 230 ANNUAL AGGREGATE DEDUCTIBLE ENDORSEMENT').getRecordTypeId();
            endorsementIL230.Effective_Date__c = System.today();
            endorsementIL230.Endorsement_Effective_Date__c = policy.Effective_Date__c;
            endorsementIL230.Event_Status__c = 'Pending';
            endorsementIL230.Policy__c = policyId;
            endorsementList.add(endorsementIL230);
        }    
        if(IL_234){
            endorsementIL234.Account__c = policy.Account__c;
            endorsementIL234.RecordTypeId = Schema.getGlobalDescribe().get('Policy_Endorsement__c').getDescribe().getRecordTypeInfosByName().get('IL 234 LOSS ONLY DEDUCTIBLE ENDORSEMENT').getRecordTypeId();
            endorsementIL234.Effective_Date__c = System.today();
            endorsementIL234.Endorsement_Effective_Date__c = policy.Effective_Date__c;
            endorsementIL234.Event_Status__c = 'Pending';
            endorsementIL234.Policy__c = policyId;
            endorsementList.add(endorsementIL234);
        }
        if(IL_261){
            endorsementIL261.Account__c = policy.Account__c;
            endorsementIL261.RecordTypeId = Schema.getGlobalDescribe().get('Policy_Endorsement__c').getDescribe().getRecordTypeInfosByName().get('IL 261 Claim Expenses Outside the Policy Limits Endorsement').getRecordTypeId();
            endorsementIL261.Effective_Date__c = System.today();
            endorsementIL261.Endorsement_Effective_Date__c = policy.Effective_Date__c;
            endorsementIL261.Event_Status__c = 'Pending';
            endorsementIL261.Policy__c = policyId;
            endorsementList.add(endorsementIL261);
        }
        
        insert endorsementList;
        
        if(IL_261){
            endorsementIL261 = [select id,Endorsement_Version__c from Policy_Endorsement__c where id=: endorsementIL261.Id];
        }
        
        
        for(Policy_Endorsement__c endorsement : endorsementList){
            endorsement.Event_Status__c = 'Complete';
        }
        
        update endorsementList;
        if(IL_230){
            createEndorsement(policyId,policyId,'IL 230 Annual Aggregate Deductible Endorsement - '+policyId,'IL 230',docVersion,policy.Account__c,null,endorsementIL230.Id);
        }
        if(IL_234){
            createEndorsement(policyId,policyId,'IL 234 Loss Only Deductible Endorsement - '+policyId,'IL 234',docVersion,policy.Account__c,null,endorsementIL234.Id);
        }
        if(IL_261){
            createEndorsement(policyId,policyId,'IL 261 Claim Expenses Outside the Policy Limits Endorsement - '+policyId,'IL 261',endorsementIL261.Endorsement_Version__c,policy.Account__c,null,endorsementIL261.Id);
        }
    }
    webservice static void createIL102(String policyId,String docVersion,Policy__c policy,Id documentId){
        /*Policy__c policy = [select id,Account__c,Effective_Date__c from Policy__c where id =: policyId];
        system.debug('policy :: ' + policy);*/
            
        Policy_Endorsement__c endorsement = new Policy_Endorsement__c();
        endorsement.Account__c = policy.Account__c;
        endorsement.RecordTypeId = Schema.getGlobalDescribe().get('Policy_Endorsement__c').getDescribe().getRecordTypeInfosByName().get('IL 102 PRIOR ACTS EXCLUSION ENDORSEMENT').getRecordTypeId();
        system.debug('endorsement.RecordTypeId == >>'+endorsement.RecordTypeId);
        endorsement.Effective_Date__c = System.today();
        endorsement.Endorsement_Effective_Date__c = policy.Effective_Date__c;
        endorsement.Event_Status__c = 'Pending';
        endorsement.Policy__c = policyId;
        insert endorsement;
        List<JsonPolicyLawyerWrapper> wrapperList = new List<JsonPolicyLawyerWrapper>();
        for(Policy_Lawyer__c lawyer :[select id,Prior_Act_Date__c,Lawyer_Name__c,ARDC_Number__c  from Policy_Lawyer__c where Policy__C = :policyId] ){
            JsonPolicyLawyerWrapper wrapper = new JsonPolicyLawyerWrapper();
            wrapper.lawyername = lawyer.Lawyer_Name__c;
            wrapper.priorActsDate = lawyer.Prior_Act_Date__c;
            wrapper.ardcNumber = lawyer.ARDC_Number__c ;
            wrapperList.add(wrapper);
        }
        String jsonString = JSON.serialize(wrapperList);
        endorsement.Event_Status__c = 'Complete';
        endorsement.Policy_Lawyer_Json__c = jsonString;
        update endorsement;
        createEndorsement(policyId,policyId,'IL 102 Prior Acts Exclusion Endorsement - '+policyId,'IL 102',docVersion,policy.Account__c,documentId,endorsement.Id);
    }
    webservice static void createIL302(String policyId,String docVersion,Policy__c policy,Id documentId){
        Policy_Endorsement__c endorsement = new Policy_Endorsement__c();
        endorsement.Account__c = policy.Account__c;
        endorsement.RecordTypeId = Schema.getGlobalDescribe().get('Policy_Endorsement__c').getDescribe().getRecordTypeInfosByName().get('IL 302 AMENDMENT OF EXTENDED REPORTING PERIOD OPTIONS ENDORSEMENT').getRecordTypeId();
        system.debug('endorsement.RecordTypeId == >>'+endorsement.RecordTypeId);
        endorsement.Effective_Date__c = System.today();
        endorsement.Endorsement_Effective_Date__c = policy.Effective_Date__c;
        endorsement.Event_Status__c = 'Pending';
        endorsement.Policy__c = policyId;
        insert endorsement;
        
        endorsement.Event_Status__c = 'Complete';
        update endorsement;
        
        createEndorsement(policyId,policyId,'IL 302 Amendment of Unlimited Retirement Extended Reporting Period Endorsement - '+policyId,'IL 302',Label.IL_302_Version,policy.Account__c,documentId,endorsement.Id);
    }
    webservice static void createEndorsement(String endorsementId,String policyId,String pdfname,String endorsementNumber,String version,String accountId,Id documentId,Id mappedEndorsementId, boolean physicalDocumentDelivery) {
        try{
            PageReference pageRef = Page.Endorsement_Pdf;
            pageRef.getParameters().put('id',(String)endorsementId);
            pageRef.getParameters().put('number',(String)endorsementNumber);
            pageRef.getParameters().put('version',(String)version);
            Blob body;
            
            if (Test.IsRunningTest()){
                body = Blob.valueOf('UNIT.TEST');
            } else {
                body = pageRef.getContentAsPDF();
            }
            ContentVersion content = createContentVersion(body,pdfname+'.pdf',policyId,accountId,'Endorsement',documentId,mappedEndorsementId,physicalDocumentDelivery);
            
        }catch(Exception e){
            System.debug('Error Message:'+e.getMessage());
        }
    }
    webservice static String policyToApplicationAccountingTransactions(String policyId) {
        SavePoint sp = Database.setSavepoint();
        try{
            Policy__c pol = [select id,Premium__c,Is_Accepted_Confirm__c,Is_Allow_to_Generate_AS__c,RecordTypeId,Account__c from Policy__c where id=:policyId];
            
            /*AS_Transaction__c asTransaction = new AS_Transaction__c();
            asTransaction.Amount__c = pol.Premium__c;
            asTransaction.Firm_Id__c = pol.Account__c;
            asTransaction.Policy_Id__c = policyId;
            asTransaction.Transaction_Type__c = 'Cancel Policy';
            asTransaction.Transaction_Sub_Type__c = 'Cancel Policy';
            
            insert asTransaction;*/
            
            List<Policy_Lawyer__c> lawyers = new List<Policy_Lawyer__c>([select id,Is_Application_Lawyer__c from Policy_Lawyer__c where Policy__c =: policyId]);
            for(Policy_Lawyer__c lawyer : lawyers){
                lawyer.Is_Application_Lawyer__c = true;
            }
            
            update lawyers;
            
            pol.Premium__c = null;
            pol.Is_Accepted_Confirm__c= false; 
            pol.Is_Allow_to_Generate_AS__c= true;
            pol.Is_Allow_Calculate_Premium__c=false;
            pol.RecordTypeId=ApplicationPolicyUtil.ApplicationRTID;
            pol.Accounting_Processed__c = false;
            
            update pol;
            
            
            return 'Policy successfully converted back to Application.';
        }catch(Exception e){
            Database.rollback(sp);
            return 'There is some error occurred while conversion : '+e.getMessage();
        }
        
    }
    
    public static ContentVersion createContentVersion(Blob body,String fileName,Id policyId,Id accountId,String documentType,Id contentDocumentId,Id mappedEndorsementId,boolean physicalDocumentDelivery){
        Decimal currentMilliSeconds = System.now().getTime();
        ContentVersion content = new ContentVersion();
        content.VersionData = body;
        content.Title = fileName;
        content.PathOnClient = fileName;
        content.Application_Policy__c = policyId;
        content.Endorsement_Id__c = mappedEndorsementId;
        content.Account__c = accountId;
        content.Document_Type__c = documentType;
        content.Is_System_Generated_Document__c = true;
        content.Unique_Identifier__c = policyId + '_' + UserInfo.getUserId() +  '_' + currentMilliSeconds;
        content.IsMajorVersion = true;
        content.Physical_document_delivery__c = physicalDocumentDelivery;
        if(contentDocumentId != null){
            content.ContentDocumentId = contentDocumentId;
        }else{
            content.FirstPublishLocationId = policyId;
        }
        insert content;
        return content;
    }
    
    public static ContentVersion createContentVersion(Blob body,String fileName,Id policyId,Id accountId,String documentType,Id contentDocumentId){
        return createContentVersion(body,fileName,policyId,accountId,documentType,contentDocumentId,null,false);
    }
    public static ContentVersion createContentVersion(Blob body,String fileName,Id policyId,Id accountId,String documentType,Id contentDocumentId,Id mappedEndorsementId){
        return createContentVersion(body,fileName,policyId,accountId,documentType,contentDocumentId,null,false);
    }
    
    public static void createEndorsement(String endorsementId,String policyId,String pdfname,String endorsementNumber,String version,String accountId,Id documentId,Id mappedEndorsementId){
        createEndorsement(endorsementId,policyId,pdfname,endorsementNumber,version,accountId,documentId,mappedEndorsementId,false);
    }
    
}