force-app/main/default/objects/AS_Transaction__c/AS_Transaction__c.object-meta.xml
<CustomObject>
    <description>This is the intermediate object that will hold the entries for Accounting Seed.</description>
    <label>AS_Transaction</label>
    <nameField>
        <displayFormat>AST-{0000000}</displayFormat>
        <label>AS_Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AS_Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AS_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>This value hold the Amount that is to be transacted based on the transaction type.</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AS_Transaction__c/fields/Firm_Id__c.field-meta.xml
<CustomField>
    <fullName>Firm_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field holds the reference to the Firm that transaction belongs to.</description>
    <label>Firm Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AS_Transactions</relationshipLabel>
    <relationshipName>AS_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AS_Transaction__c/fields/Policy_Id__c.field-meta.xml
<CustomField>
    <fullName>Policy_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference of the Policy that the transactions belongs to.</description>
    <label>Policy Id</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>AS_Transactions</relationshipLabel>
    <relationshipName>AS_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AS_Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>This field is to identify the transaction type, it is the parent field of the transaction sub type field that is used to identify sub types in the claim transactions.</description>
    <label>Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add Lawyer</fullName>
            </value>
            <value>
                <fullName>Cancel Policy</fullName>
            </value>
            <value>
                <fullName>Change Coverage</fullName>
            </value>
            <value>
                <fullName>Change Lawyer</fullName>
            </value>
            <value>
                <fullName>Close Reserve</fullName>
            </value>
            <value>
                <fullName>Deductible Expense</fullName>
            </value>
            <value>
                <fullName>Delete Lawyer</fullName>
            </value>
            <value>
                <fullName>ERE</fullName>
            </value>
            <value>
                <fullName>LAE Payment</fullName>
            </value>
            <value>
                <fullName>Loss Payment</fullName>
            </value>
            <value>
                <fullName>Open Reserve</fullName>
            </value>
            <value>
                <fullName>Reinstate Policy</fullName>
            </value>
            <value>
                <fullName>Reopen Reserve</fullName>
            </value>
            <value>
                <fullName>User Reserve</fullName>
                <label>Change Reserve</label>
            </value>
            <value>
                <fullName>Deductible Loss</fullName>
            </value>
            <value>
                <fullName>Change in Ceded LAE Reserve</fullName>
            </value>
            <value>
                <fullName>Change in Ceded Loss Reserve</fullName>
            </value>
            <value>
                <fullName>Due from Reins. - LAE</fullName>
            </value>
            <value>
                <fullName>Due from Reins. - Loss</fullName>
            </value>
            <value>
                <fullName>Claim Coverage - ARDC</fullName>
            </value>
            <value>
                <fullName>Issue Policy</fullName>
            </value>
            <value>
                <fullName>Adjust Premium</fullName>
            </value>
            <value>
                <fullName>Unallocated LAE Payment</fullName>
            </value>
            <value>
                <fullName>Deductible Expense New</fullName>
            </value>
            <value>
                <fullName>Cash Payment</fullName>
                <isActive>false</isActive>
                <label>Cash Payment</label>
            </value>
            <value>
                <fullName>Claim Coverage - Memo</fullName>
                <isActive>false</isActive>
                <label>Claim Coverage - Memo</label>
            </value>
            <value>
                <fullName>Claims Coverage</fullName>
                <isActive>false</isActive>
                <label>Claims Coverage</label>
            </value>
            <value>
                <fullName>New Policy</fullName>
                <isActive>false</isActive>
                <label>New Policy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Accounting_Processed__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accounting Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/GL_Processing_Date__c.field-meta.xml
<CustomField>
    <fullName>GL_Processing_Date__c</fullName>
    <label>GL Processing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_ID__c.field-meta.xml
<CustomField>
    <fullName>Policy_ID__c</fullName>
    <label>Policy ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to filter the related lawyers on the basis of related account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Accounting_Processed__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accounting Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Effective_Date__c</fullName>
    <label>Endorsement Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Number__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Number__c</fullName>
    <label>Endorsement Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Version__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Version__c</fullName>
    <label>Endorsement Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Event_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Lawyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Name__c</fullName>
    <formula>IF(Lawyer__c &lt;&gt; null, Lawyer__r.Lawyer_Name__c,  IF( Policy_Lawyer__c &lt;&gt; null, Policy_Lawyer__r.Lawyer__r.Lawyer_Name__c,  IL_152_First_Name__c+ IF(IL_152_Middle_Name__c &lt;&gt; null, &apos; &apos;+ IL_152_Middle_Name__c , &apos;&apos;)  +&apos; &apos;+  IL_152_Last_Name__c ) )</formula>
    <label>Lawyer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy_Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Policy_Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Policy_Lawyer__c.Deleted_Lawyer__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Policy__c</field>
            <operation>equals</operation>
            <valueField>Policy_Lawyer__c.Policy__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Policy_Lawyer__c</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy_Lawyer_Json__c.field-meta.xml
<CustomField>
    <fullName>Policy_Lawyer_Json__c</fullName>
    <label>Policy Lawyer Json</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Prior_Act_Date__c.field-meta.xml
<CustomField>
    <fullName>Prior_Act_Date__c</fullName>
    <label>Prior Act Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/Policy_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Policy Lawyer</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Lawyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Lawyer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/ARDC_Number__c.field-meta.xml
<CustomField>
    <fullName>ARDC_Number__c</fullName>
    <formula>Lawyer__r.Contact__r.ARDC_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARDC Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Firm_Id__c.field-meta.xml
<CustomField>
    <fullName>Firm_Id__c</fullName>
    <formula>Account__r.AccountNumber</formula>
    <label>Firm Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Lawyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Name__c</fullName>
    <formula>Lawyer__r.Contact__r.FirstName &amp; &quot; &quot;  &amp; Lawyer__r.Contact__r.Middle_Name__c &amp; &quot; &quot; &amp;   Lawyer__r.Contact__r.LastName &amp; &quot; &quot; &amp;   Lawyer__r.Contact__r.Suffix__c</formula>
    <label>Lawyer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Lawyers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Lawyer__c/fields/Prior_Act_Date__c.field-meta.xml
<CustomField>
    <fullName>Prior_Act_Date__c</fullName>
    <label>Prior Act Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Event_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Void</fullName>
        <isActive>false</isActive>
        <label>Void</label>
    </customValue>
    <masterLabel>Event Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PolicyEndorsementController.cls
public class PolicyEndorsementController {
	
    @AuraEnabled
    public static Policy_Endorsement__c getPolicyEndorse(String policyId){
        Policy_Endorsement__c objPolicyEndorse = [SELECT Id,Name,Event_Status__c,Endorsement_Number__c,Endorsement_Version__c,Policy__c,Policy__r.Account__c,Policy__r.recordType.Name,
                                                  GL_Processing_Date__c,Endorsement_Effective_Date__c
               									FROM Policy_Endorsement__c WHERE Id =: policyId];
        return objPolicyEndorse ;
    }
    @AuraEnabled
    public static void updatePolicy(String policyId){
    	Policy_Endorsement__c objPoliceEndor = getPolicyEndorse(policyId);
        system.debug('=====objPoliceEndor====='+objPoliceEndor.Endorsement_Number__c);
        if(objPoliceEndor.Endorsement_Number__c == 'IL 102'){
            List<JsonPolicyLawyerWrapper> wrapperList = new List<JsonPolicyLawyerWrapper>();
            for(Policy_Lawyer__c lawyer :[select id,Prior_Act_Date__c,Lawyer_Name__c, ARDC_Number__c  from Policy_Lawyer__c where Policy__c =: objPoliceEndor.Policy__c] ){
                JsonPolicyLawyerWrapper wrapper = new JsonPolicyLawyerWrapper();
                wrapper.lawyername = lawyer.Lawyer_Name__c;
                wrapper.priorActsDate = lawyer.Prior_Act_Date__c;
                wrapper.ardcNumber = lawyer.ARDC_Number__c ; 
                wrapperList.add(wrapper);
            }
            String jsonString = JSON.serialize(wrapperList);
            objPoliceEndor.Policy_Lawyer_Json__c = jsonString;
        }
        objPoliceEndor.Event_Status__c= 'Complete';
        if(Label.Process_Accounting_On_Endorsements == 'Y'){
            objPoliceEndor.Accounting_Processed__c = true;
            if(objPoliceEndor.GL_Processing_Date__c == null){
                objPoliceEndor.GL_Processing_Date__c = (objPoliceEndor.Endorsement_Effective_Date__c >= System.today() ? objPoliceEndor.Endorsement_Effective_Date__c : System.today());
            }
        }        
        update objPoliceEndor;
        if(objPoliceEndor.Policy__r.recordType.Name =='Policy'){
            PolicyDocumentsUtility.createEndorsement(objPoliceEndor.id,objPoliceEndor.Policy__c,objPoliceEndor.Name,objPoliceEndor.Endorsement_Number__c,objPoliceEndor.Endorsement_Version__c,objPoliceEndor.Policy__r.Account__c,null,objPoliceEndor.Id,true);
        }
        else{
            PolicyDocumentsUtility.createEndorsement(objPoliceEndor.id,objPoliceEndor.Policy__c,objPoliceEndor.Name,objPoliceEndor.Endorsement_Number__c,objPoliceEndor.Endorsement_Version__c,objPoliceEndor.Policy__r.Account__c,null,objPoliceEndor.Id );
        } 
    }
    
    @AuraEnabled
    public static void cancelEndorsement(String policyId){
        
        List<AS_Transaction__c> asTransactionsToInsert = new List<AS_Transaction__c>();
        
        Policy_Endorsement__c objPoliceEndor = getPolicyEndorse(policyId);
        objPoliceEndor.Event_Status__c= 'Cancel';   
        objPoliceEndor.Name = objPoliceEndor.Name + '- Cancel';
        
        if(!Test.isRunningTest()){
            update objPoliceEndor;
        }
        
        for(AS_Transaction__c as_trans: [SELECT Id,Name,Amount__c,Policy_Id__c,Firm_Id__c,Transaction_Type__c,Transaction_Sub_Type__c,Policy_Endorsement_Id__c FROM AS_Transaction__c WHERE Policy_Endorsement_Id__c = : policyId]){
            
            AS_Transaction__c as_transCopy = as_trans.clone(false, true, false, false);
            as_transCopy.Amount__c = - as_trans.Amount__c;
            asTransactionsToInsert.add(as_transCopy);
            
        }
        insert asTransactionsToInsert;
    }
    
}