force-app/main/default/objects/AS_Transaction__c/AS_Transaction__c.object-meta.xml
<CustomObject>
    <description>This is the intermediate object that will hold the entries for Accounting Seed.</description>
    <label>AS_Transaction</label>
    <nameField>
        <displayFormat>AST-{0000000}</displayFormat>
        <label>AS_Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AS_Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Accounting_Processed__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accounting Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Bound_Date__c.field-meta.xml
<CustomField>
    <fullName>Bound_Date__c</fullName>
    <label>Bound Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/GL_Processing_Date__c.field-meta.xml
<CustomField>
    <fullName>GL_Processing_Date__c</fullName>
    <label>GL Processing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Total Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <label>Primary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to filter the related lawyers on the basis of related account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Accounting_Processed__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accounting Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Effective_Date__c</fullName>
    <label>Endorsement Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Number__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Number__c</fullName>
    <label>Endorsement Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Event_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Excess__c.field-meta.xml
<CustomField>
    <fullName>Excess__c</fullName>
    <label>Excess</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Premium_10_10__c.field-meta.xml
<CustomField>
    <fullName>Premium_10_10__c</fullName>
    <label>Premium 10x10</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Premium_5_5__c.field-meta.xml
<CustomField>
    <fullName>Premium_5_5__c</fullName>
    <label>Premium 5x5</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <label>Primary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Event_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Void</fullName>
        <isActive>false</isActive>
        <label>Void</label>
    </customValue>
    <masterLabel>Event Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProcessAccountingCtrl.cls
public class ProcessAccountingCtrl {
    @AuraEnabled
    public static void processAccounting(String recordId){
        SavePoint sp = Database.setSavepoint();
        try{
            String objName = Id.valueOf(recordId).getSObjectType().getDescribe().getName();
            if(objName == 'Policy__c'){
                List<Policy__c> policy = new List<Policy__c>([select id,Accounting_Processed__c,Bound_Date__c from Policy__c where id =: recordId]);
                if(policy.size()>0){
                    if(!policy[0].Accounting_Processed__c){
                        if(policy[0].Bound_Date__c != null && policy[0].Bound_Date__c >= Date.newInstance(2020, 10, 16)){
                            Set<Id> policyIdsSet = new Set<Id>();
                            policyIdsSet.add(policy[0].Id);
                            ApplicationPolicyUtil.CreateAccuntingSeedsForPolicy(policyIdsSet);
                        }else{
                            throw new AuraHandledException('Accounting Can not be processed on this Policy') ;
                        }
                    }else{
                        System.debug('Here');
                        throw new AuraHandledException('Accounting has already been processed.') ;
                    }
                }else{
                    throw new AuraHandledException('Invalid Record Id') ;
                }
            }else if(objName == 'Policy_Endorsement__c'){
                List<Policy_Endorsement__c> endorsements = new List<Policy_Endorsement__c>([select id,Endorsement_Number__c,Accounting_Processed__c,Premium__c,Account__c,Policy__c,Premium_5_5__c,Premium_10_10__c,Primary__c,Excess__c,Event_Status__c,GL_Processing_Date__c,Endorsement_Effective_Date__c from Policy_Endorsement__c where id =: recordId]);
                if(endorsements.size() > 0){
                    if(endorsements[0].Event_Status__c == 'Complete' && !endorsements[0].Accounting_Processed__c){
                        if(endorsements[0].Endorsement_Number__c == 'IL 152' || endorsements[0].Endorsement_Number__c == 'IL 153'  || endorsements[0].Endorsement_Number__c == 'IL 107' || endorsements[0].Endorsement_Number__c == 'IL 190'){
                            List<AS_Transaction__c> lstASTransaction = new List<AS_Transaction__c>();
                            if(endorsements[0].Endorsement_Number__c == 'IL 152'){
                                lstASTransaction = PolicyEndorsementGateway.getIL_152_Transactions(endorsements[0]);
                            }else if(endorsements[0].Endorsement_Number__c == 'IL 153'){
                                lstASTransaction = PolicyEndorsementGateway.getIL_153_Transactions(endorsements[0]);
                            }else if(endorsements[0].Endorsement_Number__c == 'IL 190'){
                                lstASTransaction = PolicyEndorsementGateway.getIL_190_Transactions(endorsements[0]);
                            }else if(endorsements[0].Endorsement_Number__c == 'IL 107'){
                                lstASTransaction = PolicyEndorsementGateway.getERE_Transactions(endorsements[0]);
                            }
                            if(lstASTransaction.size() > 0){
                                insert lstASTransaction;
                                endorsements[0].Accounting_Processed__c = true;
                                if(endorsements[0].GL_Processing_Date__c == null){
                                    endorsements[0].GL_Processing_Date__c = (endorsements[0].Endorsement_Effective_Date__c >= System.today() ? endorsements[0].Endorsement_Effective_Date__c : System.today());
                                }
                                update endorsements[0];
                            }
                        }else{
                            throw new AuraHandledException('Accounting Process Not Valid On this Particular Endorsement.') ;
                        }
                    }else{
                        throw new AuraHandledException('Either Endorsement is not Approved or accounting has already been processed.') ;
                    }
                }else{
                    throw new AuraHandledException('Invalid Record Id') ;
                }
                //currentEnd.Endorsement_Sub_Type__c == 'IL 152';
                //lstASTransaction = getIL_152_Transactions(polEnd);
                //List<>
                /*if(){
                    
                }*/
            }else{
                throw new AuraHandledException('Invalid Record Id') ;
            }
            
        }catch(DmlException e){
            System.debug('Error----'+e.getMessage());
            System.debug('LIne-----'+e.getLineNumber());
            Database.rollback(sp);
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString()) ;
        }catch(LimitException e){
            Database.rollback(sp);
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString()) ;
        }catch(ListException e){
            Database.rollback(sp);
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString()) ;
        }catch(NullPointerException e){
            Database.rollback(sp);
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString()) ;
        }catch(QueryException e){
            Database.rollback(sp);
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString()) ;
        }
    }
}