force-app/main/default/objects/AS_Transaction__c/AS_Transaction__c.object-meta.xml
<CustomObject>
    <description>This is the intermediate object that will hold the entries for Accounting Seed.</description>
    <label>AS_Transaction</label>
    <nameField>
        <displayFormat>AST-{0000000}</displayFormat>
        <label>AS_Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AS_Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AS_Transaction__c/fields/Policy_Endorsement_Id__c.field-meta.xml
<CustomField>
    <fullName>Policy_Endorsement_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference of the Policy Endorsement that the transaction belongs to.</description>
    <label>Policy Endorsement Id</label>
    <referenceTo>Policy_Endorsement__c</referenceTo>
    <relationshipLabel>AS_Transactions</relationshipLabel>
    <relationshipName>AS_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Active1__c.field-meta.xml
<CustomField>
    <fullName>Active1__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Actrive Policy flag used by internal code, updated by nightly batch process.</description>
    <label>Active1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Cancel_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Date__c</fullName>
    <label>Cancel Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Excess_Premium__c.field-meta.xml
<CustomField>
    <fullName>Excess_Premium__c</fullName>
    <label>Excess Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Total Premium</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <label>Primary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Total_10x10__c.field-meta.xml
<CustomField>
    <fullName>Total_10x10__c</fullName>
    <label>Total 10x10</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Total_5x5__c.field-meta.xml
<CustomField>
    <fullName>Total_5x5__c</fullName>
    <label>Total 5x5</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Excess__c.field-meta.xml
<CustomField>
    <fullName>Excess__c</fullName>
    <label>Excess</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Premium_10_10__c.field-meta.xml
<CustomField>
    <fullName>Premium_10_10__c</fullName>
    <label>Premium 10x10</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Premium_5_5__c.field-meta.xml
<CustomField>
    <fullName>Premium_5_5__c</fullName>
    <label>Premium 5x5</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <label>Primary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/fields/Refund_Amount__c.field-meta.xml
<CustomField>
    <fullName>Refund_Amount__c</fullName>
    <description>The amount that is to be returned to the policy holder if the policy is cancelled before expiration.</description>
    <label>Return Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ReversePolicyCancellationCtrl.cls
public class ReversePolicyCancellationCtrl {
    
    public class ReversePolicyCancellationCtrlException extends Exception{}
    
	@AuraEnabled
    public static String reversePolicy(String recId){
        try{
            Policy_Endorsement__c polEndsmt = [SELECT Id,Policy__c,Policy__r.Cancel_Date__c,
                                               Policy__r.Premium__c,Refund_Amount__c,
                                               Policy__r.Total_5x5__c,Premium_5_5__c,
                                               Policy__r.Total_10x10__c,Premium_10_10__c,
                                               Policy__r.Excess_Premium__c,Excess__c,
                                               Policy__r.Primary__c,Primary__c,
                                               Policy__r.Expiration_Date__c,(SELECT Id FROM Journal_Entries__r),(SELECT Id FROM Billings__r) FROM Policy_Endorsement__c WHERE Id=:recId LIMIT 1];
            
            Set<String> billIds = new Set<String>();
            for(AcctSeed__Billing__c bill : polEndsmt.Billings__r){
                billIds.add(bill.Id);
            }
            List<AS_Transaction__c> asTransactions = [SELECT Id,(SELECT Id FROM Amortization_Entries__r) FROM  AS_Transaction__c WHERE Policy_Endorsement_Id__c=: polEndsmt.Id];
            
            Map<String, AcctSeed__Scheduled_Revenue_Expense__c> amotrizationMap = new Map<String, AcctSeed__Scheduled_Revenue_Expense__c>([SELECT Id FROM AcctSeed__Scheduled_Revenue_Expense__c WHERE AcctSeed__Billing__c IN: billIds]);
            
            for(AS_Transaction__c t: asTransactions){
                for(AcctSeed__Scheduled_Revenue_Expense__c a: t.Amortization_Entries__r){
                    amotrizationMap.put(a.Id, a);
                }
            }
            
            // Call the unpost billings service
            AcctSeed.PostResult[] unpostResults = AcctSeed.BillingPostService.unpostBillings(polEndsmt.Billings__r);
            
            // Loop through unpost results
            for (AcctSeed.PostResult theResult : unpostResults) {
                if (theResult.isSuccess) {
                    System.debug('Successfully unposted billing: ' + theResult.id);
                } 
                else {                    
                    System.debug('Error unposting billing ' + theResult.id);
                    for (AcctSeed.PostResult.PostErrorResult errorResult: theResult.errors) {
                        System.debug('Error status code ' + errorResult.statusCode);
                        System.debug('Error message ' + errorResult.message);
                    }
                }
            }
            
            // Call the unpost journal entry service
            AcctSeed.PostResult[] unpostJeResults = AcctSeed.JournalEntryPostService.unpostJournalEntries(polEndsmt.Journal_Entries__r);
            
            // Loop through unpost results
            for (AcctSeed.PostResult theResult : unpostJeResults) {
                if (theResult.isSuccess) {
                    System.debug('Successfully unposted journal entry: ' + theResult.id);
                } 
                else {
                    System.debug('Error unposting journal entry ' + theResult.id);
                    for (AcctSeed.PostResult.PostErrorResult errorResult: theResult.errors) {
                        System.debug('Error status code ' + errorResult.statusCode);
                        System.debug('Error message ' + errorResult.message);
                    }
                }
            } 
            
            // Call the unpost Amortization service
            AcctSeed.PostResult[] unpostAmoResults = AcctSeed.AmortizationPostService.unpostAmortizationEntries(amotrizationMap.values());
            
            // Loop through unpost results
            for (AcctSeed.PostResult theResult : unpostAmoResults) {
                if (theResult.isSuccess) {
                    System.debug('Successfully unposted Amortization : ' + theResult.id);
                } 
                else {
                    System.debug('Error unposting Amortization ' + theResult.id);
                    for (AcctSeed.PostResult.PostErrorResult errorResult: theResult.errors) {
                        System.debug('Error status code ' + errorResult.statusCode);
                        System.debug('Error message ' + errorResult.message);
                    }
                }
            } 
            
            Policy__c p = new Policy__c();
            p.Id = polEndsmt.Policy__c;
            p.Cancel_Date__c = null;
            System.debug('123');
            p.Premium__c = polEndsmt.Policy__r.Premium__c + polEndsmt.Refund_Amount__c;
            p.Total_5x5__c = (polEndsmt.Policy__r.Total_5x5__c == null ? 0 : polEndsmt.Policy__r.Total_5x5__c) - (polEndsmt.Premium_5_5__c == null ? 0 : polEndsmt.Premium_5_5__c);
            p.Total_10x10__c = (polEndsmt.Policy__r.Total_10x10__c == null ? 0 : polEndsmt.Policy__r.Total_10x10__c) - (polEndsmt.Premium_10_10__c == null ? 0 : polEndsmt.Premium_10_10__c);
            p.Excess_Premium__c = (polEndsmt.Policy__r.Excess_Premium__c == null ? 0 : polEndsmt.Policy__r.Excess_Premium__c) - (polEndsmt.Excess__c == null ? 0 : polEndsmt.Excess__c);
            p.Primary__c = (polEndsmt.Policy__r.Primary__c == null ? 0 : polEndsmt.Policy__r.Primary__c) - (polEndsmt.Primary__c == null ? 0 : polEndsmt.Primary__c);
            
            if(polEndsmt.Policy__r.Expiration_Date__c > System.today()){
                p.Active1__c = true;
            }
            system.debug('policy => '+p);
            Update p;
            
            Delete amotrizationMap.values();
            Delete asTransactions;
            Delete polEndsmt.Billings__r;
            Delete polEndsmt.Journal_Entries__r;            
            
            Delete polEndsmt;
            return polEndsmt.Policy__c;
        }
        catch(DmlException e){
            throw new ReversePolicyCancellationCtrlException(e.getDmlMessage(0));
        }
        catch(Exception e){
            throw new ReversePolicyCancellationCtrlException(e.getMessage());
        }
    }
}