force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Endorsement_Number__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Number__c</fullName>
    <label>Endorsement Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PolicyEndorsementEditExtension.cls
public class PolicyEndorsementEditExtension {
    private Policy_Endorsement__c endorsement;
    public PolicyEndorsementEditExtension(ApexPages.StandardController stdController) {
        this.endorsement = (Policy_Endorsement__c)stdController.getRecord();
    }
    public PageReference returnToEditPage(){
        endorsement = [select id,Endorsement_Number__c,name from Policy_Endorsement__c where id=: endorsement.Id];
        if(endorsement.Endorsement_Number__c == 'IL 102' || endorsement.Endorsement_Number__c == 'IL 260'){
            return new PageReference('/apex/PolicyEndorsement?id='+endorsement.Id);
        }else if(endorsement.Endorsement_Number__c == 'IL 152'){
            return new PageReference('/apex/AddingAnAttorney?id='+endorsement.Id);
        }else if(endorsement.Endorsement_Number__c == 'IL 153'){
            return new PageReference('/apex/DeletingAnAttorney?id='+endorsement.Id);
        }else{
            return new PageReference('/apex/EndorsementEditPage?id='+endorsement.Id+'&name='+endorsement.name);
        }
    }
}