force-app/main/default/objects/AOP_Factor__c/AOP_Factor__c.object-meta.xml
<CustomObject>
    <label>AOP Factor</label>
    <nameField>
        <label>AOP Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOP Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AOP_Factor__c/fields/From_Date__c.field-meta.xml
<CustomField>
    <fullName>From_Date__c</fullName>
    <description>This field pull the data from the &apos;From Date&apos; field on Master Factor record.</description>
    <formula>Master_Factor__r.From_Date__c</formula>
    <label>From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AOP_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>AOP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>AOP Factors</relationshipLabel>
    <relationshipName>AOP_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AOP_Factor__c/fields/To_Date__c.field-meta.xml
<CustomField>
    <fullName>To_Date__c</fullName>
    <description>This fields pulls the &apos;To Date&apos; field from the Master Factor record.</description>
    <formula>Master_Factor__r.To_Date__c</formula>
    <label>To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Base_Factor__c/Base_Factor__c.object-meta.xml
<CustomObject>
    <label>Base Factor</label>
    <nameField>
        <label>Base Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Base Value</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Base Factors</relationshipLabel>
    <relationshipName>Base_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deductible_Factor__c/Deductible_Factor__c.object-meta.xml
<CustomObject>
    <label>Deductible Factor</label>
    <nameField>
        <label>Deductible Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deductible Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deductible_Factor__c/fields/From_Date__c.field-meta.xml
<CustomField>
    <fullName>From_Date__c</fullName>
    <formula>Master_Factor__r.From_Date__c</formula>
    <label>From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deductible_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Deductible</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Deductible Factors</relationshipLabel>
    <relationshipName>Deductible_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GEO_Factor__c/GEO_Factor__c.object-meta.xml
<CustomObject>
    <label>GEO Factor</label>
    <nameField>
        <label>GEO Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEO Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GEO_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>GEO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>GEO Factors</relationshipLabel>
    <relationshipName>GEO_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/ILF_Coverage_Factor__c.object-meta.xml
<CustomObject>
    <label>ILF / Limits Factor</label>
    <nameField>
        <label>ILF / Limit Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ILF / Limits Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Coverage_Max_Per_Claim__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Max_Per_Claim__c</fullName>
    <label>Coverage Max Per Claim</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Factor_Value__c.field-meta.xml
<CustomField>
    <fullName>Factor_Value__c</fullName>
    <label>Factor Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Full_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Full_Coverage__c</fullName>
    <label>Aggregate Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Is_10X10_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Is_10X10_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this limit is for 10x10 then it should be checked.</description>
    <label>Is 10X10 Coverage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Is_5X5_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Is_5X5_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is 5X5 Coverage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Is_Excess_Value_Zero__c.field-meta.xml
<CustomField>
    <fullName>Is_Excess_Value_Zero__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Yes then Excess amount will be zero in Excess calculation otherwise another formula will be use.</description>
    <label>Is Excess Value Zero</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Limit_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Limit_External_ID__c</fullName>
    <externalId>true</externalId>
    <label>Limit External ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Lowest_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Lowest_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lowest Coverage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>ILF / Limits Factors</relationshipLabel>
    <relationshipName>ILF_Coverage_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Mid_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Mid_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>1. It is using for Excess calculation.
2. Only one coverage could be checked for one Master record.</inlineHelpText>
    <label>Mid Coverage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Percentage_5X5_Step_0__c.field-meta.xml
<CustomField>
    <fullName>Percentage_5X5_Step_0__c</fullName>
    <label>Percentage 5X5 Step 0</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Percentage_5X5_Step_1__c.field-meta.xml
<CustomField>
    <fullName>Percentage_5X5_Step_1__c</fullName>
    <label>Percentage 5X5 Step 1</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Percentage_5X5_Step_2__c.field-meta.xml
<CustomField>
    <fullName>Percentage_5X5_Step_2__c</fullName>
    <label>Percentage 5X5 Step 2</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Percentage_5X5_Step_3__c.field-meta.xml
<CustomField>
    <fullName>Percentage_5X5_Step_3__c</fullName>
    <label>Percentage 5X5 Step 3</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Percentage_5X5_Step_4__c.field-meta.xml
<CustomField>
    <fullName>Percentage_5X5_Step_4__c</fullName>
    <label>Percentage 5X5 Step 4</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Percentage_5X5_Step_5__c.field-meta.xml
<CustomField>
    <fullName>Percentage_5X5_Step_5__c</fullName>
    <label>Percentage 5X5 Step 5</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Percentage_5X5_Step_6__c.field-meta.xml
<CustomField>
    <fullName>Percentage_5X5_Step_6__c</fullName>
    <label>Percentage 5X5 Step 6</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Percentage_5X5_Step_7__c.field-meta.xml
<CustomField>
    <fullName>Percentage_5X5_Step_7__c</fullName>
    <label>Percentage 5X5 Step 7</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/To_Date__c.field-meta.xml
<CustomField>
    <fullName>To_Date__c</fullName>
    <formula>Master_Factor__r.To_Date__c</formula>
    <label>To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Factor__c/Master_Factor__c.object-meta.xml
<CustomObject>
    <description>Object to hold master records of factors involved in calculations.</description>
    <label>Master Factor</label>
    <nameField>
        <label>Master Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Factor__c/fields/Cloned_From__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloned From</label>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Master Factors</relationshipLabel>
    <relationshipName>Master_Factors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Factor__c/fields/Factor_Type__c.field-meta.xml
<CustomField>
    <fullName>Factor_Type__c</fullName>
    <label>Factor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coverage</fullName>
            </value>
            <value>
                <fullName>Deductible</fullName>
            </value>
            <value>
                <fullName>AOP</fullName>
            </value>
            <value>
                <fullName>Step Rate</fullName>
            </value>
            <value>
                <fullName>Base Value</fullName>
            </value>
            <value>
                <fullName>GEO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Factor__c/recordTypes/Deductible.recordType-meta.xml
<RecordType>
    <fullName>Deductible</fullName>
    <active>true</active>
    <label>Deductible</label>
</RecordType>

force-app/main/default/objects/Step_Rate_Factor__c/Step_Rate_Factor__c.object-meta.xml
<CustomObject>
    <label>Step Rate Factor</label>
    <nameField>
        <label>Step Rate Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Step Rate Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Step_Rate_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Step Rate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Step Rate Factors</relationshipLabel>
    <relationshipName>Step_Rate_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CloneMasterFactorWithChilds.cls
/*
 * 
 * Created By     : Ali Zaidi
 * Created Date   : 12/09/2016
 * Purpose        : This class provides extension for the CloneMasterFactorWithChildsVFP.
 * Name           : CloneMasterFactorWithChilds
 * Referenced     : Currently at the time of creation this class is referenced by CloneMasterFactorWithChildsVFP.
 * 
 *  
 */
public class CloneMasterFactorWithChilds {
    private final String currentMasterFactorId;
    private Master_Factor__c masterFactor;
    public Master_Factor__c cloneFactor {get; set;}
        
    public CloneMasterFactorWithChilds (ApexPages.StandardController stdController) {
        currentMasterFactorId = (String)stdController.getRecord().Id;
        //masterFactor = [SELECT Id, Name, Cloned_From__c, Factor_Type__c, From_Date__c, To_Date__c FROM Master_Factor__c WHERE Id =: currentMasterFactorId];
        Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Master_Factor__c').getDescribe().fields.getMap();
        List<String> fieldNames = new List<String>(fieldMap.keySet());
        List<Master_Factor__c> masterFactors = (List<Master_Factor__c>)Database.query('SELECT '+String.join(fieldNames, ', ')+' FROM Master_Factor__c WHERE Id =: currentMasterFactorId');
        masterFactor = masterFactors[0];
        cloneFactor = masterFactor.clone(false,true);
        cloneFactor.From_Date__c   = Date.today();
        cloneFactor.To_Date__c     = Date.today().addYears(1);
        cloneFactor.Name           = cloneFactor.Factor_Type__c + ' - ' +  cloneFactor.From_Date__c.day() + '/' + cloneFactor.From_Date__c.month() + '/' + cloneFactor.From_Date__c.year() + ' - ' + cloneFactor.To_Date__c.day() + '/' + cloneFactor.To_Date__c.month() + '/' + cloneFactor.To_Date__c.year();
        cloneFactor.Cloned_From__c = currentMasterFactorId;
    }
    
    public PageReference Save () {
        insert cloneFactor;
        
        if (cloneFactor.Factor_Type__c == 'Coverage') {
            list<ILF_Coverage_Factor__c> clonedCoverage = new list<ILF_Coverage_Factor__c>();
            list<ILF_Coverage_Factor__c> coverageToClone = new list<ILF_Coverage_Factor__c>();
            Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('ILF_Coverage_Factor__c').getDescribe().fields.getMap();
            List<String> fieldNames = new List<String>(fieldMap.keySet());
            System.debug('index of => '+fieldNames.indexOf('limit_external_id__c'));
            if(fieldNames.indexOf('limit_external_id__c') != -1 ){
                fieldNames.remove(fieldNames.indexOf('limit_external_id__c'));
            }
            coverageToClone = (List<ILF_Coverage_Factor__c>)Database.query('SELECT '+String.join(fieldNames, ', ')+' FROM ILF_Coverage_Factor__c WHERE Master_Factor__c =: currentMasterFactorId');

            //coverageToClone = [SELECT Coverage_Max_Per_Claim__c, Factor_Value__c, Full_Coverage__c, Id, Is_5X5_Coverage__c, Is_10X10_Coverage__c, Is_Excess_Value_Zero__c, Lowest_Coverage__c, Master_Factor__c, Mid_Coverage__c, Name, Percentage_5X5_Step_0__c, Percentage_5X5_Step_1__c, Percentage_5X5_Step_2__c, Percentage_5X5_Step_3__c, Percentage_5X5_Step_4__c, Percentage_5X5_Step_5__c, Percentage_5X5_Step_6__c, Percentage_5X5_Step_7__c, Percnt_amt_5X5_Step_0__c, Percnt_amt_5X5_Step_1__c, Percnt_amt_5X5_Step_2__c, Percnt_amt_5X5_Step_3__c, Percnt_amt_5X5_Step_4__c, Percnt_amt_5X5_Step_5__c, Percnt_amt_5X5_Step_6__c, Percnt_amt_5X5_Step_7__c, Premium_Rate_5X5__c FROM ILF_Coverage_Factor__c WHERE Master_Factor__c =: currentMasterFactorId];
            
            if (coverageToClone.size() > 0) {
                for (ILF_Coverage_Factor__c cov : coverageToClone) {
                    ILF_Coverage_Factor__c newCov = new ILF_Coverage_Factor__c();
                    newCov = cov.clone(false,true);
                    newCov.Master_Factor__c = cloneFactor.Id;
                    clonedCoverage.add(newCov);
                }
                insert clonedCoverage;
            }
        } else if (cloneFactor.Factor_Type__c == 'Deductible') {
            list<Deductible_Factor__c> clonedDeductible = new list<Deductible_Factor__c>();
            list<Deductible_Factor__c> deductibleToClone = new list<Deductible_Factor__c>();
            Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Deductible_Factor__c').getDescribe().fields.getMap();
            List<String> fieldNames = new List<String>(fieldMap.keySet());
            System.debug('index of => '+fieldNames.indexOf('deductible_external_id__c'));
            if(fieldNames.indexOf('deductible_external_id__c') != -1 ){
                fieldNames.remove(fieldNames.indexOf('deductible_external_id__c'));
            }
            deductibleToClone = (List<Deductible_Factor__c>)Database.query('SELECT '+String.join(fieldNames, ', ')+' FROM Deductible_Factor__c WHERE Master_Factor__c =: currentMasterFactorId');
            //deductibleToClone = [SELECT Deductible_Amount__c, Factor_Value__c, Id, Master_Factor__c, Name FROM Deductible_Factor__c WHERE Master_Factor__c =: currentMasterFactorId];
            
            if (deductibleToClone.size() > 0) {
                for (Deductible_Factor__c ded : deductibleToClone) {
                    Deductible_Factor__c newDed = new Deductible_Factor__c();
                    newDed = ded.clone(false,true);
                    newDed.Master_Factor__c = cloneFactor.Id;
                    clonedDeductible.add(newDed);
                }
                insert clonedDeductible;
            }
        } else if (cloneFactor.Factor_Type__c == 'AOP') {
            list<AOP_Factor__c> clonedAops = new list<AOP_Factor__c>();
            list<AOP_Factor__c> aopsToClone = new list<AOP_Factor__c>();
            Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('AOP_Factor__c').getDescribe().fields.getMap();
            List<String> fieldNames = new List<String>(fieldMap.keySet());
            System.debug('index of => '+fieldNames.indexOf('aop_external_id__c'));
            if(fieldNames.indexOf('aop_external_id__c') != -1 ){
                fieldNames.remove(fieldNames.indexOf('aop_external_id__c'));
            }
            System.debug('index of => '+fieldNames.indexOf('next_aop_factor__c'));
            if(fieldNames.indexOf('next_aop_factor__c') != -1 ){
                fieldNames.remove(fieldNames.indexOf('next_aop_factor__c'));
            }
            aopsToClone = (List<AOP_Factor__c>)Database.query('SELECT '+String.join(fieldNames, ', ')+' FROM AOP_Factor__c WHERE Master_Factor__c =: currentMasterFactorId');
            //aopsToClone = [SELECT Id, Name, AOP_Mod__c, Law_Area_Category__c, Master_Factor__c FROM AOP_Factor__c WHERE Master_Factor__c =: currentMasterFactorId];
            
            if (aopsToClone.size() > 0) {
                for (AOP_Factor__c aopfactor : aopsToClone) {
                    AOP_Factor__c factor = new AOP_Factor__c();
                    factor = aopFactor.clone(false,true);
                    factor.Master_Factor__c = cloneFactor.Id;
                    clonedAops.add(factor);
                }
                insert clonedAops;
                for(Integer i=0;i<aopsToClone.size();i++){
                    aopsToClone[i].Next_AOP_Factor__c  = clonedAops[i].Id;
                }
                update aopsToClone;
            }
        } else if (cloneFactor.Factor_Type__c == 'Step Rate') {
            list<Step_Rate_Factor__c> clonedStep = new list<Step_Rate_Factor__c>();
            list<Step_Rate_Factor__c> stepsToClone = new list<Step_Rate_Factor__c>();
            Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Step_Rate_Factor__c').getDescribe().fields.getMap();
            List<String> fieldNames = new List<String>(fieldMap.keySet());
            stepsToClone = (List<Step_Rate_Factor__c>)Database.query('SELECT '+String.join(fieldNames, ', ')+' FROM Step_Rate_Factor__c WHERE Master_Factor__c =: currentMasterFactorId');
            //stepsToClone = [SELECT Factor_Value_Step_Rate_0__c, Factor_Value_Step_Rate_1__c, Factor_Value_Step_Rate_2__c, Factor_Value_Step_Rate_3__c, Factor_Value_Step_Rate_4__c, Factor_Value_Step_Rate_5__c, Factor_Value_Step_Rate_6__c, Factor_Value_Step_Rate_7__c, Id, Master_Factor__c, Name FROM Step_Rate_Factor__c WHERE Master_Factor__c =: currentMasterFactorId];
            
            if (stepsToClone.size() > 0) {
                for (Step_Rate_Factor__c step : stepsToClone) {
                    Step_Rate_Factor__c newStep = new Step_Rate_Factor__c();
                    newStep = step.clone(false,true);
                    newStep.Master_Factor__c = cloneFactor.Id;
                    clonedStep.add(newStep);
                }
                insert clonedStep;
            }
        } else if (cloneFactor.Factor_Type__c == 'Base Value') {
            list<Base_Factor__c> clonedBase = new list<Base_Factor__c>();
            list<Base_factor__c> baseToClone = new list<Base_Factor__c>();
            Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Base_Factor__c').getDescribe().fields.getMap();
            List<String> fieldNames = new List<String>(fieldMap.keySet());
            baseToClone = (List<Base_Factor__c>)Database.query('SELECT '+String.join(fieldNames, ', ')+' FROM Base_Factor__c WHERE Master_Factor__c =: currentMasterFactorId');
            //baseToClone = [SELECT Base_Amount__c, Id, Master_Factor__c, Name FROM Base_Factor__c WHERE Master_Factor__c =: currentMasterFactorId];
            
            if (baseToClone.size() > 0) {
                for (Base_Factor__c base : baseToClone) {
                    Base_Factor__c newBase = new Base_Factor__c();
                    newBase = base.clone(false,true);
                    newBase.Master_Factor__c = cloneFactor.Id;
                    clonedBase.add(newBase);
                }
                insert clonedBase;
            }
        } else if (cloneFactor.Factor_Type__c == 'GEO') {
            list<GEO_Factor__c> clonedGeo = new list<GEO_Factor__c>();
            list<GEO_Factor__c> geoToClone = new list<GEO_Factor__c>();
            Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('GEO_Factor__c').getDescribe().fields.getMap();
            List<String> fieldNames = new List<String>(fieldMap.keySet());
            System.debug('index of => '+fieldNames.indexOf('geo_external_id__c'));
            if(fieldNames.indexOf('geo_external_id__c') != -1 ){
                fieldNames.remove(fieldNames.indexOf('geo_external_id__c'));
            }
            
            geoToClone = (List<GEO_Factor__c>)Database.query('SELECT '+String.join(fieldNames, ', ')+' FROM GEO_Factor__c WHERE Master_Factor__c =: currentMasterFactorId');
            //geoToClone = [SELECT County__c, Id, Master_Factor__c, Name, Region_Code__c, Region_Factor_Value__c FROM GEO_Factor__c WHERE Master_Factor__c =: currentMasterFactorId];
            
            if (geoToClone.size() > 0) {
                for (GEO_Factor__c geo : geoToClone) {
                    GEO_Factor__c newGeo = new GEO_Factor__c();
                    newGeo = geo.clone(false,true);
                    newGeo.Master_Factor__c = cloneFactor.Id;
                    clonedGeo.add(newGeo);
                }
                insert clonedGeo;
            }
        }
        
        PageReference newFactorPage = new PageReference('/' + cloneFactor.Id);
        newFactorPage.setRedirect(true);
        return newFactorPage;
    }
    
    public PageReference Cancel () {
        PageReference cancelPage = new PageReference('/' + currentMasterFactorId);
        cancelPage.setRedirect(true);
        return cancelPage;
    }
}