force-app/main/default/objects/AOP_Factor__c/AOP_Factor__c.object-meta.xml
<CustomObject>
    <label>AOP Factor</label>
    <nameField>
        <label>AOP Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOP Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/Customer_Application__c.object-meta.xml
<CustomObject>
    <label>Online Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Online NBA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipName>Customer_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Deductible__c.field-meta.xml
<CustomField>
    <fullName>Deductible__c</fullName>
    <label>Deductible</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_AOP__c/Customer_Application_AOP__c.object-meta.xml
<CustomObject>
    <label>Customer Application AOP</label>
    <nameField>
        <displayFormat>CA-AOP-{000000}</displayFormat>
        <label>Customer Application AOP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Application AOP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application_AOP__c/fields/AOP_Factor__c.field-meta.xml
<CustomField>
    <fullName>AOP_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AOP Factor</label>
    <referenceTo>AOP_Factor__c</referenceTo>
    <relationshipLabel>Customer Application AOP</relationshipLabel>
    <relationshipName>Customer_Application_AOP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application_AOP__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Customer Application AOP</relationshipLabel>
    <relationshipName>Customer_Application_AOP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/Customer_Application_Lawyer__c.object-meta.xml
<CustomObject>
    <label>Customer Application Lawyer</label>
    <nameField>
        <label>Customer Application Lawyer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Application Lawyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/ARDC_Number__c.field-meta.xml
<CustomField>
    <fullName>ARDC_Number__c</fullName>
    <label>ARDC Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Average_Number_of_Hours_Worked__c.field-meta.xml
<CustomField>
    <fullName>Average_Number_of_Hours_Worked__c</fullName>
    <label>Average Number of Hours Worked</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Customer Application Lawyers</relationshipLabel>
    <relationshipName>Customer_Application_Lawyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner, Officer, or Shareholder</fullName>
            </value>
            <value>
                <fullName>Partner of a Partnership</fullName>
            </value>
            <value>
                <fullName>Associate or Employed Lawyer</fullName>
            </value>
            <value>
                <fullName>Solo Practitioner</fullName>
            </value>
            <value>
                <fullName>Independent Contractor</fullName>
            </value>
            <value>
                <fullName>Of Counsel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Firm_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Firm_Email_Address__c</fullName>
    <label>Firm Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/ISBA_Number__c.field-meta.xml
<CustomField>
    <fullName>ISBA_Number__c</fullName>
    <label>ISBA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Middle_Initial__c.field-meta.xml
<CustomField>
    <fullName>Middle_Initial__c</fullName>
    <label>Middle Initial</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application_Lawyer__c/fields/Personal_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Personal_Email_Address__c</fullName>
    <label>Personal Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Deductible_Factor__c/Deductible_Factor__c.object-meta.xml
<CustomObject>
    <label>Deductible Factor</label>
    <nameField>
        <label>Deductible Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deductible Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILF_Coverage_Factor__c/ILF_Coverage_Factor__c.object-meta.xml
<CustomObject>
    <label>ILF / Limits Factor</label>
    <nameField>
        <label>ILF / Limit Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ILF / Limits Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Quote__c/Policy_Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Quote-{000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Quote__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Limits</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>ILF_Coverage_Factor__c.Master_Factor__r.Default__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_Coverage_Factor__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_Coverage_Factor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ILF_Coverage_Factor__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Deductible__c.field-meta.xml
<CustomField>
    <fullName>Deductible__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deductibles</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>Deductible_Factor__c.Master_Factor__r.Default__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_Deductible_Factor__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_Deductible_Factor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Deductible_Factor__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerApplicationCreationEmail_Ctrl.cls
public class CustomerApplicationCreationEmail_Ctrl {
    public Id customerAppId;
    public String salesforceBaseURL{get;set;}
    public Customer_Application__c application{get;set;}
    public List<Policy_Quote__c> quotes{get;set;}
    public List<Customer_Application_Lawyer__c> lawyers{get;set;}
    public List<Customer_Application_AOP__c> aopList{get;set;}
    public CustomerApplicationCreationEmail_Ctrl(){
		salesforceBaseURL=System.URL.getOrgDomainUrl().toExternalForm();
    }
    public void setCustomerAppId(Id customerAppId){
        DescribeSObjectResult describeResult = Customer_Application__c.getSObjectType().getDescribe();
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
        fieldNames.add('County__r.Name');
        String query =	  ' SELECT RecordType.Name,' +	      String.join( fieldNames, ',' ) +	  ' FROM ' +	      describeResult.getName() +	  ' WHERE ' +	      ' id = :customerAppId ' +	  ' LIMIT 1 '	;	
        if(customerAppId == null){
            application = new Customer_Application__c();
        }else{
            if(!salesforceBaseURL.endsWith('/view')){
               salesforceBaseURL = salesforceBaseURL.removeEnd('my.salesforce.com');
               salesforceBaseURL+= 'lightning.force.com/lightning/r/Customer_Application__c/'+customerAppId+'/view'; 
            }
            application = Database.query( query );
            quotes = new List<Policy_Quote__c>([select id,Coverage__r.Name,Deductible__r.Name from Policy_Quote__c where Customer_Application__c=:customerAppId ]);
            lawyers = new List<Customer_Application_Lawyer__c>([select id,Name,Middle_Initial__c,Last_Name__c,Designation__c,Date_of_Hire__c,ISBA_Number__c,ARDC_Number__c,Average_Number_of_Hours_Worked__c,Firm_Email_Address__c,Birthday__c,Cell_Phone__c,Personal_Email_Address__c from Customer_Application_Lawyer__c where Customer_Application__c=:customerAppId]);
            aopList = new List<Customer_Application_AOP__c>([SELECT Id, Percentage__c, AOP_Factor__r.Name FROM Customer_Application_AOP__c WHERE Customer_Application__c =:customerAppId and Percentage__c>0]);
        }
    }
    public Id getCustomerAppId(){
        return customerAppId;
    }
}