force-app/main/default/objects/AOP_Factor__c/AOP_Factor__c.object-meta.xml
<CustomObject>
    <label>AOP Factor</label>
    <nameField>
        <label>AOP Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOP Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AOP_Factor__c/fields/AOP_Mod__c.field-meta.xml
<CustomField>
    <fullName>AOP_Mod__c</fullName>
    <label>AOP Mod</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AOP_Factor__c/fields/From_Date__c.field-meta.xml
<CustomField>
    <fullName>From_Date__c</fullName>
    <description>This field pull the data from the &apos;From Date&apos; field on Master Factor record.</description>
    <formula>Master_Factor__r.From_Date__c</formula>
    <label>From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AOP_Factor__c/fields/Law_Area_Category__c.field-meta.xml
<CustomField>
    <fullName>Law_Area_Category__c</fullName>
    <label>Law Area Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AOP_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>AOP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>AOP Factors</relationshipLabel>
    <relationshipName>AOP_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AOP_Factor__c/fields/To_Date__c.field-meta.xml
<CustomField>
    <fullName>To_Date__c</fullName>
    <description>This fields pulls the &apos;To Date&apos; field from the Master Factor record.</description>
    <formula>Master_Factor__r.To_Date__c</formula>
    <label>To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Base_Factor__c/Base_Factor__c.object-meta.xml
<CustomObject>
    <label>Base Factor</label>
    <nameField>
        <label>Base Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Factor__c/fields/Base_Amount__c.field-meta.xml
<CustomField>
    <fullName>Base_Amount__c</fullName>
    <label>Base Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Base Value</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Base Factors</relationshipLabel>
    <relationshipName>Base_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deductible_Factor__c/Deductible_Factor__c.object-meta.xml
<CustomObject>
    <label>Deductible Factor</label>
    <nameField>
        <label>Deductible Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deductible Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deductible_Factor__c/fields/Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount__c</fullName>
    <label>Deductible Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deductible_Factor__c/fields/From_Date__c.field-meta.xml
<CustomField>
    <fullName>From_Date__c</fullName>
    <formula>Master_Factor__r.From_Date__c</formula>
    <label>From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deductible_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Deductible</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Deductible Factors</relationshipLabel>
    <relationshipName>Deductible_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GEO_Factor__c/GEO_Factor__c.object-meta.xml
<CustomObject>
    <label>GEO Factor</label>
    <nameField>
        <label>GEO Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEO Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GEO_Factor__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>GEO Factors</relationshipLabel>
    <relationshipName>GEO_Factors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GEO_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>GEO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>GEO Factors</relationshipLabel>
    <relationshipName>GEO_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GEO_Factor__c/fields/Region_Factor_Value__c.field-meta.xml
<CustomField>
    <fullName>Region_Factor_Value__c</fullName>
    <label>Geo Factor Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/ILF_Coverage_Factor__c.object-meta.xml
<CustomObject>
    <label>ILF / Limits Factor</label>
    <nameField>
        <label>ILF / Limit Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ILF / Limits Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Coverage_Max_Per_Claim__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Max_Per_Claim__c</fullName>
    <label>Coverage Max Per Claim</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Factor_Value__c.field-meta.xml
<CustomField>
    <fullName>Factor_Value__c</fullName>
    <label>Factor Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Full_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Full_Coverage__c</fullName>
    <label>Aggregate Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Lowest_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Lowest_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lowest Coverage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>ILF / Limits Factors</relationshipLabel>
    <relationshipName>ILF_Coverage_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/To_Date__c.field-meta.xml
<CustomField>
    <fullName>To_Date__c</fullName>
    <formula>Master_Factor__r.To_Date__c</formula>
    <label>To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Factor__c/Master_Factor__c.object-meta.xml
<CustomObject>
    <description>Object to hold master records of factors involved in calculations.</description>
    <label>Master Factor</label>
    <nameField>
        <label>Master Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Factor__c/fields/Factor_Type__c.field-meta.xml
<CustomField>
    <fullName>Factor_Type__c</fullName>
    <label>Factor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coverage</fullName>
            </value>
            <value>
                <fullName>Deductible</fullName>
            </value>
            <value>
                <fullName>AOP</fullName>
            </value>
            <value>
                <fullName>Step Rate</fullName>
            </value>
            <value>
                <fullName>Base Value</fullName>
            </value>
            <value>
                <fullName>GEO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Factor__c/recordTypes/Area_of_Practice.recordType-meta.xml
<RecordType>
    <fullName>Area_of_Practice</fullName>
    <active>true</active>
    <label>Area of Practice</label>
</RecordType>

force-app/main/default/objects/Master_Factor__c/recordTypes/Base_Value.recordType-meta.xml
<RecordType>
    <fullName>Base_Value</fullName>
    <active>true</active>
    <label>Base Value</label>
</RecordType>

force-app/main/default/objects/Master_Factor__c/recordTypes/Deductible.recordType-meta.xml
<RecordType>
    <fullName>Deductible</fullName>
    <active>true</active>
    <label>Deductible</label>
</RecordType>

force-app/main/default/objects/Master_Factor__c/recordTypes/GEO_Mode.recordType-meta.xml
<RecordType>
    <fullName>GEO_Mode</fullName>
    <active>true</active>
    <label>Geo Mod</label>
</RecordType>

force-app/main/default/objects/Master_Factor__c/recordTypes/Limit_Coverage.recordType-meta.xml
<RecordType>
    <fullName>Limit_Coverage</fullName>
    <active>true</active>
    <label>Limits</label>
</RecordType>

force-app/main/default/objects/Master_Factor__c/recordTypes/Step_Rate.recordType-meta.xml
<RecordType>
    <fullName>Step_Rate</fullName>
    <active>true</active>
    <label>Step Rate</label>
</RecordType>

force-app/main/default/objects/Step_Rate_Factor__c/Step_Rate_Factor__c.object-meta.xml
<CustomObject>
    <label>Step Rate Factor</label>
    <nameField>
        <label>Step Rate Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Step Rate Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Step_Rate_Factor__c/fields/Factor_Value_Step_Rate_0__c.field-meta.xml
<CustomField>
    <fullName>Factor_Value_Step_Rate_0__c</fullName>
    <label>Factor Value Step Rate 0</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Step_Rate_Factor__c/fields/Factor_Value_Step_Rate_1__c.field-meta.xml
<CustomField>
    <fullName>Factor_Value_Step_Rate_1__c</fullName>
    <label>Factor Value Step Rate 1</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Step_Rate_Factor__c/fields/Factor_Value_Step_Rate_2__c.field-meta.xml
<CustomField>
    <fullName>Factor_Value_Step_Rate_2__c</fullName>
    <label>Factor Value Step Rate 2</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Step_Rate_Factor__c/fields/Factor_Value_Step_Rate_3__c.field-meta.xml
<CustomField>
    <fullName>Factor_Value_Step_Rate_3__c</fullName>
    <label>Factor Value Step Rate 3</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Step_Rate_Factor__c/fields/Factor_Value_Step_Rate_4__c.field-meta.xml
<CustomField>
    <fullName>Factor_Value_Step_Rate_4__c</fullName>
    <label>Factor Value Step Rate 4</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Step_Rate_Factor__c/fields/Factor_Value_Step_Rate_5__c.field-meta.xml
<CustomField>
    <fullName>Factor_Value_Step_Rate_5__c</fullName>
    <label>Factor Value Step Rate 5</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Step_Rate_Factor__c/fields/Factor_Value_Step_Rate_6__c.field-meta.xml
<CustomField>
    <fullName>Factor_Value_Step_Rate_6__c</fullName>
    <label>Factor Value Step Rate 6</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Step_Rate_Factor__c/fields/Factor_Value_Step_Rate_7__c.field-meta.xml
<CustomField>
    <fullName>Factor_Value_Step_Rate_7__c</fullName>
    <label>Factor Value Step Rate 7</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Step_Rate_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Step Rate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Step Rate Factors</relationshipLabel>
    <relationshipName>Step_Rate_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestCloneMasterFactorWithChilds.cls
/*
 * 
 * Created By     : Ali Zaidi
 * Created Date   : 11/19/2016
 * Purpose        : This class is the test class for CloneMasterFactorWithChilds Controller.
 * Name           : TestCloneMasterFactorWithChilds
 * Referenced     : Currently at the time of creation this class is referenced by CloneMasterFactorWithChilds Controller.
 * 
 *  
 */
@isTest
private class TestCloneMasterFactorWithChilds {

    @testSetup static void setup() {
        Map<String,String> mapRecordTypes = new Map<String,String>();
        
        for (RecordType rt : [SELECT DeveloperName,Id FROM RecordType WHERE SobjectType = 'Master_Factor__c']) {
            mapRecordTypes.put(rt.DeveloperName,rt.Id);
        }
        
        Master_Factor__c MasterFactorAOP = new Master_Factor__c();
        MasterFactorAOP.Name = 'AOP';
        MasterFactorAOP.RecordTypeId = mapRecordTypes.get('Area_of_Practice');
        MasterFactorAOP.Factor_Type__c = 'AOP';
        MasterFactorAOP.Default__c = true;
        MasterFactorAOP.From_Date__c = Date.today();
        MasterFactorAOP.To_Date__c = Date.today() + 1;
        insert MasterFactorAOP;
        
        AOP_Factor__c FactorAOP = new AOP_Factor__c();
        FactorAOP.Name = 'Admirality';
        FactorAOP.AOP_Mod__c = 0.86;
        FactorAOP.Law_Area_Category__c = 'Admirality';
        FactorAOP.Master_Factor__c = MasterFactorAOP.Id;
        insert FactorAOP;
        
        Master_Factor__c MasterFactorCoverage = new Master_Factor__c();
        MasterFactorCoverage.Name = 'Coverage';
        MasterFactorCoverage.RecordTypeId = mapRecordTypes.get('Limit_Coverage');
        MasterFactorCoverage.Factor_Type__c = 'Coverage';
        MasterFactorCoverage.Default__c = true;
        MasterFactorCoverage.From_Date__c = Date.today();
        MasterFactorCoverage.To_Date__c = Date.today() + 1;
        insert MasterFactorCoverage;
        
        ILF_Coverage_Factor__c FactorCoverage = new ILF_Coverage_Factor__c();
        FactorCoverage.Name = '250,000 / 500,000';
        FactorCoverage.Lowest_Coverage__c = true;
        FactorCoverage.Master_Factor__c = MasterFactorCoverage.Id;
        FactorCoverage.Coverage_Max_Per_Claim__c = 500000;
        FactorCoverage.Full_Coverage__c = 250000;
        FactorCoverage.Factor_Value__c = 0.96;
        insert FactorCoverage;
        
        Master_Factor__c MasterFactorDeductible = new Master_Factor__c();
        MasterFactorDeductible.Name = 'Coverage';
        MasterFactorDeductible.RecordTypeId = mapRecordTypes.get('Deductible');
        MasterFactorDeductible.Factor_Type__c = 'Deductible';
        MasterFactorDeductible.Default__c = true;
        MasterFactorDeductible.From_Date__c = Date.today();
        MasterFactorDeductible.To_Date__c = Date.today() + 1;
        insert MasterFactorDeductible;
        
        Deductible_Factor__c FactorDeductible = new Deductible_Factor__c();
        FactorDeductible.Name = '1000';
        FactorDeductible.Deductible_Amount__c = 1000;
        FactorDeductible.Factor_Value__c = 0.96;
        FactorDeductible.Master_Factor__c = MasterFactorDeductible.Id;
        insert FactorDeductible;
        
        Master_Factor__c MasterFactorStepRate = new Master_Factor__c();
        MasterFactorStepRate.Name = 'Step Rate';
        MasterFactorStepRate.RecordTypeId = mapRecordTypes.get('Step_Rate');
        MasterFactorStepRate.Factor_Type__c = 'Step Rate';
        MasterFactorStepRate.Default__c = true;
        MasterFactorStepRate.From_Date__c = Date.today();
        MasterFactorStepRate.To_Date__c = Date.today() + 1;
        insert MasterFactorStepRate;
        
        Step_Rate_Factor__c FactorStepRate = new Step_Rate_Factor__c();
        FactorStepRate.Name = 'Step Rate';
        FactorStepRate.Factor_Value_Step_Rate_0__c = 1;
        FactorStepRate.Factor_Value_Step_Rate_1__c = 1;
        FactorStepRate.Factor_Value_Step_Rate_2__c = 1;
        FactorStepRate.Factor_Value_Step_Rate_3__c = 1;
        FactorStepRate.Factor_Value_Step_Rate_4__c = 1;
        FactorStepRate.Factor_Value_Step_Rate_5__c = 1;
        FactorStepRate.Factor_Value_Step_Rate_6__c = 1;
        FactorStepRate.Factor_Value_Step_Rate_7__c = 1;
        FactorStepRate.Master_Factor__c = MasterFactorStepRate.Id;
        insert FactorStepRate;
        
        Master_Factor__c MasterFactorGEO = new Master_Factor__c();
        MasterFactorGEO.Name = 'GEO';
        MasterFactorGEO.RecordTypeId = mapRecordTypes.get('GEO_Mode');
        MasterFactorGEO.Factor_Type__c = 'GEO';
        MasterFactorGEO.Default__c = true;
        MasterFactorGEO.From_Date__c = Date.today();
        MasterFactorGEO.To_Date__c = Date.today() + 1;
        insert MasterFactorGEO;
        
        County__c county = new County__c();
        county.Name = 'ADAMS';
        county.Region__c = '5';
        insert county;
        
        GEO_Factor__c FactorGEO = new GEO_Factor__c();
        FactorGEO.Name = 'GEO Factor';
        FactorGEO.County__c = county.Id;
        FactorGEO.Master_Factor__c = MasterFactorGEO.Id;
        FactorGEO.Region_Factor_Value__c = 5;
        insert FactorGEO;
        
        Master_Factor__c MasterFactorBase = new Master_Factor__c();
        MasterFactorBase.Name = 'Base Value';
        MasterFactorBase.RecordTypeId = mapRecordTypes.get('Base_Value');
        MasterFactorBase.Factor_Type__c = 'Base Value';
        MasterFactorBase.Default__c = true;
        MasterFactorBase.From_Date__c = Date.today();
        MasterFactorBase.To_Date__c = Date.today() + 1;
        insert MasterFactorBase;
        
        Base_Factor__c FactorBase = new Base_Factor__c();
        FactorBase.Name = 'Base Factor';
        FactorBase.Base_Amount__c = 1067;
        FactorBase.Master_Factor__c = MasterFactorBase.Id;
        insert FactorBase;
    }
    
    @isTest static void cloneAOPFactor() {
        Master_Factor__c MasterFactorAOP = [SELECT Id, Name, Factor_Type__c, Default__c, From_Date__c, To_Date__c FROM Master_Factor__c WHERE Factor_Type__c = 'AOP'];
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(MasterFactorAOP);
        CloneMasterFactorWithChilds ctrl = new CloneMasterFactorWithChilds(sc);
        
        ctrl.Cancel();
        
        ctrl.Save();
        Test.stopTest();
    }
    
    @isTest static void cloneCoverageFactor() {
        Master_Factor__c MasterFactorCoverage = [SELECT Id, Name, Factor_Type__c, Default__c, From_Date__c, To_Date__c FROM Master_Factor__c WHERE Factor_Type__c = 'Coverage'];
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(MasterFactorCoverage);
        CloneMasterFactorWithChilds ctrl = new CloneMasterFactorWithChilds(sc);
        
        ctrl.Cancel();
        
        ctrl.Save();
        Test.stopTest();
    }
    
    @isTest static void cloneDeductibleFactor() {
        Master_Factor__c MasterFactorCoverage = [SELECT Id, Name, Factor_Type__c, Default__c, From_Date__c, To_Date__c FROM Master_Factor__c WHERE Factor_Type__c = 'Deductible'];
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(MasterFactorCoverage);
        CloneMasterFactorWithChilds ctrl = new CloneMasterFactorWithChilds(sc);
        
        ctrl.Cancel();
        
        ctrl.Save();
        Test.stopTest();
    }
    
    @isTest static void cloneStepRateFactor() {
        Master_Factor__c MasterFactorStepRate = [SELECT Id, Name, Factor_Type__c, Default__c, From_Date__c, To_Date__c FROM Master_Factor__c WHERE Factor_Type__c = 'Step Rate'];
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(MasterFactorStepRate);
        CloneMasterFactorWithChilds ctrl = new CloneMasterFactorWithChilds(sc);
        
        ctrl.Cancel();
        
        ctrl.Save();
        Test.stopTest();
    }
    
    @isTest static void cloneGEOFactor() {
        Master_Factor__c MasterFactorGEO = [SELECT Id, Name, Factor_Type__c, Default__c, From_Date__c, To_Date__c FROM Master_Factor__c WHERE Factor_Type__c = 'GEO'];
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(MasterFactorGEO);
        CloneMasterFactorWithChilds ctrl = new CloneMasterFactorWithChilds(sc);
        
        ctrl.Cancel();
        
        ctrl.Save();
        Test.stopTest();
    }
    
    @isTest static void cloneBaseFactor() {
        Master_Factor__c MasterFactorBase = [SELECT Id, Name, Factor_Type__c, Default__c, From_Date__c, To_Date__c FROM Master_Factor__c WHERE Factor_Type__c = 'Base Value'];
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(MasterFactorBase);
        CloneMasterFactorWithChilds ctrl = new CloneMasterFactorWithChilds(sc);
        
        ctrl.Cancel();
        
        ctrl.Save();
        Test.stopTest();
    }
}