force-app/main/default/objects/AOP_Factor__c/AOP_Factor__c.object-meta.xml
<CustomObject>
    <label>AOP Factor</label>
    <nameField>
        <label>AOP Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOP Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AOP_Factor__c/fields/AOP_Mod__c.field-meta.xml
<CustomField>
    <fullName>AOP_Mod__c</fullName>
    <label>AOP Mod</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/AOP_Factor__c.field-meta.xml
<CustomField>
    <fullName>AOP_Factor__c</fullName>
    <defaultValue>1</defaultValue>
    <description>For sum of area of practice</description>
    <label>AOP Mod</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_AOP__c/Policy_AOP__c.object-meta.xml
<CustomObject>
    <label>Area of Practice</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Area of Practice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Area of Practice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_AOP__c/fields/AOP__c.field-meta.xml
<CustomField>
    <fullName>AOP__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AOP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>AOP_Factor__c.Master_Factor__r.Default__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_Factor__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_Factor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AOP_Factor__c</referenceTo>
    <relationshipLabel>Area of Practice (AOP)</relationshipLabel>
    <relationshipName>Area_of_Practice1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_AOP__c/fields/Factor_Mod__c.field-meta.xml
<CustomField>
    <fullName>Factor_Mod__c</fullName>
    <label>Factor Mod</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_AOP__c/fields/Percentage_Value__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Value__c</fullName>
    <label>Percentage Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_AOP__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Area of Practice</relationshipLabel>
    <relationshipName>Policy_AOPs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PolicyAOPTriggerHandler.cls
public class PolicyAOPTriggerHandler {
    public static void onBeforeDelete(List<Policy_AOP__c> oldList){
        preventAOPDeletionForPolicy(oldList);
    }
    public static void onBeforeInsert(List<Policy_AOP__c> newList){
        updatePercentageValue(newList);
    }
    public static void onBeforeUpdate(List<Policy_AOP__c> newList,Map<Id,Policy_AOP__c> newMap){
        updatePercentageValue(newList);
    }
    public static void preventAOPDeletionForPolicy(List<Policy_AOP__c> oldList){
        Set<Id> policyIds = new Set<Id>();
        for(Policy_AOP__c aop : oldList){
            policyIds.add(aop.Policy__c);
        }
        Map<Id,Policy__c> policyMap = new Map<Id,Policy__c>([select id,RecordType.Name from Policy__c where id in: policyIds]);
        for(Policy_AOP__c aop : oldList){
            if(policyMap.containsKey(aop.Policy__c) && policyMap.get(aop.Policy__c).RecordType.Name == 'Policy'){
                aop.addError('You are not allowed to delete the AOP once the Application is bound.');
            }
        }
    }
    public static void updatePercentageValue(List<Policy_AOP__c> newList){
        Map<ID,AOP_Factor__c>  AOPFactorMap  = new  Map<ID,AOP_Factor__c>([select ID,name,AOP_Mod__c from AOP_Factor__C]);
        For(Policy_AOP__C PolicyAOPFor : newList){
            PolicyAOPFor.Factor_Mod__c = AOPFactorMap.get(PolicyAOPFor.AOP__c).AOP_Mod__c;
            
            if(PolicyAOPFor.Factor_Mod__c == null){
                PolicyAOPFor.Factor_Mod__c = 0;
            }
            PolicyAOPFor.Percentage_Value__c = PolicyAOPFor.Factor_Mod__c *   PolicyAOPFor.Percentage__c / 100;          
        }
    }
}