force-app/main/default/objects/AOP_Factor__c/AOP_Factor__c.object-meta.xml
<CustomObject>
    <label>AOP Factor</label>
    <nameField>
        <label>AOP Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOP Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AOP_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>AOP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>AOP Factors</relationshipLabel>
    <relationshipName>AOP_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Base_Factor__c/Base_Factor__c.object-meta.xml
<CustomObject>
    <label>Base Factor</label>
    <nameField>
        <label>Base Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Factor__c/fields/Base_Amount__c.field-meta.xml
<CustomField>
    <fullName>Base_Amount__c</fullName>
    <label>Base Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Base Value</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Base Factors</relationshipLabel>
    <relationshipName>Base_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deductible_Factor__c/Deductible_Factor__c.object-meta.xml
<CustomObject>
    <label>Deductible Factor</label>
    <nameField>
        <label>Deductible Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deductible Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deductible_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Deductible</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Deductible Factors</relationshipLabel>
    <relationshipName>Deductible_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GEO_Factor__c/GEO_Factor__c.object-meta.xml
<CustomObject>
    <label>GEO Factor</label>
    <nameField>
        <label>GEO Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEO Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GEO_Factor__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>GEO Factors</relationshipLabel>
    <relationshipName>GEO_Factors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GEO_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>GEO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>GEO Factors</relationshipLabel>
    <relationshipName>GEO_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ILF_Coverage_Factor__c/ILF_Coverage_Factor__c.object-meta.xml
<CustomObject>
    <label>ILF / Limits Factor</label>
    <nameField>
        <label>ILF / Limit Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ILF / Limits Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILF_Coverage_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Coverage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>ILF / Limits Factors</relationshipLabel>
    <relationshipName>ILF_Coverage_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Base_Amount__c.field-meta.xml
<CustomField>
    <fullName>Base_Amount__c</fullName>
    <label>Base Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>County</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>GEO_Factor__c.Master_Factor__r.Default__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Bypass_Default_County_Factor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>GEO_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Deductible_ID__c.field-meta.xml
<CustomField>
    <fullName>Deductible_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deductible</label>
    <referenceTo>Deductible_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Firm_Mod__c.field-meta.xml
<CustomField>
    <fullName>Firm_Mod__c</fullName>
    <label>Firm Mod</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Limits</label>
    <referenceTo>ILF_Coverage_Factor__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Mod_230__c.field-meta.xml
<CustomField>
    <fullName>Mod_230__c</fullName>
    <label>Mod_230</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Mod_234__c.field-meta.xml
<CustomField>
    <fullName>Mod_234__c</fullName>
    <label>Mod_234</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Endorsement__c/Policy_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsement</label>
    <nameField>
        <label>Policy Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Endorsement__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Endorsements</relationshipLabel>
    <relationshipName>Policy_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Endorsement__c/recordTypes/General.recordType-meta.xml
<RecordType>
    <fullName>General</fullName>
    <active>true</active>
    <label>General</label>
</RecordType>

force-app/main/default/objects/Policy_Quote__c/Policy_Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Quote-{000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Quote__c/fields/Deductible_Factor__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Factor__c</fullName>
    <label>Deductible Factor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Mod_230__c.field-meta.xml
<CustomField>
    <fullName>Mod_230__c</fullName>
    <label>Mod_230</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Mod_234__c.field-meta.xml
<CustomField>
    <fullName>Mod_234__c</fullName>
    <label>Mod_234</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Application</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Policy_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Step_Rate_Factor__c/Step_Rate_Factor__c.object-meta.xml
<CustomObject>
    <label>Step Rate Factor</label>
    <nameField>
        <label>Step Rate Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Step Rate Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Step_Rate_Factor__c/fields/Master_Factor__c.field-meta.xml
<CustomField>
    <fullName>Master_Factor__c</fullName>
    <label>Master Factor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Master_Factor__c.Factor_Type__c</field>
            <operation>equals</operation>
            <value>Step Rate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Factor__c</referenceTo>
    <relationshipLabel>Step Rate Factors</relationshipLabel>
    <relationshipName>Step_Rate_Factors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EZRenewal2_Ctrl_Test.cls
@isTest
private class EZRenewal2_Ctrl_Test {
    
    @testSetup static void setup() {
        
        Account acc                   = TestDataFactory.createAccounts('Test Account');
        acc.AccountNumber             = '123456';
        acc.Vendor_Account__c         = true;
        insert acc;
        
        Contact con                   = TestDataFactory.createContact('Test Contact',acc.id);
        insert con;
        
        AccountContactJunction__c acj = TestDataFactory.createAccConJunc(acc.id, con.id);
        acj.Name                      = 'Test Name';
        insert acj;
        
        List<AcctSeed__GL_Account__c> glAccounts = TestDataFactory.createGLAccounts();        
        insert glAccounts;
        
        List<AcctSeed__Billing_Format__c> billingFormats = TestDataFactory.createBillingFormats();        
        insert billingFormats ;
        
        List<AcctSeed__Ledger__c> ledgers = TestDataFactory.createLedgers(glAccounts[0].id,billingFormats[0].id,billingFormats[1].id,billingFormats[2].id,billingFormats[3].id,billingFormats[4].id);
        insert ledgers;
        
        AcctSeed__Accounting_Settings__c settings = TestDataFactory.createAccountsetting(ledgers[0].id,glAccounts[0].Id,glAccounts[1].Id,glAccounts[2].Id,glAccounts[3].Id,glAccounts[4].Id,glAccounts[5].Id,glAccounts[6].Id,billingFormats[0].Id);
        insert settings;
        
        Opportunity opp               = TestDataFactory.createOpp(acc.id);
        insert opp;
        
        Master_Factor__c mas          = TestDataFactory.createMasterfactor('Test Master Factor','Step rate');
        insert mas;
        
        County__c county = TestDataFactory.createCounty();
        insert county ;
        
        Geo_Factor__c geo = TestDataFactory.createGeoFactor(mas.Id,county.Id);
        
        insert geo;
        
        Master_Factor__c masterFactor = TestDataFactory.createMasterfactor('Test Master Factor','Step rate');
        insert masterFactor;
        
        Step_Rate_Factor__c stepRateFactor = TestDataFactory.createStepFactor(masterFactor.Id);
        insert stepRateFactor;
        test.startTest();
        Master_Factor__c masterFactor1 = TestDataFactory.createMasterfactor('Test Master Factor1','Base Value');
        insert masterFactor1;
        
        Base_Factor__c baseFactor = TestDataFactory.createBaseFactor(masterFactor1.Id);
        insert baseFactor;
        
        Map<String,String> mapRecordTypes = new Map<String,String>();
        
        for (RecordType rt : [SELECT DeveloperName,Id FROM RecordType WHERE SobjectType = 'Master_Factor__c']) {
            mapRecordTypes.put(rt.DeveloperName,rt.Id);
        }
        
        Master_Factor__c MasterFactorCoverage = TestDataFactory.createMasterfactor('Coverage','Coverage');
        MasterFactorCoverage.RecordTypeId = mapRecordTypes.get('Limit_Coverage');
        insert MasterFactorCoverage;
        
        ILF_Coverage_Factor__c FactorCoverage = TestDataFactory.createCoveragefactor(MasterFactorCoverage.Id);
        insert FactorCoverage;
        
        Master_Factor__c mas12       = TestDataFactory.createMasterfactor('Test Master Factor1','Deductible');
        insert mas12;
        
        Deductible_Factor__c DedFac = TestDataFactory.createDeductiblefactor(mas12.Id);
        Insert DedFac; 
        /*
        Policy__c pol                 = TestDataFactory.createPolicy(acc.id,opp.id,geo.id,'Application');
        pol.Base_Amount__c = 100;
        pol.Firm_Mod__c = 2;
        pol.Limit__c = FactorCoverage.Id;
        pol.Deductible_ID__c = DedFac.id;
        
        insert pol;
        */
         
        ILF_Coverage_Factor__c ilfCoverageLowest = TestDataFactory.createCoveragefactor(mas.id);
        insert ilfCoverageLowest;
        
        Master_Factor__c masterFactorNew = TestDataFactory.createMasterfactor('Test Master Factor4','AOP');
        insert masterFactorNew;
        
        ILF_Coverage_Factor__c coverageFactorObj = TestDataFactory.createCoveragefactor(masterFactorNew.Id);
        insert coverageFactorObj;
        
        Deductible_Factor__c dedFactorObj = TestDataFactory.createDeductiblefactor(masterFactorNew.Id);
        insert dedFactorObj;
        
        Policy__c pol = TestDataFactory.createActivePolicy(acc.id,opp.id,geo.id,'Policy');
        pol.Limit__c = coverageFactorObj.Id;
        pol.Deductible_ID__c = dedFactorObj.Id;
        pol.Base_Amount__c = 100;
        pol.Firm_Mod__c = 2;
        pol.Limit__c = FactorCoverage.Id;
        pol.Deductible_ID__c = DedFac.id;
        insert pol;
        
        EZRenewal2_Ctrl  objEz1 = new EZRenewal2_Ctrl ();
        objEz1.setrecordId(pol.Id);
        objEz1.getrecordId();
            
        
        Policy_Quote__c objPolQuote = TestDataFactory.createPolicyQuote(pol.Id,coverageFactorObj.Id,DedFac.id);
        objPolQuote.Mod_230__c=10;
        objPolQuote.Mod_234__c=10;
        objPolQuote.Mod_261__c=2;
        insert objPolQuote;
        
        Id devRecordTypeId = Schema.SObjectType.Policy_Endorsement__c.getRecordTypeInfosByName().get('General').getRecordTypeId();
        
        
        Endorsement__c endorse = TestDataFactory.createEndorsement('IL 152','Functional','General');
        insert endorse;
        
        Endorsement_Version__c endorseVersion = TestDataFactory.createEndorsementVersion(endorse.Id);
        insert endorseVersion;
        
        Policy_Endorsement__c poicyEndorse = TestDataFactory.createPolicyEndorsement(acc.id,pol.id,'General');
        poicyEndorse.Endorsement_Effective_Date__c = system.today()-2;
        insert poicyEndorse;
       
        AOP_Factor__c aopFactor = TestDataFactory.createAopFactor(masterFactorNew.Id);
        insert aopFactor;
        
        PageReference pageRef = Page.EndorsementEditPage;
        System.Test.setCurrentPage(pageRef);
        
        ApexPages.currentPage().getParameters().put('name','test');
        // ApexPages.currentPage().getParameters().put('effectiveDate',string.valueof(System.today().addDays(-1)));
        ApexPages.currentPage().getParameters().put('id',pol.id);
        ApexPages.currentPage().getParameters().put('RecordType',devRecordTypeId);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(poicyEndorse);
        EndorsementEditVFCtrl objEndorsement = new EndorsementEditVFCtrl(sc); 
        
        Test.stopTest();
    }
    @isTest static void TestMethod2() {
        test.starttest();
        PageReference pageRef = Page.EndorsementEditPage;
        System.Test.setCurrentPage(pageRef);
        Id devRecordTypeId = Schema.SObjectType.Policy_Endorsement__c.getRecordTypeInfosByName().get('General').getRecordTypeId();
        
        List<policy__c> lstPolicy = [select id from policy__c];
        
        List<Policy_Endorsement__c> lstpoicyEndorse = [select id,policy__c from Policy_Endorsement__c where policy__c in : lstPolicy ];
        system.debug('-------endors-------'+lstpoicyEndorse);
        
        Policy_Endorsement__c objEndors = lstpoicyEndorse[0];
        ApexPages.currentPage().getParameters().put('name','test');
        ApexPages.currentPage().getParameters().put('id',lstPolicy[0].id);
        ApexPages.currentPage().getParameters().put('RecordType',devRecordTypeId);
        EZRenewal2_Ctrl  objEZ = new EZRenewal2_Ctrl ();
        
        objEz.setrecordId(lstPolicy[0].Id);
        objEz.getrecordId();
        Test.stopTest();
    }
}