force-app/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{0}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Note__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Policy_Claim__c</referenceTo>
    <relationshipLabel>Claim Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Application/Policy Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Note__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Note_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Note__c/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Note__c/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <label>Claim</label>
</RecordType>

force-app/main/default/objects/Note__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is to identify the type of record, the formula get the record type name that tell the type to be &apos;Application&apos; or &apos;Policy&apos;.</description>
    <formula>RecordType.Name</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claim</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Note_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAAF/RAAF</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>Address / Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Amend Complaint</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Insurance Request</fullName>
    </customValue>
    <customValue>
        <fullName>Chrono</fullName>
    </customValue>
    <customValue>
        <fullName>Close</fullName>
    </customValue>
    <customValue>
        <fullName>Coverage</fullName>
    </customValue>
    <customValue>
        <fullName>ERE / Tail</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-up</fullName>
    </customValue>
    <customValue>
        <fullName>Handler Change</fullName>
    </customValue>
    <customValue>
        <fullName>Lien</fullName>
    </customValue>
    <customValue>
        <fullName>Loss Run Request</fullName>
    </customValue>
    <customValue>
        <fullName>Medicare</fullName>
    </customValue>
    <customValue>
        <fullName>Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>New Business</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Phone Call</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Bound and Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Renewal Review</fullName>
    </customValue>
    <customValue>
        <fullName>QA / Premium Received</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Release</fullName>
    </customValue>
    <customValue>
        <fullName>Reinsurance</fullName>
    </customValue>
    <customValue>
        <fullName>Reinsurance Treaty</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Reopen</fullName>
    </customValue>
    <customValue>
        <fullName>Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Risk Management Hotline</fullName>
    </customValue>
    <masterLabel>Note Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Policy_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <label>App Sent</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Requested Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Quoted</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>Lost</label>
    </customValue>
    <customValue>
        <fullName>Bound</fullName>
    </customValue>
    <customValue>
        <fullName>Printed</fullName>
    </customValue>
    <customValue>
        <fullName>Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Pending</fullName>
        <isActive>false</isActive>
        <label>Quote Pending</label>
    </customValue>
    <masterLabel>Policy Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TaskTriggerHandler.cls
public class TaskTriggerHandler {
    //public static boolean isNoteUpdateFromTask = false;
    public static void onAfterUpdate(List<Task> newList,Map<Id,Task> newMap,List<Task> oldList,Map<Id,Task> oldMap){
        //updateRelatedNote(newList,oldMap);
    }
    public static void onAfterInsert(List<Task> newList,Map<Id,Task> newMap){
        //createNewNote(newList);
    }
    /*public static void updateRelatedNote(List<Task> newList,Map<Id,Task> oldMap){
        Map<Id,Note__c> notesMap = new Map<Id,Note__c>();
        for(Task tsk : newList){
            if(tsk.Note__c !=null){
                if(tsk.Status == 'Completed' && tsk.Status != oldMap.get(tsk.Id).Status){
                    if(notesMap.containsKey(tsk.Note__c)){
                        Note__c note = notesMap.get(tsk.Note__c);
                        note.Status__c = 'Complete';
                        notesMap.put(tsk.Note__c,note);
                    }else{
                        Note__c note = new Note__c();
                        note.Id = tsk.Note__c;
                        note.Status__c = 'Complete';
                        notesMap.put(tsk.Note__c,note);
                    }
                }
                if(tsk.ActivityDate != oldMap.get(tsk.Id).ActivityDate){
                    if(notesMap.containsKey(tsk.Note__c)){
                        Note__c note = notesMap.get(tsk.Note__c);
                        note.Due_Date__c = tsk.ActivityDate;
                        notesMap.put(tsk.Note__c,note);
                    }else{
                        Note__c note = new Note__c();
                        note.Id = tsk.Note__c;
                        note.Due_Date__c = tsk.ActivityDate;
                        notesMap.put(tsk.Note__c,note);
                    }
                }
            }
        }
        if(notesMap.size()>0){
            TaskTriggerHandler.isNoteUpdateFromTask = true;
            update notesMap.values();
            TaskTriggerHandler.isNoteUpdateFromTask = false;
        }
    }*/
    /*public static void createNewNote(List<Task> newList){
        Map<Id,Note__c> notesMap = new Map<Id,Note__c>();
        for(Task tsk : newList){
            Note__c note = new Note__c();
            note.Description__c = tsk.Description;
            note.Subject__c = tsk.Subject;
            note.Type__c = tsk.Type__c;
            note.Status__c = (tsk.Status == 'Completed' ? 'Complete ':'Pending');
            //system.debug('sObjName---'+tsk.WhatId.getSObjectType().getDescribe().getName());
            String sObjName = tsk.WhatId.getSObjectType().getDescribe().getName();
            
            if(sObjName  == 'Account'){
                note.Account__c = tsk.WhatId;
                note.RecordTypeId = Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Account').getRecordTypeId();
            }else if(sObjName  == 'Policy__c'){
                note.Policy__c = tsk.WhatId;
                note.RecordTypeId = Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Application/Policy').getRecordTypeId();
            }else if(sObjName  == 'Policy_Claim__c'){
                note.Claim__c = tsk.WhatId;
                note.RecordTypeId = Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Claim').getRecordTypeId();
            }else if(sObjName  == 'Opportunity'){
                note.Opportunity__c = tsk.WhatId;
                note.RecordTypeId = Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Opportunity').getRecordTypeId();
            }
            notesMap.put(tsk.Id,note);
        }
        if(notesMap.size()>0){
            insert notesMap.values();
            List<Task> tasksToUpdate = new List<Task>();
            for(Id ids : notesMap.keySet()){
                if(String.isNotBlank(notesMap.get(ids).Id)){
                    tasksToUpdate.add(new Task(Id = ids ,Note__c = notesMap.get(ids).Id));
                }
            }
            if(tasksToUpdate.size() > 0){
                update tasksToUpdate;
            }
        }
    }*/
}