force-app/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{0}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Note__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Policy_Claim__c</referenceTo>
    <relationshipLabel>Claim Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Cloned_Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Cloned_Task_Id__c</fullName>
    <label>Cloned Task Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Create_Task__c.field-meta.xml
<CustomField>
    <fullName>Create_Task__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Task</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Application/Policy Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Reminder_Set__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Set__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder Set</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Reminder_Time__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Time__c</fullName>
    <label>Reminder Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Task_Owner__c.field-meta.xml
<CustomField>
    <fullName>Task_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Owner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 5) OR (3 AND 4 AND 5) OR ( NOT 5)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Claim</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Claims, Claims Handler</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Account, Application/Policy</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Underwriting, Sales</value>
        </filterItems>
        <filterItems>
            <field>$Source.Create_Task__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Note_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Note__c/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <label>Claim</label>
</RecordType>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is to identify the type of record, the formula get the record type name that tell the type to be &apos;Application&apos; or &apos;Policy&apos;.</description>
    <formula>RecordType.Name</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claim</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Latest_Claim_Note__c.field-meta.xml
<CustomField>
    <fullName>Latest_Claim_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Claim Note</label>
    <referenceTo>Note__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Note_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAAF/RAAF</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>Address / Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Amend Complaint</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Insurance Request</fullName>
    </customValue>
    <customValue>
        <fullName>Chrono</fullName>
    </customValue>
    <customValue>
        <fullName>Close</fullName>
    </customValue>
    <customValue>
        <fullName>Coverage</fullName>
    </customValue>
    <customValue>
        <fullName>ERE / Tail</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-up</fullName>
    </customValue>
    <customValue>
        <fullName>Handler Change</fullName>
    </customValue>
    <customValue>
        <fullName>Lien</fullName>
    </customValue>
    <customValue>
        <fullName>Loss Run Request</fullName>
    </customValue>
    <customValue>
        <fullName>Medicare</fullName>
    </customValue>
    <customValue>
        <fullName>Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>New Business</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Phone Call</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Bound and Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Renewal Review</fullName>
    </customValue>
    <customValue>
        <fullName>QA / Premium Received</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Release</fullName>
    </customValue>
    <customValue>
        <fullName>Reinsurance</fullName>
    </customValue>
    <customValue>
        <fullName>Reinsurance Treaty</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Reopen</fullName>
    </customValue>
    <customValue>
        <fullName>Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Risk Management Hotline</fullName>
    </customValue>
    <masterLabel>Note Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NoteTriggerHandler.cls
public class NoteTriggerHandler {
    public static void onBeforeDelete(List<Note__c> oldList){
        List<String> profileNames = Label.Notes_Delete_Update_Permission.split(',');
        Map<Id,Profile> profilesMap = new Map<Id,Profile>([select id from Profile where Name in: profileNames]);
        for(Note__c note : oldList){
            if(note.CreatedDate.addDays(5) < System.today() && !profilesMap.containsKey(UserInfo.getProfileId())){
                note.addError('Only System Administrator can delete note after 5 days from created date.');
            }
        }
    }
    public static void onBeforeUpdate(List<Note__c> newList, List<Note__c> oldList, Map<Id,Note__c> newMap, Map<Id,Note__c> oldMap){
        List<String> profileNames = Label.Notes_Delete_Update_Permission.split(',');
        Map<Id,Profile> profilesMap = new Map<Id,Profile>([select id from Profile where Name in: profileNames]);
        for(Note__c note : newList){
            if(note.CreatedDate.addDays(5) < System.today() && !profilesMap.containsKey(UserInfo.getProfileId())){
                note.addError('Only System Administrator can update note after 5 days from created date.');
            }
        }
    }
    public static void onAfterInsert(List<Note__c> newList,Map<Id,Note__c> newMap){
        List<Task> tasksList = new List<Task>();
        
        for(Note__c note : newList){
            if(note.Create_Task__c){
                Id whatId;
                if(note.Policy__c!=null){
                    whatId = note.Policy__c;
                }else if(note.Claim__c!=null){
                    whatId = note.Claim__c;
                }else if(note.Account__c!=null){
                    whatId = note.Account__c;
                } 
                Task tsk = new Task(OwnerId=(note.Task_Owner__c==null?note.CreatedById:note.Task_Owner__c),Subject=note.Subject__c,ActivityDate=note.Due_Date__c,Description=note.Description__c!=null?note.Description__c.replaceAll('<br>','\n').replaceAll('\\<.*?\\>', ''):'',WhatId=whatId,Status='In Progress',Note__c=note.Id,Type__c = note.Type__c);
                if(note.Reminder_Set__c){
                    tsk.IsReminderSet  = note.Reminder_Set__c;
                    tsk.ReminderDateTime = note.Reminder_Time__c;
                }
                tasksList.add(tsk);
            }
            if(note.Cloned_Task_Id__c!=null){
                system.debug('note.Cloned_Task_Id__c :: ' + note.Cloned_Task_Id__c);
                tasksList.add(new Task(Id=note.Cloned_Task_Id__c,Status='Completed'));
            }
        }
        upsert tasksList;
    }
    
    //added on 1 Aug 2024
    public static void UpdateLatestNoteOnClaim(List<Note__c> newList){
        List<Policy_Claim__c> updatedClaims = new List<Policy_Claim__c>();
        for(Note__c note: newList){
            if(note.Claim__c != null){
                Policy_Claim__c claim = new Policy_Claim__c();
                claim.Id = note.Claim__c;
                claim.Latest_Claim_Note__c = note.Id;
                updatedClaims.add(claim);
            }
        }
        
        if(!updatedClaims.isEmpty()){
            Update updatedClaims;
        }
    }
    
}