force-app/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{0}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Note__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Policy_Claim__c</referenceTo>
    <relationshipLabel>Claim Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Created_By_Name__c.field-meta.xml
<CustomField>
    <fullName>Created_By_Name__c</fullName>
    <formula>CreatedBy.FirstName + &apos; &apos; + CreatedBy.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created By Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/of_Attachments__c.field-meta.xml
<CustomField>
    <fullName>of_Attachments__c</fullName>
    <defaultValue>0</defaultValue>
    <label># of Attachments</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Application/Policy Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Note__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Note_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Note__c/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is to identify the type of record, the formula get the record type name that tell the type to be &apos;Application&apos; or &apos;Policy&apos;.</description>
    <formula>RecordType.Name</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claim</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Note_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAAF/RAAF</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>Address / Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Amend Complaint</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Insurance Request</fullName>
    </customValue>
    <customValue>
        <fullName>Chrono</fullName>
    </customValue>
    <customValue>
        <fullName>Close</fullName>
    </customValue>
    <customValue>
        <fullName>Coverage</fullName>
    </customValue>
    <customValue>
        <fullName>ERE / Tail</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-up</fullName>
    </customValue>
    <customValue>
        <fullName>Handler Change</fullName>
    </customValue>
    <customValue>
        <fullName>Lien</fullName>
    </customValue>
    <customValue>
        <fullName>Loss Run Request</fullName>
    </customValue>
    <customValue>
        <fullName>Medicare</fullName>
    </customValue>
    <customValue>
        <fullName>Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>New Business</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Phone Call</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Bound and Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Renewal Review</fullName>
    </customValue>
    <customValue>
        <fullName>QA / Premium Received</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Release</fullName>
    </customValue>
    <customValue>
        <fullName>Reinsurance</fullName>
    </customValue>
    <customValue>
        <fullName>Reinsurance Treaty</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Reopen</fullName>
    </customValue>
    <customValue>
        <fullName>Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Risk Management Hotline</fullName>
    </customValue>
    <masterLabel>Note Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Policy_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <label>App Sent</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Requested Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Quoted</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>Lost</label>
    </customValue>
    <customValue>
        <fullName>Bound</fullName>
    </customValue>
    <customValue>
        <fullName>Printed</fullName>
    </customValue>
    <customValue>
        <fullName>Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Pending</fullName>
        <isActive>false</isActive>
        <label>Quote Pending</label>
    </customValue>
    <masterLabel>Policy Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ExportNotesCtrl.cls
public class ExportNotesCtrl {
    public List<Note__c> notesList{get;set;}
    public ExportNotesCtrl(){
        Id recordId = ApexPages.CurrentPage().getParameters().get('recordId');
        String selectedFilterValue = ApexPages.CurrentPage().getParameters().get('selectedFilterValue');
        String selectedNoteTypeFilterValue = ApexPages.CurrentPage().getParameters().get('selectedNoteTypeFilterValue');
        System.debug('recordId---'+recordId);
        String objName = Id.valueOf(recordId).getSObjectType().getDescribe().getName();
        if(objName == 'Account'){
            List<Policy__C> lstPolicies = [select id,Account__c from Policy__c where Account__C=:recordId ];
            if(selectedNoteTypeFilterValue == 'ALL' || String.isBlank(selectedNoteTypeFilterValue)){
                notesList = new List<Note__c>([select id,Name,Type__C,Status__C,Subject__c,Description__C,CreatedDate,Created_By_Name__c,of_Attachments__c from Note__C where Account__c=:recordId OR Policy__C in : lstPolicies order by createdDate desc]);
            }else{
                notesList = new List<Note__c>([select id,Name,Type__C,Status__C,Subject__c,Description__C,CreatedDate,Created_By_Name__c,of_Attachments__c from Note__C where (Account__c=:recordId OR Policy__C in : lstPolicies) AND Type__c =:selectedNoteTypeFilterValue order by createdDate desc]);
            }
            
        }else if(objName == 'Policy__c'){
            if(selectedFilterValue == 'View This Policy Notes'){
                if(selectedNoteTypeFilterValue == 'ALL' || String.isBlank(selectedNoteTypeFilterValue)){
                    notesList = new List<Note__c>([select id,Name,Type__C,Status__C,Subject__c,Description__C,CreatedDate,Created_By_Name__c,of_Attachments__c from Note__C where Policy__C = : recordId  order by createdDate desc]);
                }else{
                    notesList = new List<Note__c>([select id,Name,Type__C,Status__C,Subject__c,Description__C,CreatedDate,Created_By_Name__c,of_Attachments__c from Note__C where Policy__C = : recordId AND Type__c =:selectedNoteTypeFilterValue order by createdDate desc]);
                }
            }else{
                List<Policy__C> lstPolicies = [select id,Account__c from Policy__c where Id=:recordId ];
                if(lstPolicies.size()>0 && lstPolicies[0].Account__C!=null){
                    lstPolicies = [select id,Account__c from Policy__c where Account__C=:lstPolicies[0].Account__C ];
                    if(selectedNoteTypeFilterValue == 'ALL' || String.isBlank(selectedNoteTypeFilterValue)){
                        notesList = new List<Note__c>([select id,Name,Type__C,Status__C,Subject__c,Description__C,CreatedDate,Created_By_Name__c,of_Attachments__c from Note__C where  Policy__C in : lstPolicies OR Account__c =: lstPolicies[0].Account__C  order by createdDate desc]);
                    }else{
                        notesList = new List<Note__c>([select id,Name,Type__C,Status__C,Subject__c,Description__C,CreatedDate,Created_By_Name__c,of_Attachments__c from Note__C where  (Policy__C in : lstPolicies OR Account__c =: lstPolicies[0].Account__C) AND Type__c =:selectedNoteTypeFilterValue order by createdDate desc]);
                    }
                }else{
                    if(selectedNoteTypeFilterValue == 'ALL' || String.isBlank(selectedNoteTypeFilterValue)){
                        notesList = new List<Note__c>([select id,Name,Type__C,Status__C,Subject__c,Description__C,CreatedDate,Created_By_Name__c,of_Attachments__c from Note__C where (Policy__C = : recordId  OR Account__c =: lstPolicies[0].Account__C) order by createdDate desc]);
                    }else{
                        notesList = new List<Note__c>([select id,Name,Type__C,Status__C,Subject__c,Description__C,CreatedDate,Created_By_Name__c,of_Attachments__c from Note__C where (Policy__C = : recordId OR Account__c =: lstPolicies[0].Account__C) AND Type__c =:selectedNoteTypeFilterValue order by createdDate desc]);
                    }
                }
            }
        }else if(objName == 'Policy_Claim__c'){
            if(selectedNoteTypeFilterValue == 'ALL' || String.isBlank(selectedNoteTypeFilterValue)){
                notesList = new List<Note__c>([select id,Name,Type__C,Status__C,Subject__c,Description__C,CreatedDate,Created_By_Name__c,of_Attachments__c from Note__C where Claim__c=:recordId  order by createdDate desc]);
            }else{
                notesList = new List<Note__c>([select id,Name,Type__C,Status__C,Subject__c,Description__C,CreatedDate,Created_By_Name__c,of_Attachments__c from Note__C where Claim__c=:recordId AND Type__c =:selectedNoteTypeFilterValue  order by createdDate desc]);
            }
        }else{
            notesList = new List<Note__c>();
        }
    }
}