force-app/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{0}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Note__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Note_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Note__c/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Note__c/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <label>Claim</label>
</RecordType>

force-app/main/default/objects/Note__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Note_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAAF/RAAF</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>Address / Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Amend Complaint</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Insurance Request</fullName>
    </customValue>
    <customValue>
        <fullName>Chrono</fullName>
    </customValue>
    <customValue>
        <fullName>Close</fullName>
    </customValue>
    <customValue>
        <fullName>Coverage</fullName>
    </customValue>
    <customValue>
        <fullName>ERE / Tail</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-up</fullName>
    </customValue>
    <customValue>
        <fullName>Handler Change</fullName>
    </customValue>
    <customValue>
        <fullName>Lien</fullName>
    </customValue>
    <customValue>
        <fullName>Loss Run Request</fullName>
    </customValue>
    <customValue>
        <fullName>Medicare</fullName>
    </customValue>
    <customValue>
        <fullName>Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>New Business</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Phone Call</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Bound and Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Renewal Review</fullName>
    </customValue>
    <customValue>
        <fullName>QA / Premium Received</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Release</fullName>
    </customValue>
    <customValue>
        <fullName>Reinsurance</fullName>
    </customValue>
    <customValue>
        <fullName>Reinsurance Treaty</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Reopen</fullName>
    </customValue>
    <customValue>
        <fullName>Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Risk Management Hotline</fullName>
    </customValue>
    <masterLabel>Note Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CompleteAndCreateFollowUpTaskCtrl.cls
public class CompleteAndCreateFollowUpTaskCtrl {
    @AuraEnabled
    public static CompleteAndCreateFollowUpTaskWrapper getRecordDetails(Id recordId){
        CompleteAndCreateFollowUpTaskWrapper wrapper = new CompleteAndCreateFollowUpTaskWrapper(); 
        Task taskObj = [select Id,Note__c,Subject,Description,WhatId,Note__r.Subject__c,Note__r.Description__c,Note__r.Type__c from Task where id=: recordId];
        String whatIdName = taskObj.WhatId.getSObjectType().getDescribe().getName();
        
        wrapper.parentRecordId = taskObj.WhatId;
        wrapper.parentRecordType = whatIdName;
        
        if(whatIdName == 'Policy_Claim__c'){
            wrapper.recordTypeId = Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Claim').getRecordTypeId();
        }else if(whatIdName == 'Account'){
            wrapper.recordTypeId = Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        }else if(whatIdName == 'Opportunity'){
            wrapper.recordTypeId = Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Opportunity').getRecordTypeId();
        }else{
            wrapper.recordTypeId = Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Application/Policy').getRecordTypeId();
        }
        
        if(taskObj.Note__r.Subject__c != null){
            wrapper.subject = taskObj.Note__r.Subject__c;
        }else{
            wrapper.subject = taskObj.Subject;
        }
        if(taskObj.Note__r.Subject__c != null){
            wrapper.description = taskObj.Note__r.Description__c;
        }else{
            wrapper.description = taskObj.Description;
        }
        
        wrapper.noteType = taskObj.Note__r.Type__c;
        wrapper.taskOwner = UserInfo.getUserId();
        
        return wrapper;
    }
	public class CompleteAndCreateFollowUpTaskWrapper {
        @AuraEnabled public Id parentRecordId;
        @AuraEnabled public Id recordTypeId;
        @AuraEnabled public String parentRecordType;
        @AuraEnabled public String subject;
        @AuraEnabled public String description;
        @AuraEnabled public String noteType;
        @AuraEnabled public Id taskOwner;
    }
}