force-app/main/default/objects/Application_Block__c/Application_Block__c.object-meta.xml
<CustomObject>
    <label>Application Block</label>
    <nameField>
        <displayFormat>Block-{000000}</displayFormat>
        <label>Application Block Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Blocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Block__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Application Blocks</relationshipLabel>
    <relationshipName>Application_Blocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Block__c/fields/Application_Policy__c.field-meta.xml
<CustomField>
    <fullName>Application_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application/Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Application Blocks</relationshipLabel>
    <relationshipName>Application_Blocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/Customer_Application__c.object-meta.xml
<CustomObject>
    <label>Online Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Online NBA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Online Applications</relationshipLabel>
    <relationshipName>Online_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Application_Status__c )</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Application__c/fields/Underwriter_User__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Underwriter User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Online_Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{0}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Note__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Policy_Claim__c</referenceTo>
    <relationshipLabel>Claim Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Created_By_Name__c.field-meta.xml
<CustomField>
    <fullName>Created_By_Name__c</fullName>
    <formula>CreatedBy.FirstName + &apos; &apos; + CreatedBy.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created By Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/of_Attachments__c.field-meta.xml
<CustomField>
    <fullName>of_Attachments__c</fullName>
    <defaultValue>0</defaultValue>
    <label># of Attachments</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Application/Policy Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Note__c/fields/Task_Owner__c.field-meta.xml
<CustomField>
    <fullName>Task_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Owner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 5) OR (3 AND 4 AND 5) OR ( NOT 5)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Claim</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Claims, Claims Handler</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Account, Application/Policy</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Underwriting, Sales</value>
        </filterItems>
        <filterItems>
            <field>$Source.Create_Task__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Note_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Note__c/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Note__c/recordTypes/Application_Policy.recordType-meta.xml
<RecordType>
    <fullName>Application_Policy</fullName>
    <active>true</active>
    <label>Application/Policy</label>
</RecordType>

force-app/main/default/objects/Note__c/recordTypes/Claim.recordType-meta.xml
<RecordType>
    <fullName>Claim</fullName>
    <active>true</active>
    <label>Claim</label>
</RecordType>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Application/Policy</label>
    <nameField>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application/Policy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications/Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Customer_Application__c.field-meta.xml
<CustomField>
    <fullName>Customer_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Application</label>
    <referenceTo>Customer_Application__c</referenceTo>
    <relationshipLabel>Application/Policy</relationshipLabel>
    <relationshipName>Application_Policy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is to identify the type of record, the formula get the record type name that tell the type to be &apos;Application&apos; or &apos;Policy&apos;.</description>
    <formula>RecordType.Name</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter_User__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Underwriter User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Application</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Policy__c/recordTypes/Policy.recordType-meta.xml
<RecordType>
    <fullName>Policy</fullName>
    <active>true</active>
    <description>Policy</description>
    <label>Policy</label>
</RecordType>

force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claim</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipName>Policy_Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Note_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAAF/RAAF</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>Address / Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Amend Complaint</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Insurance Request</fullName>
    </customValue>
    <customValue>
        <fullName>Chrono</fullName>
    </customValue>
    <customValue>
        <fullName>Close</fullName>
    </customValue>
    <customValue>
        <fullName>Coverage</fullName>
    </customValue>
    <customValue>
        <fullName>ERE / Tail</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-up</fullName>
    </customValue>
    <customValue>
        <fullName>Handler Change</fullName>
    </customValue>
    <customValue>
        <fullName>Lien</fullName>
    </customValue>
    <customValue>
        <fullName>Loss Run Request</fullName>
    </customValue>
    <customValue>
        <fullName>Medicare</fullName>
    </customValue>
    <customValue>
        <fullName>Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>New Business</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Phone Call</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Bound and Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Renewal Review</fullName>
    </customValue>
    <customValue>
        <fullName>QA / Premium Received</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Release</fullName>
    </customValue>
    <customValue>
        <fullName>Reinsurance</fullName>
    </customValue>
    <customValue>
        <fullName>Reinsurance Treaty</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Reopen</fullName>
    </customValue>
    <customValue>
        <fullName>Reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Risk Management Hotline</fullName>
    </customValue>
    <masterLabel>Note Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Policy_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <label>App Sent</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Requested Additional Information</fullName>
    </customValue>
    <customValue>
        <fullName>Quoted</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>Lost</label>
    </customValue>
    <customValue>
        <fullName>Bound</fullName>
    </customValue>
    <customValue>
        <fullName>Printed</fullName>
    </customValue>
    <customValue>
        <fullName>Emailed</fullName>
    </customValue>
    <customValue>
        <fullName>Policy Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Quote Pending</fullName>
        <isActive>false</isActive>
        <label>Quote Pending</label>
    </customValue>
    <masterLabel>Policy Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountNotesComponentHandler.cls
public class AccountNotesComponentHandler {
    
    public static boolean boo = true;
    
    @AuraEnabled
    //public static List<Note__c> getNotes(Integer rowLimit,Integer rowOffset,String recordId,String selectedFilterValue){
    public static NotesComponentWrapper getNotes(String sortField,boolean isAsc,String recordId,String selectedFilterValue,Decimal pageNumber, Decimal pageSize,String selectedNoteTypeFilterValue,String objectName, String field_apiname,boolean allRequired){
        System.debug(boo);
        if(boo) boo = false;
        System.debug(boo);
        Integer rowLimit = (Integer)pageSize;
        Integer pNumber = (Integer)pageNumber;
        
        Integer rowOffset = (pNumber - 1) * rowLimit;
        
        //
        String userId = userInfo.getUserId();
        
        String orderByField;
        if(sortField == null) {
            orderByField = 'CreatedDate';
        } else {
            orderByField = sortField;
        }       
        
        String sortType = 'DESC' ;
        // if isAsc is equal tp ture then set 'asc' order otherwise set 'desc' order.
        if(isAsc != null) {
            if (isAsc) {
                sortType = 'ASC';
            }else {
                sortType = 'DESC';
            }
        }
        
        System.debug('orderByField-----'+orderByField);
        System.debug('sortType-----'+sortType);
        
        String sSoql = 'Select Id,Name,Type__C,Status__C,Subject__c,Description__C,CreatedDate,Created_By_Name__c,of_Attachments__c,Due_Date__c from Note__C ';
        
        //String sSoqlTask = 'Select Id,Type__c,Subject,Description,WhatId,CreatedDate,CreatedBy.Name from Task '; //Commented on 10/27/20 
        
        String sSoqlBlock = 'Select Id,Created_By_Name__c,CreatedDate,Name,Description__c,Status__c,Subject__c from Application_Block__c ';
        
        String objName = Id.valueOf(recordId).getSObjectType().getDescribe().getName();
        String noteRecordType = '';
        if(objName == 'Account'){
            List<Policy__C> lstPolicies1 = [select id,Account__c from Policy__c where Account__c =: recordId ];
            sSoql += 'where (Account__c = \''+recordId+ '\' OR Policy__C in: lstPolicies1' + + ') ' ;
            //sSoqlTask += 'where (WhatId = \''+recordId+ '\' OR WhatId in: lstPolicies1' + + ') ' ; //Commented on 10/27/20 
            sSoqlBlock += 'where (Account__c = \''+recordId+ '\' OR Application_Policy__c in: lstPolicies1' + + ') ' ;
            noteRecordType = 'Account';
        }else if(objName == 'Policy__c'){            
            if(selectedFilterValue == 'View This Policy Notes'){
                List<Policy__C> lstPolicies = [select id,Underwriter_User__c, Account__c from Policy__c where Id=:recordId ];//added by Ramavter 20 june 2024
                if(lstPolicies[0].Underwriter_User__c != null){
                    userId = lstPolicies[0].Underwriter_User__c;
                }
                
                sSoql += 'where Policy__c = \''+recordId+ '\'' ;
                //sSoqlTask += 'where WhatId = \''+recordId+ '\'' ; //Commented on 10/27/20 
                sSoqlBlock += 'where Application_Policy__c = \''+recordId+ '\'' ;
                noteRecordType = 'Application_Policy';
            }else{
                List<Policy__C> lstPolicies = [select id,Underwriter_User__c, Account__c from Policy__c where Id=:recordId ];
                if(lstPolicies[0].Underwriter_User__c != null){
                    userId = lstPolicies[0].Underwriter_User__c;
                }
                lstPolicies = [select id,Account__c from Policy__c where Account__C=:lstPolicies[0].Account__C ];
                sSoql += 'where (Account__c = \''+lstPolicies[0].Account__C+ '\' OR Policy__C in: lstPolicies' + + ') ' ;
                //sSoqlTask += 'where (WhatId = \''+lstPolicies[0].Account__C+ '\' OR WhatId in: lstPolicies' + + ') ' ; //Commented on 10/27/20 
                sSoqlBlock += 'where (Account__c = \''+lstPolicies[0].Account__C+ '\' OR Application_Policy__c in: lstPolicies' + + ') ' ;
                noteRecordType = 'Claim';
            }
        }else if(objName == 'Policy_Claim__c'){
            sSoql += 'where Claim__c = \''+recordId+ '\'' ;
            //sSoqlTask += 'where WhatId = \''+recordId+ '\'' ; //Commented on 10/27/20 
        }else if(objName == 'AcctSeed__Billing__c'){
            System.debug(objName);
            List<AcctSeed__Billing__c> bill = [select id,AcctSeed__Customer__c  from AcctSeed__Billing__c where Id =: recordId ];
            sSoql += 'where Account__c = \''+bill[0].AcctSeed__Customer__c+ '\'' ;
            //sSoqlTask += 'where WhatId = \''+recordId+ '\'' ; //Commented on 10/27/20 
        }
        else if(objName == 'Customer_Application__c'){
            sSoql += 'where Customer_Application__c = \''+recordId+ '\'' ;
        }
        
        if(selectedNoteTypeFilterValue == 'ALL' || String.isBlank(selectedNoteTypeFilterValue)){
            //sSoql += ' ' + 'order by ' + orderByField + ' ' + sortType + ' ' + 'LIMIT  ' + rowLimit + ' ' + 'OFFSET '+ rowOffset ;
            //List<Note__c> notesList = 	Database.query(sSoql);
            //return notesList;
        }else{
            sSoql += ' AND Type__c = \''+selectedNoteTypeFilterValue+'\'';
            //sSoqlTask += ' AND Type__c = \''+selectedNoteTypeFilterValue+'\''; //Commented on 10/27/20
            //sSoql += ' ' + 'order by ' + orderByField + ' ' + sortType + ' ' + 'LIMIT  ' + rowLimit + ' ' + 'OFFSET '+ rowOffset ;
            //List<Note__c> notesList = 	Database.query(sSoql);
            //return notesList;
        }
        sSoql += ' ' + 'order by ' + orderByField + ' ' + sortType;
        //sSoqlTask += ' ' + 'order by ' + orderByField + ' ' + sortType; //Commented on 10/27/20
        sSoqlBlock += ' ' + 'order by ' + orderByField + ' ' + sortType;
        System.debug(sSoql);
        System.debug(sSoqlBlock);
        List<AccountNotesWrapper> notesWrapper = new List<AccountNotesWrapper>();
        List<Note__c> notesList = new List<Note__c>();
        List<Application_Block__c> blocks = new List<Application_Block__c>();
        notesList = Database.query(sSoql);
        for(Note__c note : notesList){
            notesWrapper.add(new AccountNotesWrapper(note.Name,note.Type__c,note.Subject__c,note.Description__c,note.Id,Date.valueOf(note.CreatedDate),note.Created_By_Name__c,note.of_Attachments__c));
        }
        /*for(Task tsk : Database.query(sSoqlTask)){
            notesWrapper.add(new AccountNotesWrapper(tsk.Subject ,tsk.Type__c,tsk.Subject,tsk.Description,tsk.Id,Date.valueOf(tsk.CreatedDate),tsk.CreatedBy.Name,0));
        }*/ //Commented on 10/27/20
        if(objName == 'Account' || objName == 'Policy__c'){
            for(Application_Block__c block : Database.query(sSoqlBlock)){
                notesWrapper.add(new AccountNotesWrapper(block.Name ,block.Status__c,block.Subject__c,block.Description__c,block.Id,Date.valueOf(block.CreatedDate),block.Created_By_Name__c,0));
            }
        }
        AccountNotesWrapper.sortBy = orderByField;
        AccountNotesWrapper.sortType = sortType;
        notesWrapper.sort();
        List<AccountNotesWrapper> finalNotesWrapper = new List<AccountNotesWrapper>();
        Integer limitTo = notesWrapper.size() < (rowOffset+rowLimit) ? notesWrapper.size() : rowOffset+rowLimit ;
        for(Integer i= rowOffset ; i < limitTo; i++ ){
            finalNotesWrapper.add(notesWrapper[i]);
        }
        NotesComponentWrapper wrapper = new NotesComponentWrapper();
        wrapper.accountNotesWrapper = finalNotesWrapper;
        wrapper.typeOfRecord = getTypeOfRecord(recordId);
        wrapper.numberOfRows = getNotesRowCount(recordId,selectedFilterValue,selectedNoteTypeFilterValue);
        
        if(objectName != null && field_apiname != null){
            wrapper.pickListValues = getPicklistvalues(objectName,field_apiname,allRequired,noteRecordType);
        }
        wrapper.newNote = getRecord();
        if(objName == 'Policy__c'){ 
            wrapper.newNote.Task_Owner__c = userId;
        }
        wrapper.newNoteRecordTypeId = getRecordTypeId(recordId);
        return wrapper;
    }
    @AuraEnabled
    public static Integer getNotesRowCount(String recordId,String selectedFilterValue,String selectedNoteTypeFilterValue){
        String objName = Id.valueOf(recordId).getSObjectType().getDescribe().getName();
        if(objName == 'Account'){
            List<Policy__C> lstPolicies = [select id,Account__c from Policy__c where Account__C=:recordId ];
            if(selectedNoteTypeFilterValue == 'ALL' || String.isBlank(selectedNoteTypeFilterValue)){
                //return [select count() from Note__C where Account__c=:recordId OR Policy__C in : lstPolicies] + [select count() from Task where WhatId=:recordId OR WhatId in : lstPolicies] + [select count() from Application_Block__c where Account__c=:recordId OR Application_Policy__c in : lstPolicies];
                return [select count() from Note__C where Account__c=:recordId OR Policy__C in : lstPolicies]  + [select count() from Application_Block__c where Account__c=:recordId OR Application_Policy__c in : lstPolicies];
            }else{
                //return [select count() from Note__C where (Account__c=:recordId OR Policy__C in : lstPolicies) AND Type__c =:selectedNoteTypeFilterValue] + [select count() from Task where (WhatId=:recordId OR WhatId in : lstPolicies) AND Type__c =:selectedNoteTypeFilterValue] + [select count() from Application_Block__c where Account__c=:recordId OR Application_Policy__c in : lstPolicies];
                return [select count() from Note__C where (Account__c=:recordId OR Policy__C in : lstPolicies) AND Type__c =:selectedNoteTypeFilterValue] +  [select count() from Application_Block__c where Account__c=:recordId OR Application_Policy__c in : lstPolicies];
            }
            
        }else if(objName == 'Policy__c'){
            if(selectedFilterValue == 'View This Policy Notes'){
                if(selectedNoteTypeFilterValue == 'ALL' || String.isBlank(selectedNoteTypeFilterValue)){
                    //return [select count() from Note__C where Policy__C = : recordId ] + [select count() from Task where WhatId = : recordId ]  + [select count() from Application_Block__c where Application_Policy__c=:recordId];
                    return [select count() from Note__C where Policy__C = : recordId ]  + [select count() from Application_Block__c where Application_Policy__c=:recordId];
                }else{
                    //return [select count() from Note__C where Policy__C = : recordId AND Type__c =:selectedNoteTypeFilterValue] + [select count() from Task where WhatId = : recordId AND Type__c =:selectedNoteTypeFilterValue]   + [select count() from Application_Block__c where Application_Policy__c=:recordId];
                    return [select count() from Note__C where Policy__C = : recordId AND Type__c =:selectedNoteTypeFilterValue]  + [select count() from Application_Block__c where Application_Policy__c=:recordId];
                }
            }else{
                List<Policy__C> lstPolicies = [select id,Account__c from Policy__c where Id=:recordId ];
                lstPolicies = [select id,Account__c from Policy__c where Account__C=:lstPolicies[0].Account__C ];
                if(selectedNoteTypeFilterValue == 'ALL' || String.isBlank(selectedNoteTypeFilterValue)){
                    //return [select count() from Note__C where  Policy__C in : lstPolicies or Account__c=:lstPolicies[0].Account__c] + [select count() from Task where  WhatId in : lstPolicies or WhatId=:lstPolicies[0].Account__c] + [select count() from Application_Block__c where Account__c=:lstPolicies[0].Account__c OR Application_Policy__c in : lstPolicies];
                    return [select count() from Note__C where  Policy__C in : lstPolicies or Account__c=:lstPolicies[0].Account__c]  + [select count() from Application_Block__c where Account__c=:lstPolicies[0].Account__c OR Application_Policy__c in : lstPolicies];
                }else{
                    //return [select count() from Note__C where  (Policy__C in : lstPolicies or Account__c=:lstPolicies[0].Account__c) AND Type__c =:selectedNoteTypeFilterValue] + [select count() from Task where  (WhatId in : lstPolicies or WhatId=:lstPolicies[0].Account__c) AND Type__c =:selectedNoteTypeFilterValue] + [select count() from Application_Block__c where Account__c=:lstPolicies[0].Account__c OR Application_Policy__c in : lstPolicies];
                    return [select count() from Note__C where  (Policy__C in : lstPolicies or Account__c=:lstPolicies[0].Account__c) AND Type__c =:selectedNoteTypeFilterValue]  + [select count() from Application_Block__c where Account__c=:lstPolicies[0].Account__c OR Application_Policy__c in : lstPolicies];
                }
            }
        }else if(objName == 'Policy_Claim__c'){
            if(selectedNoteTypeFilterValue == 'ALL' || String.isBlank(selectedNoteTypeFilterValue)){
                //return [select count() from Note__C where Claim__c=:recordId] + [select count() from Task where WhatId=:recordId];
                return [select count() from Note__C where Claim__c=:recordId];
            }else{
                //return [select count() from Note__C where Claim__c=:recordId AND Type__c =:selectedNoteTypeFilterValue] + [select count() from Task where WhatId=:recordId AND Type__c =:selectedNoteTypeFilterValue];
                return [select count() from Note__C where Claim__c=:recordId AND Type__c =:selectedNoteTypeFilterValue] ;
            }
        }else if(objName == 'AcctSeed__Billing__c'){
            List<AcctSeed__Billing__c> bill = [select id,AcctSeed__Customer__c  from AcctSeed__Billing__c where Id =: recordId ];
            return [select count() from Note__C where Account__c =: bill[0].AcctSeed__Customer__c];
        }
        else if(objName == 'Customer_Application__c'){
            if(selectedNoteTypeFilterValue == 'ALL' || String.isBlank(selectedNoteTypeFilterValue)){
                //return [select count() from Note__C where Claim__c=:recordId] + [select count() from Task where WhatId=:recordId];
                return [select count() from Note__C where Customer_Application__c=:recordId];
            }else{
                //return [select count() from Note__C where Claim__c=:recordId AND Type__c =:selectedNoteTypeFilterValue] + [select count() from Task where WhatId=:recordId AND Type__c =:selectedNoteTypeFilterValue];
                return [select count() from Note__C where Customer_Application__c=:recordId AND Type__c =:selectedNoteTypeFilterValue] ;
            }
        }
        else{
            return 0;
        }
    }
    @AuraEnabled
    public static Id getRecordTypeId(String recordId){
        String objName = Id.valueOf(recordId).getSObjectType().getDescribe().getName();
        system.debug('objName'+objName);
        if(objName == 'Account'){
            return Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        }else if(objName == 'Policy__c'){
            return Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Application/Policy').getRecordTypeId();
        }else if(objName == 'Policy_Claim__c'){
            return Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Claim').getRecordTypeId();
        }else{
            return Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        }
    }
    @AuraEnabled
    public static String getTypeOfRecord(String recordId){
        String objName = Id.valueOf(recordId).getSObjectType().getDescribe().getName();
        return objName;
    }
    
    @AuraEnabled
    public static Note__c getRecord(){
        Note__c objNotes = new Note__c();
        objnotes.Task_Owner__c = userinfo.getUserId();
        objnotes.Status__c = 'Pending';
        return objNotes;
    } 
    
    @AuraEnabled
    public static String saveNotes(String recordId,Note__c objNotes){
        String objName = Id.valueOf(recordId).getSObjectType().getDescribe().getName();
        system.debug('objNotes'+objNotes);
      
       if(objName == 'Account'){
            objNotes.Account__c = recordId;
            objNotes.RecordTypeId =  Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        }
        else if(objName == 'Policy__c'){
            objNotes.Policy__c = recordId;  
            objNotes.RecordTypeId =  Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Application/Policy').getRecordTypeId();
        }
        else if(objName == 'Policy_Claim__c'){
            objNotes.Claim__c = recordId;   
            objNotes.RecordTypeId = Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Claim').getRecordTypeId();
        }else if(objName == 'AcctSeed__Billing__c'){
            List<AcctSeed__Billing__c> bill = [select id,AcctSeed__Customer__c  from AcctSeed__Billing__c where Id =: recordId ];
            objNotes.Account__c = bill[0].AcctSeed__Customer__c;
            objNotes.RecordTypeId =  Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        }
        else if(objName == 'Customer_Application__c'){
            objNotes.Customer_Application__c = recordId;
            objNotes.RecordTypeId =  Schema.SObjectType.Note__c.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        }
        
        try{
        insert objNotes;
        }
        catch(exception ex){
            return ex.getMessage();
        }
      
        return 'Success';
    }
    @AuraEnabled
    public static List<String> getPicklistvalues(String objectName, String field_apiname,boolean allRequired,String recordType){
        List<String> optionlist = new List<String>();
        
        Map<String,Schema.SObjectType> gd = Schema.getGlobalDescribe(); 
        Map<String, Schema.SObjectField> field_map = gd.get(objectName.toLowerCase()).getDescribe().fields.getMap(); 
        
        List<Schema.PicklistEntry> picklistValues = field_map.get(field_apiname).getDescribe().getPickListValues();
        
        if(allRequired == true){
            optionlist.add('ALL');
        }
        
        for (Schema.PicklistEntry pv : picklistValues) {
            optionlist.add(pv.getValue());
        }
        return optionlist;
    }
    
    public class NotesComponentWrapper{
        @AuraEnabled
        public List<AccountNotesWrapper> accountNotesWrapper{get;set;}
        @AuraEnabled
        public String typeOfRecord{get;set;}
        @AuraEnabled
        public Integer numberOfRows{get;set;}
        @AuraEnabled
        public List<String> pickListValues{get;set;}
        @AuraEnabled
        public Note__c newNote{get;set;}
        @AuraEnabled
        public Id newNoteRecordTypeId{get;set;}
    }
}